within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX06_DinutuximabBeta
  extends Icons.PackageDrugs;
end L01FX06_DinutuximabBeta;
