within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FE02_Panitumumab
  extends Icons.PackageDrugs;
end L01FE02_Panitumumab;
