within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX06_AtorvastatinAcetylsalicylicAcidAndRamipril
  extends Icons.Package;
end C10BX06_AtorvastatinAcetylsalicylicAcidAndRamipril;
