within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01D_VasodilatorsUsedInCardiacDiseases;
package C01DA04_MethylpropylpropanediolDinitrate
  extends Icons.Package;
end C01DA04_MethylpropylpropanediolDinitrate;
