within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DX07_IrbesartanAmlodipineAndHydrochlo
  extends Icons.Package;
end C09DX07_IrbesartanAmlodipineAndHydrochlo;
