within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials;
package J01DE51_CefepimeAndBetaLactamaseInhibito
  extends Icons.Package;
end J01DE51_CefepimeAndBetaLactamaseInhibito;
