within Pharmacolibrary.Drugs.D_Dermatologicals.D07X_CorticosteroidsOtherCombinations;
package D07XB30_CorticosteroidsCombinationsEGBetamethasoneAndGentamicinTopical
  extends Icons.Package;
end D07XB30_CorticosteroidsCombinationsEGBetamethasoneAndGentamicinTopical;
