within Pharmacolibrary.Drugs.R_RespiratorySystem.R05F_CoughSuppressantsAndExpectorantsCombinations;
package R05FB02_BromhexineCoughSuppressa
  extends Icons.PackageDrugs;
end R05FB02_BromhexineCoughSuppressa;
