within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX05_RosuvastatinAndAcetylsalicylicAc
  extends Icons.PackageDrugs;
end C10BX05_RosuvastatinAndAcetylsalicylicAc;
