within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A11H_OtherPlainVitaminPreparations.A11HA01_Nicotinamide;

model Nicotinamide
  extends Pharmacolibrary.Drugs.ATC.A.A11HA01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Nicotinamide</td></tr><tr><td>ATC code:</td><td>A11HA01</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Nicotinamide, also known as niacinamide, is a form of vitamin B3 used as a dietary supplement and medication. It is essential for human health, used to treat and prevent niacin deficiency (pellagra). It is an approved and widely used over-the-counter vitamin supplement.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters as observed in healthy adult volunteers after oral administration.</p><h4>References</h4><ol><li><p>Miyatake, D, et al., &amp; Urae, A (2020). Pharmacokinetics and Safety of a Single Oral Dose of Peficitinib (ASP015K) in Japanese Subjects With Normal and Impaired Hepatic Function. <i>Clinical pharmacology in drug development</i> 9(6) 699–708. DOI:<a href=\"https://doi.org/10.1002/cpdd.751\">10.1002/cpdd.751</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31833184/\">https://pubmed.ncbi.nlm.nih.gov/31833184</a></p></li><li><p>Larsen, MO, et al., &amp; Holst, JJ (2004). Reduction of beta cell mass: partial insulin secretory compensation from the residual beta cell population in the nicotinamide-streptozotocin Göttingen minipig after oral glucose in vivo and in the perfused pancreas. <i>Diabetologia</i> 47(11) 1873–1878. DOI:<a href=\"https://doi.org/10.1007/s00125-004-1546-9\">10.1007/s00125-004-1546-9</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/15565374/\">https://pubmed.ncbi.nlm.nih.gov/15565374</a></p></li><li><p>Sampathkumar, K (2009). Niacin and analogs for phosphate control in dialysis--perspective from a developing country. <i>International urology and nephrology</i> 41(4) 913–918. DOI:<a href=\"https://doi.org/10.1007/s11255-008-9497-6\">10.1007/s11255-008-9497-6</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/19037739/\">https://pubmed.ncbi.nlm.nih.gov/19037739</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Nicotinamide;
