within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M09A_OtherDrugsForDisordersOfTheMusculoSkeletalSystem;
package M09AB02_CollagenaseClostridiumHi
  extends Icons.PackageDrugs;
end M09AB02_CollagenaseClostridiumHi;
