within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AH06_MeningococcusBOuterMembraneVesic
  extends Icons.Package;
end J07AH06_MeningococcusBOuterMembraneVesic;
