within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M03B_MuscleRelaxantsCentrallyActingAgents;
package M03BX55_ThiocolchicosideCombinat
  extends Icons.PackageDrugs;
end M03BX55_ThiocolchicosideCombinat;
