within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA01_DiphtheriaPoliomyelitisT
  extends Icons.PackageDrugs;
end J07CA01_DiphtheriaPoliomyelitisT;
