within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M03B_MuscleRelaxantsCentrallyActingAgents;
package M03BA72_CarisoprodolCombinationsWithPsycholeptics
  extends Icons.Package;
end M03BA72_CarisoprodolCombinationsWithPsycholeptics;
