within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M05B_DrugsAffectingBoneStructureAndMineralization;
package M05BB06_AlendronicAcidAndAlfacalcidolSeq
  extends Icons.Package;
end M05BB06_AlendronicAcidAndAlfacalcidolSeq;
