within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX07_Blinatumomab
  extends Icons.PackageDrugs;
end L01FX07_Blinatumomab;
