within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AG01_HaemophilusInfluenzaeBPurifiedAntigenConjugated
  extends Icons.Package;
end J07AG01_HaemophilusInfluenzaeBPurifiedAntigenConjugated;
