within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M05B_DrugsAffectingBoneStructureAndMineralization;
package M05BX53_StrontiumRanelateAndColecalcifer
  extends Icons.PackageDrugs;
end M05BX53_StrontiumRanelateAndColecalcifer;
