within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AX15_CopperUsnate
  extends Icons.Package;
end G01AX15_CopperUsnate;
