within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01D_VasodilatorsUsedInCardiacDiseases;
package C01DA20_OrganicNitratesInCombina
  extends Icons.PackageDrugs;
end C01DA20_OrganicNitratesInCombina;
