within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02L_AntihypertensivesAndDiureticsInCombination;
package C02LA09_SyrosingopineAndDiuretics
  extends Icons.Package;
end C02LA09_SyrosingopineAndDiuretics;
