within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AC02_Clefamide
  extends Icons.PackageDrugs;
end P01AC02_Clefamide;
