within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AX06_Furazolidone
  extends Icons.PackageDrugs;
end G01AX06_Furazolidone;
