within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H05B_AntiParathyroidAgents;
package H05BX04_Etelcalcetide
  extends Icons.PackageDrugs;
end H05BX04_Etelcalcetide;
