within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BD11_PantoprazoleAmoxicillinClarithromycinAndMetronidazole
  extends Icons.Package;
end A02BD11_PantoprazoleAmoxicillinClarithromycinAndMetronidazole;
