within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DX06_CandesartanAmlodipineAndHydrochl
  extends Icons.Package;
end C09DX06_CandesartanAmlodipineAndHydrochl;
