within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX13_RosuvastatinPerindoprilA
  extends Icons.PackageDrugs;
end C10BX13_RosuvastatinPerindoprilA;
