within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DX04_ValsartanAndSacubitril
  extends Icons.Package;
end C09DX04_ValsartanAndSacubitril;
