within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B03A_IronPreparations;
package B03AD04_FerricOxidePolymaltoseComplexesAndFolicAcid
  extends Icons.Package;
end B03AD04_FerricOxidePolymaltoseComplexesAndFolicAcid;
