within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX24_Teclistamab
  extends Icons.Package;
end L01FX24_Teclistamab;
