within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BX71_CarbenoxoloneCombinationsWithPsy
  extends Icons.Package;
end A02BX71_CarbenoxoloneCombinationsWithPsy;
