within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals.J05AH02_Oseltamivir;

model Oseltamivir
  extends Pharmacolibrary.Drugs.ATC.J.J05AH02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>J05AH02</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Oseltamivir is an antiviral medication that inhibits influenza virus neuraminidase, thereby interfering with the release of progeny influenza virus from infected host cells. It is primarily used for the treatment and prophylaxis of influenza A and B. Oseltamivir is approved for clinical use and remains a standard therapy for seasonal influenza.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported for healthy adult subjects (mixed sex, ages 18-65) after single oral dose administration of oseltamivir phosphate.</p><h4>References</h4><ol><li><p>Davies, BE (2010). Pharmacokinetics of oseltamivir: an oral antiviral for the treatment and prophylaxis of influenza in diverse populations. <i>The Journal of antimicrobial chemotherapy</i> 65 Suppl 2(Suppl 2) ii5–ii10. DOI:<a href=\"https://doi.org/10.1093/jac/dkq015\">10.1093/jac/dkq015</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/20215135/\">https://pubmed.ncbi.nlm.nih.gov/20215135</a></p></li><li><p>Rayner, CR, et al., &amp; Jonsson, EN (2008). Population pharmacokinetics of oseltamivir when coadministered with probenecid. <i>Journal of clinical pharmacology</i> 48(8) 935–947. DOI:<a href=\"https://doi.org/10.1177/0091270008320317\">10.1177/0091270008320317</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/18524996/\">https://pubmed.ncbi.nlm.nih.gov/18524996</a></p></li><li><p>Reddy, MB, et al., &amp; Govorkova, EA (2015). Oseltamivir Population Pharmacokinetics in the Ferret: Model Application for Pharmacokinetic/Pharmacodynamic Study Design. <i>PloS one</i> 10(10) e0138069–None. DOI:<a href=\"https://doi.org/10.1371/journal.pone.0138069\">10.1371/journal.pone.0138069</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/26460484/\">https://pubmed.ncbi.nlm.nih.gov/26460484</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Oseltamivir;
