within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G04C_DrugsUsedInBenignProstaticHypertrophy;
package G04CA51_AlfuzosinAndFinasteride
  extends Icons.PackageDrugs;
end G04CA51_AlfuzosinAndFinasteride;
