within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L04A_Immunosuppressants.L04AD02_Tacrolimus;

model Tacrolimus
  extends Pharmacolibrary.Drugs.ATC.L.L04AD02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>L04AD02</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Tacrolimus is an immunosuppressant macrolide used primarily to prevent organ transplant rejection and to treat certain autoimmune diseases. It acts by inhibiting calcineurin, thus suppressing T-lymphocyte activation. It is approved and remains widely used in clinical practice, particularly for kidney, liver, and heart transplant recipients.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic model parameters reported for adult kidney transplant recipients following oral administration in the early post-transplant period, population containing both sexes.</p><h4>References</h4><ol><li><p>Martial, LC, et al., &amp; Moes, DJAR (2021). Population pharmacokinetics and genetics of oral meltdose tacrolimus (Envarsus) in stable adult liver transplant recipients. <i>British journal of clinical pharmacology</i> 87(11) 4262–4272. DOI:<a href=\"https://doi.org/10.1111/bcp.14842\">10.1111/bcp.14842</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33786892/\">https://pubmed.ncbi.nlm.nih.gov/33786892</a></p></li><li><p>Teng, F, et al., &amp; Wei, H (2022). Population pharmacokinetics of tacrolimus in Chinese adult liver transplant patients. <i>Biopharmaceutics &amp; drug disposition</i> 43(2) 76–85. DOI:<a href=\"https://doi.org/10.1002/bdd.2311\">10.1002/bdd.2311</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35220592/\">https://pubmed.ncbi.nlm.nih.gov/35220592</a></p></li><li><p>Kamp, J, et al., &amp; Moes, DJAR (2023). Meltdose Tacrolimus Population Pharmacokinetics and Limited Sampling Strategy Evaluation in Elderly Kidney Transplant Recipients. <i>Pharmaceutics</i> 16(1) –. DOI:<a href=\"https://doi.org/10.3390/pharmaceutics16010017\">10.3390/pharmaceutics16010017</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/38276495/\">https://pubmed.ncbi.nlm.nih.gov/38276495</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Tacrolimus;
