within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01C_AgentsAgainstLeishmaniasisAndTrypanosomiasis;
package P01CX02_SuraminSodium
  extends Icons.PackageDrugs;
end P01CX02_SuraminSodium;
