within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD25_MetforminSaxagliptinAndDapagliflozin
  extends Icons.Package;
end A10BD25_MetforminSaxagliptinAndDapagliflozin;
