within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A16A_OtherAlimentaryTractAndMetabolismProducts;
package A16AX03_SodiumPhenylbutyrate
  extends Icons.PackageDrugs;
end A16AX03_SodiumPhenylbutyrate;
