within Pharmacolibrary.Drugs.C_CardiovascularSystem.C05A_AgentsForTreatmentOfHemorrhoidsAndAnalFissuresForTopicalUse;
package C05AE01_GlycerylTrinitrate
  extends Icons.Package;
end C05AE01_GlycerylTrinitrate;
