within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD16_MetforminAndCanagliflozin
  extends Icons.Package;
end A10BD16_MetforminAndCanagliflozin;
