within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BH51_SitagliptinAndSimvastatin
  extends Icons.Package;
end A10BH51_SitagliptinAndSimvastatin;
