within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonSteroids.M01AX17_Nimesulide;

model Nimesulide
  extends Pharmacolibrary.Drugs.ATC.M.M01AX17;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>M01AX17</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Nimesulide is a non-steroidal anti-inflammatory drug (NSAID) with analgesic and antipyretic properties, primarily used in the treatment of acute pain, symptomatic treatment of osteoarthritis, and primary dysmenorrhea. Due to potential hepatotoxicity, its use is restricted or banned in some countries and generally not approved in the US, but it remains approved in several European, Asian, and Latin American countries.</p><h4>Pharmacokinetics</h4><p>Healthy adult volunteers, oral administration; single dose PK.</p><h4>References</h4><ol><li><p>Hanif, M, et al., &amp; Khan, SM (2017). PHARMACOKINETICS AND BIOEQUIVALENCE STUDIES OF TWO NIMESULIDE 100 mg TABLETS: UNIT DOSE, RANDOMIZED-SEQUENCE, TWO-WAY CROSSOVER STUDY IN HEALTHY VOLUNTEERS OF PAKISTANI POPULATION. <i>Acta poloniae pharmaceutica</i> 74(2) 489–495. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29624254/\">https://pubmed.ncbi.nlm.nih.gov/29624254</a></p></li><li><p>Kim, MS, et al., &amp; Kang, JS (2012). Quantification of nimesulide in human plasma by high-performance liquid chromatography with ultraviolet detector (HPLC-UV): application to pharmacokinetic studies in 28 healthy Korean subjects. <i>Journal of chromatographic science</i> 50(5) 396–400. DOI:<a href=\"https://doi.org/10.1093/chromsci/bms014\">10.1093/chromsci/bms014</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/22451531/\">https://pubmed.ncbi.nlm.nih.gov/22451531</a></p></li><li><p>Galligan, TH, et al., &amp; Naidoo, V (2022). The non-steroidal anti-inflammatory drug nimesulide kills Gyps vultures at concentrations found in the muscle of treated cattle. <i>The Science of the total environment</i> 807(Pt 2) 150788–None. DOI:<a href=\"https://doi.org/10.1016/j.scitotenv.2021.150788\">10.1016/j.scitotenv.2021.150788</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34619222/\">https://pubmed.ncbi.nlm.nih.gov/34619222</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Nimesulide;
