within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AJ52_PertussisPurifiedAntigenCombinat
  extends Icons.Package;
end J07AJ52_PertussisPurifiedAntigenCombinat;
