within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX22_LoncastuximabTesirine
  extends Icons.Package;
end L01FX22_LoncastuximabTesirine;
