within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis;
package A02BD02_LansoprazoleTetracycline
  extends Icons.PackageDrugs;
end A02BD02_LansoprazoleTetracycline;
