within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03F_Propulsives.A03FA01_Metoclopramide;

model Metoclopramide
  extends Pharmacolibrary.Drugs.ATC.A.A03FA01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>A03FA01</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Metoclopramide is a dopamine D2 receptor antagonist primarily used as an antiemetic and prokinetic agent for the treatment of nausea and vomiting, including that associated with chemotherapy, surgery, and migraine. It also increases gastrointestinal motility and is approved for short-term use in gastroesophageal reflux and gastroparesis. Metoclopramide is still approved and in use in many countries but carries warnings due to risk of tardive dyskinesia with prolonged use.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters in healthy adult volunteers, both male and female, after single oral dose.</p><h4>References</h4><ol><li><p>Forrest, JA, et al., &amp; Prescott, LF (1982). Clinical pharmacokinetics of paracetamol. <i>Clinical pharmacokinetics</i> 7(2) 93–107. DOI:<a href=\"https://doi.org/10.2165/00003088-198207020-00001\">10.2165/00003088-198207020-00001</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/7039926/\">https://pubmed.ncbi.nlm.nih.gov/7039926</a></p></li><li><p>Chen, L, et al., &amp; Brüggemann, RJ (2023). An Integrated Population Pharmacokinetic Analysis for Posaconazole Oral Suspension, Delayed-Release Tablet, and Intravenous Infusion in Healthy Volunteers. <i>Drugs</i> 83(1) 75–86. DOI:<a href=\"https://doi.org/10.1007/s40265-022-01819-8\">10.1007/s40265-022-01819-8</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36607589/\">https://pubmed.ncbi.nlm.nih.gov/36607589</a></p></li><li><p>Lachi-Silva, L, et al., &amp; Diniz, A (2020). Population pharmacokinetics of orally administrated bromopride: Focus on the absorption process. <i>European journal of pharmaceutical sciences : official journal of the European Federation for Pharmaceutical Sciences</i> 142 105081–None. DOI:<a href=\"https://doi.org/10.1016/j.ejps.2019.105081\">10.1016/j.ejps.2019.105081</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31669384/\">https://pubmed.ncbi.nlm.nih.gov/31669384</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Metoclopramide;
