within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A04A_AntiemeticsAndAntinauseants;
package A04AD54_ChlorobutanolCombination
  extends Icons.PackageDrugs;
end A04AD54_ChlorobutanolCombination;
