within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07F_BetaBlockingAgentsOtherCombinations;
package C07FX05_MetoprololAndIvabradine
  extends Icons.PackageDrugs;
end C07FX05_MetoprololAndIvabradine;
