within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AR08_EmtricitabineTenofovirDisoproxilAndRilpivirine
  extends Icons.Package;
end J05AR08_EmtricitabineTenofovirDisoproxilAndRilpivirine;
