within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX01_SimvastatinAndAcetylsalicylicAci
  extends Icons.PackageDrugs;
end C10BX01_SimvastatinAndAcetylsalicylicAci;
