within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins;
package J01CR03_TicarcillinAndBetaLactamaseInhib
  extends Icons.Package;
end J01CR03_TicarcillinAndBetaLactamaseInhib;
