within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J06B_Immunoglobulins;
package J06BB30_HumanNormalImmunoglobulinCombinations
  extends Icons.Package;
end J06BB30_HumanNormalImmunoglobulinCombinations;
