within Pharmacolibrary.Drugs.N_NervousSystem.N03A_Antiepileptics.N03AG03_AminobutyricAcid;

model AminobutyricAcid
  extends Pharmacolibrary.Drugs.ATC.N.N03AG03;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>AminobutyricAcid</td></tr><tr><td>ATC code:</td><td>N03AG03</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Aminobutyric acid (specifically gamma-aminobutyric acid or GABA) is a non-protein amino acid acting as a major inhibitory neurotransmitter in the mammalian central nervous system. Aminobutyric acid derivatives have been considered for anticonvulsant and anxiolytic activities. The substance corresponding to ATC code N03AG03 is gamma-aminobutyric acid (GABA), but it is not widely approved or used in current clinical practice due to poor blood-brain barrier penetration.</p><h4>Pharmacokinetics</h4><p>No human pharmacokinetic models with clinical dosing found published for aminobutyric acid (GABA) as an administered drug. Estimates provided below are based on physicochemical properties and available indirect data.</p><h4>References</h4><ol><li><p>Chevillard, L, et al., &amp; Declèves, X (2018). Population pharmacokinetics of oral baclofen at steady-state in alcoholic-dependent adult patients. <i>Fundamental &amp; clinical pharmacology</i> 32(2) 239–248. DOI:<a href=\"https://doi.org/10.1111/fcp.12330\">10.1111/fcp.12330</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29091319/\">https://pubmed.ncbi.nlm.nih.gov/29091319</a></p></li><li><p>He, Y, et al., &amp; Jusko, WJ (2014). Population pharmacokinetics of oral baclofen in pediatric patients with cerebral palsy. <i>The Journal of pediatrics</i> 164(5) 1181–1188.e8. DOI:<a href=\"https://doi.org/10.1016/j.jpeds.2014.01.029\">10.1016/j.jpeds.2014.01.029</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/24607242/\">https://pubmed.ncbi.nlm.nih.gov/24607242</a></p></li><li><p>Gould, A, &amp; Amin, S (2024). An overview of ganaxolone as a treatment for seizures associated with cyclin-dependent kinase-like 5 deficiency disorder. <i>Expert review of neurotherapeutics</i> 24(10) 945–951. DOI:<a href=\"https://doi.org/10.1080/14737175.2024.2385937\">10.1080/14737175.2024.2385937</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39082513/\">https://pubmed.ncbi.nlm.nih.gov/39082513</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end AminobutyricAcid;
