within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AX04_Phanquinone
  extends Icons.PackageDrugs;
end P01AX04_Phanquinone;
