within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BA05_AtorvastatinAndEzetimibe
  extends Icons.PackageDrugs;
end C10BA05_AtorvastatinAndEzetimibe;
