within Pharmacolibrary.Drugs.D_Dermatologicals.D10A_AntiAcnePreparationsForTopicalUse.D10AA02_Methylprednisolone;

model Methylprednisolone
  extends Pharmacolibrary.Drugs.ATC.D.D10AA02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Methylprednisolone</td></tr><tr><td>ATC code:</td><td>D10AA02</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Methylprednisolone is a synthetic glucocorticoid used primarily as an anti-inflammatory and immunosuppressant. It is indicated for a broad range of conditions, including allergies, asthma, autoimmune diseases, and certain types of arthritis. It is approved and widely used in clinical medicine.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters in healthy adult volunteers after a single intravenous bolus. Both male and female subjects included, age range 18-45, with normal renal and hepatic function.</p><h4>References</h4><ol><li><p>Barth, J, et al., &amp; Möllenhoff, G (2004). Population pharmacokinetics of methylprednisolone in accident victims with spinal cord injury. <i>International journal of clinical pharmacology and therapeutics</i> 42(9) 504–511. DOI:<a href=\"https://doi.org/10.5414/cpp42504\">10.5414/cpp42504</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/15487809/\">https://pubmed.ncbi.nlm.nih.gov/15487809</a></p></li><li><p>Hornik, CP, et al., &amp; Cohen-Wolkowiez, M (2019). Population Pharmacokinetic/Pharmacodynamic Modeling of Methylprednisolone in Neonates Undergoing Cardiopulmonary Bypass. <i>CPT: pharmacometrics &amp; systems pharmacology</i> 8(12) 913–922. DOI:<a href=\"https://doi.org/10.1002/psp4.12470\">10.1002/psp4.12470</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31646767/\">https://pubmed.ncbi.nlm.nih.gov/31646767</a></p></li><li><p>Fokkink, WJR, et al., &amp; Jacobs, BC (2022). Population Pharmacokinetic Modelling of Intravenous Immunoglobulin Treatment in Patients with Guillain-Barré Syndrome. <i>Clinical pharmacokinetics</i> 61(9) 1285–1296. DOI:<a href=\"https://doi.org/10.1007/s40262-022-01136-z\">10.1007/s40262-022-01136-z</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35781631/\">https://pubmed.ncbi.nlm.nih.gov/35781631</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Methylprednisolone;
