within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B02A_Antifibrinolytics.B02AB02_Alfa1Antitrypsin;

model Alfa1Antitrypsin
  extends Pharmacolibrary.Drugs.ATC.B.B02AB02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>B02AB02</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Alfa1 antitrypsin (AAT) is a serine protease inhibitor primarily used for the treatment of alpha-1 antitrypsin deficiency, a hereditary disorder that can lead to emphysema and chronic obstructive pulmonary disease (COPD). It is administered as an augmentation therapy in individuals with severe deficiency of this protein. The drug is approved for clinical use today, especially in patients exhibiting clinical evidence of emphysema and low AAT levels.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters in adult alpha1-antitrypsin deficient patients after intravenous administration of plasma-derived AAT; mixed-sex, stable state.</p><h4>References</h4><ol><li><p>Li, Z, et al., &amp; Yel, L (2022). Comparative biochemical efficacy analysis of an alpha. <i>Pulmonary pharmacology &amp; therapeutics</i> 73-74 102124–None. DOI:<a href=\"https://doi.org/10.1016/j.pupt.2022.102124\">10.1016/j.pupt.2022.102124</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35314325/\">https://pubmed.ncbi.nlm.nih.gov/35314325</a></p></li><li><p>Seyama, K, et al., &amp; Hayashi, KI (2019). Safety and pharmacokinetics of Alpha-1 MP (Prolastin. <i>Respiratory investigation</i> 57(1) 89–96. DOI:<a href=\"https://doi.org/10.1016/j.resinv.2018.09.006\">10.1016/j.resinv.2018.09.006</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30416054/\">https://pubmed.ncbi.nlm.nih.gov/30416054</a></p></li><li><p>Yang, Y, et al., &amp; Balthasar, JP (2017). Investigation of the Influence of Protein-Losing Enteropathy on Monoclonal Antibody Pharmacokinetics in Mice. <i>The AAPS journal</i> 19(6) 1791–1803. DOI:<a href=\"https://doi.org/10.1208/s12248-017-0135-z\">10.1208/s12248-017-0135-z</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/28849396/\">https://pubmed.ncbi.nlm.nih.gov/28849396</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Alfa1Antitrypsin;
