within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B05A_BloodAndRelatedProducts.B05AX01_Erythrocytes;

model Erythrocytes
  extends Pharmacolibrary.Drugs.ATC.B.B05AX01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>B05AX01</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Erythrocytes, or red blood cells, are administered as blood transfusions to treat or prevent anemia resulting from blood loss, surgery, or various medical conditions. They increase the oxygen-carrying capacity of blood. Erythrocyte transfusions are approved and routinely used in clinical medicine.</p><h4>Pharmacokinetics</h4><p>No conventional pharmacokinetic parameters (e.g., volume of distribution, clearance, etc.) are defined for erythrocytes as they are cellular components rather than typical chemical drugs. Their in vivo fate is governed by cell survival, sequestration, and destruction primarily in the spleen and liver. Typical pharmacokinetic modeling is not applicable.</p><h4>References</h4><ol><li><p>Bateman, RM, et al., &amp; Prandi, E (2016). 36th International Symposium on Intensive Care and Emergency Medicine : Brussels, Belgium. 15-18 March 2016. <i>Critical care (London, England)</i> 20(Suppl 2) 94–None. DOI:<a href=\"https://doi.org/10.1186/s13054-016-1208-6\">10.1186/s13054-016-1208-6</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27885969/\">https://pubmed.ncbi.nlm.nih.gov/27885969</a></p></li><li><p>Woo, S, et al., &amp; Jusko, WJ (2008). Population pharmacokinetics and pharmacodynamics of peptidic erythropoiesis receptor agonist (ERA) in healthy volunteers. <i>Journal of clinical pharmacology</i> 48(1) 43–52. DOI:<a href=\"https://doi.org/10.1177/0091270007309702\">10.1177/0091270007309702</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/18025524/\">https://pubmed.ncbi.nlm.nih.gov/18025524</a></p></li><li><p>Zufferey, PJ, et al., &amp; Ollier, E (2021). Exposure-Response Relationship of Tranexamic Acid in Cardiac Surgery. <i>Anesthesiology</i> 134(2) 165–178. DOI:<a href=\"https://doi.org/10.1097/ALN.0000000000003633\">10.1097/ALN.0000000000003633</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33316069/\">https://pubmed.ncbi.nlm.nih.gov/33316069</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Erythrocytes;
