within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins;
package J01CE10_BenzathinePhenoxymethylp
  extends Icons.PackageDrugs;
end J01CE10_BenzathinePhenoxymethylp;
