within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AH08_MeningococcusACYW135TetravalentP
  extends Icons.Package;
end J07AH08_MeningococcusACYW135TetravalentP;
