within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H03B_AntithyroidPreparations;
package H03BX01_Diiodotyrosine
  extends Icons.Package;
end H03BX01_Diiodotyrosine;
