within Pharmacolibrary.Drugs.R_RespiratorySystem.R07A_OtherRespiratorySystemProducts;
package R07AX32_IvacaftorTezacaftorAndElexacafto
  extends Icons.PackageDrugs;
end R07AX32_IvacaftorTezacaftorAndElexacafto;
