within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01R_CombinationsOfAntibacterials;
package J01RA12_CiprofloxacinAndOrnidazo
  extends Icons.PackageDrugs;
end J01RA12_CiprofloxacinAndOrnidazo;
