within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism;
package A11D_VitaminB1PlainAndInCombinationWithVitaminB6AndB1
  extends Icons.PackageDrugs;
end A11D_VitaminB1PlainAndInCombinationWithVitaminB6AndB1;
