within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10A_LipidModifyingAgentsPlain.C10AD52_NicotinicAcidCombinations;

model NicotinicAcidCombinations
  extends Pharmacolibrary.Drugs.ATC.C.C10AD52;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>C10AD52</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Nicotinic acid, also known as niacin, is a lipid-lowering agent used in combination with other agents (such as statins or other lipid-modifying agents). It has historically been employed for the treatment of dyslipidemia by reducing total cholesterol, low-density lipoprotein (LDL), and triglycerides, while increasing high-density lipoprotein (HDL). The use of nicotinic acid combinations has declined in recent years due to unfavorable side effect profiles and lack of outcome benefits shown in recent trials. Approval status for these combinations varies by country, and some combinations have been withdrawn.</p><h4>Pharmacokinetics</h4><p>No specific published pharmacokinetic parameters for nicotinic acid, combinations (ATC C10AD52) in humans are available. The following values are rough estimates based on known pharmacokinetics of oral nicotinic acid in adults; parameters may vary significantly when combined with other agents.</p><h4>References</h4><ol><li><p>Jain, L, et al., &amp; Figg, WD (2011). Population pharmacokinetic analysis of sorafenib in patients with solid tumours. <i>British journal of clinical pharmacology</i> 72(2) 294–305. DOI:<a href=\"https://doi.org/10.1111/j.1365-2125.2011.03963.x\">10.1111/j.1365-2125.2011.03963.x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/21392074/\">https://pubmed.ncbi.nlm.nih.gov/21392074</a></p></li><li><p>He, AR, et al., &amp; Plimack, ER (2019). First-in-Human Phase I Study of Merestinib, an Oral Multikinase Inhibitor, in Patients with Advanced Cancer. <i>The oncologist</i> 24(9) e930–e942. DOI:<a href=\"https://doi.org/10.1634/theoncologist.2018-0411\">10.1634/theoncologist.2018-0411</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30833489/\">https://pubmed.ncbi.nlm.nih.gov/30833489</a></p></li><li><p>Pawaskar, DK, et al., &amp; Jusko, WJ (2013). Physiologically based pharmacokinetic models for everolimus and sorafenib in mice. <i>Cancer chemotherapy and pharmacology</i> 71(5) 1219–1229. DOI:<a href=\"https://doi.org/10.1007/s00280-013-2116-y\">10.1007/s00280-013-2116-y</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/23455451/\">https://pubmed.ncbi.nlm.nih.gov/23455451</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end NicotinicAcidCombinations;
