within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism;
package A03C_AntispasmodicsInCombinationWithPsycholeptics
  extends Icons.PackageDrugs;
end A03C_AntispasmodicsInCombinationWithPsycholeptics;
