within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA04_HaemophilusInfluenzaeBAndPoliomyelitis
  extends Icons.Package;
end J07CA04_HaemophilusInfluenzaeBAndPoliomyelitis;
