within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BX13_AlginicAcid
  extends Icons.Package;
end A02BX13_AlginicAcid;
