within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials.J01DD07_Ceftizoxime;

model Ceftizoxime
  extends Pharmacolibrary.Drugs.ATC.J.J01DD07;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Ceftizoxime</td></tr><tr><td>ATC code:</td><td>J01DD07</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Ceftizoxime is a third-generation cephalosporin antibiotic indicated for the treatment of a variety of bacterial infections including respiratory tract, urinary tract, skin and soft tissue infections. It was previously widely used but has been largely replaced by newer agents and is not commonly used today.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported for healthy adult volunteers after single intravenous injection.</p><h4>References</h4><ol><li><p>Karna, P, et al., &amp; Gooch, WM (1993). Population pharmacokinetics of ceftizoxime in premature newborns. <i>Developmental pharmacology and therapeutics</i> 20(3-4) 135–143. DOI:<a href=\"https://doi.org/10.1159/000457554\">10.1159/000457554</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/7828445/\">https://pubmed.ncbi.nlm.nih.gov/7828445</a></p></li><li><p>Facca, B, et al., &amp; Triesenberg, S (1998). Population pharmacokinetics of ceftizoxime administered by continuous infusion in clinically ill adult patients. <i>Antimicrobial agents and chemotherapy</i> 42(7) 1783–1787. DOI:<a href=\"https://doi.org/10.1128/AAC.42.7.1783\">10.1128/AAC.42.7.1783</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/9661021/\">https://pubmed.ncbi.nlm.nih.gov/9661021</a></p></li><li><p>Blouin, RA, et al., &amp; Stoeckel, K (1989). Pharmacokinetics of intravenous cefetamet (Ro 15-8074) and oral cefetamet pivoxil (Ro 15-8075) in young and elderly subjects. <i>Antimicrobial agents and chemotherapy</i> 33(3) 291–296. DOI:<a href=\"https://doi.org/10.1128/AAC.33.3.291\">10.1128/AAC.33.3.291</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/2729925/\">https://pubmed.ncbi.nlm.nih.gov/2729925</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Ceftizoxime;
