within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AC06_Broxyquinoline
  extends Icons.PackageDrugs;
end G01AC06_Broxyquinoline;
