within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AC03_Chlorquinaldol
  extends Icons.PackageDrugs;
end G01AC03_Chlorquinaldol;
