within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines.J07BB02_InfluenzaInactivatedSplitVirusOrSurfaceAntigen;

model InfluenzaInactivatedSplitVirusOrSurfaceAntigen
  extends Pharmacolibrary.Drugs.ATC.J.J07BB02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>J07BB02</td></tr><td>route:</td><td>intramuscular</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Influenza, inactivated, split virus or surface antigen vaccines are used to prevent influenza (flu) caused by influenza viruses. These vaccines contain inactivated (killed) influenza viruses and are often split or contain only the surface antigens to minimize side effects. They are administered annually and are approved for use in most countries for the prevention of seasonal influenza.</p><h4>Pharmacokinetics</h4><p>No direct pharmacokinetic data published for inactivated, split virus or surface antigen influenza vaccines in humans. As these are vaccines, they are not absorbed, distributed, metabolized, or eliminated in the same way as traditional small-molecule drugs; rather, they elicit an immune response at the injection site.</p><h4>References</h4><ol><li><p>Wormser, GP (1996). Lyme disease vaccine. <i>Infection</i> 24(2) 203–207. DOI:<a href=\"https://doi.org/10.1007/BF01713340\">10.1007/BF01713340</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/8740123/\">https://pubmed.ncbi.nlm.nih.gov/8740123</a></p></li><li><p>Gregoriadis, G, et al., &amp; de Souza, JB (1997). Liposome-mediated DNA vaccination. <i>FEBS letters</i> 402(2-3) 107–110. DOI:<a href=\"https://doi.org/10.1016/s0014-5793(96)01507-4\">10.1016/s0014-5793(96)01507-4</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/9037176/\">https://pubmed.ncbi.nlm.nih.gov/9037176</a></p></li><li><p>Hasanpourghadi, M, et al., &amp; Ertl, HC (2024). A therapeutic HBV vaccine containing a checkpoint modifier enhances CD8+ T cell and antiviral responses. <i>JCI insight</i> 9(21) –. DOI:<a href=\"https://doi.org/10.1172/jci.insight.181067\">10.1172/jci.insight.181067</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39226106/\">https://pubmed.ncbi.nlm.nih.gov/39226106</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end InfluenzaInactivatedSplitVirusOrSurfaceAntigen;
