within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BB02_InfluenzaInactivatedSplitVirusOrSurfaceAntigen
  extends Icons.Package;
end J07BB02_InfluenzaInactivatedSplitVirusOrSurfaceAntigen;
