within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis;
package A02BC07_Dexrabeprazole
  extends Icons.PackageDrugs;
end A02BC07_Dexrabeprazole;
