within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03B_LowCeilingDiureticsExclThiazides;
package C03BA82_ClorexoloneCombinationsW
  extends Icons.PackageDrugs;
end C03BA82_ClorexoloneCombinationsW;
