within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX21_RosuvastatinAndPerindopr
  extends Icons.PackageDrugs;
end C10BX21_RosuvastatinAndPerindopr;
