within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombination;
package S01CA02_PrednisoloneAndAntiinfectives
  extends Icons.Package;
end S01CA02_PrednisoloneAndAntiinfectives;
