within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BA08_AtorvastatinAndOmega3FattyAcids
  extends Icons.Package;
end C10BA08_AtorvastatinAndOmega3FattyAcids;
