within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis;
package A02BD03_LansoprazoleAmoxicillinA
  extends Icons.PackageDrugs;
end A02BD03_LansoprazoleAmoxicillinA;
