within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials;
package J01DD51_CefotaximeAndBetaLactamaseInhibi
  extends Icons.PackageDrugs;
end J01DD51_CefotaximeAndBetaLactamaseInhibi;
