within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX12_AtorvastatinAcetylsalicy
  extends Icons.PackageDrugs;
end C10BX12_AtorvastatinAcetylsalicy;
