within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01X_OtherAntineoplasticAgents.L01XK01_Olaparib;

model Olaparib
  extends Pharmacolibrary.Drugs.ATC.L.L01XK01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>L01XK01</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Olaparib is a poly (ADP-ribose) polymerase (PARP) inhibitor used in the treatment of certain types of cancers, including ovarian, breast, pancreatic, and prostate cancers with BRCA mutations. It is approved for use in multiple countries, including the US and EU.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in adult cancer patients, both sexes, after oral administration of olaparib 300 mg (tablet formulation) twice daily.</p><h4>References</h4><ol><li><p>Zhou, D, et al., &amp; Xu, H (2019). Bridging Olaparib Capsule and Tablet Formulations Using Population Pharmacokinetic Meta-analysis in Oncology Patients. <i>Clinical pharmacokinetics</i> 58(5) 615–625. DOI:<a href=\"https://doi.org/10.1007/s40262-018-0714-x\">10.1007/s40262-018-0714-x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30357650/\">https://pubmed.ncbi.nlm.nih.gov/30357650</a></p></li><li><p>Dong, R, et al., &amp; Zhang, X (2024). Evaluation of Olaparib Tablet Safety and Pharmacokinetics in Healthy Chinese Male Subjects. <i>Drug design, development and therapy</i> 18 5529–5539. DOI:<a href=\"https://doi.org/10.2147/DDDT.S481481\">10.2147/DDDT.S481481</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39650853/\">https://pubmed.ncbi.nlm.nih.gov/39650853</a></p></li><li><p>Bundred, N, et al., &amp; Dixon, JM (2013). Evaluation of the pharmacodynamics and pharmacokinetics of the PARP inhibitor olaparib: a phase I multicentre trial in patients scheduled for elective breast cancer surgery. <i>Investigational new drugs</i> 31(4) 949–958. DOI:<a href=\"https://doi.org/10.1007/s10637-012-9922-7\">10.1007/s10637-012-9922-7</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/23315029/\">https://pubmed.ncbi.nlm.nih.gov/23315029</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Olaparib;
