within Pharmacolibrary.Drugs.V_Various.V10X_OtherTherapeuticRadiopharmaceuticals;
package V10XA53_TositumomabIodine131iTositumomab
  extends Icons.Package;
end V10XA53_TositumomabIodine131iTositumomab;
