within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BH51_SitagliptinAndSimvastati
  extends Icons.PackageDrugs;
end A10BH51_SitagliptinAndSimvastati;
