within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03D_AntispasmodicsInCombinationWithAnalgesics;
package A03DA04_CicloniumAndAnalgesics
  extends Icons.Package;
end A03DA04_CicloniumAndAnalgesics;
