within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials.J01DB10_Cefacetrile;

model Cefacetrile
  extends Pharmacolibrary.Drugs.ATC.J.J01DB10;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>J01DB10</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Cefacetrile is a first-generation cephalosporin antibiotic, primarily used in veterinary medicine for the treatment of bacterial infections caused by susceptible Gram-positive and Gram-negative organisms. It has limited human use and is not currently approved for clinical use in humans in most countries.</p><h4>Pharmacokinetics</h4><p>Data for pharmacokinetics of cefacetrile in humans is scarce. Some estimates are available for parenteral (intravenous) use based on studies in animals and limited human data.</p><h4>References</h4><ol><li><p>Hartman, SJF, et al., &amp; de Wildt, SN (2022). Population pharmacokinetics of intravenous cefotaxime indicates that higher doses are required for critically ill children. <i>The Journal of antimicrobial chemotherapy</i> 77(6) 1725–1732. DOI:<a href=\"https://doi.org/10.1093/jac/dkac095\">10.1093/jac/dkac095</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35383374/\">https://pubmed.ncbi.nlm.nih.gov/35383374</a></p></li><li><p>Maksoud, E, et al., &amp; Jacqz-Aigrain, E (2018). Population Pharmacokinetics of Cefotaxime and Dosage Recommendations in Children with Sickle Cell Disease. <i>Antimicrobial agents and chemotherapy</i> 62(4) –. DOI:<a href=\"https://doi.org/10.1128/AAC.00637-17\">10.1128/AAC.00637-17</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29378711/\">https://pubmed.ncbi.nlm.nih.gov/29378711</a></p></li><li><p>Boast, A, et al., &amp; Gwee, A (2024). Population pharmacokinetic modeling of ceftriaxone in cerebrospinal fluid in children: should we be using once- or twice-daily dosing for meningitis?. <i>Antimicrobial agents and chemotherapy</i> 68(11) e0074724–None. DOI:<a href=\"https://doi.org/10.1128/aac.00747-24\">10.1128/aac.00747-24</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39377581/\">https://pubmed.ncbi.nlm.nih.gov/39377581</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Cefacetrile;
