within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BD16_OmeprazoleAmoxicillinAndRifabuti
  extends Icons.Package;
end A02BD16_OmeprazoleAmoxicillinAndRifabuti;
