within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX12_AtorvastatinAcetylsalicylicAcidAndPerindopril
  extends Icons.Package;
end C10BX12_AtorvastatinAcetylsalicylicAcidAndPerindopril;
