within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A11D_VitaminB1PlainAndInCombinationWithVitaminB6AndB1;
package A11DA02_Sulbutiamine
  extends Icons.PackageDrugs;
end A11DA02_Sulbutiamine;
