within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07C_BetaBlockingAgentsAndOtherDiuretics;
package C07CB02_MetoprololAndOtherDiuret
  extends Icons.PackageDrugs;
end C07CB02_MetoprololAndOtherDiuret;
