within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01E_SulfonamidesAndTrimethoprim;
package J01EE01_SulfamethoxazoleAndTrimethoprim
  extends Icons.Package;
end J01EE01_SulfamethoxazoleAndTrimethoprim;
