within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03E_DiureticsAndPotassiumSparingAgentsInCombination;
package C03EA02_TrichlormethiazideAndPotassiumSparingAgents
  extends Icons.Package;
end C03EA02_TrichlormethiazideAndPotassiumSparingAgents;
