within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03G_GonadotropinsAndOtherOvulationStimulants.G03GA05_FollitropinAlfa;

model FollitropinAlfa
  extends Pharmacolibrary.Drugs.ATC.G.G03GA05;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>FollitropinAlfa</td></tr><tr><td>ATC code:</td><td>G03GA05</td></tr><td>route:</td><td>subcutaneous</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Follitropin alfa is a recombinant human follicle-stimulating hormone (FSH) used primarily in assisted reproductive technology (ART) to induce ovulation in women with infertility problems and stimulate spermatogenesis in men. It is approved for use in fertility treatment.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetics in healthy female volunteers after subcutaneous administration of a single dose.</p><h4>References</h4><ol><li><p>Hoy, SM (2016). XM17 Follitropin Alfa (Ovaleap(®)): A Review in Reproductive Endocrine Disorders. <i>BioDrugs : clinical immunotherapeutics, biopharmaceuticals and gene therapy</i> 30(4) 379–386. DOI:<a href=\"https://doi.org/10.1007/s40259-016-0183-4\">10.1007/s40259-016-0183-4</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27342604/\">https://pubmed.ncbi.nlm.nih.gov/27342604</a></p></li><li><p>Rose, TH, et al., &amp; Ottesen, JT (2016). Characterisation of Population Pharmacokinetics and Endogenous Follicle-Stimulating Hormone (FSH) Levels After Multiple Dosing of a Recombinant Human FSH (FE 999049) in Healthy Women. <i>Drugs in R&amp;D</i> 16(2) 165–172. DOI:<a href=\"https://doi.org/10.1007/s40268-016-0126-z\">10.1007/s40268-016-0126-z</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27139012/\">https://pubmed.ncbi.nlm.nih.gov/27139012</a></p></li><li><p>Abe, Y, &amp; Ozeki, Y (2022). [Pharmacological profile, clinical efficacy, and safety of Follitropin Delta produced by recombinant DNA technology in a human cell line (REKOVELLE. <i>Nihon yakurigaku zasshi. Folia pharmacologica Japonica</i> 157(1) 76–84. DOI:<a href=\"https://doi.org/10.1254/fpj.21079\">10.1254/fpj.21079</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34980816/\">https://pubmed.ncbi.nlm.nih.gov/34980816</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end FollitropinAlfa;
