within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AA15_ChlormadinoneAndEthinyle
  extends Icons.PackageDrugs;
end G03AA15_ChlormadinoneAndEthinyle;
