within Pharmacolibrary.Drugs.D_Dermatologicals.D07B_CorticosteroidsCombinationsWithAntiseptics;
package D07BA01_PrednisoloneAndAntiseptics
  extends Icons.Package;
end D07BA01_PrednisoloneAndAntiseptics;
