within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07F_BetaBlockingAgentsOtherCombinations;
package C07FB13_MetoprololAndAmlodipine
  extends Icons.PackageDrugs;
end C07FB13_MetoprololAndAmlodipine;
