within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX02_PravastatinAndAcetylsalicylicAcid
  extends Icons.Package;
end C10BX02_PravastatinAndAcetylsalicylicAcid;
