within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination;
package G03FA05_MethylnortestosteroneAndEstrogen
  extends Icons.Package;
end G03FA05_MethylnortestosteroneAndEstrogen;
