within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09X_OtherAgentsActingOnTheReninAngiotensinSystem;
package C09XA52_AliskirenAndHydrochlorot
  extends Icons.PackageDrugs;
end C09XA52_AliskirenAndHydrochlorot;
