within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01E_SulfonamidesAndTrimethoprim;
package J01EE04_SulfamoxoleAndTrimethoprim
  extends Icons.Package;
end J01EE04_SulfamoxoleAndTrimethoprim;
