within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AP03_TyphoidPurifiedPolysaccharideAntigen
  extends Icons.Package;
end J07AP03_TyphoidPurifiedPolysaccharideAntigen;
