within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BD52_MeaslesCombinationsWithMumpsAndR
  extends Icons.PackageDrugs;
end J07BD52_MeaslesCombinationsWithMumpsAndR;
