within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A16A_OtherAlimentaryTractAndMetabolismProducts;
package A16AX13_UridineTriacetate
  extends Icons.PackageDrugs;
end A16AX13_UridineTriacetate;
