within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H03B_AntithyroidPreparations;
package H03BC01_PotassiumPerchlorate
  extends Icons.Package;
end H03BC01_PotassiumPerchlorate;
