within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03C_AntispasmodicsInCombinationWithPsycholeptics;
package A03CA06_BevoniumAndPsycholeptics
  extends Icons.Package;
end A03CA06_BevoniumAndPsycholeptics;
