within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD22_MetforminAndEvogliptin
  extends Icons.PackageDrugs;
end A10BD22_MetforminAndEvogliptin;
