within Pharmacolibrary.Drugs.R_RespiratorySystem.R01A_DecongestantsAndOtherNasalPreparationsForTopical;
package R01AD52_PrednisoloneCombinations
  extends Icons.PackageDrugs;
end R01AD52_PrednisoloneCombinations;
