within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FF12_Serplulimab
  extends Icons.Package;
end L01FF12_Serplulimab;
