within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A11C_VitaminAAndDInclCombinationsOfTheTwo;
package A11CC20_CalciumAndVitaminDCombinations
  extends Icons.Package;
end A11CC20_CalciumAndVitaminDCombinations;
