within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02L_AntihypertensivesAndDiureticsInCombination;
package C02LA03_DeserpidineAndDiuretics
  extends Icons.Package;
end C02LA03_DeserpidineAndDiuretics;
