within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AX66_OctenidineCombinations
  extends Icons.Package;
end G01AX66_OctenidineCombinations;
