within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DA10_FimasartanAndDiuretics
  extends Icons.PackageDrugs;
end C09DA10_FimasartanAndDiuretics;
