within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02L_AntihypertensivesAndDiureticsInCombination;
package C02LA02_RescinnamineAndDiuretics
  extends Icons.Package;
end C02LA02_RescinnamineAndDiuretics;
