within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07D_BetaBlockingAgentsThiazidesAndOtherDiuretics;
package C07DB01_AtenololThiazidesAndOtherDiureti
  extends Icons.Package;
end C07DB01_AtenololThiazidesAndOtherDiureti;
