within Pharmacolibrary.Drugs.S_SensoryOrgans.S02C_CorticosteroidsAndAntiinfectivesInCombination;
package S02CA05_FluocinoloneAcetonideAnd
  extends Icons.PackageDrugs;
end S02CA05_FluocinoloneAcetonideAnd;
