within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BX51_CarbenoxoloneCombinationsExclPsycholeptics
  extends Icons.Package;
end A02BX51_CarbenoxoloneCombinationsExclPsycholeptics;
