within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02L_AntihypertensivesAndDiureticsInCombination;
package C02LA07_BietaserpineAndDiuretics
  extends Icons.PackageDrugs;
end C02LA07_BietaserpineAndDiuretics;
