within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombination;
package S01CA12_LoteprednolAndAntiinfectives
  extends Icons.Package;
end S01CA12_LoteprednolAndAntiinfectives;
