within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A08A_AntiobesityPreparationsExclDietProducts;
package A08AA56_EphedrineCombinations
  extends Icons.PackageDrugs;
end A08AA56_EphedrineCombinations;
