within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DB02_OlmesartanMedoxomilAndAm
  extends Icons.PackageDrugs;
end C09DB02_OlmesartanMedoxomilAndAm;
