within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AH09_MeningococcusBMulticomponentVacc
  extends Icons.Package;
end J07AH09_MeningococcusBMulticomponentVacc;
