within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AX09_Dehydroemetine
  extends Icons.Package;
end P01AX09_Dehydroemetine;
