within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03E_DiureticsAndPotassiumSparingAgentsInCombination;
package C03EA04_AltizideAndPotassiumSpar
  extends Icons.PackageDrugs;
end C03EA04_AltizideAndPotassiumSpar;
