within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD10_MetforminAndSaxagliptin
  extends Icons.PackageDrugs;
end A10BD10_MetforminAndSaxagliptin;
