within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01D_VasodilatorsUsedInCardiacDiseases.C01DX21_Serelaxin;

model Serelaxin
  extends Pharmacolibrary.Drugs.ATC.C.C01DX21;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Serelaxin</td></tr><tr><td>ATC code:</td><td>C01DX21</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Serelaxin is a recombinant form of human relaxin-2, a hormone involved in the cardiovascular and renal adaptive changes during pregnancy. It has been developed as a treatment for acute heart failure but is not approved for use by regulatory agencies as of 2024.</p><h4>Pharmacokinetics</h4><p>PK parameters reported in patients with acute heart failure following 48-hour intravenous infusion.</p><h4>References</h4><ol><li><p>Soubret, A, et al., &amp; Dahlke, M (2018). Population pharmacokinetics of serelaxin in patients with acute or chronic heart failure, hepatic or renal impairment, or portal hypertension and in healthy subjects. <i>British journal of clinical pharmacology</i> 84(11) 2572–2585. DOI:<a href=\"https://doi.org/10.1111/bcp.13714\">10.1111/bcp.13714</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30014598/\">https://pubmed.ncbi.nlm.nih.gov/30014598</a></p></li><li><p>Dahlke, M, et al., &amp; Pang, Y (2015). Safety and tolerability of serelaxin, a recombinant human relaxin-2 in development for the treatment of acute heart failure, in healthy Japanese volunteers and a comparison of pharmacokinetics and pharmacodynamics in healthy Japanese and Caucasian populations. <i>Journal of clinical pharmacology</i> 55(4) 415–422. DOI:<a href=\"https://doi.org/10.1002/jcph.433\">10.1002/jcph.433</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25408331/\">https://pubmed.ncbi.nlm.nih.gov/25408331</a></p></li><li><p>Sato, N, et al., &amp; Kawana, M (2015). Multicenter, Randomized, Double-Blinded, Placebo-Controlled Phase II Study of Serelaxin in Japanese Patients With Acute Heart Failure. <i>Circulation journal : official journal of the Japanese Circulation Society</i> 79(6) 1237–1247. DOI:<a href=\"https://doi.org/10.1253/circj.CJ-15-0227\">10.1253/circj.CJ-15-0227</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25912697/\">https://pubmed.ncbi.nlm.nih.gov/25912697</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Serelaxin;
