within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L03A_Immunostimulants.L03AX19_DasiprotimutT;

model DasiprotimutT
  extends Pharmacolibrary.Drugs.ATC.L.L03AX19;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>DasiprotimutT</td></tr><tr><td>ATC code:</td><td>L03AX19</td></tr><td>route:</td><td>subcutaneous</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Dasiprotimut-T is a therapeutic cancer vaccine consisting of a pool of seven synthetic peptides derived from tumor-associated antigens (TAAs) conjugated to keyhole limpet hemocyanin and mixed with Granulocyte-Macrophage Colony-Stimulating Factor (GM-CSF) as an adjuvant. It has been primarily investigated for use in melanoma as an immunotherapeutic agent. It is not approved for general clinical use at this time and remains in clinical trial investigations.</p><h4>Pharmacokinetics</h4><p>No published pharmacokinetic (PK) parameters have been reported in the literature for dasiprotimut-T in any specific population or setting, as is typical for vaccine-based immunotherapies composed of peptides and adjuvants.</p><h4>References</h4><ol><li><p>Schneck, K, &amp; Urva, S (2024). Population pharmacokinetics of the GIP/GLP receptor agonist tirzepatide. <i>CPT: pharmacometrics &amp; systems pharmacology</i> 13(3) 494–503. DOI:<a href=\"https://doi.org/10.1002/psp4.13099\">10.1002/psp4.13099</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/38356317/\">https://pubmed.ncbi.nlm.nih.gov/38356317</a></p></li><li><p>Yang, XD, &amp; Yang, YY (2024). Clinical Pharmacokinetics of Semaglutide: A Systematic Review. <i>Drug design, development and therapy</i> 18 2555–2570. DOI:<a href=\"https://doi.org/10.2147/DDDT.S470826\">10.2147/DDDT.S470826</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/38952487/\">https://pubmed.ncbi.nlm.nih.gov/38952487</a></p></li><li><p>Overgaard, RV, et al., &amp; Ingwersen, SH (2019). Population Pharmacokinetics of Semaglutide for Type 2 Diabetes. <i>Diabetes therapy : research, treatment and education of diabetes and related disorders</i> 10(2) 649–662. DOI:<a href=\"https://doi.org/10.1007/s13300-019-0581-y\">10.1007/s13300-019-0581-y</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30788808/\">https://pubmed.ncbi.nlm.nih.gov/30788808</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end DasiprotimutT;
