within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination;
package G03FB01_NorgestrelAndEstrogen
  extends Icons.PackageDrugs;
end G03FB01_NorgestrelAndEstrogen;
