within Pharmacolibrary.Drugs.C_CardiovascularSystem;
package C08C_SelectiveCalciumChannelBlockersWithMainlyVascula
  extends Icons.PackageDrugs;
end C08C_SelectiveCalciumChannelBlockersWithMainlyVascula;
