within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AP52_DasabuvirOmbitasvirParitaprevirA
  extends Icons.Package;
end J05AP52_DasabuvirOmbitasvirParitaprevirA;
