within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A08A_AntiobesityPreparationsExclDietProducts;
package A08AA51_PhentermineAndTopiramate
  extends Icons.Package;
end A08AA51_PhentermineAndTopiramate;
