within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombina;
package S01CA01_DexamethasoneAndAntiinfe
  extends Icons.PackageDrugs;
end S01CA01_DexamethasoneAndAntiinfe;
