within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A16A_OtherAlimentaryTractAndMetabolismProducts;
package A16AB10_VelagluceraseAlfa
  extends Icons.PackageDrugs;
end A16AB10_VelagluceraseAlfa;
