within Pharmacolibrary.Drugs.C_CardiovascularSystem;
package C05A_AgentsForTreatmentOfHemorrhoidsAndAnalFissuresFo
  extends Icons.PackageDrugs;
end C05A_AgentsForTreatmentOfHemorrhoidsAndAnalFissuresFo;
