within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10A_LipidModifyingAgentsPlain;
package C10AX07_MagnesiumPyridoxal5PhosphateGlut
  extends Icons.PackageDrugs;
end C10AX07_MagnesiumPyridoxal5PhosphateGlut;
