within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX08_Elotuzumab
  extends Icons.PackageDrugs;
end L01FX08_Elotuzumab;
