within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AA08_MedroxyprogesteroneAndEthinylestradiol
  extends Icons.Package;
end G03AA08_MedroxyprogesteroneAndEthinylestradiol;
