within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03G_GonadotropinsAndOtherOvulationStimulants;
package G03GA10_FollitropinDelta
  extends Icons.PackageDrugs;
end G03GA10_FollitropinDelta;
