within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BB02_InfluenzaInactivatedSplitVirusOr
  extends Icons.PackageDrugs;
end J07BB02_InfluenzaInactivatedSplitVirusOr;
