within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AR01_TyphusExanthematicusInactivatedW
  extends Icons.Package;
end J07AR01_TyphusExanthematicusInactivatedW;
