within Pharmacolibrary.Drugs.N_NervousSystem.N05C_HypnoticsAndSedatives.N05CD14_Remimazolam;

model Remimazolam
  extends Pharmacolibrary.Drugs.ATC.N.N05CD14;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>N05CD14</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>3</td></tr></table><p>Remimazolam is a short-acting benzodiazepine anesthetic used for induction and maintenance of procedural sedation and general anesthesia. It is distinguished by its rapid metabolism via tissue esterases and is approved for use in several countries for procedural sedation and general anesthesia.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters in healthy adult subjects (male and female) following single and multiple intravenous doses.</p><h4>References</h4><ol><li><p>Gao, YQ, et al., &amp; Liu, HC (2023). Pharmacokinetics of remimazolam after intravenous infusion in anaesthetised children. <i>British journal of anaesthesia</i> 131(5) 914–920. DOI:<a href=\"https://doi.org/10.1016/j.bja.2023.08.019\">10.1016/j.bja.2023.08.019</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37739904/\">https://pubmed.ncbi.nlm.nih.gov/37739904</a></p></li><li><p>Kim, SH, &amp; Fechner, J (2022). Remimazolam - current knowledge on a new intravenous benzodiazepine anesthetic agent. <i>Korean journal of anesthesiology</i> 75(4) 307–315. DOI:<a href=\"https://doi.org/10.4097/kja.22297\">10.4097/kja.22297</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35585830/\">https://pubmed.ncbi.nlm.nih.gov/35585830</a></p></li><li><p>Schüttler, J, et al., &amp; Ihmsen, H (2020). Pharmacokinetics and Pharmacodynamics of Remimazolam (CNS 7056) after Continuous Infusion in Healthy Male Volunteers: Part I. Pharmacokinetics and Clinical Pharmacodynamics. <i>Anesthesiology</i> 132(4) 636–651. DOI:<a href=\"https://doi.org/10.1097/ALN.0000000000003103\">10.1097/ALN.0000000000003103</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31972655/\">https://pubmed.ncbi.nlm.nih.gov/31972655</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Remimazolam;
