within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD12_PioglitazoneAndSitagliptin
  extends Icons.Package;
end A10BD12_PioglitazoneAndSitagliptin;
