within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FG02_Ramucirumab
  extends Icons.Package;
end L01FG02_Ramucirumab;
