within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BD02_LansoprazoleTetracyclineAndMetronidazole
  extends Icons.Package;
end A02BD02_LansoprazoleTetracyclineAndMetronidazole;
