within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AR09_EmtricitabineTenofovirDisoproxil
  extends Icons.Package;
end J05AR09_EmtricitabineTenofovirDisoproxil;
