within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BA53_FamotidineCombinations
  extends Icons.Package;
end A02BA53_FamotidineCombinations;
