within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD27_MetforminLinagliptinAndE
  extends Icons.PackageDrugs;
end A10BD27_MetforminLinagliptinAndE;
