within Pharmacolibrary.Drugs.N_NervousSystem.N07X_OtherNervousSystemDrugs;
package N07XX19_SodiumPhenylbutyrateAndUrsodoxicoltaurine
  extends Icons.Package;
end N07XX19_SodiumPhenylbutyrateAndUrsodoxicoltaurine;
