within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX16_OportuzumabMonatox
  extends Icons.Package;
end L01FX16_OportuzumabMonatox;
