within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AA01_EtynodiolAndEthinylestradiol
  extends Icons.Package;
end G03AA01_EtynodiolAndEthinylestradiol;
