within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M03B_MuscleRelaxantsCentrallyActingAgents;
package M03BB53_ChlorzoxazoneCombinationsExclPsycholeptics
  extends Icons.Package;
end M03BB53_ChlorzoxazoneCombinationsExclPsycholeptics;
