within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BD15_VonoprazanAmoxicillinAndMetronid
  extends Icons.Package;
end A02BD15_VonoprazanAmoxicillinAndMetronid;
