within Pharmacolibrary.Drugs.D_Dermatologicals.D07B_CorticosteroidsCombinationsWithAntiseptics;
package D07BA01_PrednisoloneAndAntisepti
  extends Icons.PackageDrugs;
end D07BA01_PrednisoloneAndAntisepti;
