within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination;
package G03FB12_NomegestrolAndEstrogen
  extends Icons.Package;
end G03FB12_NomegestrolAndEstrogen;
