within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01D_VasodilatorsUsedInCardiacDiseases;
package C01DA63_EritritylTetranitrateCom
  extends Icons.PackageDrugs;
end C01DA63_EritritylTetranitrateCom;
