within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FF05_Atezolizumab
  extends Icons.PackageDrugs;
end L01FF05_Atezolizumab;
