within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H01A_AnteriorPituitaryLobeHormonesAndAnalogues;
package H01AC08_Somatrogon
  extends Icons.Package;
end H01AC08_Somatrogon;
