within Pharmacolibrary.Drugs.C_CardiovascularSystem.C05A_AgentsForTreatmentOfHemorrhoidsAndAnalFissuresForTopicalUse.C05AA01_Hydrocortisone;
model Hydrocortisone = Pharmacolibrary.Drugs.ATC.C.C05AA01;