within Pharmacolibrary.Drugs.C_CardiovascularSystem.C05A_AgentsForTreatmentOfHemorrhoidsAndAnalFissuresForTopicalUse;
package C05AA01_Hydrocortisone
  extends Icons.Package;
end C05AA01_Hydrocortisone;
