within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B01A_AntithromboticAgents;
package B01AC30_AcetylsalicylicAcidAndDipyridamoleCombination
  extends Icons.Package;
end B01AC30_AcetylsalicylicAcidAndDipyridamoleCombination;
