within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombination;
package S01CA03_HydrocortisoneAndAntiinfectives
  extends Icons.Package;
end S01CA03_HydrocortisoneAndAntiinfectives;
