within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01B_Antimalarials;
package P01BF09_ArtesunateSulfadoxineAnd
  extends Icons.PackageDrugs;
end P01BF09_ArtesunateSulfadoxineAnd;
