within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD06_GlimepirideAndPioglitazo
  extends Icons.PackageDrugs;
end A10BD06_GlimepirideAndPioglitazo;
