within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A11A_MultivitaminsCombinations;
package A11AA03_MultivitaminsAndOtherMin
  extends Icons.PackageDrugs;
end A11AA03_MultivitaminsAndOtherMin;
