within Pharmacolibrary.Drugs.D_Dermatologicals.D04A_AntipruriticsInclAntihistaminesAnestheticsEtc;
package D04AA33_DiphenhydramineMethylbromide
  extends Icons.Package;
end D04AA33_DiphenhydramineMethylbromide;
