within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07A_BetaBlockingAgents.C07AG01_Labetalol;

model Labetalol
  extends Pharmacolibrary.Drugs.ATC.C.C07AG01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Labetalol</td></tr><tr><td>ATC code:</td><td>C07AG01</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Labetalol is a combined alpha- and beta-adrenergic receptor antagonist used primarily for the treatment of hypertension, including hypertensive emergencies and chronic hypertension. It is approved for clinical use and is widely prescribed today.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters derived from healthy adult volunteers after a single intravenous dose.</p><h4>References</h4><ol><li><p>Chera-Aree, P, et al., &amp; Wataganara, T (2020). Clinical Experiences of Intravenous Hydralazine and Labetalol for Acute Treatment of Severe Hypertension in Pregnant Thai Women. <i>Journal of clinical pharmacology</i> 60(12) 1662–1670. DOI:<a href=\"https://doi.org/10.1002/jcph.1685\">10.1002/jcph.1685</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32598488/\">https://pubmed.ncbi.nlm.nih.gov/32598488</a></p></li><li><p>Hafsa, H, et al., &amp; Alqahtani, F (2022). Development and Evaluation of a Physiologically Based Pharmacokinetic Model of Labetalol in Healthy and Diseased Populations. <i>Pharmaceutics</i> 14(11) –. DOI:<a href=\"https://doi.org/10.3390/pharmaceutics14112362\">10.3390/pharmaceutics14112362</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36365181/\">https://pubmed.ncbi.nlm.nih.gov/36365181</a></p></li><li><p>Rasmussen, BB, et al., &amp; Senderovitz, T (2005). Pharmacokinetic interaction studies of atosiban with labetalol or betamethasone in healthy female volunteers. <i>BJOG : an international journal of obstetrics and gynaecology</i> 112(11) 1492–1499. DOI:<a href=\"https://doi.org/10.1111/j.1471-0528.2005.00735.x\">10.1111/j.1471-0528.2005.00735.x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/16225568/\">https://pubmed.ncbi.nlm.nih.gov/16225568</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Labetalol;
