within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombina;
package S01CA07_FluorometholoneAndAntiin
  extends Icons.PackageDrugs;
end S01CA07_FluorometholoneAndAntiin;
