within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01R_CombinationsOfAntibacterials;
package J01RA14_NorfloxacinAndMetronidazole
  extends Icons.Package;
end J01RA14_NorfloxacinAndMetronidazole;
