within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01B_AntiinflammatoryAntirheumaticAgentsInCombination;
package M01BA02_DipyrocetylAndCorticosteroids
  extends Icons.Package;
end M01BA02_DipyrocetylAndCorticosteroids;
