within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B02B_VitaminKAndOtherHemostatics.B02BD08_CoagulationFactorViia;

model CoagulationFactorViia
  extends Pharmacolibrary.Drugs.ATC.B.B02BD08;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>CoagulationFactorViia</td></tr><tr><td>ATC code:</td><td>B02BD08</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Coagulation factor VIIa (recombinant) is a hemostatic agent used for treatment and prevention of bleeding episodes in patients with hemophilia A or B with inhibitors to factor VIII or IX, congenital factor VII deficiency, Glanzmann's thrombasthenia, and other acquired bleeding disorders. It is approved and widely used in clinical practice, particularly in emergency situations for controlling major bleeding.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetics reported in healthy adult volunteers (both sexes), intravenous bolus administration.</p><h4>References</h4><ol><li><p>Agersø, H, et al., &amp; Ezban, M (2011). Recombinant human factor VIIa (rFVIIa) cleared principally by antithrombin following intravenous administration in hemophilia patients. <i>Journal of thrombosis and haemostasis : JTH</i> 9(2) 333–338. DOI:<a href=\"https://doi.org/10.1111/j.1538-7836.2010.04152.x\">10.1111/j.1538-7836.2010.04152.x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/21114621/\">https://pubmed.ncbi.nlm.nih.gov/21114621</a></p></li><li><p>McConachie, SM, et al., &amp; Wilhelm, SM (2018). Pharmacotherapy in Acutely Anemic Jehovah&#x27;s Witnesses: An Evidence-Based Review. <i>The Annals of pharmacotherapy</i> 52(9) 910–919. DOI:<a href=\"https://doi.org/10.1177/1060028018766656\">10.1177/1060028018766656</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29592539/\">https://pubmed.ncbi.nlm.nih.gov/29592539</a></p></li><li><p>Shapiro, A (2003). Inhibitor treatment: state of the art. <i>Disease-a-month : DM</i> 49(1) 22–38. DOI:<a href=\"https://doi.org/10.1053/shem.2001.29506b\">10.1053/shem.2001.29506b</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/12525826/\">https://pubmed.ncbi.nlm.nih.gov/12525826</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end CoagulationFactorViia;
