within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07F_BetaBlockingAgentsOtherCombinations;
package C07FX04_BisoprololAndAcetylsalicylicAcid
  extends Icons.Package;
end C07FX04_BisoprololAndAcetylsalicylicAcid;
