within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01E_SulfonamidesAndTrimethoprim;
package J01EE07_SulfamerazineAndTrimethoprim
  extends Icons.Package;
end J01EE07_SulfamerazineAndTrimethoprim;
