within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AR03_TenofovirDisoproxilAndEmtricitab
  extends Icons.PackageDrugs;
end J05AR03_TenofovirDisoproxilAndEmtricitab;
