within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10A_InsulinsAndAnalogues;
package A10AB30_InsulinDegludecAndInsulinAspartCombination
  extends Icons.Package;
end A10AB30_InsulinDegludecAndInsulinAspartCombination;
