within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA06_DiphtheriaHaemophilusInfluenzaeBPertussisPoliomyelitisTetanus
  extends Icons.Package;
end J07CA06_DiphtheriaHaemophilusInfluenzaeBPertussisPoliomyelitisTetanus;
