within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FB01_InotuzumabOzogamicin
  extends Icons.Package;
end L01FB01_InotuzumabOzogamicin;
