within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials;
package J01DD62_CefoperazoneAndBetaLactamaseInhi
  extends Icons.PackageDrugs;
end J01DD62_CefoperazoneAndBetaLactamaseInhi;
