within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX01_SimvastatinAndAcetylsalicylicAcid
  extends Icons.Package;
end C10BX01_SimvastatinAndAcetylsalicylicAcid;
