within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BJ51_RubellaCombinationsWithMumpsLiveAttenuated
  extends Icons.Package;
end J07BJ51_RubellaCombinationsWithMumpsLiveAttenuated;
