within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P03B_InsecticidesAndRepellents;
package P03BX01_Diethyltoluamide
  extends Icons.PackageDrugs;
end P03BX01_Diethyltoluamide;
