within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DX03_OlmesartanMedoxomilAmlodipineAnd
  extends Icons.Package;
end C09DX03_OlmesartanMedoxomilAmlodipineAnd;
