within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AH07_MeningococcusCPurifiedPolysaccha
  extends Icons.PackageDrugs;
end J07AH07_MeningococcusCPurifiedPolysaccha;
