within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BA67_MagnesiumSalicylateCombinationsExclPsycholeptics
  extends Icons.Package;
end N02BA67_MagnesiumSalicylateCombinationsExclPsycholeptics;
