within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AF02_Clotrimazole
  extends Icons.PackageDrugs;
end G01AF02_Clotrimazole;
