within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01C_AgentsAgainstLeishmaniasisAndTrypanosomiasis;
package P01CB01_MeglumineAntimonate
  extends Icons.Package;
end P01CB01_MeglumineAntimonate;
