within Pharmacolibrary.Drugs.R_RespiratorySystem.R03D_OtherSystemicDrugsForObstructiveAirwayDiseases;
package R03DA51_DiprophyllineCombination
  extends Icons.PackageDrugs;
end R03DA51_DiprophyllineCombination;
