within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03A_DrugsForFunctionalGastrointestinalDisorders;
package A03AB06_OtiloniumBromide
  extends Icons.PackageDrugs;
end A03AB06_OtiloniumBromide;
