within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA12_DiphtheriaPertussisPolio
  extends Icons.PackageDrugs;
end J07CA12_DiphtheriaPertussisPolio;
