within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H02A_CorticosteroidsForSystemicUsePlain;
package H02AB15_Meprednisone
  extends Icons.PackageDrugs;
end H02AB15_Meprednisone;
