within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M03B_MuscleRelaxantsCentrallyActingAgents;
package M03BC51_OrphenadrineCombinations
  extends Icons.Package;
end M03BC51_OrphenadrineCombinations;
