within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FF04_Avelumab
  extends Icons.PackageDrugs;
end L01FF04_Avelumab;
