within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AX02_Emetine
  extends Icons.PackageDrugs;
end P01AX02_Emetine;
