within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX27_Epcoritamab
  extends Icons.PackageDrugs;
end L01FX27_Epcoritamab;
