within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M05B_DrugsAffectingBoneStructureAndMineralization;
package M05BB08_ZoledronicAcidCalciumAndColecalciferolSequential
  extends Icons.Package;
end M05BB08_ZoledronicAcidCalciumAndColecalciferolSequential;
