within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A12B_Potassium;
package A12BA30_PotassiumDifferentSaltsInCombination
  extends Icons.Package;
end A12BA30_PotassiumDifferentSaltsInCombination;
