within Pharmacolibrary.Drugs.V_Various.V03A_AllOtherTherapeuticProducts.V03AN05_MedicalAir;

model MedicalAir
  extends Pharmacolibrary.Drugs.ATC.V.V03AN05;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>MedicalAir</td></tr><tr><td>ATC code:</td><td>V03AN05</td></tr><td>route:</td><td>inhalation</td></tr><tr><td>n-compartments</td><td>0</td></tr></table><p>Medical air is a mixture of gases, primarily nitrogen and oxygen, which is used clinically as a medical gas to support respiration or as a carrier gas for inhaled drugs. It is administered through controlled ventilation and is not itself a pharmaceutical agent with direct pharmacological activity. Medical air is widely approved and used in hospitals and other healthcare settings globally.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic modeling is not applicable to medical air as it is not absorbed, distributed, metabolized, or eliminated in the body in the way typical drug substances are. It is composed of atmospheric air and behaves as a gaseous exchange medium in the lungs.</p><h4>References</h4><ol><li><p>Bateman, RM, et al., &amp; Prandi, E (2016). 36th International Symposium on Intensive Care and Emergency Medicine : Brussels, Belgium. 15-18 March 2016. <i>Critical care (London, England)</i> 20(Suppl 2) 94–None. DOI:<a href=\"https://doi.org/10.1186/s13054-016-1208-6\">10.1186/s13054-016-1208-6</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27885969/\">https://pubmed.ncbi.nlm.nih.gov/27885969</a></p></li><li><p>Merkel, OM, &amp; Kissel, T (2012). Nonviral pulmonary delivery of siRNA. <i>Accounts of chemical research</i> 45(7) 961–970. DOI:<a href=\"https://doi.org/10.1021/ar200110p\">10.1021/ar200110p</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/21905687/\">https://pubmed.ncbi.nlm.nih.gov/21905687</a></p></li><li><p>Oberdörster, G (2001). Pulmonary effects of inhaled ultrafine particles. <i>International archives of occupational and environmental health</i> 74(1) 1–8. DOI:<a href=\"https://doi.org/10.1007/s004200000185\">10.1007/s004200000185</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/11196075/\">https://pubmed.ncbi.nlm.nih.gov/11196075</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end MedicalAir;
