within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AA11_Pentamycin
  extends Icons.PackageDrugs;
end G01AA11_Pentamycin;
