within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H03B_AntithyroidPreparations;
package H03BB52_ThiamazoleCombinations
  extends Icons.Package;
end H03BB52_ThiamazoleCombinations;
