within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AA13_NorelgestrominAndEthinyl
  extends Icons.PackageDrugs;
end G03AA13_NorelgestrominAndEthinyl;
