within Pharmacolibrary.Drugs.S_SensoryOrgans.S01A_Antiinfectives.S01AD03_Aciclovir;

model Aciclovir
  extends Pharmacolibrary.Drugs.ATC.S.S01AD03;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>S01AD03</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Aciclovir is an antiviral medication primarily used for the treatment of herpes simplex virus and varicella-zoster virus infections, including shingles and genital herpes. It is well-established and widely approved for clinical use in many countries.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported for healthy adult volunteers after a single oral dose of aciclovir.</p><h4>References</h4><ol><li><p>Nguyen, T, et al., &amp; Hirt, D (2021). Population Pharmacokinetics of Intravenous Ganciclovir and Oral Valganciclovir in a Pediatric Population To Optimize Dosing Regimens. <i>Antimicrobial agents and chemotherapy</i> 65(3) –. DOI:<a href=\"https://doi.org/10.1128/AAC.02254-20\">10.1128/AAC.02254-20</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33318012/\">https://pubmed.ncbi.nlm.nih.gov/33318012</a></p></li><li><p>Abdalla, S, et al., &amp; Hirt, D (2020). Population Pharmacokinetics of Intravenous and Oral Acyclovir and Oral Valacyclovir in Pediatric Population To Optimize Dosing Regimens. <i>Antimicrobial agents and chemotherapy</i> 64(12) –. DOI:<a href=\"https://doi.org/10.1128/AAC.01426-20\">10.1128/AAC.01426-20</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32988829/\">https://pubmed.ncbi.nlm.nih.gov/32988829</a></p></li><li><p>Tod, M, et al., &amp; Aujard, Y (2001). Pharmacokinetics of oral acyclovir in neonates and in infants: a population analysis. <i>Antimicrobial agents and chemotherapy</i> 45(1) 150–157. DOI:<a href=\"https://doi.org/10.1128/AAC.45.1.150-157.2001\">10.1128/AAC.45.1.150-157.2001</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/11120958/\">https://pubmed.ncbi.nlm.nih.gov/11120958</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Aciclovir;
