within Pharmacolibrary.Drugs.N_NervousSystem.N02A_Opioids;
package N02AC54_DextropropoxypheneCombinationsExclPsycholeptics
  extends Icons.Package;
end N02AC54_DextropropoxypheneCombinationsExclPsycholeptics;
