within Pharmacolibrary.Drugs.C_CardiovascularSystem;
package C08C_SelectiveCalciumChannelBlockersWithMainlyVascularEffects
  extends Icons.Package;
end C08C_SelectiveCalciumChannelBlockersWithMainlyVascularEffects;
