within Pharmacolibrary.Drugs.D_Dermatologicals.D07C_CorticosteroidsCombinationsWithAntibiotics;
package D07CD01_ClobetasolAndAntibiotics
  extends Icons.Package;
end D07CD01_ClobetasolAndAntibiotics;
