within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J06B_Immunoglobulins;
package J06BA01_ImmunoglobulinsNormalHumanForExt
  extends Icons.PackageDrugs;
end J06BA01_ImmunoglobulinsNormalHumanForExt;
