within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03C_AntispasmodicsInCombinationWithPsycholeptics;
package A03CA05_GlycopyrroniumBromideAndPsycholeptics
  extends Icons.Package;
end A03CA05_GlycopyrroniumBromideAndPsycholeptics;
