within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01X_OtherAntineoplasticAgents;
package L01XL06_BrexucabtageneAutoleucel
  extends Icons.PackageDrugs;
end L01XL06_BrexucabtageneAutoleucel;
