within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BA67_MagnesiumSalicylateCombinationsE
  extends Icons.PackageDrugs;
end N02BA67_MagnesiumSalicylateCombinationsE;
