within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AX09_Methylrosaniline
  extends Icons.PackageDrugs;
end G01AX09_Methylrosaniline;
