within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis;
package A02BD04_PantoprazoleAmoxicillinA
  extends Icons.PackageDrugs;
end A02BD04_PantoprazoleAmoxicillinA;
