within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M03B_MuscleRelaxantsCentrallyActingAgents;
package M03BB52_ChlormezanoneCombinationsExclPsycholeptics
  extends Icons.Package;
end M03BB52_ChlormezanoneCombinationsExclPsycholeptics;
