within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FF11_Sugemalimab
  extends Icons.Package;
end L01FF11_Sugemalimab;
