within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BH02_RotaVirusPentavalentLiveReassort
  extends Icons.PackageDrugs;
end J07BH02_RotaVirusPentavalentLiveReassort;
