within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BA75_SalicylamideCombinationsWithPsycholeptics
  extends Icons.Package;
end N02BA75_SalicylamideCombinationsWithPsycholeptics;
