within Pharmacolibrary.Drugs.R_RespiratorySystem.R03A_AdrenergicsInhalants;
package R03AK01_EpinephrineAndOtherDrugsForObstructiveAirwayDiseases
  extends Icons.Package;
end R03AK01_EpinephrineAndOtherDrugsForObstructiveAirwayDiseases;
