within Pharmacolibrary.Drugs.D_Dermatologicals.D07C_CorticosteroidsCombinationsWithAntibiotics;
package D07CA02_MethylprednisoloneAndAnt
  extends Icons.PackageDrugs;
end D07CA02_MethylprednisoloneAndAnt;
