within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins;
package J01CE30_PhenoxymethylpenicillinAndSulfonamidesCombinations
  extends Icons.Package;
end J01CE30_PhenoxymethylpenicillinAndSulfonamidesCombinations;
