within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AA08_Carfecillin
  extends Icons.Package;
end G01AA08_Carfecillin;
