within Pharmacolibrary.Drugs.R_RespiratorySystem.R03D_OtherSystemicDrugsForObstructiveAirwayDiseases;
package R03DB06_EtamiphyllineAndAdrenerg
  extends Icons.PackageDrugs;
end R03DB06_EtamiphyllineAndAdrenerg;
