within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J04A_DrugsForTreatmentOfTuberculosis;
package J04AM02_RifampicinAndIsoniazid
  extends Icons.PackageDrugs;
end J04AM02_RifampicinAndIsoniazid;
