within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J04A_DrugsForTreatmentOfTuberculosis.J04AM02_RifampicinAndIsoniazid;

model RifampicinAndIsoniazid
  extends Pharmacolibrary.Drugs.ATC.J.J04AM02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>RifampicinAndIsoniazid</td></tr><tr><td>ATC code:</td><td>J04AM02</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Rifampicin and isoniazid is a fixed-dose combination medication used primarily in the treatment of tuberculosis. Rifampicin acts by inhibiting DNA-dependent RNA polymerase in bacterial cells, while isoniazid interferes with mycolic acid synthesis in the Mycobacterium tuberculosis cell wall. This combination is recommended by the World Health Organization and is included in essential medicines lists globally.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters estimated for a typical adult patient, as published population PK models for the fixed-dose combination are limited. Parameters are based on literature-reported values of rifampicin and isoniazid administered orally.</p><h4>References</h4><ol><li><p>Sullins, AK, &amp; Abdel-Rahman, SM (2013). Pharmacokinetics of antibacterial agents in the CSF of children and adolescents. <i>Paediatric drugs</i> 15(2) 93–117. DOI:<a href=\"https://doi.org/10.1007/s40272-013-0017-5\">10.1007/s40272-013-0017-5</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/23529866/\">https://pubmed.ncbi.nlm.nih.gov/23529866</a></p></li><li><p>Chen, C, et al., &amp; Simonsson, US (2016). Population pharmacokinetics, optimised design and sample size determination for rifampicin, isoniazid, ethambutol and pyrazinamide in the mouse. <i>European journal of pharmaceutical sciences : official journal of the European Federation for Pharmaceutical Sciences</i> 93 319–333. DOI:<a href=\"https://doi.org/10.1016/j.ejps.2016.07.017\">10.1016/j.ejps.2016.07.017</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27473307/\">https://pubmed.ncbi.nlm.nih.gov/27473307</a></p></li><li><p>Zvada, SP, et al., &amp; Simonsson, US (2014). Population pharmacokinetics of rifampicin, pyrazinamide and isoniazid in children with tuberculosis: in silico evaluation of currently recommended doses. <i>The Journal of antimicrobial chemotherapy</i> 69(5) 1339–1349. DOI:<a href=\"https://doi.org/10.1093/jac/dkt524\">10.1093/jac/dkt524</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/24486870/\">https://pubmed.ncbi.nlm.nih.gov/24486870</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end RifampicinAndIsoniazid;
