within Pharmacolibrary.Drugs.R_RespiratorySystem.R03D_OtherSystemicDrugsForObstructiveAirwayDiseases;
package R03DB05_AminophyllineAndAdrenerg
  extends Icons.PackageDrugs;
end R03DB05_AminophyllineAndAdrenerg;
