within Pharmacolibrary.Drugs.D_Dermatologicals.D07B_CorticosteroidsCombinationsWithAntiseptics;
package D07BC03_FluocortoloneAndAntisept
  extends Icons.PackageDrugs;
end D07BC03_FluocortoloneAndAntisept;
