within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L03A_Immunostimulants.L03AB03_InterferonGamma;

model InterferonGamma
  extends Pharmacolibrary.Drugs.ATC.L.L03AB03;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>InterferonGamma</td></tr><tr><td>ATC code:</td><td>L03AB03</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Interferon gamma (IFN-γ) is a cytokine produced by lymphocytes, especially T-lymphocytes and natural killer cells, and is involved in innate and adaptive immunity. Recombinant human interferon gamma is used as an immunomodulatory agent in the treatment of chronic granulomatous disease and severe malignant osteopetrosis. It is approved for use in certain immune deficiencies and is not typically used in standard antiviral therapy.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported for healthy adult volunteers after a single intravenous dose of recombinant human interferon gamma.</p><h4>References</h4><ol><li><p>Wlodek, E, et al., &amp; Devey, L (2021). A pilot study evaluating GSK1070806 inhibition of interleukin-18 in renal transplant delayed graft function. <i>PloS one</i> 16(3) e0247972–None. DOI:<a href=\"https://doi.org/10.1371/journal.pone.0247972\">10.1371/journal.pone.0247972</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33684160/\">https://pubmed.ncbi.nlm.nih.gov/33684160</a></p></li><li><p>Ellis, J, et al., &amp; Fernando, D (2019). Anti-IL-7 receptor α monoclonal antibody (GSK2618960) in healthy subjects - a randomized, double-blind, placebo-controlled study. <i>British journal of clinical pharmacology</i> 85(2) 304–315. DOI:<a href=\"https://doi.org/10.1111/bcp.13748\">10.1111/bcp.13748</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30161291/\">https://pubmed.ncbi.nlm.nih.gov/30161291</a></p></li><li><p>Wingender, G, et al., &amp; Knolle, PA (2006). Rapid and preferential distribution of blood-borne alphaCD3epsilonAb to the liver is followed by local stimulation of T cells and natural killer T cells. <i>Immunology</i> 117(1) 117–126. DOI:<a href=\"https://doi.org/10.1111/j.1365-2567.2005.02272.x\">10.1111/j.1365-2567.2005.02272.x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/16423047/\">https://pubmed.ncbi.nlm.nih.gov/16423047</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end InterferonGamma;
