within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AA07_LevonorgestrelAndEthinylestradiol
  extends Icons.Package;
end G03AA07_LevonorgestrelAndEthinylestradiol;
