within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AR02_Difetarsone
  extends Icons.Package;
end P01AR02_Difetarsone;
