within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AE01_Sulfatolamide
  extends Icons.Package;
end G01AE01_Sulfatolamide;
