within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AB03_LevonorgestrelAndEthinyl
  extends Icons.PackageDrugs;
end G03AB03_LevonorgestrelAndEthinyl;
