within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD23_MetforminAndErtugliflozi
  extends Icons.PackageDrugs;
end A10BD23_MetforminAndErtugliflozi;
