within Pharmacolibrary.Drugs.R_RespiratorySystem.R05D_CoughSuppressantsExclCombinationsWithExpectorant;
package R05DB20_DextromethorphanAndNosca
  extends Icons.PackageDrugs;
end R05DB20_DextromethorphanAndNosca;
