within Pharmacolibrary.Drugs.S_SensoryOrgans.S02C_CorticosteroidsAndAntiinfectivesInCombination;
package S02CA07_FludrocortisoneAndAntiinfectives
  extends Icons.Package;
end S02CA07_FludrocortisoneAndAntiinfectives;
