within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M05B_DrugsAffectingBoneStructureAndMineralization;
package M05BB04_RisedronicAcidCalciumAndColecalc
  extends Icons.Package;
end M05BB04_RisedronicAcidCalciumAndColecalc;
