within Pharmacolibrary.Drugs.R_RespiratorySystem.R03B_OtherDrugsForObstructiveAirwayDiseasesInhalants.R03BA09_FluticasoneFuroate;

model FluticasoneFuroate
  extends Pharmacolibrary.Drugs.ATC.R.R03BA09;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>R03BA09</td></tr><td>route:</td><td>inhalation</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Fluticasone furoate is a synthetic corticosteroid with potent anti-inflammatory activity. It is used primarily in the management of asthma and allergic rhinitis. The drug is approved and widely used today as an inhaled therapy for the control and prevention of respiratory tract inflammation.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters in healthy adult volunteers after single inhaled administration, fasted, both sexes.</p><h4>References</h4><ol><li><p>Siederer, S, et al., &amp; Yang, S (2016). Population Pharmacokinetics of Inhaled Fluticasone Furoate and Vilanterol in Subjects with Chronic Obstructive Pulmonary Disease. <i>European journal of drug metabolism and pharmacokinetics</i> 41(6) 743–758. DOI:<a href=\"https://doi.org/10.1007/s13318-015-0303-4\">10.1007/s13318-015-0303-4</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/26474864/\">https://pubmed.ncbi.nlm.nih.gov/26474864</a></p></li><li><p>Mehta, R, et al., &amp; Lipson, DA (2018). Population Pharmacokinetic Analysis of Fluticasone Furoate/Umeclidinium/Vilanterol via a Single Inhaler in Patients with COPD. <i>Journal of clinical pharmacology</i> 58(11) 1461–1467. DOI:<a href=\"https://doi.org/10.1002/jcph.1253\">10.1002/jcph.1253</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29762864/\">https://pubmed.ncbi.nlm.nih.gov/29762864</a></p></li><li><p>Allen, A, et al., &amp; Yang, S (2016). Population pharmacokinetics of inhaled fluticasone furoate and vilanterol in adult and adolescent patients with asthma. <i>International journal of clinical pharmacology and therapeutics</i> 54(4) 269–281. DOI:<a href=\"https://doi.org/10.5414/CP202438\">10.5414/CP202438</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/26902504/\">https://pubmed.ncbi.nlm.nih.gov/26902504</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end FluticasoneFuroate;
