within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AA03_LynestrenolAndEthinylestradiol
  extends Icons.Package;
end G03AA03_LynestrenolAndEthinylestradiol;
