within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03E_DiureticsAndPotassiumSparingAgentsInCombination;
package C03EA03_EpitizideAndPotassiumSparingAgen
  extends Icons.PackageDrugs;
end C03EA03_EpitizideAndPotassiumSparingAgen;
