within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AX05_Mepacrine
  extends Icons.Package;
end P01AX05_Mepacrine;
