within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonStero;
package M01AE57_NaproxenAndDiphenhydrami
  extends Icons.PackageDrugs;
end M01AE57_NaproxenAndDiphenhydrami;
