within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03A_DrugsForFunctionalGastrointestinalDisorders;
package A03AC02_Dimethylaminopropionylphenothiaz
  extends Icons.Package;
end A03AC02_Dimethylaminopropionylphenothiaz;
