within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03A_DrugsForFunctionalGastrointestinalDisorders;
package A03AC02_Dimethylaminopropionylphenothiaz
  extends Icons.PackageDrugs;
end A03AC02_Dimethylaminopropionylphenothiaz;
