within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A07B_IntestinalAdsorbents;
package A07BC30_PolymyxinBNeomycinAndBacitracinC
  extends Icons.PackageDrugs;
end A07BC30_PolymyxinBNeomycinAndBacitracinC;
