within Pharmacolibrary.Drugs.R_RespiratorySystem.R03B_OtherDrugsForObstructiveAirwayDiseasesInhalants;
package R03BB01_IpratropiumBromide
  extends Icons.PackageDrugs;
end R03BB01_IpratropiumBromide;
