within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G04C_DrugsUsedInBenignProstaticHypertrophy;
package G04CA55_DoxazosinAndFinasteride
  extends Icons.PackageDrugs;
end G04CA55_DoxazosinAndFinasteride;
