within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H05A_ParathyroidHormonesAndAnalogues;
package H05AA05_Palopegteriparatide
  extends Icons.Package;
end H05AA05_Palopegteriparatide;
