within Pharmacolibrary.Drugs.D_Dermatologicals.D07C_CorticosteroidsCombinationsWithAntibiotics;
package D07CB01_TriamcinoloneAndAntibiot
  extends Icons.PackageDrugs;
end D07CB01_TriamcinoloneAndAntibiot;
