within Pharmacolibrary.Drugs.V_Various.V01A_Allergens.V01AA08_Food;

model Food
  extends Pharmacolibrary.Drugs.ATC.V.V01AA08;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>V01AA08</td></tr><td>route:</td><td>orally</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Substances classified under ATC code V01AA08 refer to 'Test meals for functional investigation', commonly known as food used in diagnostic settings to assess gastrointestinal function. These are not drugs in the classical sense but standardized meals or food compositions employed to study digestion, absorption, or metabolism and are not intended as therapeutics. There is no approved pharmaceutical use for these products beyond clinical or experimental diagnostics.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic models for standard 'food' test meals do not exist, as foods are not pharmacological agents and lack defined PK parameters such as absorption, distribution, metabolism, and elimination in the conventional sense. No peer-reviewed pharmacokinetic model for test meals or 'food' with this ATC code exists.</p><h4>References</h4><ol><li><p>Chen, G, et al., &amp; Nomikos, G (2018). Vortioxetine: Clinical Pharmacokinetics and Drug Interactions. <i>Clinical pharmacokinetics</i> 57(6) 673–686. DOI:<a href=\"https://doi.org/10.1007/s40262-017-0612-7\">10.1007/s40262-017-0612-7</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29189941/\">https://pubmed.ncbi.nlm.nih.gov/29189941</a></p></li><li><p>Greenberg, RG, et al., &amp; Walter, EB (2022). Population Pharmacokinetics of Moxifloxacin in Children. <i>Paediatric drugs</i> 24(2) 163–173. DOI:<a href=\"https://doi.org/10.1007/s40272-022-00493-3\">10.1007/s40272-022-00493-3</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35284983/\">https://pubmed.ncbi.nlm.nih.gov/35284983</a></p></li><li><p>Fernandez-Teruel, C, et al., &amp; Zhou, D (2024). Population Pharmacokinetics of Capivasertib in Patients with Advanced or Metastatic Solid Tumours. <i>Clinical pharmacokinetics</i> 63(8) 1191–1204. DOI:<a href=\"https://doi.org/10.1007/s40262-024-01407-x\">10.1007/s40262-024-01407-x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39127854/\">https://pubmed.ncbi.nlm.nih.gov/39127854</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Food;
