within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations.C09DA04_IrbesartanAndDiuretics;

model IrbesartanAndDiuretics
  extends Pharmacolibrary.Drugs.ATC.C.C09DA04;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>IrbesartanAndDiuretics</td></tr><tr><td>ATC code:</td><td>C09DA04</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Irbesartan in combination with diuretics (commonly hydrochlorothiazide) is a prescription medication used primarily for the treatment of hypertension. Irbesartan is an angiotensin II receptor antagonist, while the diuretic component reduces fluid volume. This combination is approved and currently used to lower blood pressure and reduce the risk of cardiovascular events.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters estimated based on published data for individual components (irbesartan and hydrochlorothiazide), as no population PK model reporting parameters for the fixed combination product was identified. Parameters mainly reflect healthy adult subjects after single oral administration of the combination.</p><h4>References</h4><ol><li><p>Sherazi, AW, et al., &amp; Rasool, MF (2024). A Systematic Critical Review of Clinical Pharmacokinetics of Torasemide. <i>Therapeutic drug monitoring</i> 46(3) 309–320. DOI:<a href=\"https://doi.org/10.1097/FTD.0000000000001141\">10.1097/FTD.0000000000001141</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/38176856/\">https://pubmed.ncbi.nlm.nih.gov/38176856</a></p></li><li><p>Liu, J, et al., &amp; ShenTu, J (2015). Pharmacokinetic properties and bioequivalence of two irbesartan/ hydrochlorothiazide fixed-dose combination tablets in healthy male Chinese volunteers. <i>International journal of clinical pharmacology and therapeutics</i> 53(7) 573–581. DOI:<a href=\"https://doi.org/10.5414/CP202208\">10.5414/CP202208</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25828636/\">https://pubmed.ncbi.nlm.nih.gov/25828636</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end IrbesartanAndDiuretics;
