within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DA04_IrbesartanAndDiuretics
  extends Icons.PackageDrugs;
end C09DA04_IrbesartanAndDiuretics;
