within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA09_DiphtheriaHaemophilusInfluenzaeBPertussisPoliomyelitisTetanusHepatitisB
  extends Icons.Package;
end J07CA09_DiphtheriaHaemophilusInfluenzaeBPertussisPoliomyelitisTetanusHepatitisB;
