within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P03A_EctoparasiticidesInclScabicides;
package P03AA02_PotassiumPolysulfide
  extends Icons.PackageDrugs;
end P03AA02_PotassiumPolysulfide;
