within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P03A_EctoparasiticidesInclScabicides;
package P03AA02_PotassiumPolysulfide
  extends Icons.Package;
end P03AA02_PotassiumPolysulfide;
