within Pharmacolibrary.Drugs.D_Dermatologicals.D08A_AntisepticsAndDisinfectants.D08AC02_Chlorhexidine;

model Chlorhexidine
  extends Pharmacolibrary.Drugs.ATC.D.D08AC02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Chlorhexidine</td></tr><tr><td>ATC code:</td><td>D08AC02</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Chlorhexidine is a broad-spectrum antiseptic and disinfectant that is used to reduce bacteria on the skin and mucous membranes. It is commonly used for skin disinfection before surgery, wound cleaning, and as a mouthwash for oral hygiene. Chlorhexidine is approved and widely used in clinical practice.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters for chlorhexidine following oral administration in healthy adult volunteers (sex not specified; typical mucosal/skin and oral use).</p><h4>References</h4><ol><li><p>Toljanic, JA, et al., &amp; Shapiro, RD (1992). Evaluation of the substantivity of a chlorhexidine oral rinse in irradiated head and neck cancer patients. <i>Journal of oral and maxillofacial surgery : official journal of the American Association of Oral and Maxillofacial Surgeons</i> 50(10) 1055–1059. DOI:<a href=\"https://doi.org/10.1016/0278-2391(92)90490-q\">10.1016/0278-2391(92)90490-q</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/1527659/\">https://pubmed.ncbi.nlm.nih.gov/1527659</a></p></li><li><p>Lim, SY, et al., &amp; Heard, CM (2020). Mucoadhesive thin films for the simultaneous delivery of microbicide and anti-inflammatory drugs in the treatment of periodontal diseases. <i>International journal of pharmaceutics</i> 573 118860–None. DOI:<a href=\"https://doi.org/10.1016/j.ijpharm.2019.118860\">10.1016/j.ijpharm.2019.118860</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31759104/\">https://pubmed.ncbi.nlm.nih.gov/31759104</a></p></li><li><p>Salmanli, M, et al., &amp; Tuzuner, T (2021). Investigation of the antimicrobial activities of various antimicrobial agents on Streptococcus Mutans Sortase A through computer-aided drug design (CADD) approaches. <i>Computer methods and programs in biomedicine</i> 212 106454–None. DOI:<a href=\"https://doi.org/10.1016/j.cmpb.2021.106454\">10.1016/j.cmpb.2021.106454</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34656905/\">https://pubmed.ncbi.nlm.nih.gov/34656905</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Chlorhexidine;
