within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BN02_Covid19ViralVectorNonReplicating
  extends Icons.Package;
end J07BN02_Covid19ViralVectorNonReplicating;
