within Pharmacolibrary.Drugs.R_RespiratorySystem.R03D_OtherSystemicDrugsForObstructiveAirwayDiseases;
package R03DA55_AminophyllineCombination
  extends Icons.PackageDrugs;
end R03DA55_AminophyllineCombination;
