within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A16A_OtherAlimentaryTractAndMetabolismProducts;
package A16AB11_TaligluceraseAlfa
  extends Icons.PackageDrugs;
end A16AB11_TaligluceraseAlfa;
