within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD07_MetforminAndSitagliptin
  extends Icons.PackageDrugs;
end A10BD07_MetforminAndSitagliptin;
