within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination;
package G03FA15_DienogestAndEstrogen
  extends Icons.PackageDrugs;
end G03FA15_DienogestAndEstrogen;
