within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FD06_Margetuximab
  extends Icons.Package;
end L01FD06_Margetuximab;
