within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BA03_PravastatinAndFenofibrat
  extends Icons.PackageDrugs;
end C10BA03_PravastatinAndFenofibrat;
