within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M03B_MuscleRelaxantsCentrallyActingAgents;
package M03BX55_ThiocolchicosideCombinations
  extends Icons.Package;
end M03BX55_ThiocolchicosideCombinations;
