within Pharmacolibrary.Drugs.D_Dermatologicals.D07B_CorticosteroidsCombinationsWithAntiseptics;
package D07BB04_HydrocortisoneButyrateAndAntisep
  extends Icons.PackageDrugs;
end D07BB04_HydrocortisoneButyrateAndAntisep;
