within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B02B_VitaminKAndOtherHemostatics;
package B02BD03_FactorViiiInhibitorBypassingActi
  extends Icons.PackageDrugs;
end B02BD03_FactorViiiInhibitorBypassingActi;
