within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FY01_PertuzumabAndTrastuzumab
  extends Icons.Package;
end L01FY01_PertuzumabAndTrastuzumab;
