within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AX17_Dapivirine
  extends Icons.PackageDrugs;
end G01AX17_Dapivirine;
