within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03C_AntispasmodicsInCombinationWithPsycholeptics;
package A03CB02_BelladonnaTotalAlkaloidsAndPsycholeptics
  extends Icons.Package;
end A03CB02_BelladonnaTotalAlkaloidsAndPsycholeptics;
