within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD04_GlimepirideAndRosiglitazone
  extends Icons.Package;
end A10BD04_GlimepirideAndRosiglitazone;
