within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01C_CardiacStimulantsExclCardiacGlycosides;
package C01CA30_MetildigoxinAndOrganicNi
  extends Icons.PackageDrugs;
end C01CA30_MetildigoxinAndOrganicNi;
