within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials.J01DI54_CeftolozaneAndTazobactam;

model CeftolozaneAndTazobactam
  extends Pharmacolibrary.Drugs.ATC.J.J01DI54;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>CeftolozaneAndTazobactam</td></tr><tr><td>ATC code:</td><td>J01DI54</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Ceftolozane and tazobactam is a combination of a cephalosporin antibiotic (ceftolozane) and a β-lactamase inhibitor (tazobactam). It is used for the treatment of complicated intra-abdominal infections and complicated urinary tract infections, including pyelonephritis. The combination is approved for clinical use and has activity against Gram-negative pathogens, including multidrug-resistant Pseudomonas aeruginosa.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters obtained in healthy adult subjects, both male and female, age range approximately 18–50 years, following intravenous infusion.</p><h4>References</h4><ol><li><p>Larson, KB, et al., &amp; Rizk, ML (2019). Ceftolozane-Tazobactam Population Pharmacokinetics and Dose Selection for Further Clinical Evaluation in Pediatric Patients with Complicated Urinary Tract or Complicated Intra-abdominal Infections. <i>Antimicrobial agents and chemotherapy</i> 63(6) –. DOI:<a href=\"https://doi.org/10.1128/AAC.02578-18\">10.1128/AAC.02578-18</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30962340/\">https://pubmed.ncbi.nlm.nih.gov/30962340</a></p></li><li><p>Monogue, ML, et al., &amp; Kuti, JL (2016). Population Pharmacokinetics and Safety of Ceftolozane-Tazobactam in Adult Cystic Fibrosis Patients Admitted with Acute Pulmonary Exacerbation. <i>Antimicrobial agents and chemotherapy</i> 60(11) 6578–6584. DOI:<a href=\"https://doi.org/10.1128/AAC.01566-16\">10.1128/AAC.01566-16</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27550351/\">https://pubmed.ncbi.nlm.nih.gov/27550351</a></p></li><li><p>Al Jalali, V, et al., &amp; Zeitlinger, M (2021). Plasma and soft tissue pharmacokinetics of ceftolozane/tazobactam in healthy volunteers after single and multiple intravenous infusion: a microdialysis study. <i>The Journal of antimicrobial chemotherapy</i> 76(9) 2342–2351. DOI:<a href=\"https://doi.org/10.1093/jac/dkab166\">10.1093/jac/dkab166</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34050650/\">https://pubmed.ncbi.nlm.nih.gov/34050650</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end CeftolozaneAndTazobactam;
