within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials;
package J01DI54_CeftolozaneAndTazobactam
  extends Icons.Package;
end J01DI54_CeftolozaneAndTazobactam;
