within Pharmacolibrary.Drugs.S_SensoryOrgans.S03C_CorticosteroidsAndAntiinfectivesInCombination;
package S03CA04_HydrocortisoneAndAntiinf
  extends Icons.PackageDrugs;
end S03CA04_HydrocortisoneAndAntiinf;
