within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A12C_OtherMineralSupplements;
package A12CC30_MagnesiumDifferentSaltsInCombination
  extends Icons.Package;
end A12CC30_MagnesiumDifferentSaltsInCombination;
