within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01C_PlantAlkaloidsAndOtherNaturalProducts;
package L01CD03_PaclitaxelPoliglumex
  extends Icons.PackageDrugs;
end L01CD03_PaclitaxelPoliglumex;
