within Pharmacolibrary.Drugs.D_Dermatologicals.D05B_AntipsoriaticsForSystemicUse;
package D05BX51_FumaricAcidDerivativesCombinations
  extends Icons.Package;
end D05BX51_FumaricAcidDerivativesCombinations;
