within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H01A_AnteriorPituitaryLobeHormonesAndAnalogues;
package H01AC06_Tesamorelin
  extends Icons.PackageDrugs;
end H01AC06_Tesamorelin;
