within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M05B_DrugsAffectingBoneStructureAndMineralization;
package M05BB06_AlendronicAcidAndAlfacalcidolSequential
  extends Icons.Package;
end M05BB06_AlendronicAcidAndAlfacalcidolSequential;
