within Pharmacolibrary.Drugs.R_RespiratorySystem.R03D_OtherSystemicDrugsForObstructiveAirwayDiseases;
package R03DB01_DiprophyllineAndAdrenergics
  extends Icons.Package;
end R03DB01_DiprophyllineAndAdrenergics;
