within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombination;
package S01CA08_MethylprednisoloneAndAntiinfectives
  extends Icons.Package;
end S01CA08_MethylprednisoloneAndAntiinfectives;
