within Pharmacolibrary.Drugs.N_NervousSystem.N05C_HypnoticsAndSedatives.N05CH01_Melatonin;

model Melatonin_1
  extends Pharmacolibrary.Drugs.ATC.N.N05CH01_1;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Melatonin_1</td></tr><tr><td>ATC code:</td><td>N05CH01_1</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Melatonin is an endogenous hormone produced by the pineal gland involved in the regulation of circadian rhythms and sleep-wake cycles. As a drug, melatonin is primarily used to treat insomnia, jet lag, and circadian rhythm sleep disorders, and is available as an over-the-counter supplement in many countries. It is generally considered safe with limited adverse effects and is not approved as a prescription medication in most regions, but is widely used for sleep-related complaints.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters following intravenous administration of 10 mg melatonin in healthy adult volunteers (both sexes).</p><h4>References</h4><ol><li><p>Lalanne, S, et al., &amp; Tordjman, S (2021). Melatonin: From Pharmacokinetics to Clinical Use in Autism Spectrum Disorder. <i>International journal of molecular sciences</i> 22(3) –. DOI:<a href=\"https://doi.org/10.3390/ijms22031490\">10.3390/ijms22031490</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33540815/\">https://pubmed.ncbi.nlm.nih.gov/33540815</a></p></li><li><p>Balduini, W, et al., &amp; Buonocore, G (2019). Melatonin pharmacokinetics and dose extrapolation after enteral infusion in neonates subjected to hypothermia. <i>Journal of pineal research</i> 66(4) e12565–None. DOI:<a href=\"https://doi.org/10.1111/jpi.12565\">10.1111/jpi.12565</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30734962/\">https://pubmed.ncbi.nlm.nih.gov/30734962</a></p></li><li><p>Bienert, A, et al., &amp; Grześkowiak, E (2015). Melatonin and clonidine premedication has similar impact on the pharmacokinetics and pharmacodynamics of propofol target controlled-infusions. <i>Journal of clinical pharmacology</i> 55(3) 307–316. DOI:<a href=\"https://doi.org/10.1002/jcph.401\">10.1002/jcph.401</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25243731/\">https://pubmed.ncbi.nlm.nih.gov/25243731</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Melatonin_1;
