within Pharmacolibrary.Drugs.C_CardiovascularSystem.C05A_AgentsForTreatmentOfHemorrhoidsAndAnalFissuresForTopicalUse;
package C05AA12_Triamcinolone
  extends Icons.Package;
end C05AA12_Triamcinolone;
