within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03E_DiureticsAndPotassiumSparingAgentsInCombination;
package C03EA13_BendroflumethiazideAndPo
  extends Icons.PackageDrugs;
end C03EA13_BendroflumethiazideAndPo;
