within Pharmacolibrary.Drugs.V_Various.V09D_HepaticAndReticuloEndothelialSystem;
package V09DB06_Technetium99mtcRheniumsulfideCol
  extends Icons.PackageDrugs;
end V09DB06_Technetium99mtcRheniumsulfideCol;
