within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BB52_MetamizoleSodiumCombinationsExcl
  extends Icons.Package;
end N02BB52_MetamizoleSodiumCombinationsExcl;
