within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01R_CombinationsOfAntibacterials;
package J01RA14_NorfloxacinAndMetronidaz
  extends Icons.PackageDrugs;
end J01RA14_NorfloxacinAndMetronidaz;
