within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03G_GonadotropinsAndOtherOvulationStimulants;
package G03GA01_ChorionicGonadotrophin
  extends Icons.PackageDrugs;
end G03GA01_ChorionicGonadotrophin;
