within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03A_DrugsForFunctionalGastrointestinalDisorders;
package A03AB02_GlycopyrroniumBromide
  extends Icons.Package;
end A03AB02_GlycopyrroniumBromide;
