within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination;
package G03FA16_TrimegestoneAndEstrogen
  extends Icons.Package;
end G03FA16_TrimegestoneAndEstrogen;
