within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents;
package L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates
  extends Icons.Package;
end L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
