within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M05B_DrugsAffectingBoneStructureAndMineralization;
package M05BB01_EtidronicAcidAndCalciumSequentia
  extends Icons.PackageDrugs;
end M05BB01_EtidronicAcidAndCalciumSequentia;
