within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination;
package G03FB06_MedroxyprogesteroneAndEstrogen
  extends Icons.Package;
end G03FB06_MedroxyprogesteroneAndEstrogen;
