within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AX52_EmetineCombinations
  extends Icons.PackageDrugs;
end P01AX52_EmetineCombinations;
