within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01D_VasodilatorsUsedInCardiacDiseases;
package C01DA05_PentaerithritylTetranitrate
  extends Icons.Package;
end C01DA05_PentaerithritylTetranitrate;
