within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M02A_TopicalProductsForJointAndMuscularPain.M02AA01_Phenylbutazone;

model Phenylbutazone
  extends Pharmacolibrary.Drugs.ATC.M.M02AA01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Phenylbutazone</td></tr><tr><td>ATC code:</td><td>M02AA01</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Phenylbutazone is a nonsteroidal anti-inflammatory drug (NSAID) formerly used to treat pain and inflammation associated with conditions such as rheumatoid arthritis and ankylosing spondylitis in humans. Due to its risk of serious side effects, including bone marrow suppression and gastrointestinal complications, its use in humans has been discontinued or severely restricted in many countries. It is still used in veterinary medicine, particularly in horses.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in healthy adults after a single oral dose.</p><h4>References</h4><ol><li><p>Houck, EL, et al., &amp; Delk, KW (2022). Phenylbutazone pharmacokinetics in southern white rhinoceros (Ceratotherium simum simum) after oral administration. <i>Journal of veterinary pharmacology and therapeutics</i> 45(2) 196–202. DOI:<a href=\"https://doi.org/10.1111/jvp.13036\">10.1111/jvp.13036</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34894412/\">https://pubmed.ncbi.nlm.nih.gov/34894412</a></p></li><li><p>Chay, S, et al., &amp; Yocum, J (1984). Population distributions of phenylbutazone and oxyphenbutazone after oral and i.v. dosing in horses. <i>Journal of veterinary pharmacology and therapeutics</i> 7(4) 265–276. DOI:<a href=\"https://doi.org/10.1111/j.1365-2885.1984.tb00911.x\">10.1111/j.1365-2885.1984.tb00911.x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/6512917/\">https://pubmed.ncbi.nlm.nih.gov/6512917</a></p></li><li><p>Knych, HK, et al., &amp; Kass, PH (2016). Pharmacokinetics of methocarbamol and phenylbutazone in exercised Thoroughbred horses. <i>Journal of veterinary pharmacology and therapeutics</i> 39(5) 469–477. DOI:<a href=\"https://doi.org/10.1111/jvp.12298\">10.1111/jvp.12298</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/26924025/\">https://pubmed.ncbi.nlm.nih.gov/26924025</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Phenylbutazone;
