within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P03A_EctoparasiticidesInclScabicides;
package P03AC53_PhenothrinCombinations
  extends Icons.PackageDrugs;
end P03AC53_PhenothrinCombinations;
