within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M05B_DrugsAffectingBoneStructureAndMineralization;
package M05BB09_IbandronicAcidAndColecal
  extends Icons.PackageDrugs;
end M05BB09_IbandronicAcidAndColecal;
