within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A07F_AntidiarrhealMicroorganisms;
package A07FA51_LacticAcidProducingOrganismsComb
  extends Icons.PackageDrugs;
end A07FA51_LacticAcidProducingOrganismsComb;
