within Pharmacolibrary.Drugs.R_RespiratorySystem.R03D_OtherSystemicDrugsForObstructiveAirwayDiseases.R03DX11_Tezepelumab;

model Tezepelumab
  extends Pharmacolibrary.Drugs.ATC.R.R03DX11;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Tezepelumab</td></tr><tr><td>ATC code:</td><td>R03DX11</td></tr><td>route:</td><td>subcutaneous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Tezepelumab is a human monoclonal antibody targeting thymic stromal lymphopoietin (TSLP), used for the treatment of severe asthma. It is approved for clinical use in adults and adolescents with severe, uncontrolled asthma despite standard therapy.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetics reported in healthy adults and patients with severe asthma receiving subcutaneous administration.</p><h4>References</h4><ol><li><p>Ly, N, et al., &amp; Roskos, L (2021). Pharmacokinetic and Pharmacodynamic Modeling of Tezepelumab to Guide Phase 3 Dose Selection for Patients With Severe Asthma. <i>Journal of clinical pharmacology</i> 61(7) 901–912. DOI:<a href=\"https://doi.org/10.1002/jcph.1803\">10.1002/jcph.1803</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33368307/\">https://pubmed.ncbi.nlm.nih.gov/33368307</a></p></li><li><p>Zheng, Y, et al., &amp; MacDonald, A (2024). Population Pharmacokinetic Modeling and Exposure-Efficacy and Body Weight-Response Analyses for Tezepelumab in Patients With Severe, Uncontrolled Asthma. <i>Journal of clinical pharmacology</i> 64(8) 908–921. DOI:<a href=\"https://doi.org/10.1002/jcph.2433\">10.1002/jcph.2433</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/38632826/\">https://pubmed.ncbi.nlm.nih.gov/38632826</a></p></li><li><p>Sakamoto, K, et al., &amp; Ren, S (2020). A Phase 1, Randomized, Placebo-Controlled Study to Evaluate the Safety, Tolerability, Pharmacokinetics, and Immunogenicity of Subcutaneous Tezepelumab in Healthy Japanese Men. <i>Clinical pharmacology in drug development</i> 9(7) 833–840. DOI:<a href=\"https://doi.org/10.1002/cpdd.775\">10.1002/cpdd.775</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31960624/\">https://pubmed.ncbi.nlm.nih.gov/31960624</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Tezepelumab;
