within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BA59_DipyrocetylCombinationsExclPsycholeptics
  extends Icons.Package;
end N02BA59_DipyrocetylCombinationsExclPsycholeptics;
