within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX15_AtorvastatinAndPerindopr
  extends Icons.PackageDrugs;
end C10BX15_AtorvastatinAndPerindopr;
