within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BB71_PhenazoneCombinationsWithPsycholeptics
  extends Icons.Package;
end N02BB71_PhenazoneCombinationsWithPsycholeptics;
