within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B05C_IrrigatingSolutions.B05CX02_Sorbitol;

model Sorbitol
  extends Pharmacolibrary.Drugs.ATC.B.B05CX02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Sorbitol</td></tr><tr><td>ATC code:</td><td>B05CX02</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Sorbitol is a sugar alcohol often used as a sweetener and a medication. Medically, it is used as an osmotic laxative to treat constipation, as a diuretic and irrigating fluid in surgical procedures, and as a component of some intravenous formulations. It is generally regarded as safe, but oral ingestion in high doses can cause gastrointestinal discomfort.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters for sorbitol are not well-documented in the published literature for therapeutic use in humans. Most available data are from preclinical studies, food absorption contexts, or in combination with other substances. No direct human pharmacokinetic compartmental modeling published in peer-reviewed sources was found.</p><h4>References</h4><ol><li><p>Leier, CV (1985). Nitrate tolerance. <i>American heart journal</i> 110(1 Pt 2) 224–232. DOI:<a href=\"https://doi.org/10.1016/0002-8703(85)90491-0\">10.1016/0002-8703(85)90491-0</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/3925742/\">https://pubmed.ncbi.nlm.nih.gov/3925742</a></p></li><li><p>Yang, D, et al., &amp; Chen, J (2024). Bioequivalence Study of Epalrestat for Healthy Chinese Subjects. <i>Clinical pharmacology in drug development</i> 13(5) 485–490. DOI:<a href=\"https://doi.org/10.1002/cpdd.1347\">10.1002/cpdd.1347</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37971280/\">https://pubmed.ncbi.nlm.nih.gov/37971280</a></p></li><li><p>Jain, NK, et al., &amp; Pitchumoni, CS (1987). Sorbitol intolerance in adults. Prevalence and pathogenesis on two continents. <i>Journal of clinical gastroenterology</i> 9(3) 317–319. DOI:<a href=\"https://doi.org/10.1097/00004836-198706000-00015\">10.1097/00004836-198706000-00015</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/3611685/\">https://pubmed.ncbi.nlm.nih.gov/3611685</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Sorbitol;
