within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AL52_PneumococcusPurifiedPolysaccharidesAntigenAndHaemophilusInfluenzaeConjugated
  extends Icons.Package;
end J07AL52_PneumococcusPurifiedPolysaccharidesAntigenAndHaemophilusInfluenzaeConjugated;
