within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J02A_AntimycoticsForSystemicUse.J02AX06_Anidulafungin;

model Anidulafungin
  extends Pharmacolibrary.Drugs.ATC.J.J02AX06;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>J02AX06</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Anidulafungin is an echinocandin antifungal used for the treatment of invasive candidiasis and other serious fungal infections. It inhibits glucan synthesis, a crucial component of fungal cell walls. It is approved for use in many countries, including the US and Europe.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters observed in adult patients (both sexes) with invasive candidiasis after intravenous infusion.</p><h4>References</h4><ol><li><p>Wasmann, RE, et al., &amp; Brüggemann, RJ (2018). Pharmacokinetics of Anidulafungin in Obese and Normal-Weight Adults. <i>Antimicrobial agents and chemotherapy</i> 62(7) –. DOI:<a href=\"https://doi.org/10.1128/AAC.00063-18\">10.1128/AAC.00063-18</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29712664/\">https://pubmed.ncbi.nlm.nih.gov/29712664</a></p></li><li><p>Liu, P, et al., &amp; Damle, B (2013). Pharmacokinetics of anidulafungin in critically ill patients with candidemia/invasive candidiasis. <i>Antimicrobial agents and chemotherapy</i> 57(4) 1672–1676. DOI:<a href=\"https://doi.org/10.1128/AAC.02139-12\">10.1128/AAC.02139-12</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/23335738/\">https://pubmed.ncbi.nlm.nih.gov/23335738</a></p></li><li><p>Xie, R, et al., &amp; Liu, P (2020). Population Analysis of Anidulafungin in Infants to Older Adults With Confirmed or Suspected Invasive Candidiasis. <i>Clinical pharmacology and therapeutics</i> 108(2) 316–325. DOI:<a href=\"https://doi.org/10.1002/cpt.1831\">10.1002/cpt.1831</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32189334/\">https://pubmed.ncbi.nlm.nih.gov/32189334</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Anidulafungin;
