within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA13_DiphtheriaHaemophilusInfluenzaeB
  extends Icons.Package;
end J07CA13_DiphtheriaHaemophilusInfluenzaeB;
