within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03C_AntispasmodicsInCombinationWithPsycholeptics;
package A03CA04_OtiloniumBromideAndPsych
  extends Icons.PackageDrugs;
end A03CA04_OtiloniumBromideAndPsych;
