within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A16A_OtherAlimentaryTractAndMetabolismProducts;
package A16AB07_AlglucosidaseAlfa
  extends Icons.PackageDrugs;
end A16AB07_AlglucosidaseAlfa;
