within Pharmacolibrary.Drugs.N_NervousSystem.N05A_Antipsychotics.N05AN01_Lithium;

model Lithium
  extends Pharmacolibrary.Drugs.ATC.N.N05AN01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>N05AN01</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Lithium is a mood stabilizer primarily used in the treatment and prophylaxis of bipolar disorder and, to a lesser extent, depression. It is an approved drug with established efficacy for the prevention of manic and depressive episodes in bipolar disorder. Lithium is also sometimes used off-label for other psychiatric conditions.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in healthy adults after oral administration of lithium carbonate.</p><h4>References</h4><ol><li><p>Yuan, J, et al., &amp; Zhu, C (2021). Population Pharmacokinetics of Lithium in Young Pediatric Patients With Intellectual Disability. <i>Frontiers in pharmacology</i> 12 650298–None. DOI:<a href=\"https://doi.org/10.3389/fphar.2021.650298\">10.3389/fphar.2021.650298</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33935755/\">https://pubmed.ncbi.nlm.nih.gov/33935755</a></p></li><li><p>Yamaguchi, D, et al., &amp; Kamimura, H (2019). Population Pharmacokinetics and Exposure-Response of Lithium Carbonate in Patients Based on Tubular Reabsorption Mechanisms. <i>European journal of drug metabolism and pharmacokinetics</i> 44(3) 329–338. DOI:<a href=\"https://doi.org/10.1007/s13318-018-0536-0\">10.1007/s13318-018-0536-0</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30536114/\">https://pubmed.ncbi.nlm.nih.gov/30536114</a></p></li><li><p>Findling, RL, et al., &amp; Jusko, WJ (2010). First-dose pharmacokinetics of lithium carbonate in children and adolescents. <i>Journal of clinical psychopharmacology</i> 30(4) 404–410. DOI:<a href=\"https://doi.org/10.1097/JCP.0b013e3181e66a62\">10.1097/JCP.0b013e3181e66a62</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/20531219/\">https://pubmed.ncbi.nlm.nih.gov/20531219</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Lithium;
