within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J04A_DrugsForTreatmentOfTuberculosis;
package J04AM04_ThioacetazoneAndIsoniazid
  extends Icons.Package;
end J04AM04_ThioacetazoneAndIsoniazid;
