within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H03B_AntithyroidPreparations;
package H03BA03_Benzylthiouracil
  extends Icons.PackageDrugs;
end H03BA03_Benzylthiouracil;
