within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BA65_CarbasalateCalciumCombinationsExclPsycholeptics
  extends Icons.Package;
end N02BA65_CarbasalateCalciumCombinationsExclPsycholeptics;
