within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BA03_EncephalitisJapaneseLiveAttenuated
  extends Icons.Package;
end J07BA03_EncephalitisJapaneseLiveAttenuated;
