within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A16A_OtherAlimentaryTractAndMetabolismProducts;
package A16AX21_ElivaldogeneAutotemcel
  extends Icons.PackageDrugs;
end A16AX21_ElivaldogeneAutotemcel;
