within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H03B_AntithyroidPreparations;
package H03BX02_Dibromotyrosine
  extends Icons.PackageDrugs;
end H03BX02_Dibromotyrosine;
