within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis;
package A02BA05_Niperotidine
  extends Icons.PackageDrugs;
end A02BA05_Niperotidine;
