within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins.J01CF04_Oxacillin;

model Oxacillin
  extends Pharmacolibrary.Drugs.ATC.J.J01CF04;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>J01CF04</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Oxacillin is a narrow-spectrum beta-lactam antibiotic of the penicillin class, primarily used for the treatment of infections caused by penicillinase-producing staphylococci. It is still clinically approved and used especially for serious Staphylococcus aureus infections sensitive to methicillin-class drugs.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in healthy adult volunteers after intravenous administration.</p><h4>References</h4><ol><li><p>Bock, M, et al., &amp; Moser, C (2023). Attainment of Target Antibiotic Levels by Oral Treatment of Left-Sided Infective Endocarditis: A POET Substudy. <i>Clinical infectious diseases : an official publication of the Infectious Diseases Society of America</i> 77(2) 242–251. DOI:<a href=\"https://doi.org/10.1093/cid/ciad168\">10.1093/cid/ciad168</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36947131/\">https://pubmed.ncbi.nlm.nih.gov/36947131</a></p></li><li><p>Hermann, L, et al., &amp; Hammann, F (2024). Population pharmacokinetics of flucloxacillin as intermittent bolus infusion in patients with Staphylococcus aureus bloodstream infection. <i>The Journal of antimicrobial chemotherapy</i> 79(8) 2031–2039. DOI:<a href=\"https://doi.org/10.1093/jac/dkae207\">10.1093/jac/dkae207</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/38946285/\">https://pubmed.ncbi.nlm.nih.gov/38946285</a></p></li><li><p>Öbrink-Hansen, K, et al., &amp; Stilling, M (2022). Population Pharmacokinetics of Flucloxacillin In Bone and Soft Tissue- Standard Dosing is Not Sufficient to Achieve Therapeutic Concentrations. <i>Pharmaceutical research</i> 39(7) 1633–1643. DOI:<a href=\"https://doi.org/10.1007/s11095-022-03197-y\">10.1007/s11095-022-03197-y</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35233728/\">https://pubmed.ncbi.nlm.nih.gov/35233728</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Oxacillin;
