within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AX14_Lactobacillus
  extends Icons.Package;
end G01AX14_Lactobacillus;
