within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BD03_LansoprazoleAmoxicillinAndMetron
  extends Icons.Package;
end A02BD03_LansoprazoleAmoxicillinAndMetron;
