within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins;
package J01CA20_AmpicillinAndAmoxicillin
  extends Icons.PackageDrugs;
end J01CA20_AmpicillinAndAmoxicillin;
