within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01B_AntiarrhythmicsClassIAndIii;
package C01BA51_QuinidineCombinationsExclPsychol
  extends Icons.Package;
end C01BA51_QuinidineCombinationsExclPsychol;
