within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AE51_CholeraCombinationsWithTyphoidVaccineInactivatedWholeCell
  extends Icons.Package;
end J07AE51_CholeraCombinationsWithTyphoidVaccineInactivatedWholeCell;
