within Pharmacolibrary.Drugs.D_Dermatologicals.D07C_CorticosteroidsCombinationsWithAntibiotics;
package D07CC05_FluocinonideAndAntibioti
  extends Icons.PackageDrugs;
end D07CC05_FluocinonideAndAntibioti;
