within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01E_SulfonamidesAndTrimethoprim;
package J01EE03_SulfametroleAndTrimethop
  extends Icons.PackageDrugs;
end J01EE03_SulfametroleAndTrimethop;
