within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AR03_TenofovirDisoproxilAndEmtricitabine
  extends Icons.Package;
end J05AR03_TenofovirDisoproxilAndEmtricitabine;
