within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B02B_VitaminKAndOtherHemostatics;
package B02BD06_VonWillebrandFactorAndCoagulatio
  extends Icons.Package;
end B02BD06_VonWillebrandFactorAndCoagulatio;
