within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD01_PhenforminAndSulfonylureas
  extends Icons.Package;
end A10BD01_PhenforminAndSulfonylureas;
