within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonStero;
package M01AG04_MeclofenamicAcid
  extends Icons.PackageDrugs;
end M01AG04_MeclofenamicAcid;
