within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DB01_ValsartanAndAmlodipine
  extends Icons.Package;
end C09DB01_ValsartanAndAmlodipine;
