within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BE51_ParacetamolCombinationsExclPsych
  extends Icons.PackageDrugs;
end N02BE51_ParacetamolCombinationsExclPsych;
