within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BE54_BucetinCombinationsExclPsycholep
  extends Icons.Package;
end N02BE54_BucetinCombinationsExclPsycholep;
