within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01X_OtherAntineoplasticAgents;
package L01XD04_AminolevulinicAcid
  extends Icons.PackageDrugs;
end L01XD04_AminolevulinicAcid;
