within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DX02_ValsartanAndAliskiren
  extends Icons.Package;
end C09DX02_ValsartanAndAliskiren;
