within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations.C09DX02_ValsartanAndAliskiren;
model ValsartanAndAliskiren = Pharmacolibrary.Drugs.ATC.C.C09DX02;