within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AF14_Propenidazole
  extends Icons.Package;
end G01AF14_Propenidazole;
