within Pharmacolibrary.Drugs.R_RespiratorySystem.R03A_AdrenergicsInhalants;
package R03AK02_IsoprenalineAndOtherDrugsForObst
  extends Icons.PackageDrugs;
end R03AK02_IsoprenalineAndOtherDrugsForObst;
