within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03A_DrugsForFunctionalGastrointestinalDisorders;
package A03AB16_D_2BenzhydryloxyethylDiethylMeth
  extends Icons.PackageDrugs;
end A03AB16_D_2BenzhydryloxyethylDiethylMeth;
