within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B01A_AntithromboticAgents.B01AC16_Eptifibatide;

model Eptifibatide
  extends Pharmacolibrary.Drugs.ATC.B.B01AC16;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>B01AC16</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Eptifibatide is a cyclic heptapeptide antiplatelet drug, classified as a glycoprotein IIb/IIIa receptor antagonist. It is used to reduce the risk of acute cardiac ischemic events, such as in patients with acute coronary syndrome (ACS) undergoing percutaneous coronary intervention (PCI). Eptifibatide is approved and in clinical use for this indication.</p><h4>Pharmacokinetics</h4><p>Mean pharmacokinetic parameters in adults with coronary artery disease undergoing PCI, male and female, typical intravenous administration.</p><h4>References</h4><ol><li><p>Liu, L, et al., &amp; Zhang, H (2020). Clinical Evaluation of the Tolerability, Pharmacokinetics, and Inhibition of Platelet Aggregation of Eptifibatide in Healthy Chinese Subjects. <i>Clinical pharmacology in drug development</i> 9(2) 267–276. DOI:<a href=\"https://doi.org/10.1002/cpdd.717\">10.1002/cpdd.717</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31197974/\">https://pubmed.ncbi.nlm.nih.gov/31197974</a></p></li><li><p>Gretler, DD (2003). Pharmacokinetic and pharmacodynamic properties of eptifabatide in healthy subjects receiving unfractionated heparin or the low-molecular-weight heparin enoxaparin. <i>Clinical therapeutics</i> 25(10) 2564–2574. DOI:<a href=\"https://doi.org/10.1016/s0149-2918(03)80317-x\">10.1016/s0149-2918(03)80317-x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/14667957/\">https://pubmed.ncbi.nlm.nih.gov/14667957</a></p></li><li><p>Zhou, ZL, et al., &amp; Lin, SG (2010). Improved liquid chromatography-tandem mass spectrometry method for the analysis of eptifibatide in human plasma. <i>Journal of chromatography. B, Analytical technologies in the biomedical and life sciences</i> 878(23) 2094–2100. DOI:<a href=\"https://doi.org/10.1016/j.jchromb.2010.06.012\">10.1016/j.jchromb.2010.06.012</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/20599442/\">https://pubmed.ncbi.nlm.nih.gov/20599442</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Eptifibatide;
