within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03E_DiureticsAndPotassiumSparingAgentsInCombination;
package C03EA14_ButizideAndPotassiumSpar
  extends Icons.PackageDrugs;
end C03EA14_ButizideAndPotassiumSpar;
