within Pharmacolibrary.Drugs.N_NervousSystem.N05C_HypnoticsAndSedatives.N05CM18_Dexmedetomidine;

model Dexmedetomidine
  extends Pharmacolibrary.Drugs.ATC.N.N05CM18;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>N05CM18</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Dexmedetomidine is a highly selective alpha-2 adrenergic receptor agonist used for sedation in intensive care settings and during procedural sedation. It is approved and widely used for sedation of mechanically ventilated adults and can be used in perioperative settings. It has sedative, anxiolytic, and analgesic properties with minimal respiratory depression.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetics reported from healthy adult subjects undergoing elective surgery; typical intravenous administration.</p><h4>References</h4><ol><li><p>Weerink, MAS, et al., &amp; Colin, P (2017). Clinical Pharmacokinetics and Pharmacodynamics of Dexmedetomidine. <i>Clinical pharmacokinetics</i> 56(8) 893–913. DOI:<a href=\"https://doi.org/10.1007/s40262-017-0507-7\">10.1007/s40262-017-0507-7</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/28105598/\">https://pubmed.ncbi.nlm.nih.gov/28105598</a></p></li><li><p>Ashraf, MW, et al., &amp; Saari, TI (2020). Population Modelling of Dexmedetomidine Pharmacokinetics and Haemodynamic Effects After Intravenous and Subcutaneous Administration. <i>Clinical pharmacokinetics</i> 59(11) 1467–1482. DOI:<a href=\"https://doi.org/10.1007/s40262-020-00900-3\">10.1007/s40262-020-00900-3</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32462542/\">https://pubmed.ncbi.nlm.nih.gov/32462542</a></p></li><li><p>Smith, HAB, et al., &amp; Berkenbosch, JW (2022). 2022 Society of Critical Care Medicine Clinical Practice Guidelines on Prevention and Management of Pain, Agitation, Neuromuscular Blockade, and Delirium in Critically Ill Pediatric Patients With Consideration of the ICU Environment and Early Mobility. <i>Pediatric critical care medicine : a journal of the Society of Critical Care Medicine and the World Federation of Pediatric Intensive and Critical Care Societies</i> 23(2) e74–e110. DOI:<a href=\"https://doi.org/10.1097/PCC.0000000000002873\">10.1097/PCC.0000000000002873</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35119438/\">https://pubmed.ncbi.nlm.nih.gov/35119438</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Dexmedetomidine;
