within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX19_Sabatolimab
  extends Icons.Package;
end L01FX19_Sabatolimab;
