within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination;
package G03FA11_LevonorgestrelAndEstroge
  extends Icons.PackageDrugs;
end G03FA11_LevonorgestrelAndEstroge;
