within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B02B_VitaminKAndOtherHemostatics;
package B02BD06_VonWillebrandFactorAndCo
  extends Icons.PackageDrugs;
end B02BD06_VonWillebrandFactorAndCo;
