within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis;
package A02BC54_RabeprazoleCombinations
  extends Icons.PackageDrugs;
end A02BC54_RabeprazoleCombinations;
