within Pharmacolibrary.Drugs.R_RespiratorySystem.R03A_AdrenergicsInhalants.R03AK10_VilanterolAndFluticasoneFuroate;

model VilanterolAndFluticasoneFuroate
  extends Pharmacolibrary.Drugs.ATC.R.R03AK10;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>VilanterolAndFluticasoneFuroate</td></tr><tr><td>ATC code:</td><td>R03AK10</td></tr><td>route:</td><td>inhalation</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Vilanterol and fluticasone furoate is a combination inhaled medication used for the maintenance treatment of asthma and chronic obstructive pulmonary disease (COPD). Vilanterol is a long-acting beta2-adrenergic agonist (LABA), while fluticasone furoate is an inhaled corticosteroid. The drug is approved and regularly used in clinical practice for long-term management of airway obstruction.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters derived from published studies in healthy adult subjects for inhaled administration of vilanterol 25 mcg and fluticasone furoate 100 mcg once daily.</p><h4>References</h4><ol><li><p>Siederer, S, et al., &amp; Yang, S (2016). Population Pharmacokinetics of Inhaled Fluticasone Furoate and Vilanterol in Subjects with Chronic Obstructive Pulmonary Disease. <i>European journal of drug metabolism and pharmacokinetics</i> 41(6) 743–758. DOI:<a href=\"https://doi.org/10.1007/s13318-015-0303-4\">10.1007/s13318-015-0303-4</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/26474864/\">https://pubmed.ncbi.nlm.nih.gov/26474864</a></p></li><li><p>Allen, A, et al., &amp; Yang, S (2016). Population pharmacokinetics of inhaled fluticasone furoate and vilanterol in adult and adolescent patients with asthma. <i>International journal of clinical pharmacology and therapeutics</i> 54(4) 269–281. DOI:<a href=\"https://doi.org/10.5414/CP202438\">10.5414/CP202438</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/26902504/\">https://pubmed.ncbi.nlm.nih.gov/26902504</a></p></li><li><p>Yang, S, et al., &amp; Peachey, G (2021). Population Pharmacokinetic Modeling of Fluticasone Furoate, Umeclidinium Bromide, and Vilanterol in Patients with Asthma, Using Data from a Phase IIIA Study (CAPTAIN). <i>Clinical pharmacokinetics</i> 60(7) 887–896. DOI:<a href=\"https://doi.org/10.1007/s40262-021-00988-1\">10.1007/s40262-021-00988-1</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33598874/\">https://pubmed.ncbi.nlm.nih.gov/33598874</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end VilanterolAndFluticasoneFuroate;
