within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX18_Amivantamab
  extends Icons.PackageDrugs;
end L01FX18_Amivantamab;
