within Pharmacolibrary.Drugs.C_CardiovascularSystem.C05A_AgentsForTreatmentOfHemorrhoidsAndAnalFissuresForTopicalUse;
package C05AA09_Dexamethasone
  extends Icons.Package;
end C05AA09_Dexamethasone;
