within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M05B_DrugsAffectingBoneStructureAndMineralization;
package M05BB05_AlendronicAcidCalciumAndColecalc
  extends Icons.Package;
end M05BB05_AlendronicAcidCalciumAndColecalc;
