within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombination;
package S01CA01_DexamethasoneAndAntiinfectives
  extends Icons.Package;
end S01CA01_DexamethasoneAndAntiinfectives;
