within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials.J01DD04_Ceftriaxone;

model Ceftriaxone
  extends Pharmacolibrary.Drugs.ATC.J.J01DD04;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Ceftriaxone</td></tr><tr><td>ATC code:</td><td>J01DD04</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Ceftriaxone is a third-generation cephalosporin antibiotic with broad-spectrum activity against both gram-positive and gram-negative bacteria. It is widely used for the treatment of infections such as pneumonia, meningitis, gonorrhea, and sepsis. Ceftriaxone is approved for clinical use worldwide and is often administered intravenously or intramuscularly in both hospital and outpatient settings.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in healthy adult subjects after single intravenous administration.</p><h4>References</h4><ol><li><p>Simon, N, et al., &amp; Urien, S (2006). Population pharmacokinetics of ceftriaxone and pharmacodynamic considerations in haemodialysed patients. <i>Clinical pharmacokinetics</i> 45(5) 493–501. DOI:<a href=\"https://doi.org/10.2165/00003088-200645050-00004\">10.2165/00003088-200645050-00004</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/16640454/\">https://pubmed.ncbi.nlm.nih.gov/16640454</a></p></li><li><p>Boast, A, et al., &amp; Gwee, A (2024). Population pharmacokinetic modeling of ceftriaxone in cerebrospinal fluid in children: should we be using once- or twice-daily dosing for meningitis?. <i>Antimicrobial agents and chemotherapy</i> 68(11) e0074724–None. DOI:<a href=\"https://doi.org/10.1128/aac.00747-24\">10.1128/aac.00747-24</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39377581/\">https://pubmed.ncbi.nlm.nih.gov/39377581</a></p></li><li><p>Sullins, AK, &amp; Abdel-Rahman, SM (2013). Pharmacokinetics of antibacterial agents in the CSF of children and adolescents. <i>Paediatric drugs</i> 15(2) 93–117. DOI:<a href=\"https://doi.org/10.1007/s40272-013-0017-5\">10.1007/s40272-013-0017-5</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/23529866/\">https://pubmed.ncbi.nlm.nih.gov/23529866</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Ceftriaxone;
