within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01X_OtherAntibacterials.J01XX11_Tedizolid;

model Tedizolid
  extends Pharmacolibrary.Drugs.ATC.J.J01XX11;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Tedizolid</td></tr><tr><td>ATC code:</td><td>J01XX11</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Tedizolid is an oxazolidinone-class antibacterial agent, primarily used for the treatment of acute bacterial skin and skin structure infections (ABSSSI) caused by Gram-positive pathogens, including methicillin-resistant Staphylococcus aureus (MRSA). It is approved for use in adults and adolescents.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in healthy adult volunteers after administration of tedizolid phosphate 200 mg orally once daily.</p><h4>References</h4><ol><li><p>Flanagan, S, et al., &amp; Prokocimer, P (2014). Tedizolid population pharmacokinetics, exposure response, and target attainment. <i>Antimicrobial agents and chemotherapy</i> 58(11) 6462–6470. DOI:<a href=\"https://doi.org/10.1128/AAC.03423-14\">10.1128/AAC.03423-14</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25136028/\">https://pubmed.ncbi.nlm.nih.gov/25136028</a></p></li><li><p>Li, D, et al., &amp; Rizk, ML (2021). Population Pharmacokinetics, Exposure-Response, and Probability of Target Attainment Analyses for Tedizolid in Adolescent Patients with Acute Bacterial Skin and Skin Structure Infections. <i>Antimicrobial agents and chemotherapy</i> 65(12) e0089521–None. DOI:<a href=\"https://doi.org/10.1128/AAC.00895-21\">10.1128/AAC.00895-21</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34516243/\">https://pubmed.ncbi.nlm.nih.gov/34516243</a></p></li><li><p>Park, AYJ, et al., &amp; Beringer, PM (2018). Pharmacokinetics of Tedizolid in Plasma and Sputum of Adults with Cystic Fibrosis. <i>Antimicrobial agents and chemotherapy</i> 62(9) –. DOI:<a href=\"https://doi.org/10.1128/AAC.00550-18\">10.1128/AAC.00550-18</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29914949/\">https://pubmed.ncbi.nlm.nih.gov/29914949</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Tedizolid;
