within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BX05_RespiratorySyncytialVirusVaccines
  extends Icons.Package;
end J07BX05_RespiratorySyncytialVirusVaccines;
