within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem;
package M01A_AntiinflammatoryAndAntirheumaticProductsNonSteroids
  extends Icons.Package;
end M01A_AntiinflammatoryAndAntirheumaticProductsNonSteroids;
