within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H05B_AntiParathyroidAgents;
package H05BA02_CalcitoninPorkNatural
  extends Icons.Package;
end H05BA02_CalcitoninPorkNatural;
