within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics.N02BF01_Gabapentin;

model Gabapentin
  extends Pharmacolibrary.Drugs.ATC.N.N02BF01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Gabapentin</td></tr><tr><td>ATC code:</td><td>N02BF01</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Gabapentin is an anticonvulsant medication primarily used to treat neuropathic pain and partial seizures. It is also approved for the management of postherpetic neuralgia and is widely used off-label for various pain syndromes and anxiety disorders. Gabapentin is currently approved and in clinical use in many countries.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters derived from studies in healthy adult volunteers following a single oral dose.</p><h4>References</h4><ol><li><p>Hampton, CE, et al., &amp; Pypendop, BH (2021). Pharmacokinetics of oral and compounded intravenous gabapentin in Duroc swine (Sus Scrofa). <i>Journal of veterinary pharmacology and therapeutics</i> 44(5) 776–782. DOI:<a href=\"https://doi.org/10.1111/jvp.12977\">10.1111/jvp.12977</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33978255/\">https://pubmed.ncbi.nlm.nih.gov/33978255</a></p></li><li><p>Adrian, D, et al., &amp; Lascelles, BDX (2018). The pharmacokinetics of gabapentin in cats. <i>Journal of veterinary internal medicine</i> 32(6) 1996–2002. DOI:<a href=\"https://doi.org/10.1111/jvim.15313\">10.1111/jvim.15313</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30307652/\">https://pubmed.ncbi.nlm.nih.gov/30307652</a></p></li><li><p>Tran, P, et al., &amp; Lee, YB (2017). Population pharmacokinetics of gabapentin in healthy Korean subjects with influence of genetic polymorphisms of ABCB1. <i>Journal of pharmacokinetics and pharmacodynamics</i> 44(6) 567–579. DOI:<a href=\"https://doi.org/10.1007/s10928-017-9549-6\">10.1007/s10928-017-9549-6</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29018999/\">https://pubmed.ncbi.nlm.nih.gov/29018999</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Gabapentin;
