within Pharmacolibrary.Drugs.D_Dermatologicals.D01A_AntifungalsForTopicalUse;
package D01AA20_GriseofulvinAndSalicylicAcidCombination
  extends Icons.Package;
end D01AA20_GriseofulvinAndSalicylicAcidCombination;
