within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AJ51_PertussisInactivatedWholeCellCombinationsWithToxoids
  extends Icons.Package;
end J07AJ51_PertussisInactivatedWholeCellCombinationsWithToxoids;
