within Pharmacolibrary.Drugs.N_NervousSystem.N06B_PsychostimulantsAgentsUsedForAdhdAndNootropics;
package N06BA15_DexmethylphenidateAndSerdexmethy
  extends Icons.PackageDrugs;
end N06BA15_DexmethylphenidateAndSerdexmethy;
