within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX12_Tafasitamab
  extends Icons.PackageDrugs;
end L01FX12_Tafasitamab;
