within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AR17_EmtricitabineAndTenofovirAlafenamide
  extends Icons.Package;
end J05AR17_EmtricitabineAndTenofovirAlafenamide;
