within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01C_PlantAlkaloidsAndOtherNaturalProducts.L01CB01_Etoposide;

model Etoposide
  extends Pharmacolibrary.Drugs.ATC.L.L01CB01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>L01CB01</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Etoposide is a topoisomerase II inhibitor used as an antineoplastic agent for the treatment of various malignancies including small-cell lung cancer, testicular cancer, lymphoma, and leukemia. It is commonly administered intravenously or orally and is still approved and widely used in cancer chemotherapy.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetics reported in adult cancer patients following intravenous administration; large multicenter population PK study.</p><h4>References</h4><ol><li><p>Reif, S, et al., &amp; Jaehde, U (2002). Population pharmacokinetics of etoposide. <i>International journal of clinical pharmacology and therapeutics</i> 40(12) 578–579. DOI:<a href=\"https://doi.org/10.5414/cpp40578\">10.5414/cpp40578</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/12503821/\">https://pubmed.ncbi.nlm.nih.gov/12503821</a></p></li><li><p>Nguyen, L, et al., &amp; Canal, P (1998). Population pharmacokinetics of total and unbound etoposide. <i>Cancer chemotherapy and pharmacology</i> 41(2) 125–132. DOI:<a href=\"https://doi.org/10.1007/s002800050718\">10.1007/s002800050718</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/9443625/\">https://pubmed.ncbi.nlm.nih.gov/9443625</a></p></li><li><p>Cheng, Y, et al., &amp; Zhou, L (2024). Myeloprotection with trilaciclib in Chinese patients with extensive-stage small cell lung cancer receiving chemotherapy: Results from a randomized, double-blind, placebo-controlled phase III study (TRACES). <i>Lung cancer (Amsterdam, Netherlands)</i> 188 107455–None. DOI:<a href=\"https://doi.org/10.1016/j.lungcan.2023.107455\">10.1016/j.lungcan.2023.107455</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/38224653/\">https://pubmed.ncbi.nlm.nih.gov/38224653</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Etoposide;
