within Pharmacolibrary.Drugs.N_NervousSystem.N05C_HypnoticsAndSedatives;
package N05CB02_BarbituratesInCombinationWithOtherDrugs
  extends Icons.Package;
end N05CB02_BarbituratesInCombinationWithOtherDrugs;
