within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FF07_Dostarlimab
  extends Icons.PackageDrugs;
end L01FF07_Dostarlimab;
