within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals.J05AR28_StavudineAndLamivudine;

model StavudineAndLamivudine
  extends Pharmacolibrary.Drugs.ATC.J.J05AR28;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>J05AR28</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Stavudine and lamivudine are nucleoside reverse transcriptase inhibitors (NRTIs) used in combination for the treatment of HIV-1 infection. The fixed-dose combination is classified under ATC code J05AR28 and is intended to suppress viral replication in HIV-positive individuals. Both drugs are approved and used within antiretroviral therapy regimens but have largely been replaced by newer, less toxic alternatives in high-income settings. The fixed-dose combination may still be used in resource-constrained settings.</p><h4>Pharmacokinetics</h4><p>No published population pharmacokinetic studies found for the fixed-dose combination of stavudine and lamivudine. Below are rough estimated parameters based on published PK data for the individual drugs in healthy adults after oral administration.</p><h4>References</h4><ol><li><p>Panhard, X, et al., &amp; Mentré, F (2007). Population pharmacokinetic analysis of lamivudine, stavudine and zidovudine in controlled HIV-infected patients on HAART. <i>European journal of clinical pharmacology</i> 63(11) 1019–1029. DOI:<a href=\"https://doi.org/10.1007/s00228-007-0337-x\">10.1007/s00228-007-0337-x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/17694300/\">https://pubmed.ncbi.nlm.nih.gov/17694300</a></p></li><li><p>Kwara, A, et al., &amp; Court, MH (2009). Interindividual variability in pharmacokinetics of generic nucleoside reverse transcriptase inhibitors in TB/HIV-coinfected Ghanaian patients: UGT2B7*1c is associated with faster zidovudine clearance and glucuronidation. <i>Journal of clinical pharmacology</i> 49(9) 1079–1090. DOI:<a href=\"https://doi.org/10.1177/0091270009338482\">10.1177/0091270009338482</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/19628728/\">https://pubmed.ncbi.nlm.nih.gov/19628728</a></p></li><li><p>Saez-Llorens, X, et al., &amp; Rousseau, F (2008). Long-term safety and efficacy results of once-daily emtricitabine-based highly active antiretroviral therapy regimens in human immunodeficiency virus-infected pediatric subjects. <i>Pediatrics</i> 121(4) e827–e835. DOI:<a href=\"https://doi.org/10.1542/peds.2006-3078\">10.1542/peds.2006-3078</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/18332076/\">https://pubmed.ncbi.nlm.nih.gov/18332076</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end StavudineAndLamivudine;
