within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonSteroids;
package M01AX26_AvocadoAndSoyabeanOilUnsaponifiables
  extends Icons.Package;
end M01AX26_AvocadoAndSoyabeanOilUnsaponifiables;
