within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B02B_VitaminKAndOtherHemostatics;
package B02BC30_FactorIxIiViiAndXCombina
  extends Icons.PackageDrugs;
end B02BC30_FactorIxIiViiAndXCombina;
