within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03C_AntispasmodicsInCombinationWithPsycholeptics;
package A03CA09_PipenzolateAndPsycholept
  extends Icons.PackageDrugs;
end A03CA09_PipenzolateAndPsycholept;
