within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BX09_Acetoxolone
  extends Icons.Package;
end A02BX09_Acetoxolone;
