within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AX01_Clodantoin
  extends Icons.PackageDrugs;
end G01AX01_Clodantoin;
