within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07C_BetaBlockingAgentsAndOtherDiuretics;
package C07CB03_AtenololAndOtherDiuretic
  extends Icons.PackageDrugs;
end C07CB03_AtenololAndOtherDiuretic;
