within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03G_GonadotropinsAndOtherOvulationStimulants;
package G03GA06_FollitropinBeta
  extends Icons.PackageDrugs;
end G03GA06_FollitropinBeta;
