within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonStero;
package M01AX12_GlucosaminoglycanPolysul
  extends Icons.PackageDrugs;
end M01AX12_GlucosaminoglycanPolysul;
