within Pharmacolibrary.Drugs.S_SensoryOrgans.S03C_CorticosteroidsAndAntiinfectivesInCombination;
package S03CA01_DexamethasoneAndAntiinfe
  extends Icons.PackageDrugs;
end S03CA01_DexamethasoneAndAntiinfe;
