within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10A_InsulinsAndAnalogues;
package A10AD06_InsulinDegludecAndInsulinAspart
  extends Icons.Package;
end A10AD06_InsulinDegludecAndInsulinAspart;
