within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BA01_EncephalitisTickBorneInactivated
  extends Icons.PackageDrugs;
end J07BA01_EncephalitisTickBorneInactivated;
