within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD26_MetforminAndLobeglitazone
  extends Icons.Package;
end A10BD26_MetforminAndLobeglitazone;
