within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonSteroids;
package M01AE56_NaproxenAndMisoprostol
  extends Icons.Package;
end M01AE56_NaproxenAndMisoprostol;
