within Pharmacolibrary.Drugs.R_RespiratorySystem.R05C_ExpectorantsExclCombinationsWithCoughSuppressants;
package R05CA12_HederaeHelicisFolium
  extends Icons.Package;
end R05CA12_HederaeHelicisFolium;
