within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02L_AntihypertensivesAndDiureticsInCombination;
package C02LG03_PicodralazineAndDiuretic
  extends Icons.PackageDrugs;
end C02LG03_PicodralazineAndDiuretic;
