within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01B_Antimalarials.P01BF02_ArtesunateAndMefloquine;

model ArtesunateAndMefloquine
  extends Pharmacolibrary.Drugs.ATC.P.P01BF02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>P01BF02</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Artesunate and mefloquine is a fixed-dose combination antimalarial therapy used for the treatment of uncomplicated Plasmodium falciparum malaria. Artesunate is a fast-acting artemisinin derivative, while mefloquine is a longer-acting antimalarial agent. This combination is approved and widely used in endemic regions as a standard therapy for malaria.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters for artesunate and mefloquine in healthy adult subjects, mostly from Southeast Asia, following oral administration of the fixed-dose combination.</p><h4>References</h4><ol><li><p>Rattanapunya, S, et al., &amp; Na-Bangchang, K (2015). Pharmacokinetic interactions between artesunate-mefloquine and ritonavir-boosted lopinavir in healthy Thai adults. <i>Malaria journal</i> 14 400–None. DOI:<a href=\"https://doi.org/10.1186/s12936-015-0916-8\">10.1186/s12936-015-0916-8</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/26452725/\">https://pubmed.ncbi.nlm.nih.gov/26452725</a></p></li><li><p>Reuter, SE, et al., &amp; Olliaro, PL (2015). Population pharmacokinetics of orally administered mefloquine in healthy volunteers and patients with uncomplicated Plasmodium falciparum malaria. <i>The Journal of antimicrobial chemotherapy</i> 70(3) 868–876. DOI:<a href=\"https://doi.org/10.1093/jac/dku430\">10.1093/jac/dku430</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25377567/\">https://pubmed.ncbi.nlm.nih.gov/25377567</a></p></li><li><p>Birgersson, S, et al., &amp; Tarning, J (2019). Population pharmacokinetics of artesunate and dihydroartemisinin in pregnant and non-pregnant women with uncomplicated . <i>Wellcome open research</i> 4 45–None. DOI:<a href=\"https://doi.org/10.12688/wellcomeopenres.14849.2\">10.12688/wellcomeopenres.14849.2</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32025570/\">https://pubmed.ncbi.nlm.nih.gov/32025570</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end ArtesunateAndMefloquine;
