within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01B_Antimalarials;
package P01BF02_ArtesunateAndMefloquine
  extends Icons.PackageDrugs;
end P01BF02_ArtesunateAndMefloquine;
