within Pharmacolibrary.Drugs.S_SensoryOrgans.S01H_LocalAnesthetics;
package S01HA30_CombinationsOphthalmologicalsOtherAntiallergics
  extends Icons.Package;
end S01HA30_CombinationsOphthalmologicalsOtherAntiallergics;
