within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03C_AntispasmodicsInCombinationWithPsycholeptics;
package A03CA02_ClidiniumAndPsycholeptics
  extends Icons.Package;
end A03CA02_ClidiniumAndPsycholeptics;
