within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01E_ProteinKinaseInhibitors.L01EJ02_Fedratinib;

model Fedratinib
  extends Pharmacolibrary.Drugs.ATC.L.L01EJ02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Fedratinib</td></tr><tr><td>ATC code:</td><td>L01EJ02</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Fedratinib is an oral selective Janus kinase 2 (JAK2) inhibitor indicated for the treatment of adult patients with intermediate-2 or high-risk primary or secondary (post–polycythemia vera or post–essential thrombocythemia) myelofibrosis. It is currently approved by regulatory agencies such as the FDA.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters in adult patients with myelofibrosis after repeated oral administration of 400 mg once daily.</p><h4>References</h4><ol><li><p>Ogasawara, K, et al., &amp; Li, Y (2019). Population pharmacokinetics of fedratinib in patients with myelofibrosis, polycythemia vera, and essential thrombocythemia. <i>Cancer chemotherapy and pharmacology</i> 84(4) 891–898. DOI:<a href=\"https://doi.org/10.1007/s00280-019-03929-9\">10.1007/s00280-019-03929-9</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31444617/\">https://pubmed.ncbi.nlm.nih.gov/31444617</a></p></li><li><p>Chen, Y, et al., &amp; Krishna, G (2022). Effect of fluconazole on the pharmacokinetics of a single dose of fedratinib in healthy adults. <i>Cancer chemotherapy and pharmacology</i> 90(4) 325–334. DOI:<a href=\"https://doi.org/10.1007/s00280-022-04464-w\">10.1007/s00280-022-04464-w</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36001108/\">https://pubmed.ncbi.nlm.nih.gov/36001108</a></p></li><li><p>Chen, Y, et al., &amp; Ogasawara, K (2025). Exposure-response relationship of fedratinib in patients with intermediate-2 or high-risk myelofibrosis. <i>British journal of clinical pharmacology</i> None –. DOI:<a href=\"https://doi.org/10.1002/bcp.70118\">10.1002/bcp.70118</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/40485284/\">https://pubmed.ncbi.nlm.nih.gov/40485284</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Fedratinib;
