within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AA17_MedroxyprogesteroneAndEstradiol
  extends Icons.Package;
end G03AA17_MedroxyprogesteroneAndEstradiol;
