within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA11_DiphtheriaHaemophilusInfluenzaeBPertussisTetanusHepatitisB
  extends Icons.Package;
end J07CA11_DiphtheriaHaemophilusInfluenzaeBPertussisTetanusHepatitisB;
