within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J04A_DrugsForTreatmentOfTuberculosis;
package J04AM05_RifampicinPyrazinamideAn
  extends Icons.PackageDrugs;
end J04AM05_RifampicinPyrazinamideAn;
