within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G02B_ContraceptivesForTopicalUse;
package G02BA03_PlasticIudWithProgestoge
  extends Icons.PackageDrugs;
end G02BA03_PlasticIudWithProgestoge;
