within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07F_BetaBlockingAgentsOtherCombinations;
package C07FX06_CarvedilolAndIvabradine
  extends Icons.PackageDrugs;
end C07FX06_CarvedilolAndIvabradine;
