within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03A_DrugsForFunctionalGastrointestinalDisorders;
package A03AB18_PrifiniumBromide
  extends Icons.PackageDrugs;
end A03AB18_PrifiniumBromide;
