within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01E_ProteinKinaseInhibitors.L01EK01_Axitinib;

model Axitinib
  extends Pharmacolibrary.Drugs.ATC.L.L01EK01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Axitinib</td></tr><tr><td>ATC code:</td><td>L01EK01</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Axitinib is an oral, small-molecule tyrosine kinase inhibitor targeting vascular endothelial growth factor receptors (VEGFR)-1, -2, and -3. It is primarily used for the treatment of advanced renal cell carcinoma and is approved for use in several countries, including the United States and the European Union.</p><h4>Pharmacokinetics</h4><p>Population pharmacokinetic analysis in adult patients with solid tumors, including renal cell carcinoma, with oral administration. Data represents a typical adult (mean weight ~70 kg) without severe hepatic or renal impairment.</p><h4>References</h4><ol><li><p>Chen, Y, et al., &amp; Pithavala, YK (2015). Axitinib plasma pharmacokinetics and ethnic differences. <i>Investigational new drugs</i> 33(2) 521–532. DOI:<a href=\"https://doi.org/10.1007/s10637-015-0214-x\">10.1007/s10637-015-0214-x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25663295/\">https://pubmed.ncbi.nlm.nih.gov/25663295</a></p></li><li><p>Chen, Y, et al., &amp; Pithavala, YK (2013). Clinical pharmacology of axitinib. <i>Clinical pharmacokinetics</i> 52(9) 713–725. DOI:<a href=\"https://doi.org/10.1007/s40262-013-0068-3\">10.1007/s40262-013-0068-3</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/23677771/\">https://pubmed.ncbi.nlm.nih.gov/23677771</a></p></li><li><p>Chen, Y, et al., &amp; Hu, P (2011). A Phase I study to evaluate the pharmacokinetics of axitinib (AG-13736) in healthy Chinese volunteers. <i>International journal of clinical pharmacology and therapeutics</i> 49(11) 679–687. DOI:<a href=\"https://doi.org/10.5414/cp201570\">10.5414/cp201570</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/22011693/\">https://pubmed.ncbi.nlm.nih.gov/22011693</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Axitinib;
