within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis;
package A02BC05_Esomeprazole
  extends Icons.PackageDrugs;
end A02BC05_Esomeprazole;
