within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA07_DiphtheriaHepatitisBTeta
  extends Icons.PackageDrugs;
end J07CA07_DiphtheriaHepatitisBTeta;
