within Pharmacolibrary.Drugs.R_RespiratorySystem.R05D_CoughSuppressantsExclCombinationsWithExpectorants;
package R05DA20_PholcodineAndCombinations
  extends Icons.Package;
end R05DA20_PholcodineAndCombinations;
