within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombina;
package S01CA11_ClobetasoneAndAntiinfect
  extends Icons.PackageDrugs;
end S01CA11_ClobetasoneAndAntiinfect;
