within Pharmacolibrary.Drugs.R_RespiratorySystem.R03B_OtherDrugsForObstructiveAirwayDiseasesInhalants;
package R03BB03_StramoniPreparations
  extends Icons.PackageDrugs;
end R03BB03_StramoniPreparations;
