within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX13_EnfortumabVedotin
  extends Icons.Package;
end L01FX13_EnfortumabVedotin;
