within Pharmacolibrary.Drugs.R_RespiratorySystem.R05C_ExpectorantsExclCombinationsWithCoughSuppressant;
package R05CA12_HederaeHelicisFolium
  extends Icons.PackageDrugs;
end R05CA12_HederaeHelicisFolium;
