within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AA11_Pentamycin
  extends Icons.Package;
end G01AA11_Pentamycin;
