within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03A_LowCeilingDiureticsThiazides.C03AA04_Chlorothiazide;

model Chlorothiazide
  extends Pharmacolibrary.Drugs.ATC.C.C03AA04;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Chlorothiazide</td></tr><tr><td>ATC code:</td><td>C03AA04</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Chlorothiazide is a thiazide diuretic used for the management of hypertension and edema related to congestive heart failure, liver cirrhosis, or corticosteroid and estrogen therapy. It acts primarily on the distal convoluted tubule in the kidney to promote sodium and water excretion. Chlorothiazide remains approved and in clinical use.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported for healthy adult subjects after a single oral dose.</p><h4>References</h4><ol><li><p>Van Wart, SA, et al., &amp; Mager, DE (2013). Population-based meta-analysis of hydrochlorothiazide pharmacokinetics. <i>Biopharmaceutics &amp; drug disposition</i> 34(9) 527–539. DOI:<a href=\"https://doi.org/10.1002/bdd.1863\">10.1002/bdd.1863</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/24123104/\">https://pubmed.ncbi.nlm.nih.gov/24123104</a></p></li><li><p>Ngo, L, et al., &amp; Lee, YB (2018). Effects of hydrochlorothiazide and amlodipine on single oral dose pharmacokinetics of valsartan in healthy Korean subjects: Population model-based approach. <i>European journal of pharmaceutical sciences : official journal of the European Federation for Pharmaceutical Sciences</i> 118 154–164. DOI:<a href=\"https://doi.org/10.1016/j.ejps.2018.03.031\">10.1016/j.ejps.2018.03.031</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29604332/\">https://pubmed.ncbi.nlm.nih.gov/29604332</a></p></li><li><p>Kousovista, R, et al., &amp; Karalis, V (2021). Validation of population pharmacokinetic models: a comparison of internal and external validation approaches for hydrochlorothiazide. <i>Xenobiotica; the fate of foreign compounds in biological systems</i> 51(12) 1372–1388. DOI:<a href=\"https://doi.org/10.1080/00498254.2021.2012727\">10.1080/00498254.2021.2012727</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34842039/\">https://pubmed.ncbi.nlm.nih.gov/34842039</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Chlorothiazide;
