within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins;
package J01CE30_PhenoxymethylpenicillinAndSulfon
  extends Icons.PackageDrugs;
end J01CE30_PhenoxymethylpenicillinAndSulfon;
