within Pharmacolibrary.Drugs.N_NervousSystem.N07B_DrugsUsedInAddictiveDisorders.N07BC51_BuprenorphineCombinations;

model BuprenorphineCombinations
  extends Pharmacolibrary.Drugs.ATC.N.N07BC51;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>BuprenorphineCombinations</td></tr><tr><td>ATC code:</td><td>N07BC51</td></tr><td>route:</td><td>sublingual</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Buprenorphine, in combination with naloxone, is a partial opioid agonist medication primarily used for the treatment of opioid dependence and opioid use disorder. The combination is an approved and widely used pharmacotherapy to reduce withdrawal symptoms and cravings and is designed to reduce misuse potential of buprenorphine alone.</p><h4>Pharmacokinetics</h4><p>Population pharmacokinetics in adult opioid-dependent patients (males and females, aged 18-65 years), typical for sublingual tablet co-formulation buprenorphine/naloxone.</p><h4>References</h4><ol><li><p>Gu, M, et al., &amp; Zhu, X (2023). Population pharmacokinetics of buprenorphine and naloxone sublingual combination in Chinese healthy volunteers and patients with opioid use disorder: Model-based dose optimization. <i>Frontiers in pharmacology</i> 14 1089862–None. DOI:<a href=\"https://doi.org/10.3389/fphar.2023.1089862\">10.3389/fphar.2023.1089862</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36744255/\">https://pubmed.ncbi.nlm.nih.gov/36744255</a></p></li><li><p>Jones, AK, et al., &amp; Laffont, CM (2021). Population Pharmacokinetics of a Monthly Buprenorphine Depot Injection for the Treatment of Opioid Use Disorder: A Combined Analysis of Phase II and Phase III Trials. <i>Clinical pharmacokinetics</i> 60(4) 527–540. DOI:<a href=\"https://doi.org/10.1007/s40262-020-00957-0\">10.1007/s40262-020-00957-0</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33135125/\">https://pubmed.ncbi.nlm.nih.gov/33135125</a></p></li><li><p>Jones, JD, et al., &amp; Comer, SD (2015). Abuse potential of intranasal buprenorphine versus buprenorphine/naloxone in buprenorphine-maintained heroin users. <i>Addiction biology</i> 20(4) 784–798. DOI:<a href=\"https://doi.org/10.1111/adb.12163\">10.1111/adb.12163</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25060839/\">https://pubmed.ncbi.nlm.nih.gov/25060839</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end BuprenorphineCombinations;
