within Pharmacolibrary.Drugs.R_RespiratorySystem.R05D_CoughSuppressantsExclCombinationsWithExpectorants.R05DA04_Codeine;

model Codeine
  extends Pharmacolibrary.Drugs.ATC.R.R05DA04;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>R05DA04</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Codeine is an opioid analgesic used for the relief of mild to moderate pain and as an antitussive to suppress cough. It is frequently combined with other analgesics such as paracetamol or ibuprofen. Codeine is still approved and used today in many countries, although its use is controlled due to potential for abuse and variable metabolism.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters in healthy adult volunteers after oral administration of codeine phosphate.</p><h4>References</h4><ol><li><p>Lugo, RA, &amp; Kern, SE (2004). The pharmacokinetics of oxycodone. <i>Journal of pain &amp; palliative care pharmacotherapy</i> 18(4) 17–30. DOI:<a href=\"https://doi.org/10.1300/j354v18n04_03\">10.1300/j354v18n04_03</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/15760805/\">https://pubmed.ncbi.nlm.nih.gov/15760805</a></p></li><li><p>Thigpen, JC, et al., &amp; Harirforoosh, S (2019). Opioids: A Review of Pharmacokinetics and Pharmacodynamics in Neonates, Infants, and Children. <i>European journal of drug metabolism and pharmacokinetics</i> 44(5) 591–609. DOI:<a href=\"https://doi.org/10.1007/s13318-019-00552-0\">10.1007/s13318-019-00552-0</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31006834/\">https://pubmed.ncbi.nlm.nih.gov/31006834</a></p></li><li><p>Gretler, SR, et al., &amp; Knych, HK (2020). Metabolism, pharmacokinetics and selected pharmacodynamic effects of codeine following a single oral administration to horses. <i>Veterinary anaesthesia and analgesia</i> 47(5) 694–704. DOI:<a href=\"https://doi.org/10.1016/j.vaa.2020.04.004\">10.1016/j.vaa.2020.04.004</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32654915/\">https://pubmed.ncbi.nlm.nih.gov/32654915</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Codeine;
