within Pharmacolibrary.Drugs.R_RespiratorySystem.R03C_AdrenergicsForSystemicUse.R03CC02_Salbutamol;

model Salbutamol
  extends Pharmacolibrary.Drugs.ATC.R.R03CC02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Salbutamol</td></tr><tr><td>ATC code:</td><td>R03CC02</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Salbutamol (also known as albuterol) is a short-acting β2 adrenergic receptor agonist used primarily for the relief and prevention of bronchospasm in conditions such as asthma and chronic obstructive pulmonary disease (COPD). It is approved for use as a bronchodilator and is commonly administered via inhalation, but can also be given orally or intravenously in certain scenarios.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in healthy adult volunteers following oral administration.</p><h4>References</h4><ol><li><p>Marques, L, &amp; Vale, N (2024). Improving Individualized Salbutamol Treatment: A Population Pharmacokinetic Model for Oral Salbutamol in Virtual Patients. <i>Pharmaceutics</i> 17(1) –. DOI:<a href=\"https://doi.org/10.3390/pharmaceutics17010039\">10.3390/pharmaceutics17010039</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39861686/\">https://pubmed.ncbi.nlm.nih.gov/39861686</a></p></li><li><p>Tan, WC, &amp; Lee, HS (1991). Pharmacokinetics of oral salbutamol controlled-release in Asian patients with asthma. <i>European journal of clinical pharmacology</i> 41(5) 495–496. DOI:<a href=\"https://doi.org/10.1007/BF00626378\">10.1007/BF00626378</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/1761082/\">https://pubmed.ncbi.nlm.nih.gov/1761082</a></p></li><li><p>Reinecke, I, et al., &amp; Garmann, D (2018). An Integrated Population Pharmacokinetic Analysis to Characterize Levonorgestrel Pharmacokinetics After Different Administration Routes. <i>Journal of clinical pharmacology</i> 58(12) 1639–1654. DOI:<a href=\"https://doi.org/10.1002/jcph.1288\">10.1002/jcph.1288</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30207604/\">https://pubmed.ncbi.nlm.nih.gov/30207604</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Salbutamol;
