within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B03X_OtherAntianemicPreparations;
package B03XA03_MethoxyPolyethyleneGlycolEpoetin
  extends Icons.Package;
end B03XA03_MethoxyPolyethyleneGlycolEpoetin;
