within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01C_AgentsAgainstLeishmaniasisAndTrypanosomiasis;
package P01CX04_Miltefosine
  extends Icons.PackageDrugs;
end P01CX04_Miltefosine;
