within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonStero;
package M01AC56_MeloxicamCombinations
  extends Icons.PackageDrugs;
end M01AC56_MeloxicamCombinations;
