within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD15_MetforminAndDapagliflozin
  extends Icons.Package;
end A10BD15_MetforminAndDapagliflozin;
