within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AH07_MeningococcusCPurifiedPolysaccharidesAntigenConjugated
  extends Icons.Package;
end J07AH07_MeningococcusCPurifiedPolysaccharidesAntigenConjugated;
