within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01R_CombinationsOfAntibacterials;
package J01RA02_SulfonamidesCombinations
  extends Icons.PackageDrugs;
end J01RA02_SulfonamidesCombinations;
