within Pharmacolibrary.Drugs.N_NervousSystem.N06A_Antidepressants.N06AX22_Agomelatine;

model Agomelatine
  extends Pharmacolibrary.Drugs.ATC.N.N06AX22;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>N06AX22</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Agomelatine is an antidepressant that acts as an agonist at melatonergic MT1 and MT2 receptors and as an antagonist at 5-HT2C serotonin receptors. It is used primarily in the treatment of major depressive disorder in adults. Agomelatine is approved in several countries for clinical use in depression.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters summarized for healthy adult subjects after oral administration as single and multiple doses.</p><h4>References</h4><ol><li><p>Xie, F, et al., &amp; Cheng, Z (2019). A semiphysiological population pharmacokinetic model of agomelatine and its metabolites in Chinese healthy volunteers. <i>British journal of clinical pharmacology</i> 85(5) 1003–1014. DOI:<a href=\"https://doi.org/10.1111/bcp.13902\">10.1111/bcp.13902</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30761579/\">https://pubmed.ncbi.nlm.nih.gov/30761579</a></p></li><li><p>Song, L, et al., &amp; Wang, L (2014). Effect of CYP1A2 polymorphism on the pharmacokinetics of agomelatine in Chinese healthy male volunteers. <i>Journal of clinical pharmacy and therapeutics</i> 39(2) 204–209. DOI:<a href=\"https://doi.org/10.1111/jcpt.12118\">10.1111/jcpt.12118</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/24372004/\">https://pubmed.ncbi.nlm.nih.gov/24372004</a></p></li><li><p>ElKady, EF, et al., &amp; Farouk, F (2018). Optimized bio-analytical methods development and comparative pharmacokinetic studies of four antidepressants in Egyptian population based on gender difference. <i>Journal of chromatography. B, Analytical technologies in the biomedical and life sciences</i> 1102-1103 135–142. DOI:<a href=\"https://doi.org/10.1016/j.jchromb.2018.10.018\">10.1016/j.jchromb.2018.10.018</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30388703/\">https://pubmed.ncbi.nlm.nih.gov/30388703</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Agomelatine;
