within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials;
package J01DD58_CefiximeAndBetaLactamaseInhibito
  extends Icons.Package;
end J01DD58_CefiximeAndBetaLactamaseInhibito;
