within Pharmacolibrary.Drugs.R_RespiratorySystem.R03D_OtherSystemicDrugsForObstructiveAirwayDiseases;
package R03DB06_EtamiphyllineAndAdrenergics
  extends Icons.Package;
end R03DB06_EtamiphyllineAndAdrenergics;
