within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids.G01AA03_AmphotericinB;

model AmphotericinB
  extends Pharmacolibrary.Drugs.ATC.G.G01AA03;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>AmphotericinB</td></tr><tr><td>ATC code:</td><td>G01AA03</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Amphotericin B is a polyene antifungal agent used primarily in the treatment of severe, systemic fungal infections. It is considered a drug of choice for life-threatening mycoses, including cryptococcal meningitis and invasive candidiasis. Despite its effectiveness, it is associated with significant nephrotoxicity and infusion-related reactions. Conventional amphotericin B deoxycholate is still in use, while lipid formulations are also approved to reduce toxicity.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters in adult patients with systemic fungal infections, administered intravenous amphotericin B deoxycholate (non-lipid formulation).</p><h4>References</h4><ol><li><p>Groll, AH, et al., &amp; Brüggemann, RJM (2019). Clinical Pharmacokinetics, Pharmacodynamics, Safety and Efficacy of Liposomal Amphotericin B. <i>Clinical infectious diseases : an official publication of the Infectious Diseases Society of America</i> 68(Suppl 4) S260–S274. DOI:<a href=\"https://doi.org/10.1093/cid/ciz076\">10.1093/cid/ciz076</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31222253/\">https://pubmed.ncbi.nlm.nih.gov/31222253</a></p></li><li><p>Würthwein, G, et al., &amp; Walsh, TJ (2005). Population pharmacokinetics of amphotericin B lipid complex in neonates. <i>Antimicrobial agents and chemotherapy</i> 49(12) 5092–5098. DOI:<a href=\"https://doi.org/10.1128/AAC.49.12.5092-5098.2005\">10.1128/AAC.49.12.5092-5098.2005</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/16304177/\">https://pubmed.ncbi.nlm.nih.gov/16304177</a></p></li><li><p>Nath, CE, et al., &amp; Earl, JW (2001). Population pharmacokinetics of amphotericin B in children with malignant diseases. <i>British journal of clinical pharmacology</i> 52(6) 671–680. DOI:<a href=\"https://doi.org/10.1046/j.0306-5251.2001.01496.x\">10.1046/j.0306-5251.2001.01496.x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/11736878/\">https://pubmed.ncbi.nlm.nih.gov/11736878</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end AmphotericinB;
