within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AA03_AmphotericinB
  extends Icons.Package;
end G01AA03_AmphotericinB;
