within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H01A_AnteriorPituitaryLobeHormonesAndAnalogues;
package H01AC09_Lonapegsomatropin
  extends Icons.Package;
end H01AC09_Lonapegsomatropin;
