within Pharmacolibrary.Drugs.D_Dermatologicals.D07C_CorticosteroidsCombinationsWithAntibiotics;
package D07CC05_FluocinonideAndAntibiotics
  extends Icons.Package;
end D07CC05_FluocinonideAndAntibiotics;
