within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H05A_ParathyroidHormonesAndAnalogues;
package H05AA01_ParathyroidGlandExtract
  extends Icons.PackageDrugs;
end H05AA01_ParathyroidGlandExtract;
