within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01B_Antimalarials.P01BF01_ArtemetherAndLumefantrine;

model ArtemetherAndLumefantrine
  extends Pharmacolibrary.Drugs.ATC.P.P01BF01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>P01BF01</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Artemether and lumefantrine combination is an artemisinin-based antimalarial therapy (ACT) used for the treatment of uncomplicated Plasmodium falciparum malaria. It is a widely approved first-line treatment in many countries and is currently recommended by the World Health Organization for malaria therapy.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in healthy adult volunteers (non-pregnant, mixed sex, age ~18-45 years) after oral administration of standard dose.</p><h4>References</h4><ol><li><p>Lohy Das, J, et al., &amp; Dorlo, TPC (2018). Population Pharmacokinetics of Artemether, Dihydroartemisinin, and Lumefantrine in Rwandese Pregnant Women Treated for Uncomplicated Plasmodium falciparum Malaria. <i>Antimicrobial agents and chemotherapy</i> 62(10) –. DOI:<a href=\"https://doi.org/10.1128/AAC.00518-18\">10.1128/AAC.00518-18</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30061282/\">https://pubmed.ncbi.nlm.nih.gov/30061282</a></p></li><li><p>Hietala, SF, et al., &amp; Ashton, M (2010). Population pharmacokinetics and pharmacodynamics of artemether and lumefantrine during combination treatment in children with uncomplicated falciparum malaria in Tanzania. <i>Antimicrobial agents and chemotherapy</i> 54(11) 4780–4788. DOI:<a href=\"https://doi.org/10.1128/AAC.00252-10\">10.1128/AAC.00252-10</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/20713675/\">https://pubmed.ncbi.nlm.nih.gov/20713675</a></p></li><li><p>Kloprogge, F, et al., &amp; Tarning, J (2013). Population Pharmacokinetics of Lumefantrine in Pregnant and Nonpregnant Women With Uncomplicated Plasmodium falciparum Malaria in Uganda. <i>CPT: pharmacometrics &amp; systems pharmacology</i> 2(11) e83–None. DOI:<a href=\"https://doi.org/10.1038/psp.2013.59\">10.1038/psp.2013.59</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/24226803/\">https://pubmed.ncbi.nlm.nih.gov/24226803</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end ArtemetherAndLumefantrine;
