within Pharmacolibrary.Drugs.R_RespiratorySystem.R05F_CoughSuppressantsAndExpectorantsCombinations;
package R05FA02_OpiumDerivativesAndExpec
  extends Icons.PackageDrugs;
end R05FA02_OpiumDerivativesAndExpec;
