within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03E_DiureticsAndPotassiumSparingAgentsInCombination;
package C03EA04_AltizideAndPotassiumSparingAgents
  extends Icons.Package;
end C03EA04_AltizideAndPotassiumSparingAgents;
