within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03X_OtherSexHormonesAndModulatorsOfTheGenitalSystem;
package G03XC02_Bazedoxifene
  extends Icons.PackageDrugs;
end G03XC02_Bazedoxifene;
