within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AJ51_PertussisInactivatedWholeCellCom
  extends Icons.PackageDrugs;
end J07AJ51_PertussisInactivatedWholeCellCom;
