within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H02A_CorticosteroidsForSystemicUsePlain;
package H02AB10_Cortisone
  extends Icons.PackageDrugs;
end H02AB10_Cortisone;
