within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01D_VasodilatorsUsedInCardiacDiseases;
package C01DA54_MethylpropylpropanediolDinitrateCombinations
  extends Icons.Package;
end C01DA54_MethylpropylpropanediolDinitrateCombinations;
