within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A06A_DrugsForConstipation;
package A06AG10_DocusateSodiumInclCombinations
  extends Icons.Package;
end A06AG10_DocusateSodiumInclCombinations;
