within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX01_Edrecolomab
  extends Icons.PackageDrugs;
end L01FX01_Edrecolomab;
