within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A11A_MultivitaminsCombinations;
package A11AA04_MultivitaminsAndTraceElements
  extends Icons.Package;
end A11AA04_MultivitaminsAndTraceElements;
