within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DB07_CandesartanAndAmlodipine
  extends Icons.PackageDrugs;
end C09DB07_CandesartanAndAmlodipine;
