within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G04C_DrugsUsedInBenignProstaticHypertrophy;
package G04CA52_TamsulosinAndDutasteride
  extends Icons.Package;
end G04CA52_TamsulosinAndDutasteride;
