within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AA09_DesogestrelAndEthinylest
  extends Icons.PackageDrugs;
end G03AA09_DesogestrelAndEthinylest;
