within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09X_OtherAgentsActingOnTheReninAngiotensinSystem;
package C09XA54_AliskirenAmlodipineAndHy
  extends Icons.PackageDrugs;
end C09XA54_AliskirenAmlodipineAndHy;
