within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AA12_DrospirenoneAndEthinyles
  extends Icons.PackageDrugs;
end G03AA12_DrospirenoneAndEthinyles;
