within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10A_InsulinsAndAnalogues;
package A10AE54_InsulinGlargineAndLixisenatide
  extends Icons.Package;
end A10AE54_InsulinGlargineAndLixisenatide;
