within Pharmacolibrary.Drugs.D_Dermatologicals.D07B_CorticosteroidsCombinationsWithAntiseptics;
package D07BC01_BetamethasoneAndAntisept
  extends Icons.PackageDrugs;
end D07BC01_BetamethasoneAndAntisept;
