within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis;
package A02BC02_Pantoprazole
  extends Icons.PackageDrugs;
end A02BC02_Pantoprazole;
