within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01E_ProteinKinaseInhibitors.L01EJ01_Ruxolitinib;

model Ruxolitinib
  extends Pharmacolibrary.Drugs.ATC.L.L01EJ01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Ruxolitinib</td></tr><tr><td>ATC code:</td><td>L01EJ01</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Ruxolitinib is a selective Janus kinase (JAK1 and JAK2) inhibitor indicated for the treatment of myelofibrosis, polycythemia vera, and steroid-refractory acute graft-versus-host disease. It is an oral medication approved and used clinically to manage these hematological conditions.</p><h4>Pharmacokinetics</h4><p>Population pharmacokinetic model developed for adult patients with myelofibrosis, based on data from healthy subjects and patients (males and females, adults, age range ~18–80 years).</p><h4>References</h4><ol><li><p>Locatelli, F, et al., &amp; Diaz-de-Heredia, C (2024). Ruxolitinib in treatment-naive or corticosteroid-refractory paediatric patients with chronic graft-versus-host disease (REACH5): interim analysis of a single-arm, multicentre, phase 2 study. <i>The Lancet. Haematology</i> 11(8) e580–e592. DOI:<a href=\"https://doi.org/10.1016/S2352-3026(24)00174-1\">10.1016/S2352-3026(24)00174-1</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39002551/\">https://pubmed.ncbi.nlm.nih.gov/39002551</a></p></li><li><p>Hurwitz, SJ, et al., &amp; Schinazi, RF (2021). Pharmacokinetics of Ruxolitinib in HIV Suppressed Individuals on Antiretroviral Agent Therapy from the ACTG A5336 Study. <i>Journal of clinical pharmacology</i> 61(12) 1555–1566. DOI:<a href=\"https://doi.org/10.1002/jcph.1930\">10.1002/jcph.1930</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34169526/\">https://pubmed.ncbi.nlm.nih.gov/34169526</a></p></li><li><p>Chen, X, et al., &amp; Yeleswaram, S (2013). Population pharmacokinetic analysis of orally-administered ruxolitinib (INCB018424 Phosphate) in patients with primary myelofibrosis (PMF), post-polycythemia vera myelofibrosis (PPV-MF) or post-essential thrombocythemia myelofibrosis (PET MF). <i>Journal of clinical pharmacology</i> 53(7) 721–730. DOI:<a href=\"https://doi.org/10.1002/jcph.102\">10.1002/jcph.102</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/23677817/\">https://pubmed.ncbi.nlm.nih.gov/23677817</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Ruxolitinib;
