within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FF06_Cemiplimab
  extends Icons.PackageDrugs;
end L01FF06_Cemiplimab;
