within Pharmacolibrary.Drugs.C_CardiovascularSystem.C08G_CalciumChannelBlockersAndDiuretics.C08GA01_NifedipineAndDiuretics;

model NifedipineAndDiuretics
  extends Pharmacolibrary.Drugs.ATC.C.C08GA01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>C08GA01</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>This combination consists of nifedipine, a dihydropyridine calcium channel blocker that causes vasodilation and is mainly used for treating hypertension and angina, together with a diuretic (thiazide or thiazide-like), used to lower blood pressure by promoting renal excretion of sodium and water. The combination is approved for the treatment of hypertension and is currently in clinical use.</p><h4>Pharmacokinetics</h4><p>Estimated pharmacokinetic parameters for adults with hypertension treated with oral nifedipine in combination with diuretics, as direct published models or combination PK data with diuretics are unavailable. PK parameters are based on established PK data for nifedipine monotherapy, assuming no substantial PK drug-drug interaction with most thiazide diuretics.</p><h4>References</h4><ol><li><p>Langtry, HD, &amp; Markham, A (1997). Lisinopril. A review of its pharmacology and clinical efficacy in elderly patients. <i>Drugs &amp; aging</i> 10(2) 131–166. DOI:<a href=\"https://doi.org/10.2165/00002512-199710020-00006\">10.2165/00002512-199710020-00006</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/9061270/\">https://pubmed.ncbi.nlm.nih.gov/9061270</a></p></li><li><p>Hong, X, et al., &amp; Xu, X (2007). Genetic polymorphisms of the urea transporter gene are associated with antihypertensive response to nifedipine GITS. <i>Methods and findings in experimental and clinical pharmacology</i> 29(1) 3–10. DOI:<a href=\"https://doi.org/10.1358/mf.2007.29.1.1063490\">10.1358/mf.2007.29.1.1063490</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/17344938/\">https://pubmed.ncbi.nlm.nih.gov/17344938</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end NifedipineAndDiuretics;
