within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01X_OtherAntibacterials.J01XA02_Teicoplanin;

model Teicoplanin
  extends Pharmacolibrary.Drugs.ATC.J.J01XA02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>J01XA02</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Teicoplanin is a glycopeptide antibiotic effective against Gram-positive bacteria, including methicillin-resistant Staphylococcus aureus (MRSA). It is used primarily for serious infections caused by susceptible organisms, including bone and joint infections, endocarditis, and bacteremia, particularly in hospital settings. It is approved and used clinically in many countries.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetics in healthy adult volunteers following intravenous administration of teicoplanin. Two-compartment model.</p><h4>References</h4><ol><li><p>Cazaubon, Y, et al., &amp; Goutelle, S (2017). Population pharmacokinetics of teicoplanin administered by subcutaneous or intravenous route and simulation of optimal loading dose regimen. <i>The Journal of antimicrobial chemotherapy</i> 72(10) 2804–2812. DOI:<a href=\"https://doi.org/10.1093/jac/dkx242\">10.1093/jac/dkx242</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29091222/\">https://pubmed.ncbi.nlm.nih.gov/29091222</a></p></li><li><p>Colaneri, M, et al., &amp; Seminari, E (2024). Optimizing Antibiotic Therapy for Intravenous Drug Users: A Narrative Review Unraveling Pharmacokinetics/Pharmacodynamics Challenges. <i>European journal of drug metabolism and pharmacokinetics</i> 49(2) 123–129. DOI:<a href=\"https://doi.org/10.1007/s13318-024-00882-8\">10.1007/s13318-024-00882-8</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/38332425/\">https://pubmed.ncbi.nlm.nih.gov/38332425</a></p></li><li><p>Alet, P, et al., &amp; Petitjean, O (1999). Pharmacokinetics of teicoplanin during plasma exchange. <i>Clinical microbiology and infection : the official publication of the European Society of Clinical Microbiology and Infectious Diseases</i> 5(4) 213–218. DOI:<a href=\"https://doi.org/10.1111/j.1469-0691.1999.tb00126.x\">10.1111/j.1469-0691.1999.tb00126.x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/11856252/\">https://pubmed.ncbi.nlm.nih.gov/11856252</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Teicoplanin;
