within Pharmacolibrary.Drugs.S_SensoryOrgans.S03C_CorticosteroidsAndAntiinfectivesInCombination;
package S03CA02_PrednisoloneAndAntiinfec
  extends Icons.PackageDrugs;
end S03CA02_PrednisoloneAndAntiinfec;
