within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BA12_PravastatinEzetimibeAndF
  extends Icons.PackageDrugs;
end C10BA12_PravastatinEzetimibeAndF;
