within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AM52_TetanusToxoidCombinationsWithTetanusImmunoglobulin
  extends Icons.Package;
end J07AM52_TetanusToxoidCombinationsWithTetanusImmunoglobulin;
