within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BA01_EncephalitisTickBorneInactivatedWholeVirus
  extends Icons.Package;
end J07BA01_EncephalitisTickBorneInactivatedWholeVirus;
