within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01D_VasodilatorsUsedInCardiacDiseases;
package C01DA54_MethylpropylpropanediolDinitrate
  extends Icons.PackageDrugs;
end C01DA54_MethylpropylpropanediolDinitrate;
