within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A09A_DigestivesInclEnzymes.A09AB04_CitricAcid;

model CitricAcid
  extends Pharmacolibrary.Drugs.ATC.A.A09AB04;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>A09AB04</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Citric acid is a weak organic acid commonly found in citrus fruits. In medicine, it is used as an ingredient in digestive and effervescent preparations, often to promote gastric acidity and assist in the breakdown of kidney stones. Citric acid is also utilized as an excipient and pH adjuster in pharmaceutical formulations. As a single agent, it is rarely used therapeutically, and there is no specific systemic pharmacotherapy approved today exclusively for citric acid.</p><h4>Pharmacokinetics</h4><p>No published pharmacokinetic studies with typical model parameters for citric acid as a single drug in humans were found. The following is an estimate of pharmacokinetic parameters for oral administration based on general knowledge of weak acids and literature about citric acid metabolism and use.</p><h4>References</h4><ol><li><p>Hoy, SM, et al., &amp; Wagstaff, AJ (2009). Sodium picosulfate/magnesium citrate: a review of its use as a colorectal cleanser. <i>Drugs</i> 69(1) 123–136. DOI:<a href=\"https://doi.org/10.2165/00003495-200969010-00009\">10.2165/00003495-200969010-00009</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/19192941/\">https://pubmed.ncbi.nlm.nih.gov/19192941</a></p></li><li><p>Pelfrêne, A, et al., &amp; Le Bot, B (2020). Evaluation of single-extraction methods to estimate the oral bioaccessibility of metal(loid)s in soils. <i>The Science of the total environment</i> 727 138553–None. DOI:<a href=\"https://doi.org/10.1016/j.scitotenv.2020.138553\">10.1016/j.scitotenv.2020.138553</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32334219/\">https://pubmed.ncbi.nlm.nih.gov/32334219</a></p></li><li><p>Argiratos, V, &amp; Samman, S (1994). The effect of calcium carbonate and calcium citrate on the absorption of zinc in healthy female subjects. <i>European journal of clinical nutrition</i> 48(3) 198–204. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/8194505/\">https://pubmed.ncbi.nlm.nih.gov/8194505</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end CitricAcid;
