within Pharmacolibrary.Drugs.R_RespiratorySystem.R05D_CoughSuppressantsExclCombinationsWithExpectorant;
package R05DA20_PholcodineAndCombination
  extends Icons.PackageDrugs;
end R05DA20_PholcodineAndCombination;
