within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD25_MetforminSaxagliptinAndDapaglifl
  extends Icons.PackageDrugs;
end A10BD25_MetforminSaxagliptinAndDapaglifl;
