within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01B_Antimetabolites.L01BC06_Capecitabine;

model Capecitabine
  extends Pharmacolibrary.Drugs.ATC.L.L01BC06;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Capecitabine</td></tr><tr><td>ATC code:</td><td>L01BC06</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Capecitabine is an oral prodrug of 5-fluorouracil (5-FU), used as a chemotherapy agent primarily for the treatment of metastatic breast cancer and colorectal cancer. It is approved and widely used in clinical oncology. The drug is enzymatically converted to 5-FU preferentially in tumor tissues.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetics of capecitabine in adult cancer patients (median age ~56 years, both sexes, solid tumors), following repeated oral administration of 1250 mg/m2 twice daily for 14 days in a 21-day cycle.</p><h4>References</h4><ol><li><p>Jacobs, BAW, et al., &amp; Huitema, ADR (2019). Pharmacokinetics of Capecitabine and Four Metabolites in a Heterogeneous Population of Cancer Patients: A Comprehensive Analysis. <i>CPT: pharmacometrics &amp; systems pharmacology</i> 8(12) 940–950. DOI:<a href=\"https://doi.org/10.1002/psp4.12474\">10.1002/psp4.12474</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31652031/\">https://pubmed.ncbi.nlm.nih.gov/31652031</a></p></li><li><p>Janssen, JM, et al., &amp; Dorlo, TPC (2021). Population Pharmacokinetics of Intracellular 5-Fluorouridine 5&#x27;-Triphosphate and its Relationship with Hand-and-Foot Syndrome in Patients Treated with Capecitabine. <i>The AAPS journal</i> 23(1) 23–None. DOI:<a href=\"https://doi.org/10.1208/s12248-020-00533-1\">10.1208/s12248-020-00533-1</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33417061/\">https://pubmed.ncbi.nlm.nih.gov/33417061</a></p></li><li><p>Li, X, et al., &amp; Zheng, L (2023). Pharmacokinetics and Comparative Bioavailability of Test or Reference Capecitabine and Discrepant Pharmacokinetics Among Various Tumors in Chinese Solid Cancer Patients. <i>Clinical pharmacology in drug development</i> 12(3) 324–332. DOI:<a href=\"https://doi.org/10.1002/cpdd.1202\">10.1002/cpdd.1202</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36642942/\">https://pubmed.ncbi.nlm.nih.gov/36642942</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Capecitabine;
