within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AC05_Dequalinium
  extends Icons.PackageDrugs;
end G01AC05_Dequalinium;
