within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AA05_Tilbroquinol
  extends Icons.Package;
end P01AA05_Tilbroquinol;
