within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01E_SulfonamidesAndTrimethoprim;
package J01EC20_SulfamethoxazoleAndTrimethoprimCombination
  extends Icons.Package;
end J01EC20_SulfamethoxazoleAndTrimethoprimCombination;
