within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01E_OtherCardiacPreparations.C01EB10_Adenosine;

model Adenosine
  extends Pharmacolibrary.Drugs.ATC.C.C01EB10;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Adenosine</td></tr><tr><td>ATC code:</td><td>C01EB10</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Adenosine is an endogenous purine nucleoside approved for the rapid conversion of paroxysmal supraventricular tachycardia (PSVT) to normal sinus rhythm. It acts on adenosine receptors to inhibit conduction through the atrioventricular node and is used primarily in acute cardiac care settings. Adenosine is approved and widely used today as an intravenous antiarrhythmic agent.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic model reported in healthy adult subjects; most data from intravenous administration due to extremely low oral bioavailability.</p><h4>References</h4><ol><li><p>Savic, RM, et al., &amp; Karlsson, MO (2017). Population Pharmacokinetics of Cladribine in Patients with Multiple Sclerosis. <i>Clinical pharmacokinetics</i> 56(10) 1245–1253. DOI:<a href=\"https://doi.org/10.1007/s40262-017-0516-6\">10.1007/s40262-017-0516-6</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/28255849/\">https://pubmed.ncbi.nlm.nih.gov/28255849</a></p></li><li><p>Lindemalm, S, et al., &amp; Albertioni, F (2005). Application of population pharmacokinetics to cladribine. <i>BMC pharmacology</i> 5 4–None. DOI:<a href=\"https://doi.org/10.1186/1471-2210-5-4\">10.1186/1471-2210-5-4</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/15757511/\">https://pubmed.ncbi.nlm.nih.gov/15757511</a></p></li><li><p>Motovska, Z, et al., &amp; Group, DS (2024). Cangrelor versus crushed ticagrelor in patients with acute myocardial infarction and cardiogenic shock: rationale and design of the randomised, double-blind DAPT-SHOCK-AMI trial. <i>EuroIntervention : journal of EuroPCR in collaboration with the Working Group on Interventional Cardiology of the European Society of Cardiology</i> 20(20) e1309–e1318. DOI:<a href=\"https://doi.org/10.4244/EIJ-D-24-00203\">10.4244/EIJ-D-24-00203</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39432252/\">https://pubmed.ncbi.nlm.nih.gov/39432252</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Adenosine;
