within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03C_AntispasmodicsInCombinationWithPsycholeptics;
package A03CA30_EmeproniumAndPsycholeptics
  extends Icons.Package;
end A03CA30_EmeproniumAndPsycholeptics;
