within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A06A_DrugsForConstipation;
package A06AG11_SodiumLaurylSulfoacetateInclCombinations
  extends Icons.Package;
end A06AG11_SodiumLaurylSulfoacetateInclCombinations;
