within Pharmacolibrary.Drugs.C_CardiovascularSystem.C05A_AgentsForTreatmentOfHemorrhoidsAndAnalFissuresForTopicalUse;
package C05AX04_ZincPreparations
  extends Icons.Package;
end C05AX04_ZincPreparations;
