within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AF01_Metronidazole
  extends Icons.PackageDrugs;
end G01AF01_Metronidazole;
