within Pharmacolibrary.Drugs.N_NervousSystem.N06C_PsycholepticsAndPsychoanalepticsInCombination;
package N06CA03_FluoxetineAndPsycholeptics
  extends Icons.Package;
end N06CA03_FluoxetineAndPsycholeptics;
