within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombina;
package S01CA08_MethylprednisoloneAndAnt
  extends Icons.PackageDrugs;
end S01CA08_MethylprednisoloneAndAnt;
