within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AB01_Acetarsol
  extends Icons.Package;
end G01AB01_Acetarsol;
