within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AG01_HaemophilusInfluenzaeBPurifiedAn
  extends Icons.PackageDrugs;
end J07AG01_HaemophilusInfluenzaeBPurifiedAn;
