within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01X_OtherAntibacterials.J01XB01_Colistin;

model Colistin
  extends Pharmacolibrary.Drugs.ATC.J.J01XB01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>J01XB01</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Colistin (polymyxin E) is a polymyxin antibiotic used to treat infections caused by multidrug-resistant Gram-negative bacteria, especially in hospital settings. It is considered a last-resort treatment for serious infections such as pneumonia, bloodstream infections, and urinary tract infections due to resistant Acinetobacter baumannii, Pseudomonas aeruginosa, and Klebsiella pneumoniae. As of today, it is approved for clinical use, particularly for severe infections where other antibiotics are ineffective.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters for intravenous colistin administration (as colistimethate sodium) in adult critically ill patients with normal renal function.</p><h4>References</h4><ol><li><p>Xie, YL, et al., &amp; Peng, Y (2022). Population pharmacokinetics of intravenous colistin sulfate and dosage optimization in critically ill patients. <i>Frontiers in pharmacology</i> 13 967412–None. DOI:<a href=\"https://doi.org/10.3389/fphar.2022.967412\">10.3389/fphar.2022.967412</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36105229/\">https://pubmed.ncbi.nlm.nih.gov/36105229</a></p></li><li><p>Nation, RL, et al., &amp; Silveira, FP (2017). Dosing guidance for intravenous colistin in critically-ill patients. <i>Clinical infectious diseases : an official publication of the Infectious Diseases Society of America</i> 64(5) 565–571. DOI:<a href=\"https://doi.org/10.1093/cid/ciw839\">10.1093/cid/ciw839</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/28011614/\">https://pubmed.ncbi.nlm.nih.gov/28011614</a></p></li><li><p>Ooi, MH, et al., &amp; Nation, RL (2019). Population Pharmacokinetics of Intravenous Colistin in Pediatric Patients: Implications for the Selection of Dosage Regimens. <i>Clinical infectious diseases : an official publication of the Infectious Diseases Society of America</i> 69(11) 1962–1968. DOI:<a href=\"https://doi.org/10.1093/cid/ciz067\">10.1093/cid/ciz067</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30722017/\">https://pubmed.ncbi.nlm.nih.gov/30722017</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Colistin;
