within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BD54_MeaslesCombinationsWithMumpsRube
  extends Icons.PackageDrugs;
end J07BD54_MeaslesCombinationsWithMumpsRube;
