within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01X_OtherAntineoplasticAgents.L01XA04_Satraplatin;

model Satraplatin
  extends Pharmacolibrary.Drugs.ATC.L.L01XA04;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Satraplatin</td></tr><tr><td>ATC code:</td><td>L01XA04</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Satraplatin is an oral platinum-based chemotherapeutic agent that was investigated for the treatment of advanced cancers, particularly prostate cancer. Unlike other platinum drugs such as cisplatin, satraplatin is orally bioavailable. Despite promising early-phase studies, satraplatin is not an approved drug today.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in adult cancer patients (typical age range 37-78 years) receiving oral satraplatin as monotherapy.</p><h4>References</h4><ol><li><p>Sova, P, et al., &amp; Chládek, J (2011). A comparative study of pharmacokinetics, urinary excretion and tissue distribution of platinum in rats following a single-dose oral administration of two platinum(IV) complexes LA-12 (OC-6-43)-bis(acetato)(1-adamantylamine)amminedichloroplatinum(IV) and satraplatin (OC-6-43)-bis(acetato)amminedichloro(cyclohexylamine)platinum(IV). <i>Cancer chemotherapy and pharmacology</i> 67(6) 1247–1256. DOI:<a href=\"https://doi.org/10.1007/s00280-010-1411-0\">10.1007/s00280-010-1411-0</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/20697713/\">https://pubmed.ncbi.nlm.nih.gov/20697713</a></p></li><li><p>Doshi, G, et al., &amp; Sternberg, CN (2012). Clinical and pharmacokinetic evaluation of satraplatin. <i>Expert opinion on drug metabolism &amp; toxicology</i> 8(1) 103–111. DOI:<a href=\"https://doi.org/10.1517/17425255.2012.636352\">10.1517/17425255.2012.636352</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/22098065/\">https://pubmed.ncbi.nlm.nih.gov/22098065</a></p></li><li><p>Galsky, MD, et al., &amp; Bajorin, DF (2011). Retrospective analysis of satraplatin in patients with metastatic urothelial cancer refractory to standard platinum-based chemotherapy. <i>Clinical genitourinary cancer</i> 9(1) 27–30. DOI:<a href=\"https://doi.org/10.1016/j.clgc.2011.05.003\">10.1016/j.clgc.2011.05.003</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/21700509/\">https://pubmed.ncbi.nlm.nih.gov/21700509</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Satraplatin;
