within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins;
package J01CE10_BenzathinePhenoxymethylpenicilli
  extends Icons.Package;
end J01CE10_BenzathinePhenoxymethylpenicilli;
