within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01X_OtherAntineoplasticAgents;
package L01XX40_OmacetaxineMepesuccinate
  extends Icons.Package;
end L01XX40_OmacetaxineMepesuccinate;
