within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FA01_Rituximab
  extends Icons.PackageDrugs;
end L01FA01_Rituximab;
