within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates.L01FA01_Rituximab;

model Rituximab
  extends Pharmacolibrary.Drugs.ATC.L.L01FA01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Rituximab</td></tr><tr><td>ATC code:</td><td>L01FA01</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Rituximab is a chimeric monoclonal antibody directed against the CD20 antigen found on the surface of B lymphocytes. It is primarily used in the treatment of B-cell non-Hodgkin's lymphoma, chronic lymphocytic leukemia, and various autoimmune diseases such as rheumatoid arthritis and granulomatosis with polyangiitis. Rituximab is approved and widely used in clinical practice today.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters in adult patients with B-cell non-Hodgkin's lymphoma following intravenous administration. Parameters derived from a two-compartment model with first-order elimination.</p><h4>References</h4><ol><li><p>Gota, V, et al., &amp; Menon, H (2016). Population pharmacokinetics of Reditux™, a biosimilar Rituximab, in diffuse large B-cell lymphoma. <i>Cancer chemotherapy and pharmacology</i> 78(2) 353–359. DOI:<a href=\"https://doi.org/10.1007/s00280-016-3083-x\">10.1007/s00280-016-3083-x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27329361/\">https://pubmed.ncbi.nlm.nih.gov/27329361</a></p></li><li><p>Gibiansky, E, et al., &amp; Jamois, C (2021). Population pharmacokinetic and exposure-response analyses of intravenous and subcutaneous rituximab in patients with chronic lymphocytic leukemia. <i>CPT: pharmacometrics &amp; systems pharmacology</i> 10(8) 914–927. DOI:<a href=\"https://doi.org/10.1002/psp4.12665\">10.1002/psp4.12665</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34110098/\">https://pubmed.ncbi.nlm.nih.gov/34110098</a></p></li><li><p>Cohen, SB, et al., &amp; Totoritis, MC (2006). Rituximab for rheumatoid arthritis refractory to anti-tumor necrosis factor therapy: Results of a multicenter, randomized, double-blind, placebo-controlled, phase III trial evaluating primary efficacy and safety at twenty-four weeks. <i>Arthritis and rheumatism</i> 54(9) 2793–2806. DOI:<a href=\"https://doi.org/10.1002/art.22025\">10.1002/art.22025</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/16947627/\">https://pubmed.ncbi.nlm.nih.gov/16947627</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Rituximab;
