within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J06B_Immunoglobulins;
package J06BB30_HumanNormalImmunoglobulinCombina
  extends Icons.PackageDrugs;
end J06BB30_HumanNormalImmunoglobulinCombina;
