within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins;
package J01CR01_AmpicillinAndBetaLactamaseInhibitor
  extends Icons.Package;
end J01CR01_AmpicillinAndBetaLactamaseInhibitor;
