within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01C_CardiacStimulantsExclCardiacGlycosides;
package C01CA30_MetildigoxinAndOrganicNitratesCombinations
  extends Icons.Package;
end C01CA30_MetildigoxinAndOrganicNitratesCombinations;
