within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials;
package J01DD63_CeftriaxoneAndBetaLactam
  extends Icons.PackageDrugs;
end J01DD63_CeftriaxoneAndBetaLactam;
