within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins;
package J01CE09_ProcaineBenzylpenicillin
  extends Icons.PackageDrugs;
end J01CE09_ProcaineBenzylpenicillin;
