within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01B_Antimalarials;
package P01BF03_ArtesunateAndAmodiaquine
  extends Icons.Package;
end P01BF03_ArtesunateAndAmodiaquine;
