within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03A_DrugsForFunctionalGastrointestinalDisorders;
package A03AX03_Chlorbenzoxamine
  extends Icons.PackageDrugs;
end A03AX03_Chlorbenzoxamine;
