within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03E_AndrogensAndFemaleSexHormonesInCombination;
package G03EK01_Methyltestosterone
  extends Icons.Package;
end G03EK01_Methyltestosterone;
