within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis;
package A02BX01_Carbenoxolone
  extends Icons.PackageDrugs;
end A02BX01_Carbenoxolone;
