within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02A_AntiadrenergicAgentsCentrallyActing;
package C02AA53_CombinationsOfRauwolfiaAlkoloids
  extends Icons.Package;
end C02AA53_CombinationsOfRauwolfiaAlkoloids;
