within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J04A_DrugsForTreatmentOfTuberculosis.J04AK08_Pretomanid;

model Pretomanid
  extends Pharmacolibrary.Drugs.ATC.J.J04AK08;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Pretomanid</td></tr><tr><td>ATC code:</td><td>J04AK08</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Pretomanid is a nitroimidazooxazine-class antibacterial drug used as part of combination therapy for the treatment of extensively drug-resistant, treatment-intolerant or non-responsive multidrug-resistant pulmonary tuberculosis in adults. It is approved by the US FDA (2019) and EMA as a component of specific multidrug regimens.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in healthy adult volunteers after oral administration, fasted or fed conditions, both sexes.</p><h4>References</h4><ol><li><p>Lyons, MA (2018). Modeling and Simulation of Pretomanid Pharmacokinetics in Pulmonary Tuberculosis Patients. <i>Antimicrobial agents and chemotherapy</i> 62(7) –. DOI:<a href=\"https://doi.org/10.1128/AAC.02359-17\">10.1128/AAC.02359-17</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29661865/\">https://pubmed.ncbi.nlm.nih.gov/29661865</a></p></li><li><p>Zou, Y, et al., &amp; Svensson, EM (2022). Characterizing Absorption Properties of Dispersible Pretomanid Tablets Using Population Pharmacokinetic Modelling. <i>Clinical pharmacokinetics</i> 61(11) 1585–1593. DOI:<a href=\"https://doi.org/10.1007/s40262-022-01163-w\">10.1007/s40262-022-01163-w</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36180816/\">https://pubmed.ncbi.nlm.nih.gov/36180816</a></p></li><li><p>Heinrich, N, et al., &amp; Hoelscher, M (2025). Safety, bactericidal activity, and pharmacokinetics of the antituberculosis drug candidate BTZ-043 in South Africa (PanACEA-BTZ-043-02): an open-label, dose-expansion, randomised, controlled, phase 1b/2a trial. <i>The Lancet. Microbe</i> 6(2) 100952–None. DOI:<a href=\"https://doi.org/10.1016/j.lanmic.2024.07.015\">10.1016/j.lanmic.2024.07.015</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39793592/\">https://pubmed.ncbi.nlm.nih.gov/39793592</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Pretomanid;
