within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DB08_ValsartanAndLercanidipin
  extends Icons.PackageDrugs;
end C09DB08_ValsartanAndLercanidipin;
