within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis;
package A02BD12_RabeprazoleAmoxicillinAn
  extends Icons.PackageDrugs;
end A02BD12_RabeprazoleAmoxicillinAn;
