within Pharmacolibrary.Drugs.D_Dermatologicals.D07C_CorticosteroidsCombinationsWithAntibiotics;
package D07CC04_BeclometasoneAndAntibiot
  extends Icons.PackageDrugs;
end D07CC04_BeclometasoneAndAntibiot;
