within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BC54_RabeprazoleCombinations
  extends Icons.Package;
end A02BC54_RabeprazoleCombinations;
