within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonStero;
package M01AB55_DiclofenacCombinations
  extends Icons.PackageDrugs;
end M01AB55_DiclofenacCombinations;
