within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX25_Mosunetuzumab
  extends Icons.Package;
end L01FX25_Mosunetuzumab;
