within Pharmacolibrary.Drugs.D_Dermatologicals.D07C_CorticosteroidsCombinationsWithAntibiotics;
package D07CB02_FluprednideneAndAntibiot
  extends Icons.PackageDrugs;
end D07CB02_FluprednideneAndAntibiot;
