within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03A_DrugsForFunctionalGastrointestinalDisorders;
package A03AX30_Trimethyldiphenylpropyla
  extends Icons.PackageDrugs;
end A03AX30_Trimethyldiphenylpropyla;
