within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BF02_PoliomyelitisOralTrivalentLiveAttenuated
  extends Icons.Package;
end J07BF02_PoliomyelitisOralTrivalentLiveAttenuated;
