within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates.L01FF01_Nivolumab;

model Nivolumab
  extends Pharmacolibrary.Drugs.ATC.L.L01FF01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>L01FF01</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Nivolumab is a fully human IgG4 monoclonal antibody that inhibits the programmed death-1 (PD-1) immune checkpoint pathway. It is approved for the treatment of various cancers, including metastatic melanoma, non-small cell lung cancer, renal cell carcinoma, and others. Nivolumab enhances anti-tumor immune responses by blocking PD-1 receptor from binding to its ligands, PD-L1 and PD-L2.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters were obtained from studies in adult patients with cancer, both male and female, across different tumor types. Data primarily reflect intravenous administration in clinical trial populations.</p><h4>References</h4><ol><li><p>Albiges, L, et al., &amp; George, S (2025). Subcutaneous versus intravenous nivolumab for renal cell carcinoma. <i>Annals of oncology : official journal of the European Society for Medical Oncology</i> 36(1) 99–107. DOI:<a href=\"https://doi.org/10.1016/j.annonc.2024.09.002\">10.1016/j.annonc.2024.09.002</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39288844/\">https://pubmed.ncbi.nlm.nih.gov/39288844</a></p></li><li><p>Osawa, M, et al., &amp; Hruska, MW (2019). Population pharmacokinetics analysis of nivolumab in Asian and non-Asian patients with gastric and gastro-esophageal junction cancers. <i>Cancer chemotherapy and pharmacology</i> 83(4) 705–715. DOI:<a href=\"https://doi.org/10.1007/s00280-019-03771-z\">10.1007/s00280-019-03771-z</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30666395/\">https://pubmed.ncbi.nlm.nih.gov/30666395</a></p></li><li><p>Wang, W, et al., &amp; Yang, G (2024). Pharmacokinetics, Safety, and Immunogenicity of a Biosimilar of Nivolumab (LY01015): A Randomized, Double-Blind, Parallel-Controlled Phase I Clinical Trial in Healthy Chinese Male Subjects. <i>BioDrugs : clinical immunotherapeutics, biopharmaceuticals and gene therapy</i> 38(6) 855–865. DOI:<a href=\"https://doi.org/10.1007/s40259-024-00679-w\">10.1007/s40259-024-00679-w</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39317850/\">https://pubmed.ncbi.nlm.nih.gov/39317850</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Nivolumab;
