within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FF01_Nivolumab
  extends Icons.PackageDrugs;
end L01FF01_Nivolumab;
