within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A06A_DrugsForConstipation;
package A06AB20_ContactLaxativesInCombination
  extends Icons.Package;
end A06AB20_ContactLaxativesInCombination;
