within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonStero;
package M01AB51_IndometacinCombinations
  extends Icons.PackageDrugs;
end M01AB51_IndometacinCombinations;
