within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01C_AgentsAgainstLeishmaniasisAndTrypanosomiasis;
package P01CB02_SodiumStibogluconate
  extends Icons.Package;
end P01CB02_SodiumStibogluconate;
