within Pharmacolibrary.Drugs.D_Dermatologicals.D07C_CorticosteroidsCombinationsWithAntibiotics;
package D07CC03_FludroxycortideAndAntibi
  extends Icons.PackageDrugs;
end D07CC03_FludroxycortideAndAntibi;
