within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01B_Antimalarials;
package P01BF04_ArtesunateSulfaleneAndPyrimetham
  extends Icons.PackageDrugs;
end P01BF04_ArtesunateSulfaleneAndPyrimetham;
