within Pharmacolibrary.Drugs.N_NervousSystem.N06B_PsychostimulantsAgentsUsedForAdhdAndNootropics.N06BA01_Amfetamine;

model Amfetamine
  extends Pharmacolibrary.Drugs.ATC.N.N06BA01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Amfetamine</td></tr><tr><td>ATC code:</td><td>N06BA01</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Amfetamine (amphetamine) is a central nervous system stimulant used in the treatment of attention deficit hyperactivity disorder (ADHD), narcolepsy, and, historically, obesity. It acts primarily by increasing synaptic concentrations of dopamine and norepinephrine. Amfetamine is approved for medical use in several countries, but has limited indications due to dependence and abuse potential.</p><h4>Pharmacokinetics</h4><p>Healthy adult volunteers, conventional racemic amphetamine, fasted state, single oral dose.</p><h4>References</h4><ol><li><p>De Hondt, L, et al., &amp; Tommelein, E (2024). Quantification of ADHD medication in biological fluids of pregnant and breastfeeding women with liquid chromatography: a comprehensive review. <i>Frontiers in public health</i> 12 1437328–None. DOI:<a href=\"https://doi.org/10.3389/fpubh.2024.1437328\">10.3389/fpubh.2024.1437328</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39171321/\">https://pubmed.ncbi.nlm.nih.gov/39171321</a></p></li><li><p>Pal, D, &amp; Mitra, AK (2006). MDR- and CYP3A4-mediated drug-drug interactions. <i>Journal of neuroimmune pharmacology : the official journal of the Society on NeuroImmune Pharmacology</i> 1(3) 323–339. DOI:<a href=\"https://doi.org/10.1007/s11481-006-9034-2\">10.1007/s11481-006-9034-2</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/18040809/\">https://pubmed.ncbi.nlm.nih.gov/18040809</a></p></li><li><p>Kolbrich, EA, et al., &amp; Huestis, MA (2008). Plasma pharmacokinetics of 3,4-methylenedioxymethamphetamine after controlled oral administration to young adults. <i>Therapeutic drug monitoring</i> 30(3) 320–332. DOI:<a href=\"https://doi.org/10.1097/FTD.0b013e3181684fa0\">10.1097/FTD.0b013e3181684fa0</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/18520604/\">https://pubmed.ncbi.nlm.nih.gov/18520604</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Amfetamine;
