within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BX01_Carbenoxolone
  extends Icons.Package;
end A02BX01_Carbenoxolone;
