within Pharmacolibrary.Drugs.V_Various.V08B_XRayContrastMediaNonIodinated;
package V08BA01_BariumSulfateWithSuspendingAgent
  extends Icons.PackageDrugs;
end V08BA01_BariumSulfateWithSuspendingAgent;
