within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AC01_Diiodohydroxyquinoline
  extends Icons.PackageDrugs;
end G01AC01_Diiodohydroxyquinoline;
