within Pharmacolibrary.Drugs.D_Dermatologicals.D07B_CorticosteroidsCombinationsWithAntiseptics;
package D07BB04_HydrocortisoneButyrateAn
  extends Icons.PackageDrugs;
end D07BB04_HydrocortisoneButyrateAn;
