within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03D_AntispasmodicsInCombinationWithAnalgesics;
package A03DA01_TropenziloneAndAnalgesic
  extends Icons.PackageDrugs;
end A03DA01_TropenziloneAndAnalgesic;
