within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10A_LipidModifyingAgentsPlain.C10AD05_NicotinylAlcoholPyridylcarbinol;
model NicotinylAlcoholPyridylcarbinol = Pharmacolibrary.Drugs.ATC.C.C10AD05;