within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10A_LipidModifyingAgentsPlain;
package C10AD05_NicotinylAlcoholPyridylcarbinol
  extends Icons.Package;
end C10AD05_NicotinylAlcoholPyridylcarbinol;
