within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX21_Naxitamab
  extends Icons.PackageDrugs;
end L01FX21_Naxitamab;
