within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A09A_DigestivesInclEnzymes;
package A09AA02_MultienzymesLipaseProteaseEtc
  extends Icons.Package;
end A09AA02_MultienzymesLipaseProteaseEtc;
