within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01D_VasodilatorsUsedInCardiacDiseases;
package C01DA20_OrganicNitratesInCombination
  extends Icons.Package;
end C01DA20_OrganicNitratesInCombination;
