within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DB05_IrbesartanAndAmlodipine
  extends Icons.PackageDrugs;
end C09DB05_IrbesartanAndAmlodipine;
