within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BC03_Lansoprazole
  extends Icons.Package;
end A02BC03_Lansoprazole;
