within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD02_MetforminAndSulfonylurea
  extends Icons.PackageDrugs;
end A10BD02_MetforminAndSulfonylurea;
