within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M03B_MuscleRelaxantsCentrallyActingAgents;
package M03BB52_ChlormezanoneCombination
  extends Icons.PackageDrugs;
end M03BB52_ChlormezanoneCombination;
