within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX14_RosuvastatinAmlodipineAndPerindo
  extends Icons.Package;
end C10BX14_RosuvastatinAmlodipineAndPerindo;
