within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonStero;
package M01AE53_KetoprofenCombinations
  extends Icons.PackageDrugs;
end M01AE53_KetoprofenCombinations;
