within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AX03_Policresulen
  extends Icons.PackageDrugs;
end G01AX03_Policresulen;
