within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AF14_Propenidazole
  extends Icons.PackageDrugs;
end G01AF14_Propenidazole;
