within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H03B_AntithyroidPreparations;
package H03BA02_Propylthiouracil
  extends Icons.PackageDrugs;
end H03BA02_Propylthiouracil;
