within Pharmacolibrary.Drugs.S_SensoryOrgans.S03C_CorticosteroidsAndAntiinfectivesInCombination;
package S03CA01_DexamethasoneAndAntiinfectives
  extends Icons.Package;
end S03CA01_DexamethasoneAndAntiinfectives;
