within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07C_BetaBlockingAgentsAndOtherDiuretics;
package C07CA03_PindololAndOtherDiuretics
  extends Icons.Package;
end C07CA03_PindololAndOtherDiuretics;
