within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DB08_ValsartanAndLercanidipine
  extends Icons.Package;
end C09DB08_ValsartanAndLercanidipine;
