within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A06A_DrugsForConstipation;
package A06AB58_SodiumPicosulfateCombinations
  extends Icons.Package;
end A06AB58_SodiumPicosulfateCombinations;
