within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02L_AntihypertensivesAndDiureticsInCombination;
package C02LB01_MethyldopaLevorotatoryAn
  extends Icons.PackageDrugs;
end C02LB01_MethyldopaLevorotatoryAn;
