within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AR53_GlycobiarsolCombinations
  extends Icons.PackageDrugs;
end P01AR53_GlycobiarsolCombinations;
