within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01B_Antimalarials;
package P01BF05_ArtenimolAndPiperaquine
  extends Icons.Package;
end P01BF05_ArtenimolAndPiperaquine;
