within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AB01_Metronidazole
  extends Icons.Package;
end P01AB01_Metronidazole;
