within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09B_AceInhibitorsCombinations;
package C09BX01_PerindoprilAmlodipineAndIndapamide
  extends Icons.Package;
end C09BX01_PerindoprilAmlodipineAndIndapamide;
