within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01B_Antimetabolites;
package L01BC52_FluorouracilCombinations
  extends Icons.PackageDrugs;
end L01BC52_FluorouracilCombinations;
