within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX08_AtorvastatinAndAcetylsalicylicAc
  extends Icons.Package;
end C10BX08_AtorvastatinAndAcetylsalicylicAc;
