within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BD17_VonoprazanAndAmoxicillin
  extends Icons.Package;
end A02BD17_VonoprazanAndAmoxicillin;
