within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10A_LipidModifyingAgentsPlain.C10AX15_BempedoicAcid;

model BempedoicAcid
  extends Pharmacolibrary.Drugs.ATC.C.C10AX15;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>BempedoicAcid</td></tr><tr><td>ATC code:</td><td>C10AX15</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Bempedoic acid is an oral adenosine triphosphate-citrate lyase (ACL) inhibitor used to lower LDL cholesterol levels in adults with hypercholesterolemia or established atherosclerotic cardiovascular disease. It is approved for clinical use as an adjunct to diet and maximally tolerated statin therapy.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in healthy adult subjects after oral administration.</p><h4>References</h4><ol><li><p>Jadhav, SB, et al., &amp; Emery, MG (2023). Population pharmacokinetic and pharmacokinetic-pharmacodynamic modeling of bempedoic acid and low-density lipoprotein cholesterol in healthy subjects and patients with dyslipidemia. <i>Journal of pharmacokinetics and pharmacodynamics</i> 50(5) 351–364. DOI:<a href=\"https://doi.org/10.1007/s10928-023-09864-w\">10.1007/s10928-023-09864-w</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37243877/\">https://pubmed.ncbi.nlm.nih.gov/37243877</a></p></li><li><p>Amore, BM, et al., &amp; Emery, MG (2023). Phase 1, Single- and Multiple-Ascending-Dose, Food-Effect, and East Asian Subject Studies to Assess the Pharmacokinetics, Safety, and Tolerability of Bempedoic Acid, a Selective Inhibitor of Adenosine Triphosphate Citrate Lyase. <i>Clinical pharmacology in drug development</i> 12(10) 1022–1035. DOI:<a href=\"https://doi.org/10.1002/cpdd.1297\">10.1002/cpdd.1297</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37477389/\">https://pubmed.ncbi.nlm.nih.gov/37477389</a></p></li><li><p>Stoll, F, et al., &amp; Blank, A (2025). Effect of Staggered vs. Simultaneous Co-Administration of Bempedoic Acid on Pharmacokinetics of Pravastatin: Randomized, Cross-Over Clinical Trial in Healthy Volunteers. <i>Pharmaceutics</i> 17(1) –. DOI:<a href=\"https://doi.org/10.3390/pharmaceutics17010060\">10.3390/pharmaceutics17010060</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39861708/\">https://pubmed.ncbi.nlm.nih.gov/39861708</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end BempedoicAcid;
