within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX14_RosuvastatinAmlodipineAn
  extends Icons.PackageDrugs;
end C10BX14_RosuvastatinAmlodipineAn;
