within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P03B_InsecticidesAndRepellents;
package P03BX02_Dimethylphthalate
  extends Icons.Package;
end P03BX02_Dimethylphthalate;
