within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DB09_FimasartanAndAmlodipine
  extends Icons.PackageDrugs;
end C09DB09_FimasartanAndAmlodipine;
