within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FF09_Tislelizumab
  extends Icons.PackageDrugs;
end L01FF09_Tislelizumab;
