within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03E_DiureticsAndPotassiumSparingAgentsInCombination;
package C03EA05_MebutizideAndPotassiumSp
  extends Icons.PackageDrugs;
end C03EA05_MebutizideAndPotassiumSp;
