within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BE73_PhenacetinCombinationsWithPsycholeptics
  extends Icons.Package;
end N02BE73_PhenacetinCombinationsWithPsycholeptics;
