within Pharmacolibrary.Drugs.C_CardiovascularSystem.C05A_AgentsForTreatmentOfHemorrhoidsAndAnalFissuresForTopicalUse;
package C05AA06_Fluorometholone
  extends Icons.Package;
end C05AA06_Fluorometholone;
