within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03A_DrugsForFunctionalGastrointestinalDisorders;
package A03AB19_TimepidiumBromide
  extends Icons.PackageDrugs;
end A03AB19_TimepidiumBromide;
