within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03D_AntispasmodicsInCombinationWithAnalgesics;
package A03DA03_BevoniumAndAnalgesics
  extends Icons.PackageDrugs;
end A03DA03_BevoniumAndAnalgesics;
