within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M05B_DrugsAffectingBoneStructureAndMineralization;
package M05BB09_IbandronicAcidAndColecalciferol
  extends Icons.Package;
end M05BB09_IbandronicAcidAndColecalciferol;
