within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials;
package J01DC52_CefuroximeAndBetaLactama
  extends Icons.PackageDrugs;
end J01DC52_CefuroximeAndBetaLactama;
