within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombination;
package S01CA11_ClobetasoneAndAntiinfectives
  extends Icons.Package;
end S01CA11_ClobetasoneAndAntiinfectives;
