within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AA13_NorelgestrominAndEthinylestradio
  extends Icons.Package;
end G03AA13_NorelgestrominAndEthinylestradio;
