within Pharmacolibrary.Drugs.R_RespiratorySystem.R03D_OtherSystemicDrugsForObstructiveAirwayDiseases;
package R03DB03_ProxyphyllineAndAdrenergics
  extends Icons.Package;
end R03DB03_ProxyphyllineAndAdrenergics;
