within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombina;
package S01CA03_HydrocortisoneAndAntiinf
  extends Icons.PackageDrugs;
end S01CA03_HydrocortisoneAndAntiinf;
