within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03B_BelladonnaAndDerivativesPlain;
package A03BA04_BelladonnaTotalAlkaloids
  extends Icons.Package;
end A03BA04_BelladonnaTotalAlkaloids;
