within Pharmacolibrary.Drugs.D_Dermatologicals.D08A_AntisepticsAndDisinfectants;
package D08AJ58_BenzethoniumChlorideCombinations
  extends Icons.Package;
end D08AJ58_BenzethoniumChlorideCombinations;
