within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01B_Antimalarials;
package P01BF07_ArtemisininAndPiperaquine
  extends Icons.Package;
end P01BF07_ArtemisininAndPiperaquine;
