within Pharmacolibrary.Drugs.D_Dermatologicals.D07C_CorticosteroidsCombinationsWithAntibiotics;
package D07CA03_PrednisoloneAndAntibiotics
  extends Icons.Package;
end D07CA03_PrednisoloneAndAntibiotics;
