within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD18_MetforminAndGemigliptin
  extends Icons.Package;
end A10BD18_MetforminAndGemigliptin;
