within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03B_BelladonnaAndDerivativesPlain;
package A03BB06_HomatropineMethylbromide
  extends Icons.Package;
end A03BB06_HomatropineMethylbromide;
