within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BB73_AminophenazoneCombinationsWithPs
  extends Icons.Package;
end N02BB73_AminophenazoneCombinationsWithPs;
