within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AE10_SulfamethizoleAndTrimethoprimCom
  extends Icons.Package;
end G01AE10_SulfamethizoleAndTrimethoprimCom;
