within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09X_OtherAgentsActingOnTheReninAngiotensinSystem;
package C09XA53_AliskirenAndAmlodipine
  extends Icons.Package;
end C09XA53_AliskirenAndAmlodipine;
