within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AM52_TetanusToxoidCombinationsWithTet
  extends Icons.Package;
end J07AM52_TetanusToxoidCombinationsWithTet;
