within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01F_MacrolidesLincosamidesAndStreptogramins;
package J01FG02_QuinupristinDalfopristin
  extends Icons.PackageDrugs;
end J01FG02_QuinupristinDalfopristin;
