within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA11_DiphtheriaHaemophilusInf
  extends Icons.PackageDrugs;
end J07CA11_DiphtheriaHaemophilusInf;
