within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01E_ProteinKinaseInhibitors.L01ED04_Brigatinib;

model Brigatinib
  extends Pharmacolibrary.Drugs.ATC.L.L01ED04;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>L01ED04</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Brigatinib is a tyrosine kinase inhibitor indicated for the treatment of adult patients with anaplastic lymphoma kinase (ALK)-positive metastatic non-small cell lung cancer (NSCLC). It is approved for use in patients whose disease has progressed on or who are intolerant to crizotinib.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters were reported in adult patients with advanced malignancies including ALK-positive NSCLC, mostly aged 18-84 years, under steady-state following repeated dosing.</p><h4>References</h4><ol><li><p>Gupta, N, et al., &amp; Venkatakrishnan, K (2021). Population Pharmacokinetics of Brigatinib in Healthy Volunteers and Patients With Cancer. <i>Clinical pharmacokinetics</i> 60(2) 235–247. DOI:<a href=\"https://doi.org/10.1007/s40262-020-00929-4\">10.1007/s40262-020-00929-4</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32816246/\">https://pubmed.ncbi.nlm.nih.gov/32816246</a></p></li><li><p>Tugnait, M, et al., &amp; Narasimhan, N (2019). The Effect of a High-Fat Meal on the Pharmacokinetics of Brigatinib, an Oral Anaplastic Lymphoma Kinase Inhibitor, in Healthy Volunteers. <i>Clinical pharmacology in drug development</i> 8(6) 734–741. DOI:<a href=\"https://doi.org/10.1002/cpdd.641\">10.1002/cpdd.641</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30570839/\">https://pubmed.ncbi.nlm.nih.gov/30570839</a></p></li><li><p>Gupta, N, et al., &amp; Sinha, V (2023). Clinical Pharmacology of Brigatinib: A Next-Generation Anaplastic Lymphoma Kinase Inhibitor. <i>Clinical pharmacokinetics</i> 62(8) 1063–1079. DOI:<a href=\"https://doi.org/10.1007/s40262-023-01284-w\">10.1007/s40262-023-01284-w</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37493887/\">https://pubmed.ncbi.nlm.nih.gov/37493887</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Brigatinib;
