within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AA12_DrospirenoneAndEthinylestradiol
  extends Icons.Package;
end G03AA12_DrospirenoneAndEthinylestradiol;
