within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J04A_DrugsForTreatmentOfTuberculosis;
package J04AM05_RifampicinPyrazinamideAndIsoniaz
  extends Icons.Package;
end J04AM05_RifampicinPyrazinamideAndIsoniaz;
