within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX09_Mogamulizumab
  extends Icons.Package;
end L01FX09_Mogamulizumab;
