within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AR12_LamivudineAndTenofovirDisoproxil
  extends Icons.Package;
end J05AR12_LamivudineAndTenofovirDisoproxil;
