within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P03A_EctoparasiticidesInclScabicides;
package P03AX01_BenzylBenzoate
  extends Icons.Package;
end P03AX01_BenzylBenzoate;
