within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A06A_DrugsForConstipation;
package A06AB30_ContactLaxativesInCombinationWit
  extends Icons.Package;
end A06AB30_ContactLaxativesInCombinationWit;
