within Pharmacolibrary.Drugs.R_RespiratorySystem.R05F_CoughSuppressantsAndExpectorantsCombinations;
package R05FB02_BromhexineCoughSuppressantsAndEx
  extends Icons.Package;
end R05FB02_BromhexineCoughSuppressantsAndEx;
