within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01C_AgentsAgainstLeishmaniasisAndTrypanosomiasis;
package P01CX03_Eflornithine
  extends Icons.Package;
end P01CX03_Eflornithine;
