within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AB07_Secnidazole
  extends Icons.PackageDrugs;
end P01AB07_Secnidazole;
