within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H01B_PosteriorPituitaryLobeHormones;
package H01BB01_Demoxytocin
  extends Icons.PackageDrugs;
end H01BB01_Demoxytocin;
