within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03G_GonadotropinsAndOtherOvulationStimulants;
package G03GA08_ChoriogonadotropinAlfa
  extends Icons.PackageDrugs;
end G03GA08_ChoriogonadotropinAlfa;
