within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AD01_LacticAcid
  extends Icons.PackageDrugs;
end G01AD01_LacticAcid;
