within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B05A_BloodAndRelatedProducts;
package B05AX04_StemCellsFromUmbilicalCordBlood
  extends Icons.Package;
end B05AX04_StemCellsFromUmbilicalCordBlood;
