within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A16A_OtherAlimentaryTractAndMetabolismProducts.A16AB23_CipaglucosidaseAlfa;
model CipaglucosidaseAlfa = Pharmacolibrary.Drugs.ATC.A.A16AB23;