within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A16A_OtherAlimentaryTractAndMetabolismProducts;
package A16AB23_CipaglucosidaseAlfa
  extends Icons.PackageDrugs;
end A16AB23_CipaglucosidaseAlfa;
