within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A16A_OtherAlimentaryTractAndMetabolismProducts;
package A16AB23_CipaglucosidaseAlfa
  extends Icons.Package;
end A16AB23_CipaglucosidaseAlfa;
