within Pharmacolibrary.Drugs.R_RespiratorySystem.R03D_OtherSystemicDrugsForObstructiveAirwayDiseases;
package R03DA54_TheophyllineCombinationsExclPsyc
  extends Icons.PackageDrugs;
end R03DA54_TheophyllineCombinationsExclPsyc;
