within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD06_GlimepirideAndPioglitazone
  extends Icons.Package;
end A10BD06_GlimepirideAndPioglitazone;
