within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03C_AntispasmodicsInCombinationWithPsycholeptics;
package A03CA01_IsopropamideAndPsycholeptics
  extends Icons.Package;
end A03CA01_IsopropamideAndPsycholeptics;
