within Pharmacolibrary.Drugs.R_RespiratorySystem.R06A_AntihistaminesForSystemicUse.R06AE07_Cetirizine;

model Cetirizine
  extends Pharmacolibrary.Drugs.ATC.R.R06AE07;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>R06AE07</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Cetirizine is a second-generation antihistamine used primarily for the treatment of allergic rhinitis and chronic urticaria. It is a selective antagonist of the peripheral H1 receptor and is approved for use globally.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported for healthy adult volunteers after a single oral 10 mg dose in fasting conditions.</p><h4>References</h4><ol><li><p>Paine, SW, et al., &amp; Hincks, PR (2022). Plasma and urine pharmacokinetics of hydroxyzine and cetirizine following repeated oral administrations to exercised horses. <i>Journal of veterinary pharmacology and therapeutics</i> 45(1) 46–53. DOI:<a href=\"https://doi.org/10.1111/jvp.13010\">10.1111/jvp.13010</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34469007/\">https://pubmed.ncbi.nlm.nih.gov/34469007</a></p></li><li><p>Knych, HK, et al., &amp; McKemie, DS (2019). Pharmacokinetics of hydroxyzine and cetirizine following oral administration of hydroxyzine to exercised Thoroughbred horses. <i>Journal of veterinary pharmacology and therapeutics</i> 42(6) 617–623. DOI:<a href=\"https://doi.org/10.1111/jvp.12808\">10.1111/jvp.12808</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31490561/\">https://pubmed.ncbi.nlm.nih.gov/31490561</a></p></li><li><p>Hussein, Z, et al., &amp; Stockis, A (2005). Retrospective population pharmacokinetics of levocetirizine in atopic children receiving cetirizine: the ETAC study. <i>British journal of clinical pharmacology</i> 59(1) 28–37. DOI:<a href=\"https://doi.org/10.1111/j.1365-2125.2005.02242.x\">10.1111/j.1365-2125.2005.02242.x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/15606437/\">https://pubmed.ncbi.nlm.nih.gov/15606437</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Cetirizine;
