within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03A_LowCeilingDiureticsThiazides;
package C03AB02_HydroflumethiazideAndPotassium
  extends Icons.Package;
end C03AB02_HydroflumethiazideAndPotassium;
