within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombination;
package S01CA05_BetamethasoneAndAntiinfectives
  extends Icons.Package;
end S01CA05_BetamethasoneAndAntiinfectives;
