within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07A_BetaBlockingAgents.C07AA07_Sotalol;

model Sotalol
  extends Pharmacolibrary.Drugs.ATC.C.C07AA07;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>C07AA07</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Sotalol is a non-selective beta-adrenergic blocker with class III antiarrhythmic properties, used for the treatment of ventricular and supraventricular arrhythmias, including atrial fibrillation and ventricular tachycardia. It is approved and widely used today for rhythm control in various arrhythmias.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters for healthy adult subjects, following oral administration.</p><h4>References</h4><ol><li><p>Yellepeddi, VK, et al., &amp; Watt, K (2025). Population Pharmacokinetics and Pharmacodynamics of Sotalol Following Expedited Intravenous Loading in Patients With Atrial Arrhythmias. <i>CPT: pharmacometrics &amp; systems pharmacology</i> 14(4) 658–667. DOI:<a href=\"https://doi.org/10.1002/psp4.13302\">10.1002/psp4.13302</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39749676/\">https://pubmed.ncbi.nlm.nih.gov/39749676</a></p></li><li><p>Saul, JP, et al., &amp; Hinderling, PH (2001). Pharmacokinetics and pharmacodynamics of sotalol in a pediatric population with supraventricular and ventricular tachyarrhythmia. <i>Clinical pharmacology and therapeutics</i> 69(3) 145–157. DOI:<a href=\"https://doi.org/10.1067/mcp.2001.113795\">10.1067/mcp.2001.113795</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/11240979/\">https://pubmed.ncbi.nlm.nih.gov/11240979</a></p></li><li><p>Saul, JP, et al., &amp; Hinderling, PH (2001). Single-dose pharmacokinetics of sotalol in a pediatric population with supraventricular and/or ventricular tachyarrhythmia. <i>Journal of clinical pharmacology</i> 41(1) 35–43. DOI:<a href=\"https://doi.org/10.1177/00912700122009818\">10.1177/00912700122009818</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/11144992/\">https://pubmed.ncbi.nlm.nih.gov/11144992</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Sotalol;
