within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BD06_EsomeprazoleAmoxicillinAndClarit
  extends Icons.Package;
end A02BD06_EsomeprazoleAmoxicillinAndClarit;
