within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BA04_SimvastatinAndFenofibrat
  extends Icons.PackageDrugs;
end C10BA04_SimvastatinAndFenofibrat;
