within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids.G01AD02_AceticAcid;

model AceticAcid
  extends Pharmacolibrary.Drugs.ATC.G.G01AD02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>AceticAcid</td></tr><tr><td>ATC code:</td><td>G01AD02</td></tr><td>route:</td><td>intravaginal</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Acetic acid is a simple carboxylic acid with antimicrobial and antifungal properties. It has been primarily used topically or as an irrigant in gynecology, particularly as a vaginal solution for the treatment of infections such as bacterial vaginosis and for cervicovaginal cleaning. It is not an approved systemic drug, but topical or local use is recognized. Today, commercial use is uncommon and has largely been replaced by other drugs in most medical settings.</p><h4>Pharmacokinetics</h4><p>Estimated PK parameters for local (intravaginal) administration, as no published human PK studies exist for systemic absorption. Parameters are estimated based on physicochemical properties and route of administration.</p><h4>References</h4><ol><li><p>Ugaonkar, SR, et al., &amp; Zydowsky, TM (2015). A novel intravaginal ring to prevent HIV-1, HSV-2, HPV, and unintended pregnancy. <i>Journal of controlled release : official journal of the Controlled Release Society</i> 213 57–68. DOI:<a href=\"https://doi.org/10.1016/j.jconrel.2015.06.018\">10.1016/j.jconrel.2015.06.018</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/26091920/\">https://pubmed.ncbi.nlm.nih.gov/26091920</a></p></li><li><p>Friedland, BA, et al., &amp; Creasy, GW (2016). First-in-Human Trial of MIV-150 and Zinc Acetate Coformulated in a Carrageenan Gel: Safety, Pharmacokinetics, Acceptability, Adherence, and Pharmacodynamics. <i>Journal of acquired immune deficiency syndromes (1999)</i> 73(5) 489–496. DOI:<a href=\"https://doi.org/10.1097/QAI.0000000000001136\">10.1097/QAI.0000000000001136</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27437826/\">https://pubmed.ncbi.nlm.nih.gov/27437826</a></p></li><li><p>Kenney, J, et al., &amp; Robbiani, M (2012). A single dose of a MIV-150/Zinc acetate gel provides 24 h of protection against vaginal simian human immunodeficiency virus reverse transcriptase infection, with more limited protection rectally 8-24 h after gel use. <i>AIDS research and human retroviruses</i> 28(11) 1476–1484. DOI:<a href=\"https://doi.org/10.1089/aid.2012.0087\">10.1089/aid.2012.0087</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/22737981/\">https://pubmed.ncbi.nlm.nih.gov/22737981</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end AceticAcid;
