within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AD02_AceticAcid
  extends Icons.Package;
end G01AD02_AceticAcid;
