within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination.G03FB09_LevonorgestrelAndEstroge;

model LevonorgestrelAndEstroge
  extends Pharmacolibrary.Drugs.ATC.G.G03FB09;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>LevonorgestrelAndEstrogen</td></tr><tr><td>ATC code:</td><td>G03FB09</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Levonorgestrel and estrogen are used in combination as oral contraceptives for the prevention of pregnancy. The combination is widely used and approved for contraceptive purposes in many countries. Levonorgestrel is a synthetic progestogen, while estrogen (usually ethinylestradiol) is a synthetic estrogen component.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters are estimated for a typical healthy adult non-pregnant female, population for oral combined hormonal contraceptive use. No direct reference describing full compartmental PK parameters for the specific combination with ATC code G03FB09 was found.</p><h4>References</h4><ol><li><p>Adedoyin, A, et al., &amp; Iwamoto, M (2019). Effect of letermovir on levonorgestrel and ethinyl estradiol pharmacokinetics . <i>International journal of clinical pharmacology and therapeutics</i> 57(9) 450–457. DOI:<a href=\"https://doi.org/10.5414/CP203483\">10.5414/CP203483</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31232280/\">https://pubmed.ncbi.nlm.nih.gov/31232280</a></p></li><li><p>Kanarkowski, R, et al., &amp; Jusko, WJ (1988). Pharmacokinetics of single and multiple doses of ethinyl estradiol and levonorgestrel in relation to smoking. <i>Clinical pharmacology and therapeutics</i> 43(1) 23–31. DOI:<a href=\"https://doi.org/10.1038/clpt.1988.7\">10.1038/clpt.1988.7</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/3121231/\">https://pubmed.ncbi.nlm.nih.gov/3121231</a></p></li><li><p>Kuhnz, W (1990). Pharmacokinetics of the contraceptive steroids levonorgestrel and gestodene after single and multiple oral administration to women. <i>American journal of obstetrics and gynecology</i> 163(6 Pt 2) 2120–2127. DOI:<a href=\"https://doi.org/10.1016/0002-9378(90)90551-h\">10.1016/0002-9378(90)90551-h</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/2124087/\">https://pubmed.ncbi.nlm.nih.gov/2124087</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end LevonorgestrelAndEstroge;
