within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals.J05AE08_Atazanavir;

model Atazanavir
  extends Pharmacolibrary.Drugs.ATC.J.J05AE08;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>J05AE08</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Atazanavir is an antiretroviral medication used in combination with other medications to treat and prevent HIV/AIDS. It is a protease inhibitor and is commonly administered orally. Atazanavir is approved by regulatory authorities such as the FDA and continues to be used clinically today.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in healthy adult volunteers at steady-state after oral administration of atazanavir 400 mg once daily, fasted state.</p><h4>References</h4><ol><li><p>Solas, C, et al., &amp; Simon, N (2008). Population pharmacokinetics of atazanavir in human immunodeficiency virus-infected patients. <i>Therapeutic drug monitoring</i> 30(6) 670–673. DOI:<a href=\"https://doi.org/10.1097/FTD.0b013e3181897bff\">10.1097/FTD.0b013e3181897bff</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/18806695/\">https://pubmed.ncbi.nlm.nih.gov/18806695</a></p></li><li><p>Dickinson, L, et al., &amp; Aarons, L (2009). Population pharmacokinetics of ritonavir-boosted atazanavir in HIV-infected patients and healthy volunteers. <i>The Journal of antimicrobial chemotherapy</i> 63(6) 1233–1243. DOI:<a href=\"https://doi.org/10.1093/jac/dkp102\">10.1093/jac/dkp102</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/19329800/\">https://pubmed.ncbi.nlm.nih.gov/19329800</a></p></li><li><p>Singkham, N, et al., &amp; Punyawudho, B (2022). Pharmacogenetics-based population pharmacokinetic analysis for dose optimization of ritonavir-boosted atazanavir in Thai adult HIV-infected patients. <i>Expert review of clinical pharmacology</i> 15(1) 99–108. DOI:<a href=\"https://doi.org/10.1080/17512433.2022.2000858\">10.1080/17512433.2022.2000858</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34727835/\">https://pubmed.ncbi.nlm.nih.gov/34727835</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Atazanavir;
