within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AR01_Arsthinol
  extends Icons.Package;
end P01AR01_Arsthinol;
