within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AR01_Arsthinol
  extends Icons.PackageDrugs;
end P01AR01_Arsthinol;
