within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09A_AceInhibitorsPlain.C09AA07_Benazepril;

model Benazepril
  extends Pharmacolibrary.Drugs.ATC.C.C09AA07;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Benazepril</td></tr><tr><td>ATC code:</td><td>C09AA07</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Benazepril is an angiotensin-converting enzyme (ACE) inhibitor used primarily for the treatment of hypertension and congestive heart failure. It is approved and widely used in clinical practice today, both alone and in combination with other antihypertensive agents.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic data reported after single oral dose administration of benazepril in healthy adult volunteers.</p><h4>References</h4><ol><li><p>Gengo, FM, &amp; Brady, E (1991). The pharmacokinetics of benazepril relative to other ACE inhibitors. <i>Clinical cardiology</i> 14(8 Suppl 4) IV44–IV55. DOI:<a href=\"https://doi.org/10.1002/clc.4960141807\">10.1002/clc.4960141807</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/1893642/\">https://pubmed.ncbi.nlm.nih.gov/1893642</a></p></li><li><p>Ding, PY, et al., &amp; Liao, W (2000). Does Chinese ethnicity affect the pharmacokinetics and pharmacodynamics of angiotensin-converting enzyme inhibitors?. <i>Journal of human hypertension</i> 14(3) 163–170. DOI:<a href=\"https://doi.org/10.1038/sj.jhh.1000856\">10.1038/sj.jhh.1000856</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/10694829/\">https://pubmed.ncbi.nlm.nih.gov/10694829</a></p></li><li><p>Kaiser, G, et al., &amp; Holmes, IB (1990). The influence of hepatic cirrhosis on the pharmacokinetics of benazepril hydrochloride. <i>Biopharmaceutics &amp; drug disposition</i> 11(9) 753–764. DOI:<a href=\"https://doi.org/10.1002/bdd.2510110903\">10.1002/bdd.2510110903</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/2271751/\">https://pubmed.ncbi.nlm.nih.gov/2271751</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Benazepril;
