within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03A_LowCeilingDiureticsThiazides;
package C03AB01_BendroflumethiazideAndPotassium
  extends Icons.Package;
end C03AB01_BendroflumethiazideAndPotassium;
