within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BX08_Sulglicotide
  extends Icons.Package;
end A02BX08_Sulglicotide;
