within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BA02_EncephalitisJapaneseInactivatedW
  extends Icons.PackageDrugs;
end J07BA02_EncephalitisJapaneseInactivatedW;
