within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins;
package J01CR01_AmpicillinAndBetaLactamaseInhibi
  extends Icons.PackageDrugs;
end J01CR01_AmpicillinAndBetaLactamaseInhibi;
