within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M05B_DrugsAffectingBoneStructureAndMineralization;
package M05BB02_RisedronicAcidAndCalciumSequential
  extends Icons.Package;
end M05BB02_RisedronicAcidAndCalciumSequential;
