within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AR03_Glycobiarsol
  extends Icons.PackageDrugs;
end P01AR03_Glycobiarsol;
