within Pharmacolibrary.Drugs.C_CardiovascularSystem.C05A_AgentsForTreatmentOfHemorrhoidsAndAnalFissuresFo;
package C05AX04_ZincPreparations
  extends Icons.PackageDrugs;
end C05AX04_ZincPreparations;
