within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BD53_MeaslesCombinationsWithRubellaLi
  extends Icons.Package;
end J07BD53_MeaslesCombinationsWithRubellaLi;
