within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombina;
package S01CC02_IndometacinAndAntiinfect
  extends Icons.PackageDrugs;
end S01CC02_IndometacinAndAntiinfect;
