within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AR06_EmtricitabineTenofovirDisoproxil
  extends Icons.Package;
end J05AR06_EmtricitabineTenofovirDisoproxil;
