within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03C_AntispasmodicsInCombinationWithPsycholeptics;
package A03CA09_PipenzolateAndPsycholeptics
  extends Icons.Package;
end A03CA09_PipenzolateAndPsycholeptics;
