within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B02B_VitaminKAndOtherHemostatics;
package B02BC03_TetragalacturonicAcidHyd
  extends Icons.PackageDrugs;
end B02BC03_TetragalacturonicAcidHyd;
