within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonSteroids;
package M01AE57_NaproxenAndDiphenhydramine
  extends Icons.Package;
end M01AE57_NaproxenAndDiphenhydramine;
