within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B05X_IVSolutionAdditives;
package B05XA06_PotassiumPhosphateInclCombinatio
  extends Icons.Package;
end B05XA06_PotassiumPhosphateInclCombinatio;
