within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07C_BetaBlockingAgentsAndOtherDiuretics;
package C07CB53_AtenololAndOtherDiureticsCombina
  extends Icons.Package;
end C07CB53_AtenololAndOtherDiureticsCombina;
