within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AB03_Ornidazole
  extends Icons.PackageDrugs;
end P01AB03_Ornidazole;
