within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BA79_DipyrocetylCombinationsWithPsych
  extends Icons.Package;
end N02BA79_DipyrocetylCombinationsWithPsych;
