within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01D_VasodilatorsUsedInCardiacDiseases;
package C01DA57_PropatylnitrateCombinations
  extends Icons.Package;
end C01DA57_PropatylnitrateCombinations;
