within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations.C09DB06_LosartanAndAmlodipine;
model LosartanAndAmlodipine = Pharmacolibrary.Drugs.ATC.C.C09DB06;