within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DB06_LosartanAndAmlodipine
  extends Icons.PackageDrugs;
end C09DB06_LosartanAndAmlodipine;
