within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FC01_Daratumumab
  extends Icons.PackageDrugs;
end L01FC01_Daratumumab;
