within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02A_AntiadrenergicAgentsCentrallyActing;
package C02AA03_CombinationsOfRauwolfiaA
  extends Icons.PackageDrugs;
end C02AA03_CombinationsOfRauwolfiaA;
