within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials.J01DH55_PanipenemAndBetamipron;

model PanipenemAndBetamipron
  extends Pharmacolibrary.Drugs.ATC.J.J01DH55;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>PanipenemAndBetamipron</td></tr><tr><td>ATC code:</td><td>J01DH55</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Panipenem and betamipron is a combination of a carbapenem antibiotic (panipenem) and a renal dehydropeptidase inhibitor (betamipron). The combination is used to treat a variety of bacterial infections, especially those caused by resistant Gram-negative organisms. Betamipron reduces nephrotoxicity by inhibiting the renal uptake of panipenem. This combination is not approved in the US or EU but is used in some countries, notably Japan.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetics reported in healthy adult Japanese volunteers after intravenous administration.</p><h4>References</h4><ol><li><p>Tajima, N, et al., &amp; Naganuma, H (2005). Quantitative evaluation of effect of renal failure on the pharmacokinetics of panipenem in rats. <i>Biological &amp; pharmaceutical bulletin</i> 28(11) 2170–2172. DOI:<a href=\"https://doi.org/10.1248/bpb.28.2170\">10.1248/bpb.28.2170</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/16272714/\">https://pubmed.ncbi.nlm.nih.gov/16272714</a></p></li><li><p>Kimura, T, et al., &amp; Sunakawa, K (2000). [Pharmacokinetics of panipenem in neonates and dosage recommendation]. <i>The Japanese journal of antibiotics</i> 53(4) 185–193. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/10868298/\">https://pubmed.ncbi.nlm.nih.gov/10868298</a></p></li><li><p>Mikamo, H, et al., &amp; Yamada, Y (1999). [Study on the therapeutic effect of panipenem/betamipron on perinatal infection in pregnant women]. <i>The Japanese journal of antibiotics</i> 52(1) 24–33. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/10202685/\">https://pubmed.ncbi.nlm.nih.gov/10202685</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end PanipenemAndBetamipron;
