within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01B_Antimetabolites.L01BB02_Mercaptopurine;

model Mercaptopurine
  extends Pharmacolibrary.Drugs.ATC.L.L01BB02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Mercaptopurine</td></tr><tr><td>ATC code:</td><td>L01BB02</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Mercaptopurine is an antimetabolite and purine analog used primarily in the treatment of acute lymphoblastic leukemia and other hematologic malignancies. It works by inhibiting DNA and RNA synthesis in rapidly dividing cells. Mercaptopurine is still approved and commonly used as part of chemotherapy regimens.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters in adult patients with acute lymphoblastic leukemia under oral administration.</p><h4>References</h4><ol><li><p>Balis, FM, et al., &amp; Bleyer, WA (1998). Pharmacokinetics and pharmacodynamics of oral methotrexate and mercaptopurine in children with lower risk acute lymphoblastic leukemia: a joint children&#x27;s cancer group and pediatric oncology branch study. <i>Blood</i> 92(10) 3569–3577. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/9808549/\">https://pubmed.ncbi.nlm.nih.gov/9808549</a></p></li><li><p>Saiz-Rodríguez, M, et al., &amp; Abad-Santos, F (2019). Influence of thiopurine S-methyltransferase polymorphisms in mercaptopurine pharmacokinetics in healthy volunteers. <i>Basic &amp; clinical pharmacology &amp; toxicology</i> 124(4) 449–455. DOI:<a href=\"https://doi.org/10.1111/bcpt.13153\">10.1111/bcpt.13153</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30346660/\">https://pubmed.ncbi.nlm.nih.gov/30346660</a></p></li><li><p>Rosenbaum, SE, et al., &amp; Akhlaghi, F (2005). Population pharmacokinetics of cyclosporine in cardiopulmonary transplant recipients. <i>Therapeutic drug monitoring</i> 27(2) 116–122. DOI:<a href=\"https://doi.org/10.1097/01.ftd.0000148448.51225.2c\">10.1097/01.ftd.0000148448.51225.2c</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/15795639/\">https://pubmed.ncbi.nlm.nih.gov/15795639</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Mercaptopurine;
