within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H01B_PosteriorPituitaryLobeHormones;
package H01BA04_Terlipressin
  extends Icons.PackageDrugs;
end H01BA04_Terlipressin;
