within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03F_Propulsives.A03FA03_Domperidone;

model Domperidone
  extends Pharmacolibrary.Drugs.ATC.A.A03FA03;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>A03FA03</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Domperidone is a peripherally selective dopamine D2 receptor antagonist used as a prokinetic and antiemetic agent. It is primarily indicated for the treatment of nausea and vomiting, gastroparesis, and symptoms associated with chronic dyspepsia. Domperidone is not approved in the United States, but is available in several other countries, often with restrictions due to concerns about cardiac side effects.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in healthy adult subjects after a single oral dose.</p><h4>References</h4><ol><li><p>Dailly, E, et al., &amp; Jolliet, P (2008). Population pharmacokinetics of domperidone in preterm neonates. <i>European journal of clinical pharmacology</i> 64(12) 1197–1200. DOI:<a href=\"https://doi.org/10.1007/s00228-008-0535-1\">10.1007/s00228-008-0535-1</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/18685840/\">https://pubmed.ncbi.nlm.nih.gov/18685840</a></p></li><li><p>Wang, C, et al., &amp; Chen, X (2020). Development of a sensitive UPLC-MS/MS assay for domperidone and pharmacokinetics of domperidone tablet formulations in fasting and fed Chinese healthy subjects . <i>International journal of clinical pharmacology and therapeutics</i> 58(3) 177–182. DOI:<a href=\"https://doi.org/10.5414/CP203529\">10.5414/CP203529</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31933472/\">https://pubmed.ncbi.nlm.nih.gov/31933472</a></p></li><li><p>Caraballo, L, et al., &amp; Marzi, M (2014). [Proarrhythmic effects of domperidone in infants: a systematic review]. <i>Farmacia hospitalaria : organo oficial de expresion cientifica de la Sociedad Espanola de Farmacia Hospitalaria</i> 38(5) 438–444. DOI:<a href=\"https://doi.org/10.7399/fh.2014.38.5.7957\">10.7399/fh.2014.38.5.7957</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25344138/\">https://pubmed.ncbi.nlm.nih.gov/25344138</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Domperidone;
