within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AC05_Dequalinium
  extends Icons.Package;
end G01AC05_Dequalinium;
