within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AX21_PentanedioicAcidImidazolylEthana
  extends Icons.Package;
end J05AX21_PentanedioicAcidImidazolylEthana;
