within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AB08_DienogestAndEstradiol
  extends Icons.PackageDrugs;
end G03AB08_DienogestAndEstradiol;
