within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD19_LinagliptinAndEmpagliflo
  extends Icons.PackageDrugs;
end A10BD19_LinagliptinAndEmpagliflo;
