within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01D_VasodilatorsUsedInCardiacDiseases;
package C01DA55_PentaerithritylTetranitr
  extends Icons.PackageDrugs;
end C01DA55_PentaerithritylTetranitr;
