within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX23_TisotumabVedotin
  extends Icons.PackageDrugs;
end L01FX23_TisotumabVedotin;
