within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination;
package G03FA10_NorgestrelAndEstrogen
  extends Icons.PackageDrugs;
end G03FA10_NorgestrelAndEstrogen;
