within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03C_AntispasmodicsInCombinationWithPsycholeptics;
package A03CB31_HyoscyamineAndPsycholeptics
  extends Icons.Package;
end A03CB31_HyoscyamineAndPsycholeptics;
