within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BD02_LansoprazoleTetracyclineAndMetro
  extends Icons.Package;
end A02BD02_LansoprazoleTetracyclineAndMetro;
