within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD19_LinagliptinAndEmpagliflozin
  extends Icons.Package;
end A10BD19_LinagliptinAndEmpagliflozin;
