within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B01A_AntithromboticAgents;
package B01AD13_ApadamtaseAlfaAndCinaxadamtaseAlfa
  extends Icons.Package;
end B01AD13_ApadamtaseAlfaAndCinaxadamtaseAlfa;
