within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H04A_GlycogenolyticHormones;
package H04AA02_Dasiglucagon
  extends Icons.PackageDrugs;
end H04AA02_Dasiglucagon;
