within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis;
package A02BA53_FamotidineCombinations
  extends Icons.PackageDrugs;
end A02BA53_FamotidineCombinations;
