within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B06A_OtherHematologicalAgents;
package B06AA02_FibrinolysinAndDesoxyribonuclease
  extends Icons.Package;
end B06AA02_FibrinolysinAndDesoxyribonuclease;
