within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03E_DiureticsAndPotassiumSparingAgentsInCombination;
package C03EA05_MebutizideAndPotassiumSparingAge
  extends Icons.Package;
end C03EA05_MebutizideAndPotassiumSparingAge;
