within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M03B_MuscleRelaxantsCentrallyActingAgents;
package M03BA73_MethocarbamolCombinationsWithPsy
  extends Icons.PackageDrugs;
end M03BA73_MethocarbamolCombinationsWithPsy;
