within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins.A10BD01_PhenforminAndSulfonylure;

model PhenforminAndSulfonylure
  extends Pharmacolibrary.Drugs.ATC.A.A10BD01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>PhenforminAndSulfonylureas</td></tr><tr><td>ATC code:</td><td>A10BD01</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Phenformin and sulfonylureas (ATC code A10BD01) is a fixed-dose combination previously used in the management of type 2 diabetes mellitus. Phenformin is a biguanide-class antihyperglycemic agent, while sulfonylureas stimulate insulin secretion from pancreatic beta cells. Phenformin was withdrawn in many countries due to risk of lactic acidosis, and the combination is not currently approved or in regular clinical use.</p><h4>Pharmacokinetics</h4><p>No published pharmacokinetic model with quantitative parameters for the fixed-dose combination phenformin and sulfonylureas with ATC code A10BD01 was found. Thus, no referenced population pharmacokinetic data are available. Estimates here are based on typical oral pharmacokinetics for each drug class separately and assumed for the combination, with standard adult population as target.</p><h4>References</h4><ol><li><p>Scheen, AJ, &amp; Lefèbvre, PJ (1995). Antihyperglycaemic agents. Drug interactions of clinical importance. <i>Drug safety</i> 12(1) 32–45. DOI:<a href=\"https://doi.org/10.2165/00002018-199512010-00003\">10.2165/00002018-199512010-00003</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/7741982/\">https://pubmed.ncbi.nlm.nih.gov/7741982</a></p></li><li><p>Marchetti, P, et al., &amp; Navalesi, R (1991). Pharmacokinetic optimisation of oral hypoglycaemic therapy. <i>Clinical pharmacokinetics</i> 21(4) 308–317. DOI:<a href=\"https://doi.org/10.2165/00003088-199121040-00006\">10.2165/00003088-199121040-00006</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/1760902/\">https://pubmed.ncbi.nlm.nih.gov/1760902</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end PhenforminAndSulfonylure;
