within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AA04_Chlorquinaldol
  extends Icons.PackageDrugs;
end P01AA04_Chlorquinaldol;
