within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AA04_Chlorquinaldol
  extends Icons.Package;
end P01AA04_Chlorquinaldol;
