within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A04A_AntiemeticsAndAntinauseants;
package A04AD51_ScopolamineCombinations
  extends Icons.PackageDrugs;
end A04AD51_ScopolamineCombinations;
