within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M09A_OtherDrugsForDisordersOfTheMusculoSkeletalSystem;
package M09AB52_TrypsinCombinations
  extends Icons.Package;
end M09AB52_TrypsinCombinations;
