within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AP10_TyphoidCombinationsWithParatyphi
  extends Icons.Package;
end J07AP10_TyphoidCombinationsWithParatyphi;
