within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07D_BetaBlockingAgentsThiazidesAndOtherDiuretics;
package C07DB01_AtenololThiazidesAndOthe
  extends Icons.PackageDrugs;
end C07DB01_AtenololThiazidesAndOthe;
