within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01R_CombinationsOfAntibacterials;
package J01RA05_LevofloxacinAndOrnidazol
  extends Icons.PackageDrugs;
end J01RA05_LevofloxacinAndOrnidazol;
