within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M03B_MuscleRelaxantsCentrallyActingAgents;
package M03BA53_MethocarbamolCombinationsExclPsy
  extends Icons.Package;
end M03BA53_MethocarbamolCombinationsExclPsy;
