within Pharmacolibrary.Drugs.R_RespiratorySystem.R03B_OtherDrugsForObstructiveAirwayDiseasesInhalants;
package R03BB54_TiotropiumBromideCombina
  extends Icons.PackageDrugs;
end R03BB54_TiotropiumBromideCombina;
