within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09X_OtherAgentsActingOnTheReninAngiotensinSystem;
package C09XA54_AliskirenAmlodipineAndHydrochlorothiazide
  extends Icons.Package;
end C09XA54_AliskirenAmlodipineAndHydrochlorothiazide;
