within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BC06_Dexlansoprazole
  extends Icons.Package;
end A02BC06_Dexlansoprazole;
