within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BX77_GefarnateCombinationsWithPsycholeptics
  extends Icons.Package;
end A02BX77_GefarnateCombinationsWithPsycholeptics;
