within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AL01_PneumococcusPurifiedPolysacchari
  extends Icons.PackageDrugs;
end J07AL01_PneumococcusPurifiedPolysacchari;
