within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD21_SaxagliptinAndDapagliflozin
  extends Icons.Package;
end A10BD21_SaxagliptinAndDapagliflozin;
