within Pharmacolibrary.Drugs.R_RespiratorySystem.R03D_OtherSystemicDrugsForObstructiveAirwayDiseases;
package R03DB03_ProxyphyllineAndAdrenerg
  extends Icons.PackageDrugs;
end R03DB03_ProxyphyllineAndAdrenerg;
