within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DA02_EprosartanAndDiuretics
  extends Icons.Package;
end C09DA02_EprosartanAndDiuretics;
