within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H01B_PosteriorPituitaryLobeHormones;
package H01BA05_Ornipressin
  extends Icons.PackageDrugs;
end H01BA05_Ornipressin;
