within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination;
package G03FA04_ProgesteroneAndEstrogen
  extends Icons.Package;
end G03FA04_ProgesteroneAndEstrogen;
