within Pharmacolibrary.Drugs.R_RespiratorySystem.R03D_OtherSystemicDrugsForObstructiveAirwayDiseases;
package R03DA51_DiprophyllineCombinations
  extends Icons.Package;
end R03DA51_DiprophyllineCombinations;
