within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BX05_BismuthSubcitrate
  extends Icons.Package;
end A02BX05_BismuthSubcitrate;
