within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03G_GonadotropinsAndOtherOvulationStimulants;
package G03GA02_HumanMenopausalGonadotro
  extends Icons.PackageDrugs;
end G03GA02_HumanMenopausalGonadotro;
