within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BX03_Pirenzepine
  extends Icons.Package;
end A02BX03_Pirenzepine;
