within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BA05_Niperotidine
  extends Icons.Package;
end A02BA05_Niperotidine;
