within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03B_LowCeilingDiureticsExclThiazides;
package C03BB04_ChlortalidoneAndPotassiu
  extends Icons.PackageDrugs;
end C03BB04_ChlortalidoneAndPotassiu;
