within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J04A_DrugsForTreatmentOfTuberculosis.J04AM03_EthambutolAndIsoniazid;

model EthambutolAndIsoniazid
  extends Pharmacolibrary.Drugs.ATC.J.J04AM03;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>EthambutolAndIsoniazid</td></tr><tr><td>ATC code:</td><td>J04AM03</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Ethambutol and isoniazid is a fixed combination antituberculosis medication used primarily for the treatment of tuberculosis. Ethambutol acts by inhibiting cell wall synthesis, while isoniazid is a prodrug that inhibits the synthesis of mycolic acids. This combination is approved and widely used as part of multi-drug regimens for the treatment of tuberculosis.</p><h4>Pharmacokinetics</h4><p>Population pharmacokinetics of ethambutol and isoniazid in adult patients with tuberculosis, administered orally as fixed-dose combination tablets.</p><h4>References</h4><ol><li><p>Chen, C, et al., &amp; Simonsson, US (2016). Population pharmacokinetics, optimised design and sample size determination for rifampicin, isoniazid, ethambutol and pyrazinamide in the mouse. <i>European journal of pharmaceutical sciences : official journal of the European Federation for Pharmaceutical Sciences</i> 93 319–333. DOI:<a href=\"https://doi.org/10.1016/j.ejps.2016.07.017\">10.1016/j.ejps.2016.07.017</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27473307/\">https://pubmed.ncbi.nlm.nih.gov/27473307</a></p></li><li><p>Denti, P, et al., &amp; Andersen, AB (2015). Pharmacokinetics of Isoniazid, Pyrazinamide, and Ethambutol in Newly Diagnosed Pulmonary TB Patients in Tanzania. <i>PloS one</i> 10(10) e0141002–None. DOI:<a href=\"https://doi.org/10.1371/journal.pone.0141002\">10.1371/journal.pone.0141002</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/26501782/\">https://pubmed.ncbi.nlm.nih.gov/26501782</a></p></li><li><p>Langdon, G, et al., &amp; Simonsson, US (2005). Population pharmacokinetics of rifapentine and its primary desacetyl metabolite in South African tuberculosis patients. <i>Antimicrobial agents and chemotherapy</i> 49(11) 4429–4436. DOI:<a href=\"https://doi.org/10.1128/AAC.49.11.4429-4436.2005\">10.1128/AAC.49.11.4429-4436.2005</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/16251279/\">https://pubmed.ncbi.nlm.nih.gov/16251279</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end EthambutolAndIsoniazid;
