within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J04A_DrugsForTreatmentOfTuberculosis;
package J04AM03_EthambutolAndIsoniazid
  extends Icons.PackageDrugs;
end J04AM03_EthambutolAndIsoniazid;
