within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A08A_AntiobesityPreparationsExclDietProducts;
package A08AA62_BupropionAndNaltrexone
  extends Icons.Package;
end A08AA62_BupropionAndNaltrexone;
