within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AD02_AceticAcid
  extends Icons.PackageDrugs;
end G01AD02_AceticAcid;
