within Pharmacolibrary.Drugs.D_Dermatologicals.D08A_AntisepticsAndDisinfectants;
package D08AG01_IodineOctylphenoxypolyglycolethe
  extends Icons.Package;
end D08AG01_IodineOctylphenoxypolyglycolethe;
