within Pharmacolibrary.Drugs.D_Dermatologicals.D07C_CorticosteroidsCombinationsWithAntibiotics;
package D07CC06_FluocortoloneAndAntibiot
  extends Icons.PackageDrugs;
end D07CC06_FluocortoloneAndAntibiot;
