within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B02B_VitaminKAndOtherHemostatics;
package B02BC03_TetragalacturonicAcidHydroxymethylester
  extends Icons.Package;
end B02BC03_TetragalacturonicAcidHydroxymethylester;
