within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AR27_LamivudineTenofovirDisoproxilAnd
  extends Icons.Package;
end J05AR27_LamivudineTenofovirDisoproxilAnd;
