within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AR27_LamivudineTenofovirDisoproxilAnd
  extends Icons.PackageDrugs;
end J05AR27_LamivudineTenofovirDisoproxilAnd;
