within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FE01_Cetuximab
  extends Icons.PackageDrugs;
end L01FE01_Cetuximab;
