within Pharmacolibrary.Drugs.D_Dermatologicals.D06A_AntibioticsForTopicalUse.D06AX15_Rifamycin;

model Rifamycin
  extends Pharmacolibrary.Drugs.ATC.D.D06AX15;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Rifamycin</td></tr><tr><td>ATC code:</td><td>D06AX15</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Rifamycin is a semi-synthetic antibiotic belonging to the rifamycin class. It is used primarily as a topical antibacterial agent for the treatment of skin infections and some gastrointestinal infections (as rifamycin sodium or rifaximin). It is no longer widely used systemically due to resistance and other derivatives (like rifampicin) are preferred. Rifamycin is still approved for certain topical and GI indications.</p><h4>Pharmacokinetics</h4><p>Estimated pharmacokinetic parameters for topical or oral gastrointestinal use in adult population as no published compartmental PK model available for the rifamycin active substance.</p><h4>References</h4><ol><li><p>Abulfathi, AA, et al., &amp; Reuter, H (2019). Clinical Pharmacokinetics and Pharmacodynamics of Rifampicin in Human Tuberculosis. <i>Clinical pharmacokinetics</i> 58(9) 1103–1129. DOI:<a href=\"https://doi.org/10.1007/s40262-019-00764-2\">10.1007/s40262-019-00764-2</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31049868/\">https://pubmed.ncbi.nlm.nih.gov/31049868</a></p></li><li><p>Bock, M, et al., &amp; Moser, C (2023). Attainment of Target Antibiotic Levels by Oral Treatment of Left-Sided Infective Endocarditis: A POET Substudy. <i>Clinical infectious diseases : an official publication of the Infectious Diseases Society of America</i> 77(2) 242–251. DOI:<a href=\"https://doi.org/10.1093/cid/ciad168\">10.1093/cid/ciad168</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36947131/\">https://pubmed.ncbi.nlm.nih.gov/36947131</a></p></li><li><p>Zahr, N, et al., &amp; Funck-Brentano, C (2021). Ciprofloxacin population pharmacokinetics during long-term treatment of osteoarticular infections. <i>The Journal of antimicrobial chemotherapy</i> 76(11) 2906–2913. DOI:<a href=\"https://doi.org/10.1093/jac/dkab275\">10.1093/jac/dkab275</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34363656/\">https://pubmed.ncbi.nlm.nih.gov/34363656</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Rifamycin;
