within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M03B_MuscleRelaxantsCentrallyActingAgents;
package M03BA51_PhenprobamateCombinationsExclPsy
  extends Icons.Package;
end M03BA51_PhenprobamateCombinationsExclPsy;
