within Pharmacolibrary.Drugs.V_Various.V09H_InflammationAndInfectionDetection;
package V09HA03_Technetium99mtcAntigranulocyteAntibody
  extends Icons.Package;
end V09HA03_Technetium99mtcAntigranulocyteAntibody;
