within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX20_Tremelimumab
  extends Icons.Package;
end L01FX20_Tremelimumab;
