within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AR17_EmtricitabineAndTenofovirAlafena
  extends Icons.Package;
end J05AR17_EmtricitabineAndTenofovirAlafena;
