within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AR17_EmtricitabineAndTenofovirAlafena
  extends Icons.PackageDrugs;
end J05AR17_EmtricitabineAndTenofovirAlafena;
