within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AR07_StavudineLamivudineAndNevirapine
  extends Icons.Package;
end J05AR07_StavudineLamivudineAndNevirapine;
