within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AE10_SulfamethizoleAndTrimeth
  extends Icons.PackageDrugs;
end G01AE10_SulfamethizoleAndTrimeth;
