within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DA09_AzilsartanMedoxomilAndDi
  extends Icons.PackageDrugs;
end C09DA09_AzilsartanMedoxomilAndDi;
