within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01E_SulfonamidesAndTrimethoprim;
package J01EE02_SulfadiazineAndTrimethoprim
  extends Icons.Package;
end J01EE02_SulfadiazineAndTrimethoprim;
