within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J06B_Immunoglobulins.J06BB19_AnthraxImmunoglobulin;

model AnthraxImmunoglobulin
  extends Pharmacolibrary.Drugs.ATC.J.J06BB19;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>AnthraxImmunoglobulin</td></tr><tr><td>ATC code:</td><td>J06BB19</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Anthrax immunoglobulin is a human immune globulin preparation derived from the plasma of healthy donors immunized with anthrax vaccine. It contains polyclonal antibodies against Bacillus anthracis toxins and is used as an adjunctive treatment for inhalational anthrax in combination with appropriate antibacterial drugs. Anthrax immunoglobulin is FDA-approved for this indication.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters are estimated based on general properties of intravenous immunoglobulin (IVIg) products in healthy and infected adults, as no published population PK studies specific to anthrax immunoglobulin were found.</p><h4>References</h4><ol><li><p>Oosterholt, SP, &amp; Della Pasqua, O (2021). Population pharmacokinetics of raxibacumab in healthy adult subjects. <i>British journal of clinical pharmacology</i> 87(12) 4718–4725. DOI:<a href=\"https://doi.org/10.1111/bcp.14894\">10.1111/bcp.14894</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33973655/\">https://pubmed.ncbi.nlm.nih.gov/33973655</a></p></li><li><p>Beliveau, M, et al., &amp; Kammanadiminti, S (2024). Animal-to-Human Dose Translation of ANTHRASIL for Treatment of Inhalational Anthrax in Healthy Adults, Obese Adults, and Pediatric Subjects. <i>Clinical pharmacology and therapeutics</i> 115(2) 248–255. DOI:<a href=\"https://doi.org/10.1002/cpt.3097\">10.1002/cpt.3097</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/38082506/\">https://pubmed.ncbi.nlm.nih.gov/38082506</a></p></li><li><p>Skoura, N, et al., &amp; Tan, LK (2020). Effect of raxibacumab on immunogenicity of Anthrax Vaccine Adsorbed: a phase 4, open-label, parallel-group, randomised non-inferiority study. <i>The Lancet. Infectious diseases</i> 20(8) 983–991. DOI:<a href=\"https://doi.org/10.1016/S1473-3099(20)30069-4\">10.1016/S1473-3099(20)30069-4</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32333847/\">https://pubmed.ncbi.nlm.nih.gov/32333847</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end AnthraxImmunoglobulin;
