within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism;
package A03A_DrugsForFunctionalGastrointestinalDisorders
  extends Icons.PackageDrugs;
end A03A_DrugsForFunctionalGastrointestinalDisorders;
