within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DX06_CandesartanAmlodipineAndHydrochlorothiazide
  extends Icons.Package;
end C09DX06_CandesartanAmlodipineAndHydrochlorothiazide;
