within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A16A_OtherAlimentaryTractAndMetabolismProducts;
package A16AB20_PegunigalsidaseAlfa
  extends Icons.PackageDrugs;
end A16AB20_PegunigalsidaseAlfa;
