within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01X_OtherAntineoplasticAgents;
package L01XL05_CiltacabtageneAutoleucel
  extends Icons.Package;
end L01XL05_CiltacabtageneAutoleucel;
