within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AP56_SofosbuvirVelpatasvirAndVoxilapr
  extends Icons.PackageDrugs;
end J05AP56_SofosbuvirVelpatasvirAndVoxilapr;
