within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02A_Antacids;
package A02AB10_OmeprazoleAmoxicillinAndClarithr
  extends Icons.PackageDrugs;
end A02AB10_OmeprazoleAmoxicillinAndClarithr;
