within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A16A_OtherAlimentaryTractAndMetabolismProducts;
package A16AB22_AvalglucosidaseAlfa
  extends Icons.PackageDrugs;
end A16AB22_AvalglucosidaseAlfa;
