within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03C_AntispasmodicsInCombinationWithPsycholeptics;
package A03CA01_IsopropamideAndPsycholep
  extends Icons.PackageDrugs;
end A03CA01_IsopropamideAndPsycholep;
