within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G04C_DrugsUsedInBenignProstaticHypertrophy;
package G04CA53_TamsulosinAndSolifenacin
  extends Icons.PackageDrugs;
end G04CA53_TamsulosinAndSolifenacin;
