within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA04_HaemophilusInfluenzaeBAn
  extends Icons.PackageDrugs;
end J07CA04_HaemophilusInfluenzaeBAn;
