within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07B_BetaBlockingAgentsAndThiazides;
package C07BB52_MetoprololAndThiazidesCombinatio
  extends Icons.Package;
end C07BB52_MetoprololAndThiazidesCombinatio;
