within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07B_BetaBlockingAgentsAndThiazides;
package C07BB52_MetoprololAndThiazidesCombinatio
  extends Icons.PackageDrugs;
end C07BB52_MetoprololAndThiazidesCombinatio;
