within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BA55_SalicylamideCombinationsExclPsyc
  extends Icons.Package;
end N02BA55_SalicylamideCombinationsExclPsyc;
