within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BF04_PoliomyelitisOralBivalentLiveAtt
  extends Icons.Package;
end J07BF04_PoliomyelitisOralBivalentLiveAtt;
