within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B03A_IronPreparations.B03AE10_VariousCombinations;

model VariousCombinations
  extends Pharmacolibrary.Drugs.ATC.B.B03AE10;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>VariousCombinations</td></tr><tr><td>ATC code:</td><td>B03AE10</td></tr><td>route:</td><td>intramuscular</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>B03AE10 refers to various combinations of vitamin B12 (cyanocobalamin/hydroxocobalamin) with other hematinic agents. These combinations are typically used in the treatment of anemia due to vitamin B12 deficiency or in cases where there is a combined iron and B12 deficiency. Such combinations are used when dietary intake is insufficient or absorption is impaired. The approval and current use of these combinations depend on national regulatory authorities and the specific components included.</p><h4>Pharmacokinetics</h4><p>No published population pharmacokinetic models specific to 'various combinations' of B12 with other agents under B03AE10 were identified. Pharmacokinetics for vitamin B12 are generally based on single agents, with combination products assumed to have similar PK unless significant drug-drug interactions are present. The following estimates are based on standard pharmacokinetics of intramuscular hydroxocobalamin in healthy adults.</p><h4>References</h4><ol><li><p>Hornik, CP, et al., &amp; Lee, JH (2018). Population Pharmacokinetics of Intramuscular and Intravenous Ketamine in Children. <i>Journal of clinical pharmacology</i> 58(8) 1092–1104. DOI:<a href=\"https://doi.org/10.1002/jcph.1116\">10.1002/jcph.1116</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29677389/\">https://pubmed.ncbi.nlm.nih.gov/29677389</a></p></li><li><p>Dowling, J, et al., &amp; Graudins, A (2008). Population pharmacokinetics of intravenous, intramuscular, and intranasal naloxone in human volunteers. <i>Therapeutic drug monitoring</i> 30(4) 490–496. DOI:<a href=\"https://doi.org/10.1097/FTD.0b013e3181816214\">10.1097/FTD.0b013e3181816214</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/18641540/\">https://pubmed.ncbi.nlm.nih.gov/18641540</a></p></li><li><p>Samtani, MN, et al., &amp; Stuyckens, K (2009). Population pharmacokinetics of intramuscular paliperidone palmitate in patients with schizophrenia: a novel once-monthly, long-acting formulation of an atypical antipsychotic. <i>Clinical pharmacokinetics</i> 48(9) 585–600. DOI:<a href=\"https://doi.org/10.2165/11316870-000000000-00000\">10.2165/11316870-000000000-00000</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/19725593/\">https://pubmed.ncbi.nlm.nih.gov/19725593</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end VariousCombinations;
