within Pharmacolibrary.Drugs.S_SensoryOrgans.S01G_DecongestantsAndAntiallergics.S01GA07_Brimonidine;

model Brimonidine
  extends Pharmacolibrary.Drugs.ATC.S.S01GA07;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>S01GA07</td></tr><td>route:</td><td>ophthalmic</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Brimonidine is an alpha-2 adrenergic receptor agonist used primarily in ophthalmology to reduce intraocular pressure in patients with open-angle glaucoma or ocular hypertension. It is administered as an ophthalmic solution and is an approved and currently used drug.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters in adults following topical ocular administration under steady-state conditions.</p><h4>References</h4><ol><li><p>Ackerman, SL, et al., &amp; Vittitow, JL (2019). Low-dose brimonidine for relief of ocular redness: integrated analysis of four clinical trials. <i>Clinical &amp; experimental optometry</i> 102(2) 131–139. DOI:<a href=\"https://doi.org/10.1111/cxo.12846\">10.1111/cxo.12846</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30525235/\">https://pubmed.ncbi.nlm.nih.gov/30525235</a></p></li><li><p>Schnichels, S, et al., &amp; Herrmann, A (2021). Improved Treatment Options for Glaucoma with Brimonidine-Loaded Lipid DNA Nanoparticles. <i>ACS applied materials &amp; interfaces</i> 13(8) 9445–9456. DOI:<a href=\"https://doi.org/10.1021/acsami.0c18626\">10.1021/acsami.0c18626</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33528240/\">https://pubmed.ncbi.nlm.nih.gov/33528240</a></p></li><li><p>Kim, CY, et al., &amp; Seong, GJ (2007). Brimonidine 0.2% versus brimonidine Purite 0.15% in Asian ocular hypertension. <i>Journal of ocular pharmacology and therapeutics : the official journal of the Association for Ocular Pharmacology and Therapeutics</i> 23(5) 481–486. DOI:<a href=\"https://doi.org/10.1089/jop.2007.0042\">10.1089/jop.2007.0042</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/17900227/\">https://pubmed.ncbi.nlm.nih.gov/17900227</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Brimonidine;
