within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX17_SacituzumabGovitecan
  extends Icons.PackageDrugs;
end L01FX17_SacituzumabGovitecan;
