within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M09A_OtherDrugsForDisordersOfTheMusculoSkeletalSystem;
package M09AX02_ChondrocytesAutologous
  extends Icons.PackageDrugs;
end M09AX02_ChondrocytesAutologous;
