within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AA07_Oxytetracycline
  extends Icons.Package;
end G01AA07_Oxytetracycline;
