within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A01A_StomatologicalPreparations;
package A01AB53_ChlorhexidineAndCetylpyr
  extends Icons.PackageDrugs;
end A01AB53_ChlorhexidineAndCetylpyr;
