within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M05B_DrugsAffectingBoneStructureAndMineralization;
package M05BB08_ZoledronicAcidCalciumAnd
  extends Icons.PackageDrugs;
end M05BB08_ZoledronicAcidCalciumAnd;
