within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H02A_CorticosteroidsForSystemicUsePlain;
package H02AA01_Aldosterone
  extends Icons.Package;
end H02AA01_Aldosterone;
