within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BF01_PoliomyelitisOralMonovalentLiveA
  extends Icons.Package;
end J07BF01_PoliomyelitisOralMonovalentLiveA;
