within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H02A_CorticosteroidsForSystemicUsePlain;
package H02AA02_Fludrocortisone
  extends Icons.Package;
end H02AA02_Fludrocortisone;
