within Pharmacolibrary.Drugs.C_CardiovascularSystem.C04A_PeripheralVasodilators.C04AC01_NicotinicAcid;

model NicotinicAcid
  extends Pharmacolibrary.Drugs.ATC.C.C04AC01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>C04AC01</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Nicotinic acid (also known as niacin or vitamin B3) is a water-soluble vitamin used as a lipid-modifying agent for the treatment of dyslipidemia, especially to increase HDL cholesterol and lower triglycerides and LDL cholesterol. While it has been historically used for cardiovascular risk reduction, its use has declined due to side effects and the advent of more effective therapies. It is still approved in some countries as an adjunct in lipid disorders.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in healthy adult volunteers after oral administration.</p><h4>References</h4><ol><li><p>Mahmoud, SH, et al., &amp; Isse, FA (2020). Nimodipine Pharmacokinetic Variability in Various Patient Populations. <i>Drugs in R&amp;D</i> 20(4) 307–318. DOI:<a href=\"https://doi.org/10.1007/s40268-020-00322-3\">10.1007/s40268-020-00322-3</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32902829/\">https://pubmed.ncbi.nlm.nih.gov/32902829</a></p></li><li><p>Saini, R, et al., &amp; Weinberg, JM (2005). Advances in therapy for psoriasis: an overview of infliximab, etanercept, efalizumab, alefacept, adalimumab, tazarotene, and pimecrolimus. <i>Current pharmaceutical design</i> 11(2) 273–280. DOI:<a href=\"https://doi.org/10.2174/1381612053382232\">10.2174/1381612053382232</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/15638763/\">https://pubmed.ncbi.nlm.nih.gov/15638763</a></p></li><li><p>Miyatake, D, et al., &amp; Urae, A (2020). Pharmacokinetics and Safety of a Single Oral Dose of Peficitinib (ASP015K) in Japanese Subjects With Normal and Impaired Hepatic Function. <i>Clinical pharmacology in drug development</i> 9(6) 699–708. DOI:<a href=\"https://doi.org/10.1002/cpdd.751\">10.1002/cpdd.751</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31833184/\">https://pubmed.ncbi.nlm.nih.gov/31833184</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end NicotinicAcid;
