within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01E_ProteinKinaseInhibitors.L01EX03_Pazopanib;

model Pazopanib
  extends Pharmacolibrary.Drugs.ATC.L.L01EX03;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>L01EX03</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Pazopanib is an oral, small-molecule tyrosine kinase inhibitor that targets vascular endothelial growth factor receptor (VEGFR), platelet-derived growth factor receptor (PDGFR), and c-Kit. It is primarily used for the treatment of advanced renal cell carcinoma and advanced soft tissue sarcoma. Pazopanib is approved by regulatory agencies and is currently in clinical use for these indications.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters in adult patients with advanced solid tumors; healthy male and female, multiple ethnicities, after oral administration of pazopanib tablets.</p><h4>References</h4><ol><li><p>Imbs, DC, et al., &amp; Chatelut, E (2014). Pharmacokinetics of pazopanib administered in combination with bevacizumab. <i>Cancer chemotherapy and pharmacology</i> 73(6) 1189–1196. DOI:<a href=\"https://doi.org/10.1007/s00280-014-2455-3\">10.1007/s00280-014-2455-3</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/24705975/\">https://pubmed.ncbi.nlm.nih.gov/24705975</a></p></li><li><p>Turner, DC, et al., &amp; Stewart, CF (2013). Combination metronomic oral topotecan and pazopanib: a pharmacokinetic study in patients with gynecological cancer. <i>Anticancer research</i> 33(9) 3823–3829. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/24023315/\">https://pubmed.ncbi.nlm.nih.gov/24023315</a></p></li><li><p>McLaughlin, MM, et al., &amp; Kim, RY (2013). Initial exploration of oral pazopanib in healthy participants and patients with age-related macular degeneration. <i>JAMA ophthalmology</i> 131(12) 1595–1601. DOI:<a href=\"https://doi.org/10.1001/jamaophthalmol.2013.5002\">10.1001/jamaophthalmol.2013.5002</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/24113783/\">https://pubmed.ncbi.nlm.nih.gov/24113783</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Pazopanib;
