within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J04B_DrugsForTreatmentOfLepra;
package J04BA51_DapsoneRifampicinAndClofazimine
  extends Icons.Package;
end J04BA51_DapsoneRifampicinAndClofazimine;
