within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AA10_Clindamycin
  extends Icons.Package;
end G01AA10_Clindamycin;
