within Pharmacolibrary.Drugs.S_SensoryOrgans.S01A_Antiinfectives.S01AE06_Gatifloxacin;

model Gatifloxacin
  extends Pharmacolibrary.Drugs.ATC.S.S01AE06;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Gatifloxacin</td></tr><tr><td>ATC code:</td><td>S01AE06</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Gatifloxacin is a fourth-generation fluoroquinolone antibiotic used primarily for the treatment of bacterial conjunctivitis (eye infections) and formerly for systemic infections. Due to concerns about dysglycemia, its systemic use is now withdrawn or heavily restricted in many countries, but ophthalmic formulations are still used.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported for healthy adult volunteers after oral and intravenous administration.</p><h4>References</h4><ol><li><p>Peloquin, CA, et al., &amp; Johnson, JL (2008). Population pharmacokinetics of levofloxacin, gatifloxacin, and moxifloxacin in adults with pulmonary tuberculosis. <i>Antimicrobial agents and chemotherapy</i> 52(3) 852–857. DOI:<a href=\"https://doi.org/10.1128/AAC.01036-07\">10.1128/AAC.01036-07</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/18070980/\">https://pubmed.ncbi.nlm.nih.gov/18070980</a></p></li><li><p>Kikuchi, J, et al., &amp; Nishimura, M (2007). Pharmacokinetics of gatifloxacin after a single oral dose in healthy young adult subjects and adult patients with chronic bronchitis, with a comparison of drug concentrations obtained by bronchoscopic microsampling and bronchoalveolar lavage. <i>Clinical therapeutics</i> 29(1) 123–130. DOI:<a href=\"https://doi.org/10.1016/j.clinthera.2007.01.005\">10.1016/j.clinthera.2007.01.005</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/17379052/\">https://pubmed.ncbi.nlm.nih.gov/17379052</a></p></li><li><p>Corrêa, JC, et al., &amp; Yang, JY (2003). Randomized, open-label, parallel-group, multicenter study of the efficacy and tolerability of IV gatifloxacin with the option for oral stepdown gatifloxacin versus IV ceftriaxone (with or without erythromycin or clarithromycin) with the option for oral stepdown clarithromycin for treatment of patients with mild to moderate community-acquired pneumonia requiring hospitalization. <i>Clinical therapeutics</i> 25(5) 1453–1468. DOI:<a href=\"https://doi.org/10.1016/s0149-2918(03)80132-7\">10.1016/s0149-2918(03)80132-7</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/12867221/\">https://pubmed.ncbi.nlm.nih.gov/12867221</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Gatifloxacin;
