within Pharmacolibrary.Drugs.D_Dermatologicals.D07B_CorticosteroidsCombinationsWithAntiseptics;
package D07BB03_TriamcinoloneAndAntisept
  extends Icons.PackageDrugs;
end D07BB03_TriamcinoloneAndAntisept;
