within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AH03_MeningococcusACBivalentPurifiedP
  extends Icons.PackageDrugs;
end J07AH03_MeningococcusACBivalentPurifiedP;
