within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials.J01DE03_Cefozopran;

model Cefozopran
  extends Pharmacolibrary.Drugs.ATC.J.J01DE03;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>J01DE03</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Cefozopran is a fourth-generation cephalosporin antibiotic used primarily in Japan for the treatment of a broad spectrum of bacterial infections, including respiratory tract, urinary tract, skin, and intra-abdominal infections. It is administered mainly in hospital settings and is not currently approved in the US or EU.</p><h4>Pharmacokinetics</h4><p>Healthy adult subjects after single intravenous administration.</p><h4>References</h4><ol><li><p>Wu, GL, et al., &amp; Wu, LH (2015). Pharmacokinetics of cefozopran by single and multiple intravenous infusions in healthy Chinese volunteers. <i>Drugs in R&amp;D</i> 15(1) 63–70. DOI:<a href=\"https://doi.org/10.1007/s40268-014-0075-3\">10.1007/s40268-014-0075-3</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25644122/\">https://pubmed.ncbi.nlm.nih.gov/25644122</a></p></li><li><p>Nomura, K, et al., &amp; Taniwaki, M (2008). Optimized dosage and frequency of cefozopran for patients with febrile neutropenia based on population pharmacokinetic and pharmacodynamic analysis. <i>The Journal of antimicrobial chemotherapy</i> 61(4) 892–900. DOI:<a href=\"https://doi.org/10.1093/jac/dkn038\">10.1093/jac/dkn038</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/18276604/\">https://pubmed.ncbi.nlm.nih.gov/18276604</a></p></li><li><p>Ikawa, K, et al., &amp; Kobayashi, R (2009). Population pharmacokinetic modeling and pharmacodynamic assessment of cefozopran in pediatric patients. <i>The Japanese journal of antibiotics</i> 62(5) 435–444. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/20055120/\">https://pubmed.ncbi.nlm.nih.gov/20055120</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Cefozopran;
