within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombination;
package S01CA09_ChloroprednisoneAndAntiinfectives
  extends Icons.Package;
end S01CA09_ChloroprednisoneAndAntiinfectives;
