within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M09A_OtherDrugsForDisordersOfTheMusculoSkeletalSystem;
package M09AA72_QuinineCombinationsWithPsycholeptics
  extends Icons.Package;
end M09AA72_QuinineCombinationsWithPsycholeptics;
