within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AB06_GestodeneAndEthinylestra
  extends Icons.PackageDrugs;
end G03AB06_GestodeneAndEthinylestra;
