within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination.G03FA12_MedroxyprogesteroneAndEs;

model MedroxyprogesteroneAndEs
  extends Pharmacolibrary.Drugs.ATC.G.G03FA12;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>MedroxyprogesteroneAndEstrogen</td></tr><tr><td>ATC code:</td><td>G03FA12</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Medroxyprogesterone and estrogen is a combination hormonal therapy primarily indicated for hormone replacement therapy in postmenopausal women to alleviate menopausal symptoms and to reduce the risk of osteoporosis. Medroxyprogesterone is a synthetic progestin, and estrogen (usually as conjugated estrogens or estradiol) is a natural female sex hormone. This combination is approved and used currently for hormone replacement therapy.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters estimated for a typical adult woman following oral administration of standard clinical doses. No published population pharmacokinetic model or clinical PK study directly reporting all parameters for this combination. Estimates are based on published PK for single agents.</p><h4>References</h4><ol><li><p>Garza-Flores, J, et al., &amp; Perez-Palacios, G (1991). Long-acting hormonal contraceptives for women. <i>The Journal of steroid biochemistry and molecular biology</i> 40(4-6) 697–704. DOI:<a href=\"https://doi.org/10.1016/0960-0760(91)90293-e\">10.1016/0960-0760(91)90293-e</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/1958567/\">https://pubmed.ncbi.nlm.nih.gov/1958567</a></p></li><li><p>Zhou, XF, et al., &amp; Sang, GW (1998). Pharmacokinetics of medroxyprogesterone acetate after single and multiple injection of Cyclofem in Chinese women. <i>Contraception</i> 57(6) 405–411. DOI:<a href=\"https://doi.org/10.1016/s0010-7824(98)00048-1\">10.1016/s0010-7824(98)00048-1</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/9693401/\">https://pubmed.ncbi.nlm.nih.gov/9693401</a></p></li><li><p>Cromie, MA, et al., &amp; Wajszczuk, CP (2000). Comparative effects of Lunelle monthly contraceptive injection (medroxyprogesterone acetate and estradiol cypionate injectable suspension) and ortho-Novum 7/7/7 oral contraceptive (norethindrone/ethinyl estradiol triphasic) on lipid profiles. Investigators from the Lunelle Study Group. <i>Contraception</i> 61(1) 51–59. DOI:<a href=\"https://doi.org/10.1016/s0010-7824(99)00114-6\">10.1016/s0010-7824(99)00114-6</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/10745070/\">https://pubmed.ncbi.nlm.nih.gov/10745070</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end MedroxyprogesteroneAndEs;
