within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination;
package G03FA12_MedroxyprogesteroneAndEs
  extends Icons.PackageDrugs;
end G03FA12_MedroxyprogesteroneAndEs;
