within Pharmacolibrary.Drugs.R_RespiratorySystem.R05C_ExpectorantsExclCombinationsWithCoughSuppressants;
package R05CA10_OxomemazineAndGuaifenesinCombination
  extends Icons.Package;
end R05CA10_OxomemazineAndGuaifenesinCombination;
