within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DA01_LosartanAndDiuretics
  extends Icons.Package;
end C09DA01_LosartanAndDiuretics;
