within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AH02_OtherMeningococcalMonovalentPuri
  extends Icons.Package;
end J07AH02_OtherMeningococcalMonovalentPuri;
