within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B02B_VitaminKAndOtherHemostatics;
package B02BD15_ValoctocogeneRoxaparvove
  extends Icons.PackageDrugs;
end B02BD15_ValoctocogeneRoxaparvove;
