within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H02A_CorticosteroidsForSystemicUsePlain;
package H02AB05_Paramethasone
  extends Icons.Package;
end H02AB05_Paramethasone;
