within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01R_CombinationsOfAntibacterials;
package J01RA01_PenicillinsCombinationsWithOtherAntibacterials
  extends Icons.Package;
end J01RA01_PenicillinsCombinationsWithOtherAntibacterials;
