within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AG53_HaemophilusInfluenzaeBCombinationsWithMeningococcusCConjugated
  extends Icons.Package;
end J07AG53_HaemophilusInfluenzaeBCombinationsWithMeningococcusCConjugated;
