within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02L_AntihypertensivesAndDiureticsInCombination;
package C02LA71_ReserpineAndDiureticsCombination
  extends Icons.PackageDrugs;
end C02LA71_ReserpineAndDiureticsCombination;
