within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BE51_ParacetamolCombinationsExclPsycholeptics
  extends Icons.Package;
end N02BE51_ParacetamolCombinationsExclPsycholeptics;
