within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FF03_Durvalumab
  extends Icons.PackageDrugs;
end L01FF03_Durvalumab;
