within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FC02_Isatuximab
  extends Icons.PackageDrugs;
end L01FC02_Isatuximab;
