within Pharmacolibrary.Drugs.R_RespiratorySystem.R03A_AdrenergicsInhalants;
package R03AL12_IndacaterolGlycopyrroniumBromide
  extends Icons.PackageDrugs;
end R03AL12_IndacaterolGlycopyrroniumBromide;
