within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02A_AntiadrenergicAgentsCentrallyActing;
package C02AA04_RauwolfiaAlkaloidsWholeRoot
  extends Icons.Package;
end C02AA04_RauwolfiaAlkaloidsWholeRoot;
