within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD03_MetforminAndRosiglitazon
  extends Icons.PackageDrugs;
end A10BD03_MetforminAndRosiglitazon;
