within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials;
package J01DD64_CefpodoximeAndBetaLactamaseInhib
  extends Icons.Package;
end J01DD64_CefpodoximeAndBetaLactamaseInhib;
