within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials;
package J01DD64_CefpodoximeAndBetaLactamaseInhib
  extends Icons.PackageDrugs;
end J01DD64_CefpodoximeAndBetaLactamaseInhib;
