within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03C_Estrogens.G03CA01_Ethinylestradiol;

model Ethinylestradiol
  extends Pharmacolibrary.Drugs.ATC.G.G03CA01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>G03CA01</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Ethinylestradiol is a synthetic derivative of the natural estrogen estradiol. It is primarily used as an oral contraceptive, either alone or in combination with progestins, for the prevention of pregnancy. It is approved for clinical use and is a common component of combined oral contraceptive pills.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported for healthy adult females after a single oral dose.</p><h4>References</h4><ol><li><p>Luo, D, et al., &amp; Jusko, WJ (2019). Altered pharmacokinetics of combined oral contraceptives in obesity - multistudy assessment. <i>Contraception</i> 99(4) 256–263. DOI:<a href=\"https://doi.org/10.1016/j.contraception.2018.12.009\">10.1016/j.contraception.2018.12.009</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30684471/\">https://pubmed.ncbi.nlm.nih.gov/30684471</a></p></li><li><p>Mohamed, MF, et al., &amp; Othman, AA (2019). The JAK1 Inhibitor Upadacitinib Has No Effect on the Pharmacokinetics of Levonorgestrel and Ethinylestradiol: A Study in Healthy Female Subjects. <i>Journal of clinical pharmacology</i> 59(4) 510–516. DOI:<a href=\"https://doi.org/10.1002/jcph.1350\">10.1002/jcph.1350</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30500075/\">https://pubmed.ncbi.nlm.nih.gov/30500075</a></p></li><li><p>Luna, BG, et al., &amp; Greenblatt, DJ (1989). Doxylamine and diphenhydramine pharmacokinetics in women on low-dose estrogen oral contraceptives. <i>Journal of clinical pharmacology</i> 29(3) 257–260. DOI:<a href=\"https://doi.org/10.1002/j.1552-4604.1989.tb03323.x\">10.1002/j.1552-4604.1989.tb03323.x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/2723113/\">https://pubmed.ncbi.nlm.nih.gov/2723113</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Ethinylestradiol;
