within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02A_Antacids;
package A02AC10_PantoprazoleAndAmoxicillinAndClarithromycin
  extends Icons.Package;
end A02AC10_PantoprazoleAndAmoxicillinAndClarithromycin;
