within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BE73_PhenacetinCombinationsWithPsycho
  extends Icons.PackageDrugs;
end N02BE73_PhenacetinCombinationsWithPsycho;
