within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A12A_Calcium.A12AA04_CalciumCarbonate;

model CalciumCarbonate
  extends Pharmacolibrary.Drugs.ATC.A.A12AA04;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>CalciumCarbonate</td></tr><tr><td>ATC code:</td><td>A12AA04</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Calcium carbonate is a mineral supplement used in the prevention and treatment of calcium deficiencies, such as osteoporosis and rickets, and as an antacid for relief from heartburn and indigestion. It is widely used and is approved for use today in many countries as an over-the-counter supplement and medication.</p><h4>Pharmacokinetics</h4><p>Estimated pharmacokinetic parameters for healthy adults, typical oral dose.</p><h4>References</h4><ol><li><p>Junkert, AM, et al., &amp; Pontarolo, R (2024). Pharmacokinetics of oral ciprofloxacin in adult patients: A scoping review. <i>British journal of clinical pharmacology</i> 90(2) 528–547. DOI:<a href=\"https://doi.org/10.1111/bcp.15933\">10.1111/bcp.15933</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37850318/\">https://pubmed.ncbi.nlm.nih.gov/37850318</a></p></li><li><p>Wiria, M, et al., &amp; Pouteau, E (2020). Relative bioavailability and pharmacokinetic comparison of calcium glucoheptonate with calcium carbonate. <i>Pharmacology research &amp; perspectives</i> 8(2) e00589–None. DOI:<a href=\"https://doi.org/10.1002/prp2.589\">10.1002/prp2.589</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32302064/\">https://pubmed.ncbi.nlm.nih.gov/32302064</a></p></li><li><p>Pai, MP, et al., &amp; Amsden, GW (2006). Altered steady state pharmacokinetics of levofloxacin in adult cystic fibrosis patients receiving calcium carbonate. <i>Journal of cystic fibrosis : official journal of the European Cystic Fibrosis Society</i> 5(3) 153–157. DOI:<a href=\"https://doi.org/10.1016/j.jcf.2006.01.003\">10.1016/j.jcf.2006.01.003</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/16481224/\">https://pubmed.ncbi.nlm.nih.gov/16481224</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end CalciumCarbonate;
