within Pharmacolibrary.Drugs.V_Various.V09I_TumourDetection.V09IA04_Technetium99mtcVotumumab;

model Technetium99mtcVotumumab
  extends Pharmacolibrary.Drugs.ATC.V.V09IA04;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>V09IA04</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Technetium (99mTc) votumumab is a radiopharmaceutical composed of the monoclonal antibody votumumab labeled with the radioisotope technetium-99m (99mTc). It was developed for tumor imaging, particularly targeting tumor necrosis and specific cancer antigens in diagnostic nuclear medicine. The drug was intended for use in cancer imaging, but is not widely approved or in mainstream clinical use today.</p><h4>Pharmacokinetics</h4><p>No published pharmacokinetic data available for technetium (99mTc) votumumab. The following PK parameters are estimated based on general properties of radiolabeled monoclonal antibodies administered intravenously for imaging purposes in adults.</p><h4>References</h4><ol><li><p>Castronovo, FP (1981). Normal pharmacokinetics of 99mTc-diphosphonate after intravenous administration. <i>Biopharmaceutics &amp; drug disposition</i> 2(3) 283–289. DOI:<a href=\"https://doi.org/10.1002/bdd.2510020309\">10.1002/bdd.2510020309</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/7295885/\">https://pubmed.ncbi.nlm.nih.gov/7295885</a></p></li><li><p>Wong, M, et al., &amp; Gurney, H (2006). Predictors of vinorelbine pharmacokinetics and pharmacodynamics in patients with cancer. <i>Journal of clinical oncology : official journal of the American Society of Clinical Oncology</i> 24(16) 2448–2455. DOI:<a href=\"https://doi.org/10.1200/JCO.2005.02.1295\">10.1200/JCO.2005.02.1295</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/16651648/\">https://pubmed.ncbi.nlm.nih.gov/16651648</a></p></li><li><p>Castagnetti, M, et al., &amp; Buxton-Thomas, M (2007). Hepatobiliary scintigraphy after Kasai procedure for biliary atresia: clinical correlation and prognostic value. <i>Journal of pediatric surgery</i> 42(6) 1107–1113. DOI:<a href=\"https://doi.org/10.1016/j.jpedsurg.2007.01.063\">10.1016/j.jpedsurg.2007.01.063</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/17560230/\">https://pubmed.ncbi.nlm.nih.gov/17560230</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Technetium99mtcVotumumab;
