within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H04A_GlycogenolyticHormones.H04AA01_Glucagon;

model Glucagon
  extends Pharmacolibrary.Drugs.ATC.H.H04AA01_1;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Glucagon_1</td></tr><tr><td>ATC code:</td><td>H04AA01_1</td></tr><td>route:</td><td>intramuscular</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Glucagon is a peptide hormone produced by the alpha cells of the pancreas. It raises blood glucose levels by promoting glycogen breakdown and gluconeogenesis in the liver. It is mainly used as an emergency treatment for severe hypoglycemia and as a diagnostic aid in radiological examinations. Glucagon is approved and in clinical use.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters after intramuscular administration in healthy individuals.</p><h4>References</h4><ol><li><p>Huang, CJ, et al., &amp; Shih, KC (2023). Pharmacokinetics and Safety of Long-Acting Release Formulations of Pasireotide (SOM230) in a Male Population Who Are Hyperendemic Hepatitis B/C and Chronic Kidney Disease: An Open-Label, Phase I Study. <i>European journal of drug metabolism and pharmacokinetics</i> 48(6) 665–674. DOI:<a href=\"https://doi.org/10.1007/s13318-023-00854-4\">10.1007/s13318-023-00854-4</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37751056/\">https://pubmed.ncbi.nlm.nih.gov/37751056</a></p></li><li><p>Nasu, R, et al., &amp; Nagai, Y (2023). Dose Rationale of Nasal Glucagon in Japanese Pediatric Patients with Diabetes Using Pharmacokinetic/Pharmacodynamic Modeling and Simulation. <i>Paediatric drugs</i> 25(3) 377–387. DOI:<a href=\"https://doi.org/10.1007/s40272-023-00565-y\">10.1007/s40272-023-00565-y</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36973474/\">https://pubmed.ncbi.nlm.nih.gov/36973474</a></p></li><li><p>Chen, X, et al., &amp; Hu, P (2014). Pharmacokinetics and safety of subcutaneous pasireotide and intramuscular pasireotide long-acting release in Chinese male healthy volunteers: a phase I, single-center, open-label, randomized study. <i>Clinical therapeutics</i> 36(8) 1196–1210. DOI:<a href=\"https://doi.org/10.1016/j.clinthera.2014.06.006\">10.1016/j.clinthera.2014.06.006</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25012727/\">https://pubmed.ncbi.nlm.nih.gov/25012727</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Glucagon;
