within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AA17_MedroxyprogesteroneAndEs
  extends Icons.PackageDrugs;
end G03AA17_MedroxyprogesteroneAndEs;
