within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonStero.M01AE17_Dexketoprofen;

model Dexketoprofen
  extends Pharmacolibrary.Drugs.ATC.M.M01AE17;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Dexketoprofen</td></tr><tr><td>ATC code:</td><td>M01AE17</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Dexketoprofen is a non-steroidal anti-inflammatory drug (NSAID) and the S(+)-enantiomer of ketoprofen. It is used for the treatment of mild to moderate pain, including musculoskeletal pain, dysmenorrhea, and dental pain. It is currently approved and in use in several countries.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in healthy adult volunteers after a single oral dose.</p><h4>References</h4><ol><li><p>Rodríguez, MJ, et al., &amp; Amaro, SR (2008). Dexketoprofen trometamol: clinical evidence supporting its role as a painkiller. <i>Expert review of neurotherapeutics</i> 8(11) 1625–1640. DOI:<a href=\"https://doi.org/10.1586/14737175.8.11.1625\">10.1586/14737175.8.11.1625</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/18986233/\">https://pubmed.ncbi.nlm.nih.gov/18986233</a></p></li><li><p>Valles, J, et al., &amp; Capriati, A (2006). Single and repeated dose pharmacokinetics of dexketoprofen trometamol in young and elderly subjects. <i>Methods and findings in experimental and clinical pharmacology</i> 28 Suppl A 13–19. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/16801988/\">https://pubmed.ncbi.nlm.nih.gov/16801988</a></p></li><li><p>Varrassi, G, et al., &amp; Scarpignato, C (2017). Multimodal analgesia in moderate-to-severe pain: a role for a new fixed combination of dexketoprofen and tramadol. <i>Current medical research and opinion</i> 33(6) 1165–1173. DOI:<a href=\"https://doi.org/10.1080/03007995.2017.1310092\">10.1080/03007995.2017.1310092</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/28326850/\">https://pubmed.ncbi.nlm.nih.gov/28326850</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Dexketoprofen;
