within Pharmacolibrary.Drugs.R_RespiratorySystem.R03A_AdrenergicsInhalants.R03AC18_Indacaterol;

model Indacaterol
  extends Pharmacolibrary.Drugs.ATC.R.R03AC18;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>R03AC18</td></tr><td>route:</td><td>inhalation</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Indacaterol is a long-acting beta2-adrenergic agonist (LABA) indicated for the maintenance treatment of chronic obstructive pulmonary disease (COPD), including chronic bronchitis and/or emphysema. It is inhaled once daily as a bronchodilator and is approved for clinical use in many countries.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in healthy adult volunteers, both male and female, after single and multiple-dose inhalation.</p><h4>References</h4><ol><li><p>Demin, I, et al., &amp; Sechaud, R (2016). Population pharmacokinetics of IND/GLY (indacaterol/glycopyrronium) in COPD patients. <i>International journal of clinical pharmacology and therapeutics</i> 54(6) 405–415. DOI:<a href=\"https://doi.org/10.5414/CP202558\">10.5414/CP202558</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27049057/\">https://pubmed.ncbi.nlm.nih.gov/27049057</a></p></li><li><p>Bartels, C, et al., &amp; Vaidya, S (2021). Population Pharmacokinetic Analysis of Indacaterol/Glycopyrronium/Mometasone Furoate After Administration of Combination Therapies Using the Breezhaler. <i>European journal of drug metabolism and pharmacokinetics</i> 46(4) 487–504. DOI:<a href=\"https://doi.org/10.1007/s13318-021-00689-x\">10.1007/s13318-021-00689-x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34024035/\">https://pubmed.ncbi.nlm.nih.gov/34024035</a></p></li><li><p>Ren, S, et al., &amp; Zhao, R (2017). Pharmacokinetics and safety of indacaterol and glycopyrronium (IND/GLY) following repeated once daily inhalation from a fixed-dose combination in healthy Chinese subjects . <i>International journal of clinical pharmacology and therapeutics</i> 55(2) 147–155. DOI:<a href=\"https://doi.org/10.5414/CP202640\">10.5414/CP202640</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27841152/\">https://pubmed.ncbi.nlm.nih.gov/27841152</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Indacaterol;
