within Pharmacolibrary.Drugs.R_RespiratorySystem.R05C_ExpectorantsExclCombinationsWithCoughSuppressants;
package R05CA07_AntimonyPentasulfide
  extends Icons.Package;
end R05CA07_AntimonyPentasulfide;
