within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01C_AgentsAgainstLeishmaniasisAndTrypanosomiasis;
package P01CD02_Acetarsol
  extends Icons.Package;
end P01CD02_Acetarsol;
