within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M03B_MuscleRelaxantsCentrallyActingAgents;
package M03BB53_ChlorzoxazoneCombinationsExclPsy
  extends Icons.PackageDrugs;
end M03BB53_ChlorzoxazoneCombinationsExclPsy;
