within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AR18_EmtricitabineTenofovirAlafenamid
  extends Icons.PackageDrugs;
end J05AR18_EmtricitabineTenofovirAlafenamid;
