within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FF08_Prolgolimab
  extends Icons.Package;
end L01FF08_Prolgolimab;
