within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M05B_DrugsAffectingBoneStructureAndMineralization;
package M05BB03_AlendronicAcidAndColecal
  extends Icons.PackageDrugs;
end M05BB03_AlendronicAcidAndColecal;
