within Pharmacolibrary.Drugs.C_CardiovascularSystem.C05A_AgentsForTreatmentOfHemorrhoidsAndAnalFissuresFo;
package C05AE01_GlycerylTrinitrate
  extends Icons.PackageDrugs;
end C05AE01_GlycerylTrinitrate;
