within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M03B_MuscleRelaxantsCentrallyActingAgents;
package M03BB72_ChlormezanoneCombinationsWithPsy
  extends Icons.Package;
end M03BB72_ChlormezanoneCombinationsWithPsy;
