within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01E_SulfonamidesAndTrimethoprim;
package J01EE05_SulfadimidineAndTrimetho
  extends Icons.PackageDrugs;
end J01EE05_SulfadimidineAndTrimetho;
