within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AX15_CopperUsnate
  extends Icons.PackageDrugs;
end G01AX15_CopperUsnate;
