within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX02_PravastatinAndAcetylsali
  extends Icons.PackageDrugs;
end C10BX02_PravastatinAndAcetylsali;
