within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BA71_AcetylsalicylicAcidCombinationsW
  extends Icons.Package;
end N02BA71_AcetylsalicylicAcidCombinationsW;
