within Pharmacolibrary.Drugs.D_Dermatologicals.D07X_CorticosteroidsOtherCombinations;
package D07XB30_CorticosteroidsCombinationsEGBet
  extends Icons.Package;
end D07XB30_CorticosteroidsCombinationsEGBet;
