within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03C_AntispasmodicsInCombinationWithPsycholeptics;
package A03CA07_AmbutoniumAndPsycholeptics
  extends Icons.Package;
end A03CA07_AmbutoniumAndPsycholeptics;
