within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD09_PioglitazoneAndAloglipti
  extends Icons.PackageDrugs;
end A10BD09_PioglitazoneAndAloglipti;
