within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L02B_HormoneAntagonistsAndRelatedAgents.L02BG01_Aminoglutethimide;
model Aminoglutethimide = Pharmacolibrary.Drugs.ATC.L.L02BG01;