within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AB05_Propenidazole
  extends Icons.PackageDrugs;
end P01AB05_Propenidazole;
