within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AB05_Propenidazole
  extends Icons.Package;
end P01AB05_Propenidazole;
