within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01E_SulfonamidesAndTrimethoprim;
package J01EE05_SulfadimidineAndTrimethoprim
  extends Icons.Package;
end J01EE05_SulfadimidineAndTrimethoprim;
