within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis;
package A02BX12_BismuthSubnitrate
  extends Icons.PackageDrugs;
end A02BX12_BismuthSubnitrate;
