within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD23_MetforminAndErtugliflozin
  extends Icons.Package;
end A10BD23_MetforminAndErtugliflozin;
