within Pharmacolibrary.Drugs.S_SensoryOrgans.S03C_CorticosteroidsAndAntiinfectivesInCombination;
package S03CA05_FludrocortisoneAndAntiinfectives
  extends Icons.Package;
end S03CA05_FludrocortisoneAndAntiinfectives;
