within Pharmacolibrary.Drugs.C_CardiovascularSystem.C04A_PeripheralVasodilators.C04AF01_Kallidinogenase;

model Kallidinogenase
  extends Pharmacolibrary.Drugs.ATC.C.C04AF01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>C04AF01</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Kallidinogenase is an enzyme derived from animal pancreas, used primarily in certain Asian countries to treat peripheral vascular diseases and cerebrovascular disorders by facilitating vasodilation through the kinin–kallikrein system. It is not widely approved or used in the United States or Europe for these indications.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters for kallidinogenase in humans have not been reported in peer-reviewed publications. The following are estimated parameters based on general enzyme characteristics and dose regimens reported in clinical and therapeutic product information.</p><h4>References</h4><ol><li><p>Petrylak, DP, et al., &amp; Israel, RJ (2019). Phase 1 study of PSMA ADC, an antibody-drug conjugate targeting prostate-specific membrane antigen, in chemotherapy-refractory prostate cancer. <i>The Prostate</i> 79(6) 604–613. DOI:<a href=\"https://doi.org/10.1002/pros.23765\">10.1002/pros.23765</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30663074/\">https://pubmed.ncbi.nlm.nih.gov/30663074</a></p></li><li><p>Ning, YM, et al., &amp; Dahut, WL (2010). Phase II trial of bevacizumab, thalidomide, docetaxel, and prednisone in patients with metastatic castration-resistant prostate cancer. <i>Journal of clinical oncology : official journal of the American Society of Clinical Oncology</i> 28(12) 2070–2076. DOI:<a href=\"https://doi.org/10.1200/JCO.2009.25.4524\">10.1200/JCO.2009.25.4524</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/20308663/\">https://pubmed.ncbi.nlm.nih.gov/20308663</a></p></li><li><p>Rago, RP, et al., &amp; Dalton, WS (2003). Safety and efficacy of the MDR inhibitor Incel (biricodar, VX-710) in combination with mitoxantrone and prednisone in hormone-refractory prostate cancer. <i>Cancer chemotherapy and pharmacology</i> 51(4) 297–305. DOI:<a href=\"https://doi.org/10.1007/s00280-003-0573-4\">10.1007/s00280-003-0573-4</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/12721757/\">https://pubmed.ncbi.nlm.nih.gov/12721757</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Kallidinogenase;
