within Pharmacolibrary.Drugs.D_Dermatologicals.D07B_CorticosteroidsCombinationsWithAntiseptics;
package D07BC02_FluocinoloneAcetonideAndAntisept
  extends Icons.Package;
end D07BC02_FluocinoloneAcetonideAndAntisept;
