within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AA02_Clioquinol
  extends Icons.Package;
end P01AA02_Clioquinol;
