within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination;
package G03FA17_DrospirenoneAndEstrogen
  extends Icons.Package;
end G03FA17_DrospirenoneAndEstrogen;
