within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07C_BetaBlockingAgentsAndOtherDiuretics;
package C07CB02_MetoprololAndOtherDiuretics
  extends Icons.Package;
end C07CB02_MetoprololAndOtherDiuretics;
