within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01B_AntiinflammatoryAntirheumaticAgentsInCombination;
package M01BA03_AcetylsalicylicAcidAndCorticoste
  extends Icons.PackageDrugs;
end M01BA03_AcetylsalicylicAcidAndCorticoste;
