within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials;
package J01DE51_CefepimeAndBetaLactamaseInhibitor
  extends Icons.Package;
end J01DE51_CefepimeAndBetaLactamaseInhibitor;
