within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10A_InsulinsAndAnalogues;
package A10AD30_InsulinDegludecAndLiraglutide
  extends Icons.Package;
end A10AD30_InsulinDegludecAndLiraglutide;
