within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BA02_EncephalitisJapaneseInactivatedWholeVirus
  extends Icons.Package;
end J07BA02_EncephalitisJapaneseInactivatedWholeVirus;
