within Pharmacolibrary.Drugs.R_RespiratorySystem.R06A_AntihistaminesForSystemicUse.R06AB52_DexchlorpheniramineCombinations;
model DexchlorpheniramineCombinations = Pharmacolibrary.Drugs.ATC.R.R06AB52;