within Pharmacolibrary.Drugs.R_RespiratorySystem.R06A_AntihistaminesForSystemicUse;
package R06AB52_DexchlorpheniramineCombinations
  extends Icons.Package;
end R06AB52_DexchlorpheniramineCombinations;
