within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01D_VasodilatorsUsedInCardiacDiseases.C01DX19_Nesiritide;

model Nesiritide
  extends Pharmacolibrary.Drugs.ATC.C.C01DX19;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>C01DX19</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Nesiritide is a recombinant form of human B-type natriuretic peptide (BNP), used as a vasodilator for the treatment of acutely decompensated heart failure. It has been used in hospital settings for short-term intravenous therapy in patients with heart failure who have dyspnea at rest or with minimal activity. The drug is not commonly used today, as newer therapies have supplanted its use, and concerns have been raised about safety and efficacy.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported for adult heart failure patients following intravenous infusion.</p><h4>References</h4><ol><li><p>Trujillo, ME, et al., &amp; Gheyas, F (2022). Population Pharmacokinetics of Vericiguat in Patients With Heart Failure With Reduced Ejection Fraction: An Integrated Analysis. <i>Clinical pharmacology and therapeutics</i> 112(5) 1061–1069. DOI:<a href=\"https://doi.org/10.1002/cpt.2712\">10.1002/cpt.2712</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35841202/\">https://pubmed.ncbi.nlm.nih.gov/35841202</a></p></li><li><p>Bateman, RM, et al., &amp; Prandi, E (2016). 36th International Symposium on Intensive Care and Emergency Medicine : Brussels, Belgium. 15-18 March 2016. <i>Critical care (London, England)</i> 20(Suppl 2) 94–None. DOI:<a href=\"https://doi.org/10.1186/s13054-016-1208-6\">10.1186/s13054-016-1208-6</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27885969/\">https://pubmed.ncbi.nlm.nih.gov/27885969</a></p></li><li><p>Ait-Oudhia, S, et al., &amp; Gheyas, F (2025). Population Pharmacokinetic/Pharmacodynamic and Exposure-Response Modeling Analyses of Sotatercept in Healthy Participants and Patients with Pulmonary Arterial Hypertension. <i>Clinical pharmacology and therapeutics</i> 117(3) 798–807. DOI:<a href=\"https://doi.org/10.1002/cpt.3524\">10.1002/cpt.3524</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39668469/\">https://pubmed.ncbi.nlm.nih.gov/39668469</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Nesiritide;
