within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AR11_LamivudineTenofovirDisoproxilAnd
  extends Icons.Package;
end J05AR11_LamivudineTenofovirDisoproxilAnd;
