within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BB72_MetamizoleSodiumCombinationsWith
  extends Icons.PackageDrugs;
end N02BB72_MetamizoleSodiumCombinationsWith;
