within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01X_OtherAntineoplasticAgents.L01XY01_CytarabineAndDaunorubicin;

model CytarabineAndDaunorubicin
  extends Pharmacolibrary.Drugs.ATC.L.L01XY01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>L01XY01</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Cytarabine and daunorubicin is a combination chemotherapy regimen commonly used in the treatment of acute myeloid leukemia (AML). Cytarabine is an antimetabolite, and daunorubicin is an anthracycline; both act to inhibit cancer cell growth. The combination is a standard induction treatment in AML and is approved and widely used.</p><h4>Pharmacokinetics</h4><p>No specific published pharmacokinetic data for the fixed combination of cytarabine and daunorubicin (L01XY01) exist. The following parameters are estimates based on the known pharmacokinetics of the individual drugs in adult patients with AML, administered intravenously.</p><h4>References</h4><ol><li><p>Sonneveld, P, et al., &amp; Löwenberg, B (2000). Dose-finding study of valspodar (PSC 833) with daunorubicin and cytarabine to reverse multidrug resistance in elderly patients with previously untreated acute myeloid leukemia. <i>The hematology journal : the official journal of the European Haematology Association</i> 1(6) 411–421. DOI:<a href=\"https://doi.org/10.1038/sj.thj.6200050\">10.1038/sj.thj.6200050</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/11920222/\">https://pubmed.ncbi.nlm.nih.gov/11920222</a></p></li><li><p>Pefani, E, et al., &amp; Pistikopoulos, EN (2014). Chemotherapy drug scheduling for the induction treatment of patients with acute myeloid leukemia. <i>IEEE transactions on bio-medical engineering</i> 61(7) 2049–2056. DOI:<a href=\"https://doi.org/10.1109/TBME.2014.2313226\">10.1109/TBME.2014.2313226</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/24686224/\">https://pubmed.ncbi.nlm.nih.gov/24686224</a></p></li><li><p>Bouabdallah, R, et al., &amp; Fenaux, P (1999). A phase II trial of induction and consolidation therapy of acute myeloid leukemia with weekly oral idarubicin alone in poor risk elderly patients. <i>Leukemia</i> 13(10) 1491–1496. DOI:<a href=\"https://doi.org/10.1038/sj.leu.2401522\">10.1038/sj.leu.2401522</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/10516747/\">https://pubmed.ncbi.nlm.nih.gov/10516747</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end CytarabineAndDaunorubicin;
