within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02A_Antacids.A02AB02_Algeldrate;

model Algeldrate
  extends Pharmacolibrary.Drugs.ATC.A.A02AB02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Algeldrate</td></tr><tr><td>ATC code:</td><td>A02AB02</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Algeldrate (aluminum magnesium carbonate hydrate) is an antacid used to neutralize gastric acid in the stomach. It is employed in the symptomatic treatment of conditions such as dyspepsia and peptic ulcer disease, but is less commonly used today due to the availability of other antacids and acid-suppressing agents.</p><h4>Pharmacokinetics</h4><p>No published pharmacokinetic models or quantitative PK parameters for algeldrate are available in the scientific literature. As an antacid, algeldrate acts locally in the gastrointestinal tract and is not systemically absorbed.</p><h4>References</h4><ol><li><p>Masson, JD, et al., &amp; Gherardi, RK (2017). [Critical analysis of reference studies on aluminium-based adjuvants toxicokinetics]. <i>Annales pharmaceutiques francaises</i> 75(4) 245–256. DOI:<a href=\"https://doi.org/10.1016/j.pharma.2017.04.004\">10.1016/j.pharma.2017.04.004</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/28576261/\">https://pubmed.ncbi.nlm.nih.gov/28576261</a></p></li><li><p>Masson, JD, et al., &amp; Gherardi, RK (2018). Critical analysis of reference studies on the toxicokinetics of aluminum-based adjuvants. <i>Journal of inorganic biochemistry</i> 181 87–95. DOI:<a href=\"https://doi.org/10.1016/j.jinorgbio.2017.12.015\">10.1016/j.jinorgbio.2017.12.015</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29307441/\">https://pubmed.ncbi.nlm.nih.gov/29307441</a></p></li><li><p>Scott, G, et al., &amp; Rordorf, C (2004). Lack of effect of omeprazole or of an aluminium hydroxide/magnesium hydroxide antacid on the pharmacokinetics of lumiracoxib. <i>Clinical pharmacokinetics</i> 43(5) 341–348. DOI:<a href=\"https://doi.org/10.2165/00003088-200443050-00006\">10.2165/00003088-200443050-00006</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/15080766/\">https://pubmed.ncbi.nlm.nih.gov/15080766</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Algeldrate;
