within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P03A_EctoparasiticidesInclScabicides;
package P03AX06_BenzylAlcohol
  extends Icons.PackageDrugs;
end P03AX06_BenzylAlcohol;
