within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03X_OtherSexHormonesAndModulatorsOfTheGenitalSystem;
package G03XX01_Prasterone
  extends Icons.PackageDrugs;
end G03XX01_Prasterone;
