within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BD10_LansoprazoleAmoxicillinAndLevofloxacin
  extends Icons.Package;
end A02BD10_LansoprazoleAmoxicillinAndLevofloxacin;
