within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BH52_GemigliptinAndRosuvastatin
  extends Icons.Package;
end A10BH52_GemigliptinAndRosuvastatin;
