within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07B_ViralVaccines;
package J07BF03_PoliomyelitisTrivalentInactivatedWholeVirus
  extends Icons.Package;
end J07BF03_PoliomyelitisTrivalentInactivatedWholeVirus;
