within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AX01_Clodantoin
  extends Icons.Package;
end G01AX01_Clodantoin;
