within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01B_AntiinflammatoryAntirheumaticAgentsInCombination;
package M01BA02_DipyrocetylAndCorticoste
  extends Icons.PackageDrugs;
end M01BA02_DipyrocetylAndCorticoste;
