within Pharmacolibrary.Drugs.S_SensoryOrgans.S02C_CorticosteroidsAndAntiinfectivesInCombination;
package S02CA01_PrednisoloneAndAntiinfectives
  extends Icons.Package;
end S02CA01_PrednisoloneAndAntiinfectives;
