within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AG51_HaemophilusInfluenzaeBCombinatio
  extends Icons.PackageDrugs;
end J07AG51_HaemophilusInfluenzaeBCombinatio;
