within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BB54_PropyphenazoneCombinationsExclPs
  extends Icons.PackageDrugs;
end N02BB54_PropyphenazoneCombinationsExclPs;
