within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA04_HaemophilusInfluenzaeBAndPoliomy
  extends Icons.PackageDrugs;
end J07CA04_HaemophilusInfluenzaeBAndPoliomy;
