within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G02B_ContraceptivesForTopicalUse;
package G02BB01_VaginalRingWithProgestogenAndEstrogen
  extends Icons.Package;
end G02BB01_VaginalRingWithProgestogenAndEstrogen;
