within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AC04_Teclozan
  extends Icons.PackageDrugs;
end P01AC04_Teclozan;
