within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H01B_PosteriorPituitaryLobeHormones;
package H01BB02_Oxytocin
  extends Icons.PackageDrugs;
end H01BB02_Oxytocin;
