within Pharmacolibrary.Drugs.R_RespiratorySystem.R05C_ExpectorantsExclCombinationsWithCoughSuppressant;
package R05CA10_OxomemazineAndGuaifenesi
  extends Icons.PackageDrugs;
end R05CA10_OxomemazineAndGuaifenesi;
