within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L04A_Immunosuppressants;
package L04AA04_AntithymocyteImmunoglobulinRabbit
  extends Icons.Package;
end L04AA04_AntithymocyteImmunoglobulinRabbit;
