within Pharmacolibrary.Drugs.D_Dermatologicals.D11A_OtherDermatologicalPreparations.D11AC08_SulfurCompounds;

model SulfurCompounds
  extends Pharmacolibrary.Drugs.ATC.D.D11AC08;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>D11AC08</td></tr><td>route:</td><td>topical</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Sulfur compounds (ATC code D11AC08) refer primarily to preparations containing elemental sulfur for topical dermatologic use, mainly as a keratolytic and antiseptic in the treatment of acne, seborrheic dermatitis, and other skin conditions. Sulfur has also been historically used in scabicides. Currently, sulfur preparations are approved for topical use but are less frequently used due to more modern alternatives.</p><h4>Pharmacokinetics</h4><p>No published pharmacokinetic parameters are available for the topical administration of sulfur compounds in the dermatologic context. Due to the topical route, systemic absorption is minimal and systemic pharmacokinetics are negligible; estimates below are standard for topical drugs with low percutaneous absorption.</p><h4>References</h4><ol><li><p>Schmitz, K, et al., &amp; Behrens-Baumann, W (1999). Population pharmacokinetics of 2% topical dorzolamide in the aqueous humor of humans. <i>Investigative ophthalmology &amp; visual science</i> 40(7) 1621–1624. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/10359348/\">https://pubmed.ncbi.nlm.nih.gov/10359348</a></p></li><li><p>Pickert, A, &amp; Raimer, S (2009). An evaluation of dapsone gel 5% in the treatment of acne vulgaris. <i>Expert opinion on pharmacotherapy</i> 10(9) 1515–1521. DOI:<a href=\"https://doi.org/10.1517/14656560903002097\">10.1517/14656560903002097</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/19505219/\">https://pubmed.ncbi.nlm.nih.gov/19505219</a></p></li><li><p>Stotland, M, et al., &amp; Kissling, RF (2009). Dapsone 5% gel: a review of its efficacy and safety in the treatment of acne vulgaris. <i>American journal of clinical dermatology</i> 10(4) 221–227. DOI:<a href=\"https://doi.org/10.2165/00128071-200910040-00002\">10.2165/00128071-200910040-00002</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/19489655/\">https://pubmed.ncbi.nlm.nih.gov/19489655</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end SulfurCompounds;
