within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BE74_BucetinCombinationsWithPsycholep
  extends Icons.Package;
end N02BE74_BucetinCombinationsWithPsycholep;
