within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BE71_ParacetamolCombinationsWithPsych
  extends Icons.PackageDrugs;
end N02BE71_ParacetamolCombinationsWithPsych;
