within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03C_AntispasmodicsInCombinationWithPsycholeptics;
package A03CA05_GlycopyrroniumBromideAnd
  extends Icons.PackageDrugs;
end A03CA05_GlycopyrroniumBromideAnd;
