within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AF16_Omoconazole
  extends Icons.PackageDrugs;
end G01AF16_Omoconazole;
