within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX10_RosuvastatinAndValsartan
  extends Icons.PackageDrugs;
end C10BX10_RosuvastatinAndValsartan;
