within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M03B_MuscleRelaxantsCentrallyActingAgents;
package M03BA71_PhenprobamateCombination
  extends Icons.PackageDrugs;
end M03BA71_PhenprobamateCombination;
