within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B03A_IronPreparations.B03AA07_FerrousSulfate;

model FerrousSulfate
  extends Pharmacolibrary.Drugs.ATC.B.B03AA07;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>B03AA07</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Ferrous sulfate is an iron supplement used to treat or prevent low blood levels of iron (such as those caused by anemia or during pregnancy). It is commonly prescribed for iron-deficiency anemia and is available in oral formulations. Ferrous sulfate is a well-established and widely used medication approved in many countries.</p><h4>Pharmacokinetics</h4><p>Typical pharmacokinetics in healthy adults (non-pregnant, both sexes). PK parameters may vary in special populations (e.g., pregnant women, patients with gastrointestinal disease).</p><h4>References</h4><ol><li><p>Leary, A, et al., &amp; Brunner, V (2016). Pharmacokinetics of Ferrous Sulphate (Tardyferon®) after Single Oral Dose Administration in Women with Iron Deficiency Anaemia. <i>Drug research</i> 66(1) 51–56. DOI:<a href=\"https://doi.org/10.1055/s-0035-1549934\">10.1055/s-0035-1549934</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25989284/\">https://pubmed.ncbi.nlm.nih.gov/25989284</a></p></li><li><p>Leary, A, et al., &amp; Edmond, JM (2017). Iron Pharmacokinetics in Women with Iron Deficiency Anaemia Following A Single Oral Dose of a Novel Formulation of Tardyferon (Prolonged Release Ferrous Sulphate). <i>Drug research</i> 67(11) 647–652. DOI:<a href=\"https://doi.org/10.1055/s-0043-113636\">10.1055/s-0043-113636</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/28724166/\">https://pubmed.ncbi.nlm.nih.gov/28724166</a></p></li><li><p>Troesch, B, et al., &amp; Zimmermann, MB (2011). Fortification iron as ferrous sulfate plus ascorbic acid is more rapidly absorbed than as sodium iron EDTA but neither increases serum nontransferrin-bound iron in women. <i>The Journal of nutrition</i> 141(5) 822–827. DOI:<a href=\"https://doi.org/10.3945/jn.110.136127\">10.3945/jn.110.136127</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/21430252/\">https://pubmed.ncbi.nlm.nih.gov/21430252</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end FerrousSulfate;
