within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics.N02BG06_Nefopam;

model Nefopam_1
  extends Pharmacolibrary.Drugs.ATC.N.N02BG06_1;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>N02BG06_1</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Nefopam is a centrally-acting non-opioid analgesic used for the relief of moderate to severe pain. It is unrelated chemically to NSAIDs or opioids and acts by inhibiting the reuptake of serotonin, norepinephrine, and dopamine. Nefopam is used in some countries for acute and chronic pain management but is not approved in the United States.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetics after single intravenous bolus in healthy adults.</p><h4>References</h4><ol><li><p>Djerada, Z, et al., &amp; Malinovsky, JM (2014). Population pharmacokinetics of nefopam in elderly, with or without renal impairment, and its link to treatment response. <i>British journal of clinical pharmacology</i> 77(6) 1027–1038. DOI:<a href=\"https://doi.org/10.1111/bcp.12291\">10.1111/bcp.12291</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/24252055/\">https://pubmed.ncbi.nlm.nih.gov/24252055</a></p></li><li><p>Mimoz, O, et al., &amp; Levy, RH (2010). Nefopam pharmacokinetics in patients with end-stage renal disease. <i>Anesthesia and analgesia</i> 111(5) 1146–1153. DOI:<a href=\"https://doi.org/10.1213/ANE.0b013e3181f33488\">10.1213/ANE.0b013e3181f33488</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/20971961/\">https://pubmed.ncbi.nlm.nih.gov/20971961</a></p></li><li><p>Mittur, A (2018). A Simultaneous Mixed-Effects Pharmacokinetic Model for Nefopam, N-desmethylnefopam, and Nefopam N-Oxide in Human Plasma and Urine. <i>European journal of drug metabolism and pharmacokinetics</i> 43(4) 391–404. DOI:<a href=\"https://doi.org/10.1007/s13318-017-0457-3\">10.1007/s13318-017-0457-3</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29305813/\">https://pubmed.ncbi.nlm.nih.gov/29305813</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Nefopam_1;
