within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombination;
package S01CA07_FluorometholoneAndAntiinfectives
  extends Icons.Package;
end S01CA07_FluorometholoneAndAntiinfectives;
