within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DX08_TelmisartanAmlodipineAndHydrochl
  extends Icons.PackageDrugs;
end C09DX08_TelmisartanAmlodipineAndHydrochl;
