within Pharmacolibrary.Drugs.S_SensoryOrgans.S02C_CorticosteroidsAndAntiinfectivesInCombination;
package S02CA03_HydrocortisoneAndAntiinfectives
  extends Icons.Package;
end S02CA03_HydrocortisoneAndAntiinfectives;
