within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03A_DrugsForFunctionalGastrointestinalDisorders;
package A03AX58_AlverineCombinations
  extends Icons.Package;
end A03AX58_AlverineCombinations;
