within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03C_AntispasmodicsInCombinationWithPsycholeptics;
package A03CB04_HomatropineMethylbromide
  extends Icons.PackageDrugs;
end A03CB04_HomatropineMethylbromide;
