within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AA06_Hachimycin
  extends Icons.Package;
end G01AA06_Hachimycin;
