within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01R_CombinationsOfAntibacterials;
package J01RA12_CiprofloxacinAndOrnidazole
  extends Icons.Package;
end J01RA12_CiprofloxacinAndOrnidazole;
