within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins;
package H02B_CorticosteroidsForSystemicUseCombinations
  extends Icons.PackageDrugs;
end H02B_CorticosteroidsForSystemicUseCombinations;
