within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03E_DiureticsAndPotassiumSparingAgentsInCombination;
package C03EB02_BumetanideAndPotassiumSp
  extends Icons.PackageDrugs;
end C03EB02_BumetanideAndPotassiumSp;
