within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DA07_TelmisartanAndDiuretics
  extends Icons.Package;
end C09DA07_TelmisartanAndDiuretics;
