within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AA18_DrospirenoneAndEstetrol
  extends Icons.Package;
end G03AA18_DrospirenoneAndEstetrol;
