within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DX07_IrbesartanAmlodipineAndH
  extends Icons.PackageDrugs;
end C09DX07_IrbesartanAmlodipineAndH;
