within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01D_VasodilatorsUsedInCardiacDiseases;
package C01DA55_PentaerithritylTetranitrateCombinations
  extends Icons.Package;
end C01DA55_PentaerithritylTetranitrateCombinations;
