within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P03B_InsecticidesAndRepellents;
package P03BX03_Dibutylphthalate
  extends Icons.PackageDrugs;
end P03BX03_Dibutylphthalate;
