within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01B_Antimalarials;
package P01BF09_ArtesunateSulfadoxineAndPyrimethamine
  extends Icons.Package;
end P01BF09_ArtesunateSulfadoxineAndPyrimethamine;
