within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonSteroids.M01AE09_Flurbiprofen;

model Flurbiprofen
  extends Pharmacolibrary.Drugs.ATC.M.M01AE09;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>M01AE09</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Flurbiprofen is a nonsteroidal anti-inflammatory drug (NSAID) primarily used for the treatment of inflammation and pain associated with conditions such as rheumatoid arthritis and osteoarthritis. It has analgesic, anti-inflammatory, and antipyretic properties. The drug is approved and used in clinical practice for acute and chronic pain management, as well as in the treatment of inflammatory disorders.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported for healthy adult subjects following oral administration.</p><h4>References</h4><ol><li><p>Qayyum, A, et al., &amp; Farooqi, ZU (2011). Determination of pharmacokinetics of flurbiprofen in Pakistani population using modified HPLC method. <i>Journal of chromatographic science</i> 49(2) 108–113. DOI:<a href=\"https://doi.org/10.1093/chrsci/49.2.108\">10.1093/chrsci/49.2.108</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/21223634/\">https://pubmed.ncbi.nlm.nih.gov/21223634</a></p></li><li><p>Lee, YJ, et al., &amp; Lee, SY (2015). Effects of CYP2C9*1/*3 genotype on the pharmacokinetics of flurbiprofen in Korean subjects. <i>Archives of pharmacal research</i> 38(6) 1232–1237. DOI:<a href=\"https://doi.org/10.1007/s12272-015-0580-0\">10.1007/s12272-015-0580-0</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25712887/\">https://pubmed.ncbi.nlm.nih.gov/25712887</a></p></li><li><p>Kumpulainen, E, et al., &amp; Kokki, H (2010). Plasma and cerebrospinal fluid pharmacokinetics of flurbiprofen in children. <i>British journal of clinical pharmacology</i> 70(4) 557–566. DOI:<a href=\"https://doi.org/10.1111/j.1365-2125.2010.03720.x\">10.1111/j.1365-2125.2010.03720.x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/20840447/\">https://pubmed.ncbi.nlm.nih.gov/20840447</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Flurbiprofen;
