within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents;
package P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases
  extends Icons.Package;
end P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
