within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents;
package P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases
  extends Icons.PackageDrugs;
end P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
