within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01D_VasodilatorsUsedInCardiacDiseases;
package C01DA63_EritritylTetranitrateCombinations
  extends Icons.Package;
end C01DA63_EritritylTetranitrateCombinations;
