within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H05A_ParathyroidHormonesAndAnalogues;
package H05AA04_Abaloparatide
  extends Icons.Package;
end H05AA04_Abaloparatide;
