within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DA03_ValsartanAndDiuretics
  extends Icons.PackageDrugs;
end C09DA03_ValsartanAndDiuretics;
