within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03E_DiureticsAndPotassiumSparingAgentsInCombination;
package C03EA12_MetolazoneAndPotassiumSparingAgents
  extends Icons.Package;
end C03EA12_MetolazoneAndPotassiumSparingAgents;
