within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AR05_ZidovudineLamivudineAndNevirapine
  extends Icons.Package;
end J05AR05_ZidovudineLamivudineAndNevirapine;
