within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonSteroids;
package M01AB55_DiclofenacCombinations
  extends Icons.Package;
end M01AB55_DiclofenacCombinations;
