within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonStero;
package M01AE51_IbuprofenCombinations
  extends Icons.PackageDrugs;
end M01AE51_IbuprofenCombinations;
