within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AX06_Furazolidone
  extends Icons.Package;
end G01AX06_Furazolidone;
