within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02L_AntihypertensivesAndDiureticsInCombination;
package C02LA51_ReserpineAndDiureticsCombination
  extends Icons.Package;
end C02LA51_ReserpineAndDiureticsCombination;
