within Pharmacolibrary.Drugs.R_RespiratorySystem.R06A_AntihistaminesForSystemicUse.R06AX13_Loratadine;

model Loratadine
  extends Pharmacolibrary.Drugs.ATC.R.R06AX13;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Loratadine</td></tr><tr><td>ATC code:</td><td>R06AX13</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Loratadine is a second-generation, non-sedating antihistamine used to relieve symptoms of allergy such as sneezing, runny nose, and itchy eyes. It is commonly prescribed for the treatment of allergic rhinitis and urticaria, and is approved for use in many countries worldwide.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported for healthy adult volunteers, both male and female, following single oral dose.</p><h4>References</h4><ol><li><p>Liu, T, et al., &amp; Liu, X (2024). Simultaneously Predicting Pharmacokinetics of Loratadine and Desloratadine in Children Using a Whole-Body Physiologically Based Pharmacokinetic Model. <i>Journal of clinical pharmacology</i> None –. DOI:<a href=\"https://doi.org/10.1002/jcph.6120\">10.1002/jcph.6120</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39171895/\">https://pubmed.ncbi.nlm.nih.gov/39171895</a></p></li><li><p>Salem, II, et al., &amp; Idkaidek, NM (2010). A retrospective, open-label analysis of the population pharmacokinetics of a single 10-mg dose of loratadine in healthy white Jordanian male volunteers. <i>Clinical therapeutics</i> 32(2) 391–395. DOI:<a href=\"https://doi.org/10.1016/j.clinthera.2010.02.001\">10.1016/j.clinthera.2010.02.001</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/20206796/\">https://pubmed.ncbi.nlm.nih.gov/20206796</a></p></li><li><p>Zhang, YF, et al., &amp; Dong, YM (2003). Pharmacokinetics of loratadine and its active metabolite descarboethoxyloratadine in healthy Chinese subjects. <i>Acta pharmacologica Sinica</i> 24(7) 715–718. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/12852841/\">https://pubmed.ncbi.nlm.nih.gov/12852841</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Loratadine;
