within Pharmacolibrary.Drugs.N_NervousSystem.N03A_Antiepileptics.N03AE01_Clonazepam;

model Clonazepam
  extends Pharmacolibrary.Drugs.ATC.N.N03AE01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Clonazepam</td></tr><tr><td>ATC code:</td><td>N03AE01</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Clonazepam is a benzodiazepine anticonvulsant used primarily for the treatment of epilepsy, panic disorders, and sometimes for movement disorders. It enhances the activity of gamma-aminobutyric acid (GABA) and is approved for use in many countries including the US.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters determined in healthy adult subjects after single oral dose administration.</p><h4>References</h4><ol><li><p>Kruizinga, MD, et al., &amp; van Esdonk, MJ (2022). Population pharmacokinetics of clonazepam in saliva and plasma: Steps towards noninvasive pharmacokinetic studies in vulnerable populations. <i>British journal of clinical pharmacology</i> 88(5) 2236–2245. DOI:<a href=\"https://doi.org/10.1111/bcp.15152\">10.1111/bcp.15152</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34811788/\">https://pubmed.ncbi.nlm.nih.gov/34811788</a></p></li><li><p>dos Santos, FM, et al., &amp; Noël, F (2009). Pharmacokinetic/pharmacodynamic modeling of psychomotor impairment induced by oral clonazepam in healthy volunteers. <i>Therapeutic drug monitoring</i> 31(5) 566–574. DOI:<a href=\"https://doi.org/10.1097/FTD.0b013e3181b1dd76\">10.1097/FTD.0b013e3181b1dd76</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/19730280/\">https://pubmed.ncbi.nlm.nih.gov/19730280</a></p></li><li><p>Genis-Najera, L, &amp; Sañudo-Maury, ME (2024). Bioequivalence Study of Two Tablet Formulations of Clonazepam 2 mg: A Randomized, Open-Label, Crossover Study in Healthy Mexican Volunteers Under Fasting Conditions. <i>Neurology and therapy</i> 13(1) 141–152. DOI:<a href=\"https://doi.org/10.1007/s40120-023-00567-5\">10.1007/s40120-023-00567-5</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/38041794/\">https://pubmed.ncbi.nlm.nih.gov/38041794</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Clonazepam;
