within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins.J01CA51_AmpicillinCombinations;
model AmpicillinCombinations = Pharmacolibrary.Drugs.ATC.J.J01CA51;