within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA08_HaemophilusInfluenzaeBAndHepatit
  extends Icons.PackageDrugs;
end J07CA08_HaemophilusInfluenzaeBAndHepatit;
