within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01B_Antimetabolites.L01BC07_Azacitidine;

model Azacitidine
  extends Pharmacolibrary.Drugs.ATC.L.L01BC07;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Azacitidine</td></tr><tr><td>ATC code:</td><td>L01BC07</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Azacitidine is a nucleoside metabolic inhibitor with antineoplastic activity, primarily used in the treatment of myelodysplastic syndromes (MDS) and certain types of acute myeloid leukemia (AML). It acts by incorporation into DNA and RNA, resulting in cytotoxicity and inhibition of DNA methyltransferase. Azacitidine is approved for clinical use and is currently used in therapy.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported for adult patients with myelodysplastic syndromes after subcutaneous and intravenous administration of azacitidine.</p><h4>References</h4><ol><li><p>Watts, JM, et al., &amp; Cortes, JE (2023). Olutasidenib alone or with azacitidine in IDH1-mutated acute myeloid leukaemia and myelodysplastic syndrome: phase 1 results of a phase 1/2 trial. <i>The Lancet. Haematology</i> 10(1) e46–e58. DOI:<a href=\"https://doi.org/10.1016/S2352-3026(22)00292-7\">10.1016/S2352-3026(22)00292-7</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36370742/\">https://pubmed.ncbi.nlm.nih.gov/36370742</a></p></li><li><p>DiNardo, CD, et al., &amp; Pollyea, DA (2018). Safety and preliminary efficacy of venetoclax with decitabine or azacitidine in elderly patients with previously untreated acute myeloid leukaemia: a non-randomised, open-label, phase 1b study. <i>The Lancet. Oncology</i> 19(2) 216–228. DOI:<a href=\"https://doi.org/10.1016/S1470-2045(18)30010-X\">10.1016/S1470-2045(18)30010-X</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29339097/\">https://pubmed.ncbi.nlm.nih.gov/29339097</a></p></li><li><p>Ikezoe, T, et al., &amp; Yamauchi, T (2023). Cusatuzumab plus azacitidine in Japanese patients with newly diagnosed acute myeloid leukemia ineligible for intensive treatment. <i>Cancer science</i> 114(3) 1037–1044. DOI:<a href=\"https://doi.org/10.1111/cas.15663\">10.1111/cas.15663</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36394119/\">https://pubmed.ncbi.nlm.nih.gov/36394119</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Azacitidine;
