within Pharmacolibrary.Drugs.V_Various.V09H_InflammationAndInfectionDetection;
package V09HB02_Indium111inTropolonateLabelledCe
  extends Icons.PackageDrugs;
end V09HB02_Indium111inTropolonateLabelledCe;
