within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD08_MetforminAndVildagliptin
  extends Icons.Package;
end A10BD08_MetforminAndVildagliptin;
