within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01D_VasodilatorsUsedInCardiacDiseases;
package C01DX51_ItraminTosilateCombinati
  extends Icons.PackageDrugs;
end C01DX51_ItraminTosilateCombinati;
