within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09B_AceInhibitorsCombinations;
package C09BX03_RamiprilAmlodipineAndHydrochloro
  extends Icons.PackageDrugs;
end C09BX03_RamiprilAmlodipineAndHydrochloro;
