within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FG01_Bevacizumab
  extends Icons.Package;
end L01FG01_Bevacizumab;
