within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals.J05AB16_Remdesivir;

model Remdesivir
  extends Pharmacolibrary.Drugs.ATC.J.J05AB16;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>J05AB16</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Remdesivir is a broad-spectrum antiviral medication that inhibits viral RNA-dependent RNA polymerase. It was originally developed for the treatment of Ebola virus, but is more widely used today for the treatment of COVID-19 in hospitalized patients. Remdesivir is approved or authorized in many countries as a treatment for COVID-19.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters in healthy adult subjects following single intravenous dose administration.</p><h4>References</h4><ol><li><p>Walimbwa, SI, et al., &amp; Lamorde, M (2021). An open-label, randomized, single intravenous dosing study to investigate the effect of fixed-dose combinations of tenofovir/lamivudine or atazanavir/ritonavir on the pharmacokinetics of remdesivir in Ugandan healthy volunteers (RemTLAR). <i>Trials</i> 22(1) 831–None. DOI:<a href=\"https://doi.org/10.1186/s13063-021-05752-1\">10.1186/s13063-021-05752-1</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34814933/\">https://pubmed.ncbi.nlm.nih.gov/34814933</a></p></li><li><p>Ahmed, A, et al., &amp; Rojo, P (2024). Remdesivir for COVID-19 in Hospitalized Children: A Phase 2/3 Study. <i>Pediatrics</i> 153(3) –. DOI:<a href=\"https://doi.org/10.1542/peds.2023-063775\">10.1542/peds.2023-063775</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/38332740/\">https://pubmed.ncbi.nlm.nih.gov/38332740</a></p></li><li><p>Coggins, SJ, et al., &amp; Kimble, B (2025). Pharmacokinetics of GS-441524 following intravenous remdesivir in six cats and results of therapeutic drug monitoring during treatment of feline infectious peritonitis: 22 cases (2021-2024). <i>The Journal of small animal practice</i> None –. DOI:<a href=\"https://doi.org/10.1111/jsap.13849\">10.1111/jsap.13849</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/40097914/\">https://pubmed.ncbi.nlm.nih.gov/40097914</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Remdesivir;
