within Pharmacolibrary.Drugs.V_Various.V01A_Allergens.V01AA11_Animals;

model Animals
  extends Pharmacolibrary.Drugs.ATC.V.V01AA11;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Animals</td></tr><tr><td>ATC code:</td><td>V01AA11</td></tr><td>route:</td><td></td></tr><tr><td>n-compartments</td><td>0</td></tr></table><p>ATC code V01AA11 corresponds to allergens of animal origin used for diagnostic purposes, such as in allergen extracts for skin testing in suspected allergies. These are not conventional drugs but biological extracts derived from animal tissues. Such products are used for identifying allergic sensitivities and are generally not used therapeutically. They are approved and regulated for diagnostic use.</p><h4>Pharmacokinetics</h4><p>No published pharmacokinetic (PK) data available for allergens of animal origin classified under ATC code V01AA11. These agents are protein extracts used in very small and variable doses for diagnostic testing, not for systemic pharmacological effect. Thus, conventional PK parameters such as clearance, volume of distribution, bioavailability, and absorption rates are not established or typically reported.</p><h4>References</h4><ol><li><p>Sheiner, LB, &amp; Ludden, TM (1992). Population pharmacokinetics/dynamics. <i>Annual review of pharmacology and toxicology</i> 32 185–209. DOI:<a href=\"https://doi.org/10.1146/annurev.pa.32.040192.001153\">10.1146/annurev.pa.32.040192.001153</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/1605567/\">https://pubmed.ncbi.nlm.nih.gov/1605567</a></p></li><li><p>Grant, DM (1991). Detoxification pathways in the liver. <i>Journal of inherited metabolic disease</i> 14(4) 421–430. DOI:<a href=\"https://doi.org/10.1007/BF01797915\">10.1007/BF01797915</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/1749210/\">https://pubmed.ncbi.nlm.nih.gov/1749210</a></p></li><li><p>Keizer, RJ, et al., &amp; Beijnen, JH (2010). Clinical pharmacokinetics of therapeutic monoclonal antibodies. <i>Clinical pharmacokinetics</i> 49(8) 493–507. DOI:<a href=\"https://doi.org/10.2165/11531280-000000000-00000\">10.2165/11531280-000000000-00000</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/20608753/\">https://pubmed.ncbi.nlm.nih.gov/20608753</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Animals;
