within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02L_AntihypertensivesAndDiureticsInCombination;
package C02LA50_CombinationOfRauwolfiaAlkaloidsA
  extends Icons.Package;
end C02LA50_CombinationOfRauwolfiaAlkaloidsA;
