within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03E_DiureticsAndPotassiumSparingAgentsInCombination;
package C03EA03_EpitizideAndPotassiumSparingAgents
  extends Icons.Package;
end C03EA03_EpitizideAndPotassiumSparingAgents;
