within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins;
package J01CE08_BenzathineBenzylpenicill
  extends Icons.PackageDrugs;
end J01CE08_BenzathineBenzylpenicill;
