within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01X_OtherAntineoplasticAgents;
package L01XD03_MethylAminolevulinate
  extends Icons.PackageDrugs;
end L01XD03_MethylAminolevulinate;
