within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AD01_LacticAcid
  extends Icons.Package;
end G01AD01_LacticAcid;
