within Pharmacolibrary.Drugs.N_NervousSystem.N04B_DopaminergicAgents;
package N04BA03_LevodopaDecarboxylaseInhibitorAndComtInhibitor
  extends Icons.Package;
end N04BA03_LevodopaDecarboxylaseInhibitorAndComtInhibitor;
