within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J04A_DrugsForTreatmentOfTuberculosis;
package J04AA02_SodiumAminosalicylate
  extends Icons.PackageDrugs;
end J04AA02_SodiumAminosalicylate;
