within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AP58_DaclatasvirAsunaprevirAndBeclabu
  extends Icons.PackageDrugs;
end J05AP58_DaclatasvirAsunaprevirAndBeclabu;
