within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A11C_VitaminAAndDInclCombinationsOfTheTwo;
package A11CC02_Dihydrotachysterol
  extends Icons.PackageDrugs;
end A11CC02_Dihydrotachysterol;
