within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AA16_DienogestAndEthinylestra
  extends Icons.PackageDrugs;
end G03AA16_DienogestAndEthinylestra;
