within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M05B_DrugsAffectingBoneStructureAndMineralization;
package M05BB05_AlendronicAcidCalciumAnd
  extends Icons.PackageDrugs;
end M05BB05_AlendronicAcidCalciumAnd;
