within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AG52_HaemophilusInfluenzaeBCombinationsWithPertussisAndToxoids
  extends Icons.Package;
end J07AG52_HaemophilusInfluenzaeBCombinationsWithPertussisAndToxoids;
