within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01C_AgentsAgainstLeishmaniasisAndTrypanosomiasis.P01CC01_Nifurtimox;

model Nifurtimox
  extends Pharmacolibrary.Drugs.ATC.P.P01CC01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Nifurtimox</td></tr><tr><td>ATC code:</td><td>P01CC01</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Nifurtimox is a nitrofuran derivative used primarily for the treatment of Chagas disease (American trypanosomiasis), caused by Trypanosoma cruzi. It has antiparasitic activity and is sometimes used off-label for other trypanosomal diseases. Nifurtimox has been approved for use in several countries, but is often reserved for cases where benznidazole is not available or appropriate.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters in healthy adults after oral administration; data primarily from non-compartmental and compartmental PK studies.</p><h4>References</h4><ol><li><p>Amilon, C, et al., &amp; Jansson-Löfmark, R (2022). Population Pharmacodynamic Modeling of Eflornithine-Based Treatments Against Late-Stage Gambiense Human African Trypanosomiasis and Efficacy Predictions of L-eflornithine-Based Therapy. <i>The AAPS journal</i> 24(3) 48–None. DOI:<a href=\"https://doi.org/10.1208/s12248-022-00693-2\">10.1208/s12248-022-00693-2</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35338410/\">https://pubmed.ncbi.nlm.nih.gov/35338410</a></p></li><li><p>Del Moral Sanchez, JM, et al., &amp; Bermejo, M (2018). Biopharmaceutical optimization in neglected diseases for paediatric patients by applying the provisional paediatric biopharmaceutical classification system. <i>British journal of clinical pharmacology</i> 84(10) 2231–2241. DOI:<a href=\"https://doi.org/10.1111/bcp.13650\">10.1111/bcp.13650</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29846973/\">https://pubmed.ncbi.nlm.nih.gov/29846973</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Nifurtimox;
