within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01C_AgentsAgainstLeishmaniasisAndTrypanosomiasis;
package P01CC01_Nifurtimox
  extends Icons.PackageDrugs;
end P01CC01_Nifurtimox;
