within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX11_AtorvastatinAmlodipineAn
  extends Icons.PackageDrugs;
end C10BX11_AtorvastatinAmlodipineAn;
