within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BB51_PhenazoneCombinationsExclPsychol
  extends Icons.Package;
end N02BB51_PhenazoneCombinationsExclPsychol;
