within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01R_CombinationsOfAntibacterials;
package J01RA05_LevofloxacinAndOrnidazole
  extends Icons.Package;
end J01RA05_LevofloxacinAndOrnidazole;
