within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates.L01FX05_BrentuximabVedotin;

model BrentuximabVedotin
  extends Pharmacolibrary.Drugs.ATC.L.L01FX05;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>L01FX05</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Brentuximab vedotin is an antibody-drug conjugate targeting CD30, used primarily for the treatment of Hodgkin lymphoma and systemic anaplastic large cell lymphoma. It is approved and widely used in current clinical practice for relapsed or refractory cases and for some front-line regimens.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetics reported in adult patients with malignant lymphomas, following single and multiple intravenous infusions.</p><h4>References</h4><ol><li><p>Zhang, D, et al., &amp; Chia, YL (2024). Time-varying brentuximab vedotin pharmacokinetics and weight-based dosing in paediatric patients despite lower exposure in those aged 2 to &lt;6 and 6-11 years. <i>British journal of clinical pharmacology</i> 90(9) 2299–2313. DOI:<a href=\"https://doi.org/10.1111/bcp.16128\">10.1111/bcp.16128</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/38866401/\">https://pubmed.ncbi.nlm.nih.gov/38866401</a></p></li><li><p>Song, Y, et al., &amp; Zhu, J (2021). Phase II single-arm study of brentuximab vedotin in Chinese patients with relapsed/refractory classical Hodgkin lymphoma or systemic anaplastic large cell lymphoma. <i>Expert review of hematology</i> 14(9) 867–875. DOI:<a href=\"https://doi.org/10.1080/17474086.2021.1942831\">10.1080/17474086.2021.1942831</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34275403/\">https://pubmed.ncbi.nlm.nih.gov/34275403</a></p></li><li><p>Koga, Y, et al., &amp; Horibe, K (2020). Phase I study of brentuximab vedotin (SGN-35) in Japanese children with relapsed or refractory CD30-positive Hodgkin&#x27;s lymphoma or systemic anaplastic large cell lymphoma. <i>International journal of hematology</i> 111(5) 711–718. DOI:<a href=\"https://doi.org/10.1007/s12185-020-02820-1\">10.1007/s12185-020-02820-1</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31960285/\">https://pubmed.ncbi.nlm.nih.gov/31960285</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end BrentuximabVedotin;
