within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX05_BrentuximabVedotin
  extends Icons.PackageDrugs;
end L01FX05_BrentuximabVedotin;
