within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01R_CombinationsOfAntibacterials;
package J01RA03_CefuroximeAndMetronidazo
  extends Icons.PackageDrugs;
end J01RA03_CefuroximeAndMetronidazo;
