within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombina;
package S01CA02_PrednisoloneAndAntiinfec
  extends Icons.PackageDrugs;
end S01CA02_PrednisoloneAndAntiinfec;
