within Pharmacolibrary.Drugs.D_Dermatologicals.D01A_AntifungalsForTopicalUse;
package D01AE20_CiclopiroxAndZincPyrithioneCombination
  extends Icons.Package;
end D01AE20_CiclopiroxAndZincPyrithioneCombination;
