within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BA51_AcetylsalicylicAcidCombinationsE
  extends Icons.PackageDrugs;
end N02BA51_AcetylsalicylicAcidCombinationsE;
