within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AF02_Clotrimazole
  extends Icons.Package;
end G01AF02_Clotrimazole;
