within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX15_BelantamabMafodotin
  extends Icons.PackageDrugs;
end L01FX15_BelantamabMafodotin;
