within Pharmacolibrary.Drugs.R_RespiratorySystem.R03D_OtherSystemicDrugsForObstructiveAirwayDiseases;
package R03DA20_CombinationsOfXanthines
  extends Icons.Package;
end R03DA20_CombinationsOfXanthines;
