within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BC04_Rabeprazole
  extends Icons.Package;
end A02BC04_Rabeprazole;
