within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AC01_Diiodohydroxyquinoline
  extends Icons.Package;
end G01AC01_Diiodohydroxyquinoline;
