within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B02B_VitaminKAndOtherHemostatics;
package B02BD03_FactorViiiInhibitorBypassingActivity
  extends Icons.Package;
end B02BD03_FactorViiiInhibitorBypassingActivity;
