within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B03A_IronPreparations;
package B03AD01_FerrousAminoAcidComplexAndFolicAcid
  extends Icons.Package;
end B03AD01_FerrousAminoAcidComplexAndFolicAcid;
