within Pharmacolibrary.Drugs.V_Various.V09H_InflammationAndInfectionDetection;
package V09HA02_Technetium99mtcExametazimeLabelledCells
  extends Icons.Package;
end V09HA02_Technetium99mtcExametazimeLabelledCells;
