within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01R_CombinationsOfAntibacterials;
package J01RA03_CefuroximeAndMetronidazole
  extends Icons.Package;
end J01RA03_CefuroximeAndMetronidazole;
