within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01X_OtherAntineoplasticAgents;
package L01XL03_AxicabtageneCiloleucel
  extends Icons.Package;
end L01XL03_AxicabtageneCiloleucel;
