within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BD05_OmeprazoleAmoxicillinAndClarithr
  extends Icons.Package;
end A02BD05_OmeprazoleAmoxicillinAndClarithr;
