within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01E_SulfonamidesAndTrimethoprim.J01EB03_Sulfadimidine;

model Sulfadimidine
  extends Pharmacolibrary.Drugs.ATC.J.J01EB03;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Sulfadimidine</td></tr><tr><td>ATC code:</td><td>J01EB03</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Sulfadimidine (also known as sulfamethazine) is a sulfonamide antibacterial drug, historically used for bacterial infections in humans and still commonly used in veterinary medicine, especially in cattle and pigs. Its use in humans has largely been discontinued in many countries due to safety and resistance concerns.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in healthy adult humans after single oral dose administration.</p><h4>References</h4><ol><li><p>Mason, SE, et al., &amp; Almond, GW (2008). Sulfamethazine water medication pharmacokinetics and contamination in a commercial pig production unit. <i>Journal of food protection</i> 71(3) 584–589. DOI:<a href=\"https://doi.org/10.4315/0362-028x-71.3.584\">10.4315/0362-028x-71.3.584</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/18389704/\">https://pubmed.ncbi.nlm.nih.gov/18389704</a></p></li><li><p>Mason, SE, et al., &amp; Baynes, RE (2015). Tissue concentrations of sulfamethazine and tetracycline hydrochloride of swine (Sus scrofa domestica) as it relates to withdrawal methods for international export. <i>Regulatory toxicology and pharmacology : RTP</i> 71(3) 590–596. DOI:<a href=\"https://doi.org/10.1016/j.yrtph.2015.02.013\">10.1016/j.yrtph.2015.02.013</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25707857/\">https://pubmed.ncbi.nlm.nih.gov/25707857</a></p></li><li><p>Buur, J, et al., &amp; Riviere, J (2006). Use of probabilistic modeling within a physiologically based pharmacokinetic model to predict sulfamethazine residue withdrawal times in edible tissues in swine. <i>Antimicrobial agents and chemotherapy</i> 50(7) 2344–2351. DOI:<a href=\"https://doi.org/10.1128/AAC.01355-05\">10.1128/AAC.01355-05</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/16801411/\">https://pubmed.ncbi.nlm.nih.gov/16801411</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Sulfadimidine;
