within Pharmacolibrary.Drugs.N_NervousSystem.N06B_PsychostimulantsAgentsUsedForAdhdAndNootropics;
package N06BA15_DexmethylphenidateAndSerdexmethylphenidate
  extends Icons.Package;
end N06BA15_DexmethylphenidateAndSerdexmethylphenidate;
