within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem;
package M09A_OtherDrugsForDisordersOfTheMusculoSkeletalSystem
  extends Icons.Package;
end M09A_OtherDrugsForDisordersOfTheMusculoSkeletalSystem;
