within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem;
package M09A_OtherDrugsForDisordersOfTheMusculoSkeletalSystem
  extends Icons.PackageDrugs;
end M09A_OtherDrugsForDisordersOfTheMusculoSkeletalSystem;
