within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombina;
package S01CA05_BetamethasoneAndAntiinfe
  extends Icons.PackageDrugs;
end S01CA05_BetamethasoneAndAntiinfe;
