within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02L_AntihypertensivesAndDiureticsInCombination;
package C02LG73_PicodralazineAndDiureticsCombinationsWithPsycholeptics
  extends Icons.Package;
end C02LG73_PicodralazineAndDiureticsCombinationsWithPsycholeptics;
