within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01D_VasodilatorsUsedInCardiacDiseases;
package C01DA52_GlycerylTrinitrateCombin
  extends Icons.PackageDrugs;
end C01DA52_GlycerylTrinitrateCombin;
