within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials;
package J01DD52_CeftazidimeAndBetaLactamaseInhib
  extends Icons.PackageDrugs;
end J01DD52_CeftazidimeAndBetaLactamaseInhib;
