within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AL01_PneumococcusPurifiedPolysaccharidesAntigen
  extends Icons.Package;
end J07AL01_PneumococcusPurifiedPolysaccharidesAntigen;
