within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AB05_DesogestrelAndEthinylest
  extends Icons.PackageDrugs;
end G03AB05_DesogestrelAndEthinylest;
