within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins;
package J01CE02_Phenoxymethylpenicillin
  extends Icons.PackageDrugs;
end J01CE02_Phenoxymethylpenicillin;
