within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins.J01CE02_Phenoxymethylpenicillin;

model Phenoxymethylpenicillin
  extends Pharmacolibrary.Drugs.ATC.J.J01CE02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Phenoxymethylpenicillin</td></tr><tr><td>ATC code:</td><td>J01CE02</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Phenoxymethylpenicillin, also known as penicillin V, is a narrow-spectrum beta-lactam antibiotic of the penicillin class, mainly active against Gram-positive bacteria. It is approved and commonly used today for the treatment of mild to moderate infections including streptococcal pharyngitis, tonsillitis, and some dental infections, generally administered orally due to its acid stability.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters in healthy adult volunteers after oral administration.</p><h4>References</h4><ol><li><p>Rawson, TM, et al., &amp; Holmes, AH (2021). Exploring the Pharmacokinetics of Phenoxymethylpenicillin (Penicillin-V) in Adults: A Healthy Volunteer Study. <i>Open forum infectious diseases</i> 8(12) ofab573–None. DOI:<a href=\"https://doi.org/10.1093/ofid/ofab573\">10.1093/ofid/ofab573</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34934774/\">https://pubmed.ncbi.nlm.nih.gov/34934774</a></p></li><li><p>Wilson, RC, et al., &amp; Rawson, TM (2022). Addition of probenecid to oral β-lactam antibiotics: a systematic review and meta-analysis. <i>The Journal of antimicrobial chemotherapy</i> 77(9) 2364–2372. DOI:<a href=\"https://doi.org/10.1093/jac/dkac200\">10.1093/jac/dkac200</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35726853/\">https://pubmed.ncbi.nlm.nih.gov/35726853</a></p></li><li><p>Langtry, HD, &amp; Balfour, JA (1998). Azithromycin. A review of its use in paediatric infectious diseases. <i>Drugs</i> 56(2) 273–297. DOI:<a href=\"https://doi.org/10.2165/00003495-199856020-00014\">10.2165/00003495-199856020-00014</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/9711451/\">https://pubmed.ncbi.nlm.nih.gov/9711451</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Phenoxymethylpenicillin;
