within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H02A_CorticosteroidsForSystemicUsePlain;
package H02AB01_Betamethasone
  extends Icons.Package;
end H02AB01_Betamethasone;
