within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX18_AtorvastatinAmlodipineAndRamipri
  extends Icons.Package;
end C10BX18_AtorvastatinAmlodipineAndRamipri;
