within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX18_AtorvastatinAmlodipineAndRamipri
  extends Icons.PackageDrugs;
end C10BX18_AtorvastatinAmlodipineAndRamipri;
