within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A11D_VitaminB1PlainAndInCombinationWithVitaminB6AndB1;
package A11DA01_ThiamineVitB1
  extends Icons.PackageDrugs;
end A11DA01_ThiamineVitB1;
