within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism;
package A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis
  extends Icons.PackageDrugs;
end A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis;
