within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA02_DiphtheriaPertussisPoliomyelitisTetanus
  extends Icons.Package;
end J07CA02_DiphtheriaPertussisPoliomyelitisTetanus;
