within Pharmacolibrary.Drugs.C_CardiovascularSystem.C01D_VasodilatorsUsedInCardiacDiseases;
package C01DA57_PropatylnitrateCombinati
  extends Icons.PackageDrugs;
end C01DA57_PropatylnitrateCombinati;
