within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B02B_VitaminKAndOtherHemostatics;
package B02BD03_FactorViiiInhibitorBypas
  extends Icons.PackageDrugs;
end B02BD03_FactorViiiInhibitorBypas;
