within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03A_DrugsForFunctionalGastrointestinalDisorders;
package A03AB17_TiemoniumIodide
  extends Icons.PackageDrugs;
end A03AB17_TiemoniumIodide;
