within Pharmacolibrary.Drugs.N_NervousSystem.N02A_Opioids.N02AJ17_OxycodoneAndParacetamol;

model OxycodoneAndParacetamol
  extends Pharmacolibrary.Drugs.ATC.N.N02AJ17;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>N02AJ17</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Oxycodone and paracetamol is a fixed-dose combination medication used for the treatment of moderate to severe pain. Oxycodone is a semi-synthetic opioid analgesic, while paracetamol (acetaminophen) is a widely used non-opioid analgesic and antipyretic. The combination is approved and commonly prescribed for acute pain management in both inpatient and outpatient clinical settings.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters estimated from published studies in healthy adult subjects (mixed sex, age 18–55). Primarily based on single oral dose of oxycodone/paracetamol fixed-combination tablets.</p><h4>References</h4><ol><li><p>Thigpen, JC, et al., &amp; Harirforoosh, S (2019). Opioids: A Review of Pharmacokinetics and Pharmacodynamics in Neonates, Infants, and Children. <i>European journal of drug metabolism and pharmacokinetics</i> 44(5) 591–609. DOI:<a href=\"https://doi.org/10.1007/s13318-019-00552-0\">10.1007/s13318-019-00552-0</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31006834/\">https://pubmed.ncbi.nlm.nih.gov/31006834</a></p></li><li><p>Morton, T, et al., &amp; Devarakonda, K (2016). Pooled Post Hoc Analysis of Population Pharmacokinetics of Oxycodone and Acetaminophen Following Multiple Oral Doses of Biphasic Immediate-Release/Extended-Release Oxycodone/Acetaminophen Tablets. <i>Pain practice : the official journal of World Institute of Pain</i> 16(6) 730–736. DOI:<a href=\"https://doi.org/10.1111/papr.12329\">10.1111/papr.12329</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/26218586/\">https://pubmed.ncbi.nlm.nih.gov/26218586</a></p></li><li><p>Franke, RM, et al., &amp; Devarakonda, K (2015). Pooled post hoc analysis of population pharmacokinetics of oxycodone and acetaminophen following a single oral dose of biphasic immediate-release/extended-release oxycodone/acetaminophen tablets. <i>Drug design, development and therapy</i> 9 4587–4597. DOI:<a href=\"https://doi.org/10.2147/DDDT.S79499\">10.2147/DDDT.S79499</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/26316698/\">https://pubmed.ncbi.nlm.nih.gov/26316698</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end OxycodoneAndParacetamol;
