within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AB06_Nimorazole
  extends Icons.PackageDrugs;
end P01AB06_Nimorazole;
