within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01A_AlkylatingAgents.L01AB01_Busulfan;

model Busulfan
  extends Pharmacolibrary.Drugs.ATC.L.L01AB01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>L01AB01</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Busulfan is an alkylating agent that is used primarily as a chemotherapy drug for conditioning regimens prior to hematopoietic stem cell transplantation, especially in chronic myelogenous leukemia and other hematological malignancies. It is approved and in clinical use today.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported for adult patients undergoing hematopoietic stem cell transplantation; intravenous administration.</p><h4>References</h4><ol><li><p>Takahashi, T, et al., &amp; Al-Kofahi, M (2023). Population Pharmacokinetic Model of Intravenous Busulfan in Hematopoietic Cell Transplantation: Systematic Review and Comparative Simulations. <i>Clinical pharmacokinetics</i> 62(7) 955–968. DOI:<a href=\"https://doi.org/10.1007/s40262-023-01275-x\">10.1007/s40262-023-01275-x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37415003/\">https://pubmed.ncbi.nlm.nih.gov/37415003</a></p></li><li><p>Wu, X, et al., &amp; Huang, X (2017). Population pharmacokinetics analysis of intravenous busulfan in Chinese patients undergoing hematopoietic stem cell transplantation. <i>Clinical and experimental pharmacology &amp; physiology</i> 44(5) 529–538. DOI:<a href=\"https://doi.org/10.1111/1440-1681.12735\">10.1111/1440-1681.12735</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/28135768/\">https://pubmed.ncbi.nlm.nih.gov/28135768</a></p></li><li><p>Ishiwata, Y, et al., &amp; Yasuhara, M (2018). Population Pharmacokinetics of Intravenous Busulfan in Japanese Pediatric Patients With Primary Immunodeficiency Diseases. <i>Journal of clinical pharmacology</i> 58(3) 327–331. DOI:<a href=\"https://doi.org/10.1002/jcph.1027\">10.1002/jcph.1027</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29077206/\">https://pubmed.ncbi.nlm.nih.gov/29077206</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Busulfan;
