within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX03_Catumaxomab
  extends Icons.Package;
end L01FX03_Catumaxomab;
