within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M05B_DrugsAffectingBoneStructureAndMineralization;
package M05BB07_RisedronicAcidAndColecal
  extends Icons.PackageDrugs;
end M05BB07_RisedronicAcidAndColecal;
