within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H05A_ParathyroidHormonesAndAnalogues;
package H05AA02_Teriparatide
  extends Icons.Package;
end H05AA02_Teriparatide;
