within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03D_Progestogens.G03DA04_Progesterone;

model Progesterone
  extends Pharmacolibrary.Drugs.ATC.G.G03DA04;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>G03DA04</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Progesterone is a natural steroid hormone involved in the menstrual cycle, pregnancy, and embryogenesis. It is used as a medication primarily for hormone replacement therapy, treatment of menstrual disorders, and as a component of hormonal contraceptives. Progesterone is approved for use today in various oral, vaginal, and injectable forms.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported for healthy adult women after a single oral dose administration of micronized progesterone.</p><h4>References</h4><ol><li><p>Wang, H, et al., &amp; Deng, C (2019). Pharmacokinetics of hard micronized progesterone capsules via vaginal or oral route compared with soft micronized capsules in healthy postmenopausal women: a randomized open-label clinical study. <i>Drug design, development and therapy</i> 13 2475–2482. DOI:<a href=\"https://doi.org/10.2147/DDDT.S204624\">10.2147/DDDT.S204624</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31440031/\">https://pubmed.ncbi.nlm.nih.gov/31440031</a></p></li><li><p>Beumer, JH, &amp; Foldi, J (2023). Pharmacology and pharmacokinetics of elacestrant. <i>Cancer chemotherapy and pharmacology</i> 92(2) 157–163. DOI:<a href=\"https://doi.org/10.1007/s00280-023-04550-7\">10.1007/s00280-023-04550-7</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37314500/\">https://pubmed.ncbi.nlm.nih.gov/37314500</a></p></li><li><p>Liu, H, et al., &amp; Schultze-Mosgau, MH (2021). Pharmacokinetics and Safety of the Selective Progesterone Receptor Modulator Vilaprisan in Chinese Healthy Postmenopausal Women. <i>Clinical pharmacology in drug development</i> 10(5) 486–493. DOI:<a href=\"https://doi.org/10.1002/cpdd.851\">10.1002/cpdd.851</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32716091/\">https://pubmed.ncbi.nlm.nih.gov/32716091</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Progesterone;
