within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AA01_Broxyquinoline
  extends Icons.Package;
end P01AA01_Broxyquinoline;
