within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01C_PlantAlkaloidsAndOtherNaturalProducts.L01CE01_Topotecan;

model Topotecan
  extends Pharmacolibrary.Drugs.ATC.L.L01CE01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>L01CE01</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Topotecan is a topoisomerase I inhibitor used primarily in the treatment of various cancers including ovarian cancer, small cell lung cancer, and cervical cancer. It is an antineoplastic agent that interferes with the replication of DNA in cancer cells. Topotecan is an approved drug and is administered commonly via intravenous infusion or orally.</p><h4>Pharmacokinetics</h4><p>Population pharmacokinetics in adult cancer patients following intravenous administration.</p><h4>References</h4><ol><li><p>Requejo, F, et al., &amp; Schaiquevich, P (2023). Pharmacokinetics of Orbital Topotecan After Ophthalmic Artery Chemosurgery and Intravenous Infusion in the Swine Model. <i>Investigative ophthalmology &amp; visual science</i> 64(12) 3–None. DOI:<a href=\"https://doi.org/10.1167/iovs.64.12.3\">10.1167/iovs.64.12.3</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37656475/\">https://pubmed.ncbi.nlm.nih.gov/37656475</a></p></li><li><p>Cheng, Y, et al., &amp; Zhou, L (2024). Myeloprotection with trilaciclib in Chinese patients with extensive-stage small cell lung cancer receiving chemotherapy: Results from a randomized, double-blind, placebo-controlled phase III study (TRACES). <i>Lung cancer (Amsterdam, Netherlands)</i> 188 107455–None. DOI:<a href=\"https://doi.org/10.1016/j.lungcan.2023.107455\">10.1016/j.lungcan.2023.107455</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/38224653/\">https://pubmed.ncbi.nlm.nih.gov/38224653</a></p></li><li><p>Roberts, JK, et al., &amp; Stewart, CF (2016). Population Pharmacokinetics of Oral Topotecan in Infants and Very Young Children with Brain Tumors Demonstrates a Role of ABCG2 rs4148157 on the Absorption Rate Constant. <i>Drug metabolism and disposition: the biological fate of chemicals</i> 44(7) 1116–1122. DOI:<a href=\"https://doi.org/10.1124/dmd.115.068676\">10.1124/dmd.115.068676</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27052877/\">https://pubmed.ncbi.nlm.nih.gov/27052877</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Topotecan;
