within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AX13_Protiofate
  extends Icons.PackageDrugs;
end G01AX13_Protiofate;
