within Pharmacolibrary.Drugs.V_Various.V09H_InflammationAndInfectionDetection;
package V09HA03_Technetium99mtcAntigranulocyteAn
  extends Icons.PackageDrugs;
end V09HA03_Technetium99mtcAntigranulocyteAn;
