within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H02A_CorticosteroidsForSystemicUsePlain.H02AA03_Desoxycortone;

model Desoxycortone
  extends Pharmacolibrary.Drugs.ATC.H.H02AA03;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>H02AA03</td></tr><td>route:</td><td></td></tr><tr><td>n-compartments</td><td>0</td></tr></table><p>Desoxycortone (deoxycorticosterone, DOC) is a corticosteroid hormone with mineralocorticoid properties, historically used as an injectable medication for conditions like Addison's disease and adrenocortical insufficiency. It is rarely used today due to the availability of other corticosteroids and mineralocorticoids such as fludrocortisone.</p><h4>Pharmacokinetics</h4><p>No published pharmacokinetic studies were found for desoxycortone in humans. PK parameters are not reported in the literature. The following parameters are left empty as no primary data or studies available.</p><h4>References</h4><ol><li><p>Maksay, G, &amp; Bíró, T (2005). High affinity, heterogeneous displacement of [3H]EBOB binding to cerebellar GABA A receptors by neurosteroids and GABA agonists. <i>Neuropharmacology</i> 49(4) 431–438. DOI:<a href=\"https://doi.org/10.1016/j.neuropharm.2005.04.003\">10.1016/j.neuropharm.2005.04.003</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/15913670/\">https://pubmed.ncbi.nlm.nih.gov/15913670</a></p></li><li><p>Gee, KW, &amp; Lan, NC (1991). Gamma-aminobutyric acidA receptor complexes in rat frontal cortex and spinal cord show differential responses to steroid modulation. <i>Molecular pharmacology</i> 40(6) 995–999. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/1661843/\">https://pubmed.ncbi.nlm.nih.gov/1661843</a></p></li><li><p>Vandewalle, A, et al., &amp; Bonvalet, JP (1985). Cellular heterogeneity of uridine incorporation in collecting tubules: effect of DOCA. <i>The American journal of physiology</i> 248(4 Pt 2) F552–F564. DOI:<a href=\"https://doi.org/10.1152/ajprenal.1985.248.4.F552\">10.1152/ajprenal.1985.248.4.F552</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/3985163/\">https://pubmed.ncbi.nlm.nih.gov/3985163</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Desoxycortone;
