within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H02A_CorticosteroidsForSystemicUsePlain;
package H02AA03_Desoxycortone
  extends Icons.Package;
end H02AA03_Desoxycortone;
