within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H02A_CorticosteroidsForSystemicUsePlain;
package H02AB18_Vamorolone
  extends Icons.PackageDrugs;
end H02AB18_Vamorolone;
