within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DX01_ValsartanAmlodipineAndHydrochlor
  extends Icons.PackageDrugs;
end C09DX01_ValsartanAmlodipineAndHydrochlor;
