within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AR20_EmtricitabineTenofovirAlafenamid
  extends Icons.PackageDrugs;
end J05AR20_EmtricitabineTenofovirAlafenamid;
