within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A16A_OtherAlimentaryTractAndMetabolismProducts;
package A16AX30_SodiumBenzoateAndSodiumPhenylace
  extends Icons.PackageDrugs;
end A16AX30_SodiumBenzoateAndSodiumPhenylace;
