within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03E_DiureticsAndPotassiumSparingAgentsInCombination;
package C03EB02_BumetanideAndPotassiumSparingAge
  extends Icons.Package;
end C03EB02_BumetanideAndPotassiumSparingAge;
