within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BA57_EthenzamideCombinationsExclPsycholeptics
  extends Icons.Package;
end N02BA57_EthenzamideCombinationsExclPsycholeptics;
