within Pharmacolibrary.Drugs.R_RespiratorySystem.R03D_OtherSystemicDrugsForObstructiveAirwayDiseases;
package R03DA02_CholineTheophyllinate
  extends Icons.PackageDrugs;
end R03DA02_CholineTheophyllinate;
