within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M03B_MuscleRelaxantsCentrallyActingAgents;
package M03BA52_CarisoprodolCombinations
  extends Icons.PackageDrugs;
end M03BA52_CarisoprodolCombinations;
