within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J02A_AntimycoticsForSystemicUse.J02AC02_Itraconazole;

model Itraconazole
  extends Pharmacolibrary.Drugs.ATC.J.J02AC02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Itraconazole</td></tr><tr><td>ATC code:</td><td>J02AC02</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Itraconazole is a triazole antifungal agent used for the treatment of various fungal infections including those caused by Aspergillus, Candida, and dermatophytes. It is FDA-approved and commonly used for systemic mycoses and onychomycosis.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in healthy adult volunteers following a single oral dose of 200 mg capsule under fasting conditions.</p><h4>References</h4><ol><li><p>Sánchez, CR, et al., &amp; Papich, MG (2019). Population pharmacokinetics of itraconazole solution after a single oral administration in captive lesser flamingos (Phoeniconaias minor). <i>Journal of veterinary pharmacology and therapeutics</i> 42(1) 1–6. DOI:<a href=\"https://doi.org/10.1111/jvp.12721\">10.1111/jvp.12721</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30302773/\">https://pubmed.ncbi.nlm.nih.gov/30302773</a></p></li><li><p>Willems, L, et al., &amp; de Beule, K (2001). Itraconazole oral solution and intravenous formulations: a review of pharmacokinetics and pharmacodynamics. <i>Journal of clinical pharmacy and therapeutics</i> 26(3) 159–169. DOI:<a href=\"https://doi.org/10.1046/j.1365-2710.2001.00338.x\">10.1046/j.1365-2710.2001.00338.x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/11422598/\">https://pubmed.ncbi.nlm.nih.gov/11422598</a></p></li><li><p>Junkert, AM, et al., &amp; Pontarolo, R (2024). Pharmacokinetics of oral ciprofloxacin in adult patients: A scoping review. <i>British journal of clinical pharmacology</i> 90(2) 528–547. DOI:<a href=\"https://doi.org/10.1111/bcp.15933\">10.1111/bcp.15933</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37850318/\">https://pubmed.ncbi.nlm.nih.gov/37850318</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Itraconazole;
