within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD21_SaxagliptinAndDapagliflo
  extends Icons.PackageDrugs;
end A10BD21_SaxagliptinAndDapagliflo;
