within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AC01_Diloxanide
  extends Icons.PackageDrugs;
end P01AC01_Diloxanide;
