within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H01B_PosteriorPituitaryLobeHormones;
package H01BA03_Lypressin
  extends Icons.PackageDrugs;
end H01BA03_Lypressin;
