within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07D_BetaBlockingAgentsThiazidesAndOtherDiuretics;
package C07DA06_TimololThiazidesAndOtherDiuretic
  extends Icons.PackageDrugs;
end C07DA06_TimololThiazidesAndOtherDiuretic;
