within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01X_OtherAntineoplasticAgents;
package L01XL08_LisocabtageneMaraleucel
  extends Icons.Package;
end L01XL08_LisocabtageneMaraleucel;
