within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX12_AtorvastatinAcetylsalicylicAcidA
  extends Icons.Package;
end C10BX12_AtorvastatinAcetylsalicylicAcidA;
