within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01B_Antimalarials.P01BE05_Artenimol;

model Artenimol
  extends Pharmacolibrary.Drugs.ATC.P.P01BE05;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>P01BE05</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Artenimol, also known as dihydroartemisinin, is a semisynthetic derivative of artemisinin, which is an antimalarial agent derived from the plant Artemisia annua. It is used in combination therapies for the treatment of uncomplicated Plasmodium falciparum malaria and is an approved medication in many countries.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters in healthy adult volunteers after oral administration.</p><h4>References</h4><ol><li><p>Ericsson, T, et al., &amp; Äbelö, A (2014). Population pharmacokinetics of artesunate and dihydroartemisinin during long-term oral administration of artesunate to patients with metastatic breast cancer. <i>European journal of clinical pharmacology</i> 70(12) 1453–1463. DOI:<a href=\"https://doi.org/10.1007/s00228-014-1754-2\">10.1007/s00228-014-1754-2</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25248945/\">https://pubmed.ncbi.nlm.nih.gov/25248945</a></p></li><li><p>Lohy Das, J, et al., &amp; Dorlo, TPC (2018). Population Pharmacokinetics of Artemether, Dihydroartemisinin, and Lumefantrine in Rwandese Pregnant Women Treated for Uncomplicated Plasmodium falciparum Malaria. <i>Antimicrobial agents and chemotherapy</i> 62(10) –. DOI:<a href=\"https://doi.org/10.1128/AAC.00518-18\">10.1128/AAC.00518-18</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/30061282/\">https://pubmed.ncbi.nlm.nih.gov/30061282</a></p></li><li><p>Sambol, NC, et al., &amp; Parikh, S (2015). Population Pharmacokinetics of Piperaquine in Young Ugandan Children Treated With Dihydroartemisinin-Piperaquine for Uncomplicated Malaria. <i>Clinical pharmacology and therapeutics</i> 98(1) 87–95. DOI:<a href=\"https://doi.org/10.1002/cpt.104\">10.1002/cpt.104</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25732044/\">https://pubmed.ncbi.nlm.nih.gov/25732044</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Artenimol;
