within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07B_BetaBlockingAgentsAndThiazides;
package C07BA68_MetipranololAndThiazidesCombinat
  extends Icons.PackageDrugs;
end C07BA68_MetipranololAndThiazidesCombinat;
