within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P03A_EctoparasiticidesInclScabicides;
package P03AC54_PermethrinCombinations
  extends Icons.Package;
end P03AC54_PermethrinCombinations;
