within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01R_CombinationsOfAntibacterials;
package J01RA04_SpiramycinAndMetronidazo
  extends Icons.PackageDrugs;
end J01RA04_SpiramycinAndMetronidazo;
