within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G04C_DrugsUsedInBenignProstaticHypertrophy;
package G04CB51_FinasterideAndTadalafil
  extends Icons.PackageDrugs;
end G04CB51_FinasterideAndTadalafil;
