within Pharmacolibrary.Drugs.S_SensoryOrgans.S01E_AntiglaucomaPreparationsAndMiotics.S01EA04_Clonidine;

model Clonidine
  extends Pharmacolibrary.Drugs.ATC.S.S01EA04;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Clonidine</td></tr><tr><td>ATC code:</td><td>S01EA04</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Clonidine is a centrally acting alpha-2 adrenergic agonist used primarily for the treatment of hypertension, but also for attention deficit hyperactivity disorder (ADHD), certain pain conditions, withdrawal syndromes, and in ophthalmic formulation (with ATC code S01EA04) for lowering intraocular pressure in glaucoma or ocular hypertension. It remains an approved and clinically used medication.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters following oral administration in healthy adult volunteers.</p><h4>References</h4><ol><li><p>Larsson, P, et al., &amp; Anderson, BJ (2011). Oral bioavailability of clonidine in children. <i>Paediatric anaesthesia</i> 21(3) 335–340. DOI:<a href=\"https://doi.org/10.1111/j.1460-9592.2010.03397.x\">10.1111/j.1460-9592.2010.03397.x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/20735802/\">https://pubmed.ncbi.nlm.nih.gov/20735802</a></p></li><li><p>De Hondt, L, et al., &amp; Tommelein, E (2024). Quantification of ADHD medication in biological fluids of pregnant and breastfeeding women with liquid chromatography: a comprehensive review. <i>Frontiers in public health</i> 12 1437328–None. DOI:<a href=\"https://doi.org/10.3389/fpubh.2024.1437328\">10.3389/fpubh.2024.1437328</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39171321/\">https://pubmed.ncbi.nlm.nih.gov/39171321</a></p></li><li><p>Bienert, A, et al., &amp; Grześkowiak, E (2015). Melatonin and clonidine premedication has similar impact on the pharmacokinetics and pharmacodynamics of propofol target controlled-infusions. <i>Journal of clinical pharmacology</i> 55(3) 307–316. DOI:<a href=\"https://doi.org/10.1002/jcph.401\">10.1002/jcph.401</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/25243731/\">https://pubmed.ncbi.nlm.nih.gov/25243731</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Clonidine;
