within Pharmacolibrary.Drugs.C_CardiovascularSystem.C05A_AgentsForTreatmentOfHemorrhoidsAndAnalFissuresForTopicalUse;
package C05AX06_Phenylephrine
  extends Icons.Package;
end C05AX06_Phenylephrine;
