within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A09A_DigestivesInclEnzymes.A09AA04_Tilactase;

model Tilactase
  extends Pharmacolibrary.Drugs.ATC.A.A09AA04;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>A09AA04</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Tilactase, also known as beta-galactosidase or lactase, is an enzyme used as an oral digestive aid for individuals with lactose intolerance to hydrolyze lactose in dairy products. It is not absorbed systemically and acts locally in the gastrointestinal tract, and is available as a non-prescription supplement in many countries.</p><h4>Pharmacokinetics</h4><p>No published pharmacokinetic parameters in humans, since tilactase is an enzyme that remains in the gastrointestinal tract and is not absorbed into systemic circulation. Therefore, classic PK parameters (Vd, clearance) are not meaningful or reported.</p><h4>References</h4><ol><li><p>Meloni, GF, et al., &amp; Cherchi, PL (1999). Lactose absorption in patients with ovarian cancer. <i>American journal of epidemiology</i> 150(2) 183–186. DOI:<a href=\"https://doi.org/10.1093/oxfordjournals.aje.a009978\">10.1093/oxfordjournals.aje.a009978</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/10412963/\">https://pubmed.ncbi.nlm.nih.gov/10412963</a></p></li><li><p>Perlow, W, et al., &amp; Lieber, CS (1977). Symptomatic intestinal disaccharidase deficiency in alcoholics. <i>Gastroenterology</i> 72(4 Pt 1) 680–684. PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/838222/\">https://pubmed.ncbi.nlm.nih.gov/838222</a></p></li><li><p>Meloni, T, et al., &amp; Meloni, GF (1996). Lactose absorption in patients with glucose 6-phosphate dehydrogenase deficiency with and without favism. <i>Gut</i> 39(2) 210–213. DOI:<a href=\"https://doi.org/10.1136/gut.39.2.210\">10.1136/gut.39.2.210</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/8991858/\">https://pubmed.ncbi.nlm.nih.gov/8991858</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Tilactase;
