within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J04A_DrugsForTreatmentOfTuberculosis;
package J04AM08_IsoniazidSulfamethoxazoleTrimethoprimAndPyridoxine
  extends Icons.Package;
end J04AM08_IsoniazidSulfamethoxazoleTrimethoprimAndPyridoxine;
