within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B01A_AntithromboticAgents;
package B01AC56_AcetylsalicylicAcidCombinationsW
  extends Icons.PackageDrugs;
end B01AC56_AcetylsalicylicAcidCombinationsW;
