within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis;
package A02BX51_CarbenoxoloneCombination
  extends Icons.PackageDrugs;
end A02BX51_CarbenoxoloneCombination;
