within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BX12_BismuthSubnitrate
  extends Icons.Package;
end A02BX12_BismuthSubnitrate;
