within Pharmacolibrary.Drugs.R_RespiratorySystem.R03A_AdrenergicsInhalants;
package R03AL11_FormoterolGlycopyrroniumBromideAndBudesonide
  extends Icons.Package;
end R03AL11_FormoterolGlycopyrroniumBromideAndBudesonide;
