within Pharmacolibrary.Drugs.C_CardiovascularSystem.C03E_DiureticsAndPotassiumSparingAgentsInCombination;
package C03EA01_HydrochlorothiazideAndPo
  extends Icons.PackageDrugs;
end C03EA01_HydrochlorothiazideAndPo;
