within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD29_SitagliptinAndDapagliflo
  extends Icons.PackageDrugs;
end A10BD29_SitagliptinAndDapagliflo;
