within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10A_LipidModifyingAgentsPlain;
package C10AX06_Omega3TriglyceridesInclOtherEste
  extends Icons.PackageDrugs;
end C10AX06_Omega3TriglyceridesInclOtherEste;
