within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J04A_DrugsForTreatmentOfTuberculosis;
package J04AM04_ThioacetazoneAndIsoniazi
  extends Icons.PackageDrugs;
end J04AM04_ThioacetazoneAndIsoniazi;
