within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BD01_OmeprazoleAmoxicillinAndMetronidazole
  extends Icons.Package;
end A02BD01_OmeprazoleAmoxicillinAndMetronidazole;
