within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD09_PioglitazoneAndAlogliptin
  extends Icons.Package;
end A10BD09_PioglitazoneAndAlogliptin;
