within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination;
package G03FB06_MedroxyprogesteroneAndEs
  extends Icons.PackageDrugs;
end G03FB06_MedroxyprogesteroneAndEs;
