within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B03A_IronPreparations;
package B03AD01_FerrousAminoAcidComplexAndFolicA
  extends Icons.PackageDrugs;
end B03AD01_FerrousAminoAcidComplexAndFolicA;
