within Pharmacolibrary.Drugs.R_RespiratorySystem.R05D_CoughSuppressantsExclCombinationsWithExpectorant;
package R05DA05_OpiumAlkaloidsWithMorphi
  extends Icons.PackageDrugs;
end R05DA05_OpiumAlkaloidsWithMorphi;
