within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02L_AntihypertensivesAndDiureticsInCombination;
package C02LL01_PargylineAndDiuretics
  extends Icons.PackageDrugs;
end C02LL01_PargylineAndDiuretics;
