within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01R_CombinationsOfAntibacterials;
package J01RA11_CiprofloxacinAndTinidazo
  extends Icons.PackageDrugs;
end J01RA11_CiprofloxacinAndTinidazo;
