within Pharmacolibrary.Drugs.N_NervousSystem.N05C_HypnoticsAndSedatives.N05CD08_Midazolam;

model Midazolam
  extends Pharmacolibrary.Drugs.ATC.N.N05CD08;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Midazolam</td></tr><tr><td>ATC code:</td><td>N05CD08</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Midazolam is a short-acting benzodiazepine used for sedation, anesthesia, procedural sedation, or the treatment of acute seizures. It is approved for medical use and is commonly administered in hospitals for premedication before surgeries, sedation in intensive care, and acute seizure management.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetics described for healthy adult volunteers after single intravenous and oral administration.</p><h4>References</h4><ol><li><p>Kim, SH, &amp; Fechner, J (2022). Remimazolam - current knowledge on a new intravenous benzodiazepine anesthetic agent. <i>Korean journal of anesthesiology</i> 75(4) 307–315. DOI:<a href=\"https://doi.org/10.4097/kja.22297\">10.4097/kja.22297</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/35585830/\">https://pubmed.ncbi.nlm.nih.gov/35585830</a></p></li><li><p>van Rongen, A, et al., &amp; van den Anker, JN (2015). Population pharmacokinetics of midazolam and its metabolites in overweight and obese adolescents. <i>British journal of clinical pharmacology</i> 80(5) 1185–1196. DOI:<a href=\"https://doi.org/10.1111/bcp.12693\">10.1111/bcp.12693</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/26044579/\">https://pubmed.ncbi.nlm.nih.gov/26044579</a></p></li><li><p>Dholakia, U, et al., &amp; Pypendop, BH (2020). Pharmacokinetics of midazolam in sevoflurane-anesthetized cats. <i>Veterinary anaesthesia and analgesia</i> 47(2) 200–209. DOI:<a href=\"https://doi.org/10.1016/j.vaa.2019.11.005\">10.1016/j.vaa.2019.11.005</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31983556/\">https://pubmed.ncbi.nlm.nih.gov/31983556</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Midazolam;
