within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AX07_Trimetrexate
  extends Icons.Package;
end P01AX07_Trimetrexate;
