within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02L_AntihypertensivesAndDiureticsInCombination;
package C02LA51_ReserpineAndDiureticsCom
  extends Icons.PackageDrugs;
end C02LA51_ReserpineAndDiureticsCom;
