within Pharmacolibrary.Drugs.C_CardiovascularSystem.C08C_SelectiveCalciumChannelBlockersWithMainlyVascula;
package C08CA51_AmlodipineAndCelecoxib
  extends Icons.PackageDrugs;
end C08CA51_AmlodipineAndCelecoxib;
