within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AA01_EtynodiolAndEthinylestra
  extends Icons.PackageDrugs;
end G03AA01_EtynodiolAndEthinylestra;
