within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AX11_Nitazoxanide
  extends Icons.Package;
end P01AX11_Nitazoxanide;
