within Pharmacolibrary.Drugs.R_RespiratorySystem.R06A_AntihistaminesForSystemicUse;
package R06AD55_HydroxyethylpromethazineCombinat
  extends Icons.Package;
end R06AD55_HydroxyethylpromethazineCombinat;
