within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AX10_Fumagillin
  extends Icons.Package;
end P01AX10_Fumagillin;
