within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA06_DiphtheriaHaemophilusInf
  extends Icons.PackageDrugs;
end J07CA06_DiphtheriaHaemophilusInf;
