within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FX04_Ipilimumab
  extends Icons.PackageDrugs;
end L01FX04_Ipilimumab;
