within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01E_SulfonamidesAndTrimethoprim;
package J01ED20_TrimethoprimAndSulfonamidesCombinationsEGTrimethoprimSulfamethoxazole
  extends Icons.Package;
end J01ED20_TrimethoprimAndSulfonamidesCombinationsEGTrimethoprimSulfamethoxazole;
