within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01D_OtherBetaLactamAntibacterials;
package J01DD58_CefiximeAndBetaLactamase
  extends Icons.PackageDrugs;
end J01DD58_CefiximeAndBetaLactamase;
