within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX19_AtorvastatinAmlodipineAndCandesartan
  extends Icons.Package;
end C10BX19_AtorvastatinAmlodipineAndCandesartan;
