within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H03A_ThyroidPreparations.H03AA01_LevothyroxineSodium;

model LevothyroxineSodium
  extends Pharmacolibrary.Drugs.ATC.H.H03AA01;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>LevothyroxineSodium</td></tr><tr><td>ATC code:</td><td>H03AA01</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Levothyroxine sodium is a synthetic form of the thyroid hormone thyroxine (T4), used primarily for the treatment of hypothyroidism and as replacement therapy in patients with thyroid hormone deficiency. It is an FDA-approved medication and widely used today.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetics in healthy adult volunteers after oral administration of a single dose; both sexes, fasting condition.</p><h4>References</h4><ol><li><p>Fitch, R, et al., &amp; Harper, D (2025). Phase 1 Study Evaluating the Pharmacokinetics, Dose Proportionality, Bioavailability, and Tolerability of Subcutaneous Levothyroxine Sodium (XP-8121). <i>Clinical and translational science</i> 18(5) e70244–None. DOI:<a href=\"https://doi.org/10.1111/cts.70244\">10.1111/cts.70244</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/40348586/\">https://pubmed.ncbi.nlm.nih.gov/40348586</a></p></li><li><p>Mateo, RCI, &amp; Hennessey, JV (2019). Thyroxine and treatment of hypothyroidism: seven decades of experience. <i>Endocrine</i> 66(1) 10–17. DOI:<a href=\"https://doi.org/10.1007/s12020-019-02006-8\">10.1007/s12020-019-02006-8</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/31321670/\">https://pubmed.ncbi.nlm.nih.gov/31321670</a></p></li><li><p>Yannovits, N, et al., &amp; Benakis, A (2006). A bioequivalence study of levothyroxine tablets versus an oral levothyroxine solution in healthy volunteers. <i>European journal of drug metabolism and pharmacokinetics</i> 31(2) 73–78. DOI:<a href=\"https://doi.org/10.1007/BF03191122\">10.1007/BF03191122</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/16898074/\">https://pubmed.ncbi.nlm.nih.gov/16898074</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end LevothyroxineSodium;
