within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09B_AceInhibitorsCombinations;
package C09BX06_PerindoprilBisoprololAmlodipineA
  extends Icons.PackageDrugs;
end C09BX06_PerindoprilBisoprololAmlodipineA;
