within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07C_BetaBlockingAgentsAndOtherDiuretics;
package C07CA03_PindololAndOtherDiuretic
  extends Icons.PackageDrugs;
end C07CA03_PindololAndOtherDiuretic;
