within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A03C_AntispasmodicsInCombinationWithPsycholeptics;
package A03CA03_OxyphencyclimineAndPsycholeptics
  extends Icons.Package;
end A03CA03_OxyphencyclimineAndPsycholeptics;
