within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H02A_CorticosteroidsForSystemicUsePlain;
package H02AB02_Dexamethasone
  extends Icons.PackageDrugs;
end H02AB02_Dexamethasone;
