within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonStero;
package M01AE52_NaproxenAndEsomeprazole
  extends Icons.PackageDrugs;
end M01AE52_NaproxenAndEsomeprazole;
