within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DB02_OlmesartanMedoxomilAndAmlodipine
  extends Icons.Package;
end C09DB02_OlmesartanMedoxomilAndAmlodipine;
