within Pharmacolibrary.Drugs.D_Dermatologicals.D01A_AntifungalsForTopicalUse;
package D01AC20_ImidazolesTriazolesInCombination
  extends Icons.PackageDrugs;
end D01AC20_ImidazolesTriazolesInCombination;
