within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombina;
package S01CC01_DiclofenacAndAntiinfecti
  extends Icons.PackageDrugs;
end S01CC01_DiclofenacAndAntiinfecti;
