within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA05_DiphtheriaHepatitisBPertussisTetanus
  extends Icons.Package;
end J07CA05_DiphtheriaHepatitisBPertussisTetanus;
