within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins.A10BD17_MetforminAndAcarbose;

model MetforminAndAcarbose
  extends Pharmacolibrary.Drugs.ATC.A.A10BD17;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>A10BD17</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Metformin and acarbose is a combination drug used in the management of type 2 diabetes mellitus, particularly to improve glycemic control when monotherapy is insufficient. Metformin decreases hepatic glucose production and improves insulin sensitivity, while acarbose inhibits intestinal alpha-glucosidases to delay carbohydrate absorption. This fixed-dose combination is approved for use in several countries.</p><h4>Pharmacokinetics</h4><p>No publication was found reporting combined pharmacokinetic parameters for metformin and acarbose as a fixed-dose combination in humans. Individual PK profiles are known: metformin is commonly described by a one-compartment oral model with rapid absorption, while acarbose has minimal systemic absorption. The following estimates are provided based on published data for individual drugs in adult type 2 diabetic patients under oral administration.</p><h4>References</h4><ol><li><p>Scheen, AJ, &amp; Lefèbvre, PJ (1995). Antihyperglycaemic agents. Drug interactions of clinical importance. <i>Drug safety</i> 12(1) 32–45. DOI:<a href=\"https://doi.org/10.2165/00002018-199512010-00003\">10.2165/00002018-199512010-00003</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/7741982/\">https://pubmed.ncbi.nlm.nih.gov/7741982</a></p></li><li><p>Jennings, PE (1997). Oral antihyperglycaemics. Considerations in older patients with non-insulin-dependent diabetes mellitus. <i>Drugs &amp; aging</i> 10(5) 323–331. DOI:<a href=\"https://doi.org/10.2165/00002512-199710050-00001\">10.2165/00002512-199710050-00001</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/9143853/\">https://pubmed.ncbi.nlm.nih.gov/9143853</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end MetforminAndAcarbose;
