within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD17_MetforminAndAcarbose
  extends Icons.PackageDrugs;
end A10BD17_MetforminAndAcarbose;
