within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B05A_BloodAndRelatedProducts.B05AX02_Thrombocytes;

model Thrombocytes
  extends Pharmacolibrary.Drugs.ATC.B.B05AX02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Thrombocytes</td></tr><tr><td>ATC code:</td><td>B05AX02</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Thrombocytes, also known as platelets, are cellular components of blood involved in hemostasis, leading to the formation of blood clots. Thrombocyte (platelet) concentrates are commonly used as blood products to prevent or treat bleeding in patients with low platelet counts, such as those with hematological diseases, cancer chemotherapy, or major surgery. As a 'drug', platelet transfusions are approved and widely used in modern clinical practice.</p><h4>Pharmacokinetics</h4><p>No traditional pharmacokinetic parameters (such as volume of distribution or clearance) are typically reported for thrombocyte transfusions in medical literature, because the product consists of viable cells rather than a single molecule. The pharmacokinetics are more related to platelet survival, recovery, and lifespan in recipient's circulation. Thus, standard PK parameters like volume of distribution or clearance are not applicable.</p><h4>References</h4><ol><li><p>Dash, D (2015). Current Status of Antiplatelet Therapy in Acute Coronary Syndrome. <i>Cardiovascular &amp; hematological agents in medicinal chemistry</i> 13(1) 40–49. DOI:<a href=\"https://doi.org/10.2174/187152571301150730114514\">10.2174/187152571301150730114514</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/26245659/\">https://pubmed.ncbi.nlm.nih.gov/26245659</a></p></li><li><p>Peer, CJ, et al., &amp; Figg, WD (2018). A population pharmacokinetic/toxicity model for the reduction of platelets during a 48-h continuous intravenous infusion of the histone deacetylase inhibitor belinostat. <i>Cancer chemotherapy and pharmacology</i> 82(3) 565–570. DOI:<a href=\"https://doi.org/10.1007/s00280-018-3631-7\">10.1007/s00280-018-3631-7</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/29951694/\">https://pubmed.ncbi.nlm.nih.gov/29951694</a></p></li><li><p>Kathman, SJ, et al., &amp; Lee, JS (2022). Population pharmacokinetic-pharmacodynamic modeling of PB2452, a monoclonal antibody fragment being developed as a ticagrelor reversal agent, in healthy volunteers. <i>CPT: pharmacometrics &amp; systems pharmacology</i> 11(1) 68–81. DOI:<a href=\"https://doi.org/10.1002/psp4.12734\">10.1002/psp4.12734</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34713987/\">https://pubmed.ncbi.nlm.nih.gov/34713987</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Thrombocytes;
