within Pharmacolibrary.Drugs.D_Dermatologicals.D07B_CorticosteroidsCombinationsWithAntiseptics;
package D07BA04_HydrocortisoneAndAntisep
  extends Icons.PackageDrugs;
end D07BA04_HydrocortisoneAndAntisep;
