within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins;
package J01CR50_AmoxicillinAndClavulanic
  extends Icons.PackageDrugs;
end J01CR50_AmoxicillinAndClavulanic;
