within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J04B_DrugsForTreatmentOfLepra;
package J04BA51_DapsoneRifampicinAndClof
  extends Icons.PackageDrugs;
end J04BA51_DapsoneRifampicinAndClof;
