within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H02A_CorticosteroidsForSystemicUsePlain;
package H02AB04_Methylprednisolone
  extends Icons.Package;
end H02AB04_Methylprednisolone;
