within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonStero;
package M01AX25_ChondroitinSulfate
  extends Icons.PackageDrugs;
end M01AX25_ChondroitinSulfate;
