within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FD02_Pertuzumab
  extends Icons.PackageDrugs;
end L01FD02_Pertuzumab;
