within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AX16_Hexetidine
  extends Icons.Package;
end G01AX16_Hexetidine;
