within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01X_OtherAntineoplasticAgents;
package L01XL07_IdecabtageneVicleucel
  extends Icons.PackageDrugs;
end L01XL07_IdecabtageneVicleucel;
