within Pharmacolibrary.Drugs.S_SensoryOrgans.S01A_Antiinfectives.S01AA23_Netilmicin;

model Netilmicin
  extends Pharmacolibrary.Drugs.ATC.S.S01AA23;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Netilmicin</td></tr><tr><td>ATC code:</td><td>S01AA23</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Netilmicin is a semisynthetic aminoglycoside antibiotic derived from sisomicin. It is used to treat serious bacterial infections, particularly those caused by Gram-negative bacteria, and is typically reserved for use when other aminoglycosides may not be effective due to resistance. It is primarily administered parenterally due to poor absorption orally. While it has been clinically used in the past, current use is limited due to concerns about nephrotoxicity and ototoxicity, and safer alternatives being available.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported for adults with normal renal function following intravenous administration.</p><h4>References</h4><ol><li><p>Jauregizar, N, et al., &amp; Calvo, R (2003). Population pharmacokinetics of netilmicin in short-term prophylactic treatment. <i>British journal of clinical pharmacology</i> 55(6) 552–559. DOI:<a href=\"https://doi.org/10.1046/j.1365-2125.2003.01783.x\">10.1046/j.1365-2125.2003.01783.x</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/12814449/\">https://pubmed.ncbi.nlm.nih.gov/12814449</a></p></li><li><p>Tréluyer, JM, et al., &amp; Pons, G (2000). Population pharmacokinetic analysis of netilmicin in neonates and infants with use of a nonparametric method. <i>Clinical pharmacology and therapeutics</i> 67(6) 600–609. DOI:<a href=\"https://doi.org/10.1067/mcp.2000.106695\">10.1067/mcp.2000.106695</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/10872642/\">https://pubmed.ncbi.nlm.nih.gov/10872642</a></p></li><li><p>Sherwin, CM, et al., &amp; Reith, DM (2008). Individualising netilmicin dosing in neonates. <i>European journal of clinical pharmacology</i> 64(12) 1201–1208. DOI:<a href=\"https://doi.org/10.1007/s00228-008-0536-0\">10.1007/s00228-008-0536-0</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/18685839/\">https://pubmed.ncbi.nlm.nih.gov/18685839</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Netilmicin;
