within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AF06_Ornidazole
  extends Icons.Package;
end G01AF06_Ornidazole;
