within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A07F_AntidiarrhealMicroorganisms;
package A07FA01_LacticAcidProducingOrganisms
  extends Icons.Package;
end A07FA01_LacticAcidProducingOrganisms;
