within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination;
package G03FB10_DesogestrelAndEstrogen
  extends Icons.Package;
end G03FB10_DesogestrelAndEstrogen;
