within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01R_CombinationsOfAntibacterials.J01RA16_CefiximeAndAzithromycin;

model CefiximeAndAzithromycin
  extends Pharmacolibrary.Drugs.ATC.J.J01RA16;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>CefiximeAndAzithromycin</td></tr><tr><td>ATC code:</td><td>J01RA16</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Cefixime is a third-generation oral cephalosporin antibiotic, and azithromycin is a macrolide antibiotic. The fixed-dose combination is used primarily for the treatment of uncomplicated gonorrhea and other sexually transmitted infections due to their synergistic antibacterial effects. This combination is currently approved and in clinical use in several regions.</p><h4>Pharmacokinetics</h4><p>No published studies providing direct pharmacokinetic parameters for the fixed-dose combination of cefixime and azithromycin (J01RA16) were identified. The following values are estimated based on pharmacokinetic data for the individual drugs in healthy adults, given as a single oral dose.</p><h4>References</h4><ol><li><p>Kong, FYS, et al., &amp; Hocking, JS (2022). Optimisation of treatments for oral . <i>BMJ open</i> 12(11) e064782–None. DOI:<a href=\"https://doi.org/10.1136/bmjopen-2022-064782\">10.1136/bmjopen-2022-064782</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/36368750/\">https://pubmed.ncbi.nlm.nih.gov/36368750</a></p></li><li><p>Alonso, R, et al., &amp; Canut, A (2021). Molecular Epidemiology, Antimicrobial Surveillance, and PK/PD Analysis to Guide the Treatment of . <i>Pharmaceutics</i> 13(10) –. DOI:<a href=\"https://doi.org/10.3390/pharmaceutics13101699\">10.3390/pharmaceutics13101699</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34683991/\">https://pubmed.ncbi.nlm.nih.gov/34683991</a></p></li><li><p>Jacobs, MR, et al., &amp; Appelbaum, PC (1999). Susceptibilities of Streptococcus pneumoniae and Haemophilus influenzae to 10 oral antimicrobial agents based on pharmacodynamic parameters: 1997 U.S. Surveillance study. <i>Antimicrobial agents and chemotherapy</i> 43(8) 1901–1908. DOI:<a href=\"https://doi.org/10.1128/AAC.43.8.1901\">10.1128/AAC.43.8.1901</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/10428910/\">https://pubmed.ncbi.nlm.nih.gov/10428910</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end CefiximeAndAzithromycin;
