within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD05_MetforminAndPioglitazone
  extends Icons.PackageDrugs;
end A10BD05_MetforminAndPioglitazone;
