within Pharmacolibrary.Drugs.S_SensoryOrgans.S02A_Antiinfectives.S02AA17_Fosfomycin;

model Fosfomycin
  extends Pharmacolibrary.Drugs.ATC.S.S02AA17;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>S02AA17</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Fosfomycin is a broad-spectrum antibiotic, primarily active against Gram-negative and some Gram-positive bacteria. It is commonly used for the treatment of uncomplicated urinary tract infections, especially due to its oral availability and good safety profile. Fosfomycin trometamol is approved and widely used in the management of acute cystitis. Other formulations are used intravenously for systemic infections.</p><h4>Pharmacokinetics</h4><p>Single dose pharmacokinetics in healthy adult volunteers following oral fosfomycin trometamol administration.</p><h4>References</h4><ol><li><p>Isla, A, et al., &amp; Rodríguez-Gascón, A (2024). Population pharmacokinetics of oral fosfomycin calcium in healthy women. <i>The Journal of antimicrobial chemotherapy</i> 79(11) 2837–2845. DOI:<a href=\"https://doi.org/10.1093/jac/dkae295\">10.1093/jac/dkae295</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/39205651/\">https://pubmed.ncbi.nlm.nih.gov/39205651</a></p></li><li><p>Kane, Z, et al., &amp; Standing, JF (2021). IV and oral fosfomycin pharmacokinetics in neonates with suspected clinical sepsis. <i>The Journal of antimicrobial chemotherapy</i> 76(7) 1855–1864. DOI:<a href=\"https://doi.org/10.1093/jac/dkab083\">10.1093/jac/dkab083</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33855449/\">https://pubmed.ncbi.nlm.nih.gov/33855449</a></p></li><li><p>Wenzler, E, et al., &amp; Rodvold, KA (2017). Pharmacokinetics, Safety, and Tolerability of Single-Dose Intravenous (ZTI-01) and Oral Fosfomycin in Healthy Volunteers. <i>Antimicrobial agents and chemotherapy</i> 61(9) –. DOI:<a href=\"https://doi.org/10.1128/AAC.00775-17\">10.1128/AAC.00775-17</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/28630194/\">https://pubmed.ncbi.nlm.nih.gov/28630194</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Fosfomycin;
