within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M05B_DrugsAffectingBoneStructureAndMineralization;
package M05BB02_RisedronicAcidAndCalcium
  extends Icons.PackageDrugs;
end M05BB02_RisedronicAcidAndCalcium;
