within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J05A_DirectActingAntivirals;
package J05AP53_OmbitasvirParitaprevirAndRitonav
  extends Icons.PackageDrugs;
end J05AP53_OmbitasvirParitaprevirAndRitonav;
