within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03A_HormonalContraceptivesForSystemicUse;
package G03AA07_LevonorgestrelAndEthinyl
  extends Icons.PackageDrugs;
end G03AA07_LevonorgestrelAndEthinyl;
