within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H05B_AntiParathyroidAgents;
package H05BA03_CalcitoninHumanSynthetic
  extends Icons.Package;
end H05BA03_CalcitoninHumanSynthetic;
