within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02L_AntihypertensivesAndDiureticsInCombination;
package C02LA04_MethoserpidineAndDiureti
  extends Icons.PackageDrugs;
end C02LA04_MethoserpidineAndDiureti;
