within Pharmacolibrary.Drugs.V_Various.V09I_TumourDetection;
package V09IA01_Technetium99mtcAnticarcinoembryonicantigenAntibody
  extends Icons.Package;
end V09IA01_Technetium99mtcAnticarcinoembryonicantigenAntibody;
