within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AH10_MeningococcusAPurifiedPolysaccha
  extends Icons.Package;
end J07AH10_MeningococcusAPurifiedPolysaccha;
