within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined.J07CA03_DiphtheriaRubellaTetanus;

model DiphtheriaRubellaTetanus
  extends Pharmacolibrary.Drugs.ATC.J.J07CA03;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>J07CA03</td></tr><td>route:</td><td>intramuscular</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>The diphtheria-rubella-tetanus (DRT) vaccine is a combined immunization used primarily to protect against three infectious diseases: diphtheria, caused by Corynebacterium diphtheriae; rubella, caused by rubella virus; and tetanus, caused by Clostridium tetani. This vaccine is widely used in routine childhood immunization schedules across the globe and is approved for use today to prevent these diseases.</p><h4>Pharmacokinetics</h4><p>There are no published pharmacokinetic (PK) models or quantitative PK parameters available for the diphtheria-rubella-tetanus vaccine in the literature. The vaccine consists of inactivated bacterial toxoids (diphtheria, tetanus) and live-attenuated virus (rubella) administered intramuscularly, and the pharmacokinetic evaluation is not typically performed for vaccines. The following parameters are not available and are left empty or default as appropriate.</p><h4>References</h4><ol><li><p>Muraro, A, et al., &amp; Roberts, G (2022). EAACI guidelines: Anaphylaxis (2021 update). <i>Allergy</i> 77(2) 357–377. DOI:<a href=\"https://doi.org/10.1111/all.15032\">10.1111/all.15032</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34343358/\">https://pubmed.ncbi.nlm.nih.gov/34343358</a></p></li><li><p>Saari, TI, et al., &amp; Dale, O (2024). Clinical Pharmacokinetics and Pharmacodynamics of Naloxone. <i>Clinical pharmacokinetics</i> 63(4) 397–422. DOI:<a href=\"https://doi.org/10.1007/s40262-024-01355-6\">10.1007/s40262-024-01355-6</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/38485851/\">https://pubmed.ncbi.nlm.nih.gov/38485851</a></p></li><li><p>Lugo, RA, &amp; Kern, SE (2002). Clinical pharmacokinetics of morphine. <i>Journal of pain &amp; palliative care pharmacotherapy</i> 16(4) 5–18. DOI:<a href=\"https://doi.org/10.1080/j354v16n04_02\">10.1080/j354v16n04_02</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/14635822/\">https://pubmed.ncbi.nlm.nih.gov/14635822</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end DiphtheriaRubellaTetanus;
