within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA03_DiphtheriaRubellaTetanus
  extends Icons.Package;
end J07CA03_DiphtheriaRubellaTetanus;
