within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P03A_EctoparasiticidesInclScabicides;
package P03AX02_CopperOleinate
  extends Icons.Package;
end P03AX02_CopperOleinate;
