within Pharmacolibrary.Drugs.C_CardiovascularSystem.C02L_AntihypertensivesAndDiureticsInCombination;
package C02LB01_MethyldopaLevorotatoryAndDiureti
  extends Icons.Package;
end C02LB01_MethyldopaLevorotatoryAndDiureti;
