within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AA08_Carfecillin
  extends Icons.PackageDrugs;
end G01AA08_Carfecillin;
