within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AA03_AmphotericinB
  extends Icons.PackageDrugs;
end G01AA03_AmphotericinB;
