within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AB02_Tinidazole
  extends Icons.PackageDrugs;
end P01AB02_Tinidazole;
