within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01E_SulfonamidesAndTrimethoprim;
package J01ED20_TrimethoprimAndSulfonami
  extends Icons.PackageDrugs;
end J01ED20_TrimethoprimAndSulfonami;
