within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B01A_AntithromboticAgents.B01AE07_DabigatranEtexilate;

model DabigatranEtexilate
  extends Pharmacolibrary.Drugs.ATC.B.B01AE07;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>DabigatranEtexilate</td></tr><tr><td>ATC code:</td><td>B01AE07</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Dabigatran etexilate is an oral direct thrombin inhibitor used for prevention of stroke and systemic embolism in patients with non-valvular atrial fibrillation, and for treatment and prevention of deep vein thrombosis and pulmonary embolism. It is approved and widely used today as a novel oral anticoagulant (NOAC).</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported for healthy adult volunteers, both male and female, following a single oral dose.</p><h4>References</h4><ol><li><p>Elenjickal, EJ, et al., &amp; Mavrakanas, TA (2024). Anticoagulation in Patients with Chronic Kidney Disease. <i>American journal of nephrology</i> 55(2) 146–164. DOI:<a href=\"https://doi.org/10.1159/000535546\">10.1159/000535546</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/38035566/\">https://pubmed.ncbi.nlm.nih.gov/38035566</a></p></li><li><p>Martin, KA, et al., &amp; Moll, S (2017). Oral Anticoagulant Use After Bariatric Surgery: A Literature Review and Clinical Guidance. <i>The American journal of medicine</i> 130(5) 517–524. DOI:<a href=\"https://doi.org/10.1016/j.amjmed.2016.12.033\">10.1016/j.amjmed.2016.12.033</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/28159600/\">https://pubmed.ncbi.nlm.nih.gov/28159600</a></p></li><li><p>Dunois, C (2021). Laboratory Monitoring of Direct Oral Anticoagulants (DOACs). <i>Biomedicines</i> 9(5) –. DOI:<a href=\"https://doi.org/10.3390/biomedicines9050445\">10.3390/biomedicines9050445</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/33919121/\">https://pubmed.ncbi.nlm.nih.gov/33919121</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end DabigatranEtexilate;
