within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDis;
package A02BD05_OmeprazoleAmoxicillinAnd
  extends Icons.PackageDrugs;
end A02BD05_OmeprazoleAmoxicillinAnd;
