within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination;
package G03FA08_MegestrolAndEstrogen
  extends Icons.PackageDrugs;
end G03FA08_MegestrolAndEstrogen;
