within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A11C_VitaminAAndDInclCombinationsOfTheTwo;
package A11CC55_ColecalciferolCombinations
  extends Icons.Package;
end A11CC55_ColecalciferolCombinations;
