within Pharmacolibrary.Drugs.C_CardiovascularSystem.C07D_BetaBlockingAgentsThiazidesAndOtherDiuretics;
package C07DA06_TimololThiazidesAndOther
  extends Icons.PackageDrugs;
end C07DA06_TimololThiazidesAndOther;
