within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination;
package G03FA07_LynestrenolAndEstrogen
  extends Icons.PackageDrugs;
end G03FA07_LynestrenolAndEstrogen;
