within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA12_DiphtheriaPertussisPoliomyelitis
  extends Icons.Package;
end J07CA12_DiphtheriaPertussisPoliomyelitis;
