within Pharmacolibrary.Drugs.C_CardiovascularSystem.C10B_LipidModifyingAgentsCombinations;
package C10BX07_RosuvastatinAmlodipineAndLisinop
  extends Icons.Package;
end C10BX07_RosuvastatinAmlodipineAndLisinop;
