within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07A_BacterialVaccines;
package J07AH05_OtherMeningococcalPolyvalentPuri
  extends Icons.Package;
end J07AH05_OtherMeningococcalPolyvalentPuri;
