within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWithCorticosteroids;
package G01AF13_Azanidazole
  extends Icons.Package;
end G01AF13_Azanidazole;
