within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10A_InsulinsAndAnalogues;
package A10AB30_InsulinDegludecAndInsulinAspartC
  extends Icons.PackageDrugs;
end A10AB30_InsulinDegludecAndInsulinAspartC;
