within Pharmacolibrary.Drugs.S_SensoryOrgans.S01C_AntiinflammatoryAgentsAndAntiinfectivesInCombination;
package S01CA10_FluocinoloneAcetonideAndAntiinfectives
  extends Icons.Package;
end S01CA10_FluocinoloneAcetonideAndAntiinfectives;
