within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01B_AntiinflammatoryAntirheumaticAgentsInCombination;
package M01BA03_AcetylsalicylicAcidAndCorticosteroids
  extends Icons.Package;
end M01BA03_AcetylsalicylicAcidAndCorticosteroids;
