within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BD04_PantoprazoleAmoxicillinAndClarithromycin
  extends Icons.Package;
end A02BD04_PantoprazoleAmoxicillinAndClarithromycin;
