within Pharmacolibrary.Drugs.H_SystemicHormonalPreparationsExclSexHormonesAndInsulins.H02A_CorticosteroidsForSystemicUsePlain;
package H02AB12_Rimexolone
  extends Icons.PackageDrugs;
end H02AB12_Rimexolone;
