within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M01A_AntiinflammatoryAndAntirheumaticProductsNonStero;
package M01AE56_NaproxenAndMisoprostol
  extends Icons.PackageDrugs;
end M01AE56_NaproxenAndMisoprostol;
