within Pharmacolibrary.Drugs.N_NervousSystem.N05A_Antipsychotics.N05AX16_Brexpiprazole;

model Brexpiprazole
  extends Pharmacolibrary.Drugs.ATC.N.N05AX16;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Brexpiprazole</td></tr><tr><td>ATC code:</td><td>N05AX16</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Brexpiprazole is a second-generation (atypical) antipsychotic medication used in the treatment of schizophrenia and as an adjunct in major depressive disorder. It acts as a partial agonist at serotonin 5-HT1A and dopamine D2 receptors, and as an antagonist at serotonin 5-HT2A receptors. It is approved for clinical use in multiple countries.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters reported in healthy adult subjects after single-dose oral administration.</p><h4>References</h4><ol><li><p>Higashi, K, et al., &amp; Kawai, Y (2025). Population pharmacokinetics of brexpiprazole in Japanese healthy subjects and patients with schizophrenia. <i>Drug metabolism and pharmacokinetics</i> 62 101057–None. DOI:<a href=\"https://doi.org/10.1016/j.dmpk.2025.101057\">10.1016/j.dmpk.2025.101057</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/40157325/\">https://pubmed.ncbi.nlm.nih.gov/40157325</a></p></li><li><p>Bruno, CD, et al., &amp; Greenblatt, DJ (2022). Impact of Obesity on Brexpiprazole Pharmacokinetics: Proposal for Improved Initiation of Treatment. <i>Journal of clinical pharmacology</i> 62(1) 55–65. DOI:<a href=\"https://doi.org/10.1002/jcph.1947\">10.1002/jcph.1947</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34339048/\">https://pubmed.ncbi.nlm.nih.gov/34339048</a></p></li><li><p>Elmokadem, A, et al., &amp; Greenblatt, DJ (2022). Brexpiprazole Pharmacokinetics in CYP2D6 Poor Metabolizers: Using Physiologically Based Pharmacokinetic Modeling to Optimize Time to Effective Concentrations. <i>Journal of clinical pharmacology</i> 62(1) 66–75. DOI:<a href=\"https://doi.org/10.1002/jcph.1946\">10.1002/jcph.1946</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/34328221/\">https://pubmed.ncbi.nlm.nih.gov/34328221</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Brexpiprazole;
