within Pharmacolibrary.Drugs.S_SensoryOrgans.S02C_CorticosteroidsAndAntiinfectivesInCombination;
package S02CA02_FlumetasoneAndAntiinfect
  extends Icons.PackageDrugs;
end S02CA02_FlumetasoneAndAntiinfect;
