within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BD14_MetforminAndRepaglinide
  extends Icons.Package;
end A10BD14_MetforminAndRepaglinide;
