within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DB04_TelmisartanAndAmlodipine
  extends Icons.Package;
end C09DB04_TelmisartanAndAmlodipine;
