within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A10B_BloodGlucoseLoweringDrugsExclInsulins;
package A10BH52_GemigliptinAndRosuvastat
  extends Icons.PackageDrugs;
end A10BH52_GemigliptinAndRosuvastat;
