within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents.L01F_MonoclonalAntibodiesAndAntibodyDrugConjugates;
package L01FA03_Obinutuzumab
  extends Icons.PackageDrugs;
end L01FA03_Obinutuzumab;
