within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M03B_MuscleRelaxantsCentrallyActingAgents;
package M03BA71_PhenprobamateCombinationsWithPsy
  extends Icons.Package;
end M03BA71_PhenprobamateCombinationsWithPsy;
