within Pharmacolibrary.Drugs.N_NervousSystem.N02B_OtherAnalgesicsAndAntipyretics;
package N02BE53_PhenacetinCombinationsExclPsycholeptics
  extends Icons.Package;
end N02BE53_PhenacetinCombinationsExclPsycholeptics;
