within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J07C_BacterialAndViralVaccinesCombined;
package J07CA01_DiphtheriaPoliomyelitisTetanus
  extends Icons.Package;
end J07CA01_DiphtheriaPoliomyelitisTetanus;
