within Pharmacolibrary.Drugs.M_MusculoSkeletalSystem.M03B_MuscleRelaxantsCentrallyActingAgents;
package M03BB73_ChlorzoxazoneCombinationsWithPsy
  extends Icons.PackageDrugs;
end M03BB73_ChlorzoxazoneCombinationsWithPsy;
