within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord.A02BC05_Esomeprazole;

model Esomeprazole
  extends Pharmacolibrary.Drugs.ATC.A.A02BC05;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Esomeprazole</td></tr><tr><td>ATC code:</td><td>A02BC05</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>2</td></tr></table><p>Esomeprazole is a proton pump inhibitor (PPI) used to decrease stomach acid production. It is widely used for treatment of gastroesophageal reflux disease (GERD), erosive esophagitis, and peptic ulcer disease. Esomeprazole is an enantiomer of omeprazole and is approved and commonly prescribed today.</p><h4>Pharmacokinetics</h4><p>Healthy adult volunteers, single oral administration. Values represent typical PK profile after a 40 mg oral dose.</p><h4>References</h4><ol><li><p>Nagase, M, et al., &amp; Al-Huniti, N (2020). Population pharmacokinetic analysis of esomeprazole in Japanese subjects with various CYP2C19 phenotypes. <i>Journal of clinical pharmacy and therapeutics</i> 45(5) 1030–1038. DOI:<a href=\"https://doi.org/10.1111/jcpt.13129\">10.1111/jcpt.13129</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/32227647/\">https://pubmed.ncbi.nlm.nih.gov/32227647</a></p></li><li><p>Zhou, J, et al., &amp; Sellami, D (2016). Effect of esomeprazole, a proton pump inhibitor on the pharmacokinetics of sonidegib in healthy volunteers. <i>British journal of clinical pharmacology</i> 82(4) 1022–1029. DOI:<a href=\"https://doi.org/10.1111/bcp.13038\">10.1111/bcp.13038</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/27277189/\">https://pubmed.ncbi.nlm.nih.gov/27277189</a></p></li><li><p>Parekh, PJ, et al., &amp; Johnson, DA (2014). Treatment of gastroesophageal reflux disease: two new oral formulations dexlansoprazole MR and esomezol (esomeprazole strontium). <i>Expert opinion on pharmacotherapy</i> 15(9) 1215–1222. DOI:<a href=\"https://doi.org/10.1517/14656566.2014.911841\">10.1517/14656566.2014.911841</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/24749891/\">https://pubmed.ncbi.nlm.nih.gov/24749891</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Esomeprazole;
