within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A02B_DrugsForPepticUlcerAndGastroOesophagealRefluxDiseaseGord;
package A02BC05_Esomeprazole
  extends Icons.Package;
end A02BC05_Esomeprazole;
