within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01E_SulfonamidesAndTrimethoprim;
package J01EE03_SulfametroleAndTrimethoprim
  extends Icons.Package;
end J01EE03_SulfametroleAndTrimethoprim;
