within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03F_ProgestogensAndEstrogensInCombination;
package G03FB02_LynestrenolAndEstrogen
  extends Icons.PackageDrugs;
end G03FB02_LynestrenolAndEstrogen;
