within Pharmacolibrary.Drugs.L_AntineoplasticAndImmunomodulatingAgents;
package L01C_PlantAlkaloidsAndOtherNaturalProducts
  extends Icons.PackageDrugs;
end L01C_PlantAlkaloidsAndOtherNaturalProducts;
