within Pharmacolibrary.Drugs.S_SensoryOrgans.S02C_CorticosteroidsAndAntiinfectivesInCombination;
package S02CA04_TriamcinoloneAndAntiinfe
  extends Icons.PackageDrugs;
end S02CA04_TriamcinoloneAndAntiinfe;
