within Pharmacolibrary.Drugs.B_BloodAndBloodFormingOrgans.B05B_IVSolutions.B05BA03_Carbohydrates;

model Carbohydrates
  extends Pharmacolibrary.Drugs.ATC.B.B05BA03;

  annotation (Documentation(
info       = "<html><body><table><tr><td>name:</td><td>Carbohydrates</td></tr><tr><td>ATC code:</td><td>B05BA03</td></tr><td>route:</td><td>intravenous</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Carbohydrates for parenteral nutrition (such as glucose and related solutions) are used as sources of energy and are typically administered intravenously to patients who cannot obtain nutrition via the oral or enteral route. These are commonly employed in hospital settings for patients requiring supportive care. While not a 'drug' in the traditional sense, intravenous carbohydrates (glucose/dextrose) remain a standard and essential component of parenteral nutrition and are widely approved and used in clinical medicine today.</p><h4>Pharmacokinetics</h4><p>Estimated pharmacokinetic parameters for intravenous infusion of glucose in healthy adult individuals. Published literature directly reporting compartmental pharmacokinetic values for this ATC category is limited; parameters are estimated based on reported ranges for intravenous 5% dextrose solutions in adults.</p><h4>References</h4><ol><li><p>Graham, GG, et al., &amp; Williams, KM (2011). Clinical pharmacokinetics of metformin. <i>Clinical pharmacokinetics</i> 50(2) 81–98. DOI:<a href=\"https://doi.org/10.2165/11534750-000000000-00000\">10.2165/11534750-000000000-00000</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/21241070/\">https://pubmed.ncbi.nlm.nih.gov/21241070</a></p></li><li><p>Chen, Z, et al., &amp; Liebchen, U (2023). Plasma and Cerebrospinal Fluid Population Pharmacokinetics of Vancomycin in Patients with External Ventricular Drain. <i>Antimicrobial agents and chemotherapy</i> 67(6) e0024123–None. DOI:<a href=\"https://doi.org/10.1128/aac.00241-23\">10.1128/aac.00241-23</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/37162349/\">https://pubmed.ncbi.nlm.nih.gov/37162349</a></p></li><li><p>An, G, et al., &amp; Veng-Pedersen, P (2017). Population Pharmacokinetics of Darbepoetin in Infants Following Single Intravenous and Subcutaneous Dosing. <i>Journal of pharmaceutical sciences</i> 106(6) 1644–1649. DOI:<a href=\"https://doi.org/10.1016/j.xphs.2017.02.001\">10.1016/j.xphs.2017.02.001</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/28189627/\">https://pubmed.ncbi.nlm.nih.gov/28189627</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Carbohydrates;
