within Pharmacolibrary.Drugs.N_NervousSystem.N05C_HypnoticsAndSedatives.N05CF02_Zolpidem;

model Zolpidem
  extends Pharmacolibrary.Drugs.ATC.N.N05CF02;

  annotation (Documentation(
info       = "<html><body><table><tr><td>Drug:</td><td>N05CF02</td></tr><td>route:</td><td>oral</td></tr><tr><td>n-compartments</td><td>1</td></tr></table><p>Zolpidem is a non-benzodiazepine hypnotic agent of the imidazopyridine class primarily used for the short-term treatment of insomnia. It works by enhancing the activity of gamma-aminobutyric acid (GABA) via selective agonism at the benzodiazepine-1 (omega-1) receptor subtype. Zolpidem is approved and widely used today for sleep disorders.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic parameters were reported in healthy adult volunteers (both sexes), typically aged 18-45 years, under fasting conditions after single oral dose.</p><h4>References</h4><ol><li><p>Monti, JM, et al., &amp; Pandi-Perumal, SR (2017). Zolpidem&#x27;s use for insomnia. <i>Asian journal of psychiatry</i> 25 79–90. DOI:<a href=\"https://doi.org/10.1016/j.ajp.2016.10.006\">10.1016/j.ajp.2016.10.006</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/28262178/\">https://pubmed.ncbi.nlm.nih.gov/28262178</a></p></li><li><p>Guo, T, et al., &amp; Yang, L (2014). Comparative pharmacokinetics of zolpidem tartrate in five ethnic populations of China. <i>Acta pharmaceutica Sinica. B</i> 4(2) 146–150. DOI:<a href=\"https://doi.org/10.1016/j.apsb.2014.02.001\">10.1016/j.apsb.2014.02.001</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/26579377/\">https://pubmed.ncbi.nlm.nih.gov/26579377</a></p></li><li><p>Shen, M, et al., &amp; Xiang, P (2013). CYP3A4 and CYP2C19 genetic polymorphisms and zolpidem metabolism in the Chinese Han population: a pilot study. <i>Forensic science international</i> 227(1-3) 77–81. DOI:<a href=\"https://doi.org/10.1016/j.forsciint.2012.08.035\">10.1016/j.forsciint.2012.08.035</a>  PUBMED:<a href=\"https://pubmed.ncbi.nlm.nih.gov/22964165/\">https://pubmed.ncbi.nlm.nih.gov/22964165</a></p></li></ol></body></html>",
    revisions  = "<html><body><ul><li>06/2025 initial generated model</li></ul></body></html>",
    experiment (StartTime = 0, StopTime = 86400, Tolerance = 1e-9, Interval = 1)
  ));
end Zolpidem;
