within Pharmacolibrary.Drugs.A_AlimentaryTractAndMetabolism.A16A_OtherAlimentaryTractAndMetabolismProducts;
package A16AX30_SodiumBenzoateAndSodiumPhenylacetate
  extends Icons.Package;
end A16AX30_SodiumBenzoateAndSodiumPhenylacetate;
