within Pharmacolibrary.Drugs.R_RespiratorySystem.R01A_DecongestantsAndOtherNasalPreparationsForTopical;
package R01AD12_FluticasoneFuroate
  extends Icons.PackageDrugs;
end R01AD12_FluticasoneFuroate;
