within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G04C_DrugsUsedInBenignProstaticHypertrophy;
package G04CX02_SabalisSerrulataeFructus
  extends Icons.Package;
end G04CX02_SabalisSerrulataeFructus;
