within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J04A_DrugsForTreatmentOfTuberculosis;
package J04AM06_RifampicinPyrazinamideEthambutolAndIsoniazid
  extends Icons.Package;
end J04AM06_RifampicinPyrazinamideEthambutolAndIsoniazid;
