within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G01A_AntiinfectivesAndAntisepticsExclCombinationsWith;
package G01AX14_Lactobacillus
  extends Icons.PackageDrugs;
end G01AX14_Lactobacillus;
