within Pharmacolibrary.Drugs.C_CardiovascularSystem.C09D_AngiotensinIiReceptorBlockersArbsCombinations;
package C09DA08_OlmesartanMedoxomilAndDi
  extends Icons.PackageDrugs;
end C09DA08_OlmesartanMedoxomilAndDi;
