within Pharmacolibrary.Drugs.J_AntiinfectivesForSystemicUse.J01C_BetaLactamAntibacterialsPenicillins;
package J01CE10_BenzathinePhenoxymethylpenicillin
  extends Icons.Package;
end J01CE10_BenzathinePhenoxymethylpenicillin;
