within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03C_Estrogens;
package G03CC07_ConjugatedEstrogensAndBazedoxife
  extends Icons.PackageDrugs;
end G03CC07_ConjugatedEstrogensAndBazedoxife;
