within Pharmacolibrary.Drugs.G_GenitoUrinarySystemAndSexHormones.G03C_Estrogens;
package G03CC07_ConjugatedEstrogensAndBazedoxife
  extends Icons.Package;
end G03CC07_ConjugatedEstrogensAndBazedoxife;
