within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AX08_Tenonitrozole
  extends Icons.PackageDrugs;
end P01AX08_Tenonitrozole;
