within Pharmacolibrary.Drugs.P_AntiparasiticProductsInsecticidesAndRepellents.P01A_AgentsAgainstAmoebiasisAndOtherProtozoalDiseases;
package P01AX08_Tenonitrozole
  extends Icons.Package;
end P01AX08_Tenonitrozole;
