within Pharmacolibrary.Drugs.D_Dermatologicals.D07C_CorticosteroidsCombinationsWithAntibiotics;
package D07CB01_TriamcinoloneAndAntibiotics
  extends Icons.Package;
end D07CB01_TriamcinoloneAndAntibiotics;
